workspace-sf/force-app/main/default/objects/ControleIntegracao__c/ControleIntegracao__c.object-meta.xml
<CustomObject>
    <description>Objeto responsável por conter os logs das integrações</description>
    <label>Controle de integração</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Controles de integração</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/ControleIntegracao__c/fields/CodigoIntegracao__c.field-meta.xml
<CustomField>
    <fullName>CodigoIntegracao__c</fullName>
    <label>Código da integração</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/ControleIntegracao__c/fields/DataCriacaoRegistro__c.field-meta.xml
<CustomField>
    <fullName>DataCriacaoRegistro__c</fullName>
    <label>Data de criação do registro</label>
    <type>Date</type>
</CustomField>

workspace-sf/force-app/main/default/objects/ControleIntegracao__c/fields/IdExterno__c.field-meta.xml
<CustomField>
    <fullName>IdExterno__c</fullName>
    <description>Id Externo para Heroku Connect</description>
    <externalId>true</externalId>
    <label>Id externo</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

workspace-sf/force-app/main/default/objects/ControleIntegracao__c/fields/IdObjeto__c.field-meta.xml
<CustomField>
    <fullName>IdObjeto__c</fullName>
    <label>Id do objeto</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/ControleIntegracao__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pendente</fullName>
            </value>
            <value>
                <fullName>Em processamento</fullName>
            </value>
            <value>
                <fullName>Processado</fullName>
            </value>
            <value>
                <fullName>Erro</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/Pagamento__x/Pagamento__x.object-meta.xml
<CustomObject>
    <description>public$pagamento</description>
    <externalDataSource>Heroku</externalDataSource>
    <externalName>public$pagamento</externalName>
    <externalRepository>Id</externalRepository>
    <label>Pagamento</label>
    <pluralLabel>Pagamentos</pluralLabel>
</CustomObject>

workspace-sf/force-app/main/default/objects/Pagamento__x/fields/idObjeto__c.field-meta.xml
<CustomField>
    <fullName>idObjeto__c</fullName>
    <externalDeveloperName>idobjeto</externalDeveloperName>
    <label>id Objeto</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Pagamento__x/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <externalDeveloperName>status</externalDeveloperName>
    <label>Status</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/classes/PagamentoBO.cls
/**
 * Created by Fabio Rente on 17/04/2019.
 */

public class PagamentoBO {
	private static final PagamentoBO instancia = new PagamentoBO();
	private static PagamentoDAO dao = PagamentoDAO.getInstance();

	public PagamentoBO() {}

	public static PagamentoBO getInstance(){
        return instancia;
    }

    //INICIO | PLV-2376-29
    public RetornoAcaoBotaoTO reenviarPagamento(String pagamentoId) {

        // variaveis
        RetornoAcaoBotaoTO retorno = new RetornoAcaoBotaoTO();
        List<Id> idPagamentos = new List<Id>();
        
        if(String.isNotBlank(pagamentoId))
            idPagamentos.add(Id.valueOf(pagamentoId));

        List<Pagamento__x> listPagamento = dao.buscarPagamentosPorIds(idPagamentos);
        //FIM | PLV-2376-29

        // Recupera dados do pagamento
        Pagamento__x pagamento = listPagamento[0];

        if(pagamento.Status__c != 'ERRO'){
            retorno.tipo = RetornoAcaoBotaoTO.WARNING;
            retorno.mensagens.add('Pagamento não pode ser reenviado, pois o Status não esta como "Devolvido"!');
        }else{
            pagamento.Status__c = 'EM REPROCESSAMENTO';
            try {
                
                //INICIO | PLV-2376-29
                // Atualiza tb pagamento
                if(!Test.isRunningTest())
                    Database.updateAsync(pagamento);

                // Efetua o Controle de Integração (25) - Cria um registro com Status - Pendente 
                CriarControleIntegracao(pagamento);
                //FIM | PLV-2376-29

                retorno.tipo = RetornoAcaoBotaoTO.SUCCESS;
                retorno.mensagens.add('Pagamento reenviado com sucesso!');
            }catch (Exception e){
                retorno.tipo = RetornoAcaoBotaoTO.ERROR;
                retorno.mensagens.add('Erro ao tentar reenviar o pagamento!');
                retorno.mensagens.add(e.getMessage());
            }
        }

        return retorno;
    }

    //INICIO | PLV-2376-29
    private void CriarControleIntegracao(Pagamento__x pagamento)
    {
        ControleIntegracao__c log = new ControleIntegracao__c();

        log.IdExterno__c = String.valueOf(pagamento.Id__c);
        log.CodigoIntegracao__c     = '25';
        log.DataCriacaoRegistro__c  = Date.today();
        // INICIO | PLV-2376-28-ajustes
        log.IdObjeto__c = String.ValueOf(pagamento.Id__c);
        // FIM | PLV-2376-28-ajustes
        log.Status__c               = 'Pendente';

        insert log;

        System.debug('Gravou Controle Integração Pagamento');

    }
    //FIM | PLV-2376-29
}