workspace-sf/force-app/main/default/objects/ControleIntegracao__c/ControleIntegracao__c.object-meta.xml
<CustomObject>
    <description>Objeto responsável por conter os logs das integrações</description>
    <label>Controle de integração</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Controles de integração</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/ControleIntegracao__c/fields/CodigoIntegracao__c.field-meta.xml
<CustomField>
    <fullName>CodigoIntegracao__c</fullName>
    <label>Código da integração</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/ControleIntegracao__c/fields/DataCriacaoRegistro__c.field-meta.xml
<CustomField>
    <fullName>DataCriacaoRegistro__c</fullName>
    <label>Data de criação do registro</label>
    <type>Date</type>
</CustomField>

workspace-sf/force-app/main/default/objects/ControleIntegracao__c/fields/IdObjeto__c.field-meta.xml
<CustomField>
    <fullName>IdObjeto__c</fullName>
    <label>Id do objeto</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/ControleIntegracao__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pendente</fullName>
            </value>
            <value>
                <fullName>Em processamento</fullName>
            </value>
            <value>
                <fullName>Processado</fullName>
            </value>
            <value>
                <fullName>Erro</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/NotaFiscal__c/NotaFiscal__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar os dados das notas fiscais.</description>
    <label>Nota fiscal</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Tipo de Pagamento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notas fiscais</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/NotaFiscal__c/fields/Pagamento__c.field-meta.xml
<CustomField>
    <fullName>Pagamento__c</fullName>
    <label>Pagamento</label>
    <length>18</length>
    <referenceTo>Pagamento__x</referenceTo>
    <relationshipLabel>Notas fiscais</relationshipLabel>
    <relationshipName>NotasFiscais</relationshipName>
    <type>ExternalLookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/NotaFiscal__c/fields/StatusAprovacao__c.field-meta.xml
<CustomField>
    <fullName>StatusAprovacao__c</fullName>
    <label>Status da Aprovação</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pendente</fullName>
                <default>true</default>
                <label>Pendente</label>
            </value>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>Reprovado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/Pagamento__x/Pagamento__x.object-meta.xml
<CustomObject>
    <description>public$pagamento</description>
    <externalDataSource>Heroku</externalDataSource>
    <externalName>public$pagamento</externalName>
    <externalRepository>Id</externalRepository>
    <label>Pagamento</label>
    <pluralLabel>Pagamentos</pluralLabel>
</CustomObject>

workspace-sf/force-app/main/default/objects/Pagamento__x/fields/idObjeto__c.field-meta.xml
<CustomField>
    <fullName>idObjeto__c</fullName>
    <externalDeveloperName>idobjeto</externalDeveloperName>
    <label>id Objeto</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Pagamento__x/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <externalDeveloperName>status</externalDeveloperName>
    <label>Status</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/classes/NotaFiscalBO.cls
//INICIO | PLV-2233-27 
/*
*  @author Everymind - Sprint 27
*  @Descrição: manipulação de dados referentes ao objeto nota fiscal
*/
public with sharing class NotaFiscalBO {
    
    public NotaFiscalBO() {}
    private static final NotaFiscalBO instancia = new NotaFiscalBO();
    public static NotaFiscalBO getInstance(){ return instancia; }

    /*
    *  @author Everymind - Sprint 27
    *  @Descrição: Atualiza obj pagamento de acordo com as informações da NF
    */
    @future(callout=true)
    public static void atualizaPagamento(String strListNew){
        PagamentoDAO daoPgto = PagamentoDAO.getInstance();
        List<NotaFiscal__c> listaNew= (List<NotaFiscal__c>)JSON.deserialize(strListNew, List<NotaFiscal__c>.class);
        List<Integer> setChavePgto = new List<Integer>();
        List<Pagamento__x> lstPagamento = new List<Pagamento__x>();
        List<Pagamento__x> lstPagamentoUpdate = new List<Pagamento__x>();
        Map<Integer, NotaFiscal__c> mapNfs = new Map<Integer, NotaFiscal__c>();
        //INICIO | PLV-2376-29
        List<ControleIntegracao__c> lstLog = new List<ControleIntegracao__c>();
        //FIM | PLV-2376-29
        
        // monta chave de busca p/ obter os pagamentos relacionados as notas fiscais
        System.debug('monta chave de busca p/ obter os pagamentos relacionados as notas fiscais'); 
        for(NotaFiscal__c nf: listaNew){
            //PLV-3918-FIX4 - INICIO
            if(String.isNotBlank(nf.Pagamento__c)){
                if(!setChavePgto.contains(Integer.valueOf(nf.Pagamento__c))){
                    setChavePgto.add(Integer.valueOf(nf.Pagamento__c));
                    mapNfs.put(Integer.valueOf(nf.Pagamento__c), nf);
                }
            }
             //PLV-3918-FIX4 - FIM
        }
        
        // lista os pagamentos relacionados
        System.debug(JSON.serialize(setChavePgto));
        lstPagamento = daoPgto.buscarPagamentosPorIdcs(setChavePgto);
        System.debug(JSON.serialize(lstPagamento));

        if(!lstPagamento.isEmpty()){
            // varre osregistros de pgt e atualiza o status pela nf
            for(Pagamento__x pgto : lstPagamento){

                NotaFiscal__c nf = mapNfs.get(Integer.valueOf(pgto.Id__c));
                System.debug('atualizaPagamento >> nf' + nf);
            
                if(nf.StatusAprovacao__c == 'Pendente')
                    pgto.Status__c = 'PAGAMENTO EM APROVAÇÃO';
                //INICIO | PLV-2376-29
                else if(nf.StatusAprovacao__c == 'Aprovado'){
                    pgto.Status__c = 'PAGAMENTO LIBERADO';
                   
                    // cria log na controle integração quando status do pagamento for alterado p/ PAGAMENTO LIBERADO
                    ControleIntegracao__c log = new ControleIntegracao__c();
                    log.CodigoIntegracao__c = '25';
                    log.DataCriacaoRegistro__c = Date.today();
                    // INICIO | PLV-2376-28-ajustes
                    log.IdObjeto__c = String.ValueOf(pgto.Id__c);
                    // FIM | PLV-2376-28-ajustes
                    log.Status__c = 'Pendente';

                    lstLog.add(log);
                }
                //FIM | PLV-2376-29
                    
                else if(nf.StatusAprovacao__c == 'Reprovado')
                    pgto.Status__c = 'PAGAMENTO REJEITADO';
                    
                lstPagamentoUpdate.add(pgto);
            }
        }
        
        // Atualiza tb pagamento
        if(!Test.isRunningTest()){
            if (lstPagamento.size() > 0){
                System.debug('lstPagamentoUpdate >> ' + JSON.serialize(lstPagamentoUpdate));
                Database.updateAsync(lstPagamentoUpdate);
                //INICIO | PLV-2376-29
                // insere o registro de log

                Insert lstLog;
                //FIM | PLV-2376-29
            }

        }
    }
}
//FIM | PLV-2233-27