workspace-sf/force-app/main/default/objects/ControleIntegracao__c/ControleIntegracao__c.object-meta.xml
<CustomObject>
    <description>Objeto responsável por conter os logs das integrações</description>
    <label>Controle de integração</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Controles de integração</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/ControleIntegracao__c/fields/CodigoIntegracao__c.field-meta.xml
<CustomField>
    <fullName>CodigoIntegracao__c</fullName>
    <label>Código da integração</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/ControleIntegracao__c/fields/DataCriacaoRegistro__c.field-meta.xml
<CustomField>
    <fullName>DataCriacaoRegistro__c</fullName>
    <label>Data de criação do registro</label>
    <type>Date</type>
</CustomField>

workspace-sf/force-app/main/default/objects/ControleIntegracao__c/fields/IdObjeto__c.field-meta.xml
<CustomField>
    <fullName>IdObjeto__c</fullName>
    <label>Id do objeto</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/ControleIntegracao__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pendente</fullName>
            </value>
            <value>
                <fullName>Em processamento</fullName>
            </value>
            <value>
                <fullName>Processado</fullName>
            </value>
            <value>
                <fullName>Erro</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/Fatura__c/Fatura__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar os dados das faturas</description>
    <label>Fatura</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número da fatura</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Faturas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/Fatura__c/fields/DataPagamento__c.field-meta.xml
<CustomField>
    <fullName>DataPagamento__c</fullName>
    <label>Data de pagamento</label>
    <type>Date</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Fatura__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Em criação</fullName>
            </value>
            <value>
                <fullName>Pendente</fullName>
            </value>
            <value>
                <fullName>Paga</fullName>
            </value>
            <value>
                <fullName>Cancelada</fullName>
            </value>
            <value>
                <fullName>Erro - SAP</fullName>
            </value>
            <value>
                <fullName>Criada - SAP</fullName>
                <isActive>false</isActive>
                <label>Criada - SAP</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/Fatura__c/fields/TipoFatura__c.field-meta.xml
<CustomField>
    <fullName>TipoFatura__c</fullName>
    <label>Tipo de fatura</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BatimentoContabil</fullName>
                <label>Batimento Contábil</label>
            </value>
            <value>
                <fullName>Cobranca</fullName>
                <label>Cobrança</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/classes/FaturaBO.cls
public class FaturaBO {

    private static final FaturaBO instancia = new FaturaBO();
    private static FaturaDAO dao = FaturaDAO.getInstance();
    private static HerokuService servicoHeroku = HerokuService.getInstance();

    private static final String FATURA_STATUS_CANCELADA = 'Cancelada';
    private static final String FATURA_STATUS_PAGA = 'Paga';
    private static final String FATURA_STATUS_PENDENTE = 'Pendente';

    public static FaturaBO getInstance(){
        return instancia;
    }

    public List<Fatura__c> buscarFaturas(Set<Id> faturaIds) {
        return dao.buscarFaturasPorIds(faturaIds);
    }

    public String gerarNumeroContratoFinanceiro(String origemProposta, String numeroProposta, String sucursal, String ramo, String apolice, String endosso ){

        return origemProposta.leftPad(2,'0') + numeroProposta.leftPad(8,'0') + sucursal.leftPad(3,'0') + Ramo.leftPad(4,'0') + apolice.leftPad(9,'0') + endosso.leftPad(10,'0');

    }
    //------ Trigger creating Contract
    public void atualizarFaturasPagasHeroku(List<Fatura__c> lstFaturas, Map<Id, Fatura__c> mapOldFaturas) {
        Set<Id> IdsFatura = new Set<Id>();

        // Make sure of the map's instance
        if(mapOldFaturas == null)
            mapOldFaturas = new Map<Id, Fatura__c>();

        // Verify if is a new record or if have changes in the date field
        for(Fatura__c objFatura : lstFaturas) {
            Fatura__c faturaOld = mapOldFaturas.get(objFatura.Id);
        
            if(objFatura.Status__c == 'Paga' && (FaturaOld == null || FaturaOld.Status__c != 'Paga'))
            {
                IdsFatura.add(objFatura.Id);
            }
        } 

        if(IdsFatura.size()>0)
        {
            executaServicoAtualizcao(IdsFatura);
        }
      
    }
    public void gerarControleIntegracao(List<Fatura__c> lstFaturas, Map<Id, Fatura__c> mapOldFaturas) {
        List<ControleIntegracao__c> listControleIntegracao = new List<ControleIntegracao__c>();

        if(mapOldFaturas == null)
            mapOldFaturas = new Map<Id, Fatura__c>();

        for(Fatura__c objFatura : lstFaturas) {
            Fatura__c faturaOld = mapOldFaturas.get(objFatura.Id);

            if(( objFatura.Status__c == FATURA_STATUS_PENDENTE || objFatura.Status__c == FATURA_STATUS_PAGA || objFatura.Status__c == FATURA_STATUS_CANCELADA )
                    && faturaOld.Status__c != objFatura.Status__c && objFatura.TipoFatura__c == 'Cobranca')
            {
                ControleIntegracao__c controleIntegracao = new ControleIntegracao__c(
                        IdObjeto__c = objFatura.Id,
                        CodigoIntegracao__c = '63',
                        DataCriacaoRegistro__c = System.today(),
                        Status__c = 'Pendente'
                );

                listControleIntegracao.add(controleIntegracao);
            }
        }

        if(listControleIntegracao.size() > 0)
        {
            try{
                insert listControleIntegracao;
            }catch (Exception e){
                throw new FaturaException('Erro ao gerar o controle de integração: ' + e.getLineNumber() + ' : ' + e.getMessage());
            }
        }

    }


    @future(callout=true)
    private static void executaServicoAtualizcao(Set<Id> IdsFatura)
    {
        List<FaturaTO.AtualizarParcelaTO> payload = new List<FaturaTO.AtualizarParcelaTO>();

        for(Fatura__c objFatura : FaturaDAO.getInstance().buscarFaturasPorIds(IdsFatura))
        {
            // PLV-2192-27-INICIO
            FaturaTO.AtualizarParcelaTO fatura = new FaturaTO.AtualizarParcelaTO();
            fatura.numeroFatura = objFatura.Name;
            fatura.dataPagamento = String.valueOf(objFatura.DataPagamento__c);

            payload.add(fatura);
            // PLV-2192-27-FIM
        }

        if(!Test.isRunningTest()){
            System.debug('Payload fatura :' + JSON.serialize(payload));
            servicoHeroku.atualizaStatusFatura(payload);
        }
    }

    public class FaturaException extends Exception{}

}