workspace-sf/force-app/main/default/objects/InformacaoBancaria__c/InformacaoBancaria__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar as informações bancárias das contas</description>
    <label>Informação bancária</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Informações bancárias</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/InformacaoBancaria__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>InformacoesBancarias</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/InformacaoBancaria__c/fields/Principal__c.field-meta.xml
<CustomField>
    <fullName>Principal__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Define se a informação bancária é a principal informação da conta relacionada.</inlineHelpText>
    <label>Principal?</label>
    <type>Checkbox</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Pagamento_de_Sinistro__c/Pagamento_de_Sinistro__c.object-meta.xml
<CustomObject>
    <label>Pagamento de Sinistro</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Pagamento de Sinistro</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pagamentos de Sinistro</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/Pagamento_de_Sinistro__c/fields/Beneficiario_da_Garantia__c.field-meta.xml
<CustomField>
    <fullName>Beneficiario_da_Garantia__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Este campo receberá o ID da conta que receberá o pagamento</description>
    <label>Beneficiário da Garantia</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Pagamentos de Sinistro</relationshipLabel>
    <relationshipName>Pagamentos_de_Sinistro</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Pagamento_de_Sinistro__c/fields/Caso_de_Sinistro__c.field-meta.xml
<CustomField>
    <fullName>Caso_de_Sinistro__c</fullName>
    <label>Caso de Sinistro</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Case.RecordTypeId</field>
            <operation>equals</operation>
            <value>Sinistro</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Pagamentos de Sinistro</relationshipLabel>
    <relationshipName>Pagamentos_de_Sinistro</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Pagamento_de_Sinistro__c/fields/Dados_Bancarios__c.field-meta.xml
<CustomField>
    <fullName>Dados_Bancarios__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dados Bancários</label>
    <referenceTo>InformacaoBancaria__c</referenceTo>
    <relationshipLabel>Pagamentos de Sinistro</relationshipLabel>
    <relationshipName>Pagamentos_de_Sinistro</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Pagamento_de_Sinistro__c/fields/Data_de_pagamento__c.field-meta.xml
<CustomField>
    <fullName>Data_de_pagamento__c</fullName>
    <label>Data de pagamento;</label>
    <type>Date</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Pagamento_de_Sinistro__c/fields/OP_SAP__c.field-meta.xml
<CustomField>
    <fullName>OP_SAP__c</fullName>
    <externalId>true</externalId>
    <label>OP SAP</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Pagamento_de_Sinistro__c/fields/Requisicao_de_Pagamento__c.field-meta.xml
<CustomField>
    <fullName>Requisicao_de_Pagamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>campo que terá o vinculo com a requisição de pagamento</description>
    <inlineHelpText>Identificador da requisição de pagamento</inlineHelpText>
    <label>Requisição de Pagamento</label>
    <referenceTo>Requisicao_de_Pagamento__c</referenceTo>
    <relationshipLabel>Pagamentos de Sinistro</relationshipLabel>
    <relationshipName>Pagamentos_de_Sinistro</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Pagamento_de_Sinistro__c/fields/Sinistro_com_Pendencias__c.field-meta.xml
<CustomField>
    <fullName>Sinistro_com_Pendencias__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sinistro com Pendências</label>
    <type>Checkbox</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Pagamento_de_Sinistro__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pendente</fullName>
            </value>
            <value>
                <fullName>Liberado</fullName>
            </value>
            <value>
                <fullName>OP em criação</fullName>
            </value>
            <value>
                <fullName>OP criada</fullName>
            </value>
            <value>
                <fullName>Em aprovação</fullName>
            </value>
            <value>
                <fullName>Aprovada</fullName>
            </value>
            <value>
                <fullName>Rejeitada</fullName>
            </value>
            <value>
                <fullName>Pago</fullName>
            </value>
            <value>
                <fullName>Erro</fullName>
            </value>
            <value>
                <fullName>Em pagamento</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/Pagamento_de_Sinistro__c/fields/Tipo_de_Aprova_o__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Aprova_o__c</fullName>
    <label>Tipo de Aprovação</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Alçada Salesforce</fullName>
            </value>
            <value>
                <fullName>Alçada SAP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/Pagamento_de_Sinistro__c/fields/Tipo_de_OP__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_OP__c</fullName>
    <label>Tipo de OP</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Registro</fullName>
            </value>
            <value>
                <fullName>Pagamento</fullName>
            </value>
            <value>
                <fullName>Operacional</fullName>
            </value>
            <value>
                <fullName>Indenização</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/Pagamento_de_Sinistro__c/fields/Valor_total_a_ser_indenizado__c.field-meta.xml
<CustomField>
    <fullName>Valor_total_a_ser_indenizado__c</fullName>
    <label>Valor total a ser indenizado</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Currency</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Parceiro__c/Parceiro__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar as informações dos parceiros da Porto</description>
    <label>Parceiro</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parceiros</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/Parceiro__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Parceiros</relationshipLabel>
    <relationshipName>Parceiro</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Parceiro__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Em Criação</fullName>
                <default>true</default>
                <label>Em Criação</label>
            </value>
            <value>
                <fullName>Ativo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/ProdutoParceiro__c/ProdutoParceiro__c.object-meta.xml
<CustomObject>
    <description>Objeto de relacionamento entre o parceiro e o produto</description>
    <label>Produto do parceiro</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número do Produto do Parceiro</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Produtos do parceiro</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/ProdutoParceiro__c/fields/CodigoProdutoParceiro__c.field-meta.xml
<CustomField>
    <fullName>CodigoProdutoParceiro__c</fullName>
    <description>Esse campo terá a descrição do código do produto no parceiro (no caso da Renner, seria V0003065 para o CCR e V0003064 para o EP).</description>
    <label>Código do Produto no Parceiro</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/ProdutoParceiro__c/fields/Parceiro__c.field-meta.xml
<CustomField>
    <fullName>Parceiro__c</fullName>
    <label>Parceiro</label>
    <referenceTo>Parceiro__c</referenceTo>
    <relationshipLabel>Produtos do parceiro</relationshipLabel>
    <relationshipName>ProdutosParceiro</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/ProdutoParceiro__c/fields/Valor_do_Atendimento__c.field-meta.xml
<CustomField>
    <fullName>Valor_do_Atendimento__c</fullName>
    <label>Valor do Atendimento</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Requisicao_de_Pagamento__c/Requisicao_de_Pagamento__c.object-meta.xml
<CustomObject>
    <label>Requisição de Pagamento</label>
    <nameField>
        <displayFormat>RP-{0000}</displayFormat>
        <label>Requisição de Pagamento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requisições de Pagamento</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/Requisicao_de_Pagamento__c/fields/data_de_pagamento__c.field-meta.xml
<CustomField>
    <fullName>data_de_pagamento__c</fullName>
    <label>Data de Pagamento</label>
    <type>Date</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Requisicao_de_Pagamento__c/fields/Data_Programada_de_Pagamento__c.field-meta.xml
<CustomField>
    <fullName>Data_Programada_de_Pagamento__c</fullName>
    <label>Data Programada de Pagamento</label>
    <type>Date</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Requisicao_de_Pagamento__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pendente</fullName>
            </value>
            <value>
                <fullName>Enviar p/ Financeiro</fullName>
            </value>
            <value>
                <fullName>Enviado p/ Financeiro</fullName>
            </value>
            <value>
                <fullName>Em aprovação</fullName>
            </value>
            <value>
                <fullName>Aprovada</fullName>
            </value>
            <value>
                <fullName>Enviar p/ Tesouraria</fullName>
            </value>
            <value>
                <fullName>Enviado p/ Tesouraria</fullName>
            </value>
            <value>
                <fullName>OP Em criação</fullName>
            </value>
            <value>
                <fullName>OP criada</fullName>
            </value>
            <value>
                <fullName>Rejeitada</fullName>
            </value>
            <value>
                <fullName>Pago</fullName>
            </value>
            <value>
                <fullName>Erro</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
            <value>
                <fullName>Em Pagamento</fullName>
            </value>
            <value>
                <fullName>Enviar para Registro Financeiro</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/classes/CriarPagamentoSinistro.cls
//PLV-3918 Inicio
public class CriarPagamentoSinistro  {
	public static void inserirPagamentoSinistro(Set<Id> listIds){
		Pagamento_de_Sinistro__c pgSinistro = new Pagamento_de_Sinistro__c();

		List<Case> listCaso = [select Id, Parceiro__c, Parceiro__r.conta__c, ProdutoContratoFormula__c from Case where Id in : (listIds) ];
		
		Case casoObj = listCaso[0];
				
		List<ProdutoParceiro__c> produtoParceiro = [select Id, Valor_do_Atendimento__c, CurrencyIsoCode from ProdutoParceiro__c where  CodigoProdutoParceiro__c  =: casoObj.ProdutoContratoFormula__c and  Parceiro__c =: casoObj.Parceiro__c ]; //PLV-4826 - Inicio/Fim
					
		List<InformacaoBancaria__c> listInformacaobancaria  = [select Id from InformacaoBancaria__c where Conta__c =: casoObj.Parceiro__r.conta__c and Principal__c = true];
		
		List<Pagamento_de_Sinistro__c> listPgSinistro = [select Id from Pagamento_de_Sinistro__c where Caso_de_Sinistro__c =: casoObj.Id];

		if(listPgSinistro.isEmpty()){
			pgSinistro.Caso_de_Sinistro__c				= casoObj.Id;
			pgSinistro.Dados_Bancarios__c				= !listInformacaobancaria.isEmpty() ? listInformacaobancaria[0].Id : null;//PLV-4826 - Inicio/Fim
			pgSinistro.Beneficiario_da_Garantia__c		= casoObj.Parceiro__r.conta__c;			
			pgSinistro.Valor_total_a_ser_indenizado__c	= !produtoParceiro.isEmpty() ? produtoParceiro[0].Valor_do_Atendimento__c : null; //PLV-4826 - Inicio/Fim
			pgSinistro.CurrencyIsoCode					= !produtoParceiro.isEmpty() ? produtoParceiro[0].CurrencyIsoCode : null; //PLV-4826 - Inicio/Fim
			pgSinistro.Tipo_de_Aprova_o__c				= 'Alçada SAP';
			pgSinistro.Tipo_de_OP__c					= 'Operacional';            
			pgSinistro.OP_SAP__c						= null;
			pgSinistro.Status__c						= 'Pendente';
			pgSinistro.Data_Programada_de_Pagamento__c	= null;                           
			pgSinistro.Data_de_pagamento__c				= null;                                      
			pgSinistro.Requisicao_de_Pagamento__c		= null;
			pgSinistro.Sinistro_com_Pendencias__c		= False;

			System.debug('casoObj.Id = '+ casoObj.Id);
		
			upsert pgSinistro;
		}
			
	}
}
//PLV-3918 Fim