workspace-sf/force-app/main/default/objects/Integracao__c/Integracao__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar os eventos de integração com outros sistemas</description>
    <label>Integração</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Integrações</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/Integracao__c/fields/DeveloperName__c.field-meta.xml
<CustomField>
    <fullName>DeveloperName__c</fullName>
    <label>Developer name</label>
    <length>128</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

workspace-sf/force-app/main/default/objects/Integracao__c/fields/UltimaExecucao__c.field-meta.xml
<CustomField>
    <fullName>UltimaExecucao__c</fullName>
    <label>Última Execução</label>
    <type>DateTime</type>
</CustomField>

workspace-sf/force-app/main/default/classes/IntegracaoDAO.cls
/**
 * IntegracaoDAO
 * @author Fernando Barcellos @ 01/12/2017
 *
 **/
public class IntegracaoDAO {
	
	private static final IntegracaoDAO instance = new IntegracaoDAO();
	
	public static IntegracaoDAO getInstance() {
		return instance;
	}

	private IntegracaoDAO() { }

	public Integracao__c buscarIntegracaoPorId(Id idIntegracao) {
		return [
			SELECT
				Id,
				Name,
				DeveloperName__c,
				UltimaExecucao__c
			FROM
				Integracao__c
			WHERE
				Id =: idIntegracao
			LIMIT 1
		];
	}

	public Integracao__c buscarIntegracaoPorNomeObjeto(String nomeObjeto) {
		return [
			SELECT
				Id,
				Name,
				DeveloperName__c,
				UltimaExecucao__c
			FROM
				Integracao__c
			WHERE
				DeveloperName__c =: nomeObjeto
			LIMIT 1
		];
	}
}