workspace-sf/force-app/main/default/objects/FaixaDevolucao__c/FaixaDevolucao__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar as faixas de devolução dos parâmetros de vigência</description>
    <label>Faixa de devolução</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Faixas de devolução</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/FaixaDevolucao__c/fields/FaixaAte__c.field-meta.xml
<CustomField>
    <fullName>FaixaAte__c</fullName>
    <inlineHelpText>Valor em anos</inlineHelpText>
    <label>Faixa até</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

workspace-sf/force-app/main/default/objects/FaixaDevolucao__c/fields/FaixaDe__c.field-meta.xml
<CustomField>
    <fullName>FaixaDe__c</fullName>
    <inlineHelpText>Valor em anos</inlineHelpText>
    <label>Faixa de</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

workspace-sf/force-app/main/default/objects/FaixaDevolucao__c/fields/FaixaDevolucao__c.field-meta.xml
<CustomField>
    <fullName>FaixaDevolucao__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Faixa de devolução</label>
    <referenceTo>FaixaDevolucao__c</referenceTo>
    <relationshipLabel>Faixas de devolução</relationshipLabel>
    <relationshipName>FaixasDevolucao</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/FaixaDevolucao__c/fields/ParametroVigencia__c.field-meta.xml
<CustomField>
    <fullName>ParametroVigencia__c</fullName>
    <label>Parâmetro de vigência</label>
    <referenceTo>ParametroVigencia__c</referenceTo>
    <relationshipLabel>Faixas de devolução</relationshipLabel>
    <relationshipName>FaixasDevolucao</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/FaixaDevolucao__c/recordTypes/ProdutoComercial.recordType-meta.xml
<RecordType>
    <fullName>ProdutoComercial</fullName>
    <active>true</active>
    <label>Produto comercial</label>
</RecordType>

workspace-sf/force-app/main/default/objects/ParametroVigencia__c/ParametroVigencia__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar os parâmetros de vigência de um produto</description>
    <label>Parâmetro de vigência</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parâmetros de vigência</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/ParametroVigencia__c/fields/IndiceReajuste__c.field-meta.xml
<CustomField>
    <fullName>IndiceReajuste__c</fullName>
    <label>Índice de reajuste</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>IGP-M</fullName>
            </value>
            <value>
                <fullName>IPCA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/ParametroVigencia__c/fields/ModeloResgate__c.field-meta.xml
<CustomField>
    <fullName>ModeloResgate__c</fullName>
    <label>Modelo de resgate</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Percentual do capital</fullName>
            </value>
            <value>
                <fullName>Valor de prêmio pago</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/ParametroVigencia__c/fields/ParametroVigencia__c.field-meta.xml
<CustomField>
    <fullName>ParametroVigencia__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parâmetro de vigência</label>
    <referenceTo>ParametroVigencia__c</referenceTo>
    <relationshipLabel>Parâmetros de vigência</relationshipLabel>
    <relationshipName>ParametrosVigencia</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/ParametroVigencia__c/fields/Periodicidade__c.field-meta.xml
<CustomField>
    <fullName>Periodicidade__c</fullName>
    <label>Periodicidade</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Dias</fullName>
            </value>
            <value>
                <fullName>Anos</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/ParametroVigencia__c/fields/PeriodoCoberturaMaximo__c.field-meta.xml
<CustomField>
    <fullName>PeriodoCoberturaMaximo__c</fullName>
    <label>Período de cobertura máximo</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

workspace-sf/force-app/main/default/objects/ParametroVigencia__c/fields/PeriodoCoberturaMinimo__c.field-meta.xml
<CustomField>
    <fullName>PeriodoCoberturaMinimo__c</fullName>
    <label>Período de cobertura mínimo</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

workspace-sf/force-app/main/default/objects/ParametroVigencia__c/fields/PeriodoMaximoInadimplencia__c.field-meta.xml
<CustomField>
    <fullName>PeriodoMaximoInadimplencia__c</fullName>
    <description>Campo para verificar em dias o Período máximo de inadimplência. Localizado na section &quot;Informações de periódico&quot;</description>
    <inlineHelpText>Em dias</inlineHelpText>
    <label>Período máximo de inadimplência</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

workspace-sf/force-app/main/default/objects/ParametroVigencia__c/fields/PeriodoMaximoInadimplenciaPeriodica__c.field-meta.xml
<CustomField>
    <fullName>PeriodoMaximoInadimplenciaPeriodica__c</fullName>
    <description>Campo para verificar em dias o Período máximo de inadimplência. Localizado na section &quot;Informações de periódico&quot;</description>
    <inlineHelpText>Em dias</inlineHelpText>
    <label>Período máximo de Inadimplência</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

workspace-sf/force-app/main/default/objects/ParametroVigencia__c/fields/PeriodoMaximoVigencia__c.field-meta.xml
<CustomField>
    <fullName>PeriodoMaximoVigencia__c</fullName>
    <label>Período máximo de vigência</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

workspace-sf/force-app/main/default/objects/ParametroVigencia__c/fields/PeriodoMinimoVigencia__c.field-meta.xml
<CustomField>
    <fullName>PeriodoMinimoVigencia__c</fullName>
    <label>Período mínimo de vigência</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

workspace-sf/force-app/main/default/objects/ParametroVigencia__c/fields/PrazoAplicacaoReajuste__c.field-meta.xml
<CustomField>
    <fullName>PrazoAplicacaoReajuste__c</fullName>
    <inlineHelpText>Em anos</inlineHelpText>
    <label>Prazo para aplicação de reajuste</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/ParametroVigencia__c/fields/PrazoAvisarRenovacao__c.field-meta.xml
<CustomField>
    <fullName>PrazoAvisarRenovacao__c</fullName>
    <inlineHelpText>Em dias</inlineHelpText>
    <label>Prazo para avisar renovação</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

workspace-sf/force-app/main/default/objects/ParametroVigencia__c/fields/PrazoDesistenciaRenovacao__c.field-meta.xml
<CustomField>
    <fullName>PrazoDesistenciaRenovacao__c</fullName>
    <inlineHelpText>Em dias</inlineHelpText>
    <label>Prazo para desistência da renovação</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

workspace-sf/force-app/main/default/objects/ParametroVigencia__c/fields/PrazoMinimoCancelamento__c.field-meta.xml
<CustomField>
    <fullName>PrazoMinimoCancelamento__c</fullName>
    <inlineHelpText>Em anos</inlineHelpText>
    <label>Prazo mínimo de cancelamento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/ParametroVigencia__c/fields/PrazoRetornoAviso__c.field-meta.xml
<CustomField>
    <fullName>PrazoRetornoAviso__c</fullName>
    <label>Prazo para retorno do aviso</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

workspace-sf/force-app/main/default/objects/ParametroVigencia__c/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Parâmetros de vigência</relationshipLabel>
    <relationshipName>ParametrosVigencia</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/ParametroVigencia__c/fields/ProdutoRenovavel__c.field-meta.xml
<CustomField>
    <fullName>ProdutoRenovavel__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Produto renovável?</label>
    <type>Checkbox</type>
</CustomField>

workspace-sf/force-app/main/default/objects/ParametroVigencia__c/fields/QuantidadeRenovacaoesAnuencia__c.field-meta.xml
<CustomField>
    <fullName>QuantidadeRenovacaoesAnuencia__c</fullName>
    <label>Quantidade de renovações sem anuência</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

workspace-sf/force-app/main/default/objects/ParametroVigencia__c/fields/RenovaEsgotamentoIndenizacao__c.field-meta.xml
<CustomField>
    <fullName>RenovaEsgotamentoIndenizacao__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Renova com esgotamento de indenização?</label>
    <type>Checkbox</type>
</CustomField>

workspace-sf/force-app/main/default/objects/ParametroVigencia__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Determinado</fullName>
            </value>
            <value>
                <fullName>Periódico</fullName>
            </value>
            <value>
                <fullName>Vitalício</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/ParametroVigencia__c/fields/TipoPeriodo__c.field-meta.xml
<CustomField>
    <fullName>TipoPeriodo__c</fullName>
    <label>Tipo de período</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Anos</fullName>
            </value>
            <value>
                <fullName>Dias</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/ParametroVigencia__c/fields/VigenciaMinimaRenovacao__c.field-meta.xml
<CustomField>
    <fullName>VigenciaMinimaRenovacao__c</fullName>
    <description>RVI-80 - Mudança da Label de &quot;Vigência mínima para renovação&quot; para &quot;Início de Renovação (Dias)&quot; - API name nao foi modificado. -- Uile</description>
    <inlineHelpText>Prazo antes do final da vigência, em quantidade de dias, para início do processo de renovação</inlineHelpText>
    <label>Início de Renovação (Dias)</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

workspace-sf/force-app/main/default/objects/ParametroVigencia__c/recordTypes/ProdutoComercial.recordType-meta.xml
<RecordType>
    <fullName>ProdutoComercial</fullName>
    <active>true</active>
    <label>Produto comercial</label>
</RecordType>

workspace-sf/force-app/main/default/classes/SeletorParametrosVigenciaController.cls
/**
 * Controller para o componente SeletorParametrosVigencia.cmp
 * @author Fernando Barcellos @ 07/05/2018
 *
 **/
public class SeletorParametrosVigenciaController {

	@AuraEnabled
	public static List<ParametroVigencia__c> buscarParametrosVigencia(Id idProduto) {
		Product2 produtoComercial = ProductBO.getInstance().buscarProdutos(new Set<Id>{ idProduto }, false)[0];
		List<ParametroVigencia__c> parametrosVigenciaProdutoTec = ProductDAO.getInstance().buscarParametrosVigencia(produtoComercial.ProdutoTecnico__c);
		return parametrosVigenciaProdutoTec;
	}

	@AuraEnabled
	public static Id clonarParametroVigencia(Id idProdutoComercial, Id idParametroVigencia) {
		try {

			List<ParametroVigencia__c> parametrosVigenciaRemover = [SELECT Id FROM ParametroVigencia__c WHERE Produto__c =: idProdutoComercial];
			//List<FaixaDevolucao__c> faixasDevolucaoRemover = [SELECT Id FROM FaixaDevolucao__c WHERE ParametroVigencia__c IN : parametrosVigenciaRemover];

			delete parametrosVigenciaRemover;
			//delete faixasDevolucaoRemover;

			Product2 produtoComercial = [SELECT Id, RecordTypeId FROM Product2 WHERE Id =: idProdutoComercial LIMIT 1];
			System.debug('::: produtoComercial: ' + produtoComercial);

			ParametroVigencia__c parametroVigenciaExistente = [SELECT Id, Name, RecordTypeId, IdadeMaximaRenovacao__c, IndiceReajuste__c, ModeloResgate__c, ParametroVigencia__c, Periodicidade__c, PeriodoCoberturaMinimo__c, PeriodoCoberturaMaximo__c, PeriodoMaximoInadimplenciaPeriodica__c, PeriodoMaximoVigencia__c, PeriodoMinimoVigencia__c, PrazoAplicacaoReajuste__c, PrazoAvisarRenovacao__c, PrazoDesistenciaRenovacao__c, PrazoMinimoCancelamento__c, PrazoRetornoAviso__c, Produto__c, ProdutoRenovavel__c, QuantidadeRenovacaoesAnuencia__c, RenovaEsgotamentoIndenizacao__c, Tipo__c, TipoPeriodo__c, VigenciaMinimaRenovacao__c, PeriodoMaximoInadimplencia__c  FROM ParametroVigencia__c WHERE Id =: idParametroVigencia LIMIT 1];
			System.debug('::: parametroVigenciaExistente: ' + parametroVigenciaExistente);

			ParametroVigencia__c parametroVigenciaClone = parametroVigenciaExistente.clone();
			parametroVigenciaClone.RecordTypeId = RecordTypeBO.buscarTipoRegistro('ParametroVigencia__c', 'ProdutoComercial').Id;
			parametroVigenciaClone.Produto__c = produtoComercial.Id;
			parametroVigenciaClone.ParametroVigencia__c = parametroVigenciaExistente.Id;
			parametroVigenciaClone.PeriodoMaximoInadimplencia__c = parametroVigenciaExistente.PeriodoMaximoInadimplencia__c;
			insert parametroVigenciaClone;

			List<FaixaDevolucao__c> faixasDevolucaoClone = new List<FaixaDevolucao__c>();
			List<FaixaDevolucao__c> faixasDevolucaoExistentes = [SELECT Id, FaixaDe__c, FaixaAte__c, FaixaDevolucao__c, Name, ParametroVigencia__c, Percentual__c, RecordTypeId FROM FaixaDevolucao__c WHERE ParametroVigencia__c =: parametroVigenciaExistente.Id];

			if (faixasDevolucaoExistentes.size() > 0) {
				for (FaixaDevolucao__c faixaDevolucaoOriginal : faixasDevolucaoExistentes) {
					FaixaDevolucao__c faixaDevolucao = faixaDevolucaoOriginal.clone();
					faixaDevolucao.RecordTypeId = RecordTypeBO.buscarTipoRegistro('FaixaDevolucao__c', 'ProdutoComercial').Id;
					faixaDevolucao.ParametroVigencia__c = parametroVigenciaClone.Id;
					faixasDevolucaoClone.add(faixaDevolucao);
				}
				insert faixasDevolucaoClone;
			}

			//System.debug('::: parametroVigenciaClone: ' + parametroVigenciaClone);

			return parametroVigenciaClone.Id;
		}
		catch(Exception e) {
			System.debug('::: ERR: ' + e.getLineNumber() + ' @ ' + e.getMessage());
			return null;
		}
	}

}