workspace-sf/force-app/main/default/objects/Pergunta__c/Pergunta__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar o cadastro de perguntas</description>
    <label>Questão de Risco</label>
    <nameField>
        <label>Nome da Pergunta</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questões de Risco</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/Pergunta__c/fields/OpcoesResposta__c.field-meta.xml
<CustomField>
    <fullName>OpcoesResposta__c</fullName>
    <inlineHelpText>Colocar os valores separados por ;</inlineHelpText>
    <label>Opções da lista</label>
    <type>TextArea</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Pergunta__c/fields/Pergunta__c.field-meta.xml
<CustomField>
    <fullName>Pergunta__c</fullName>
    <label>Pergunta</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Pergunta__c/fields/TipoResposta__c.field-meta.xml
<CustomField>
    <fullName>TipoResposta__c</fullName>
    <label>Tipo de dado da resposta</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Booleano</fullName>
            </value>
            <value>
                <fullName>Data</fullName>
            </value>
            <value>
                <fullName>Opção</fullName>
                <label>Lista Fixa</label>
            </value>
            <value>
                <fullName>Moeda</fullName>
            </value>
            <value>
                <fullName>Número</fullName>
            </value>
            <value>
                <fullName>Texto</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/PerguntaQuestionario__c/PerguntaQuestionario__c.object-meta.xml
<CustomObject>
    <description>Objeto de relacionamento entre o questionário e a pergunta</description>
    <label>Pergunta do questionário de risco</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número da pergunta do questionário</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Perguntas do questionário de risco</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/PerguntaQuestionario__c/fields/Numero__c.field-meta.xml
<CustomField>
    <fullName>Numero__c</fullName>
    <label>Ordenação</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

workspace-sf/force-app/main/default/objects/PerguntaQuestionario__c/fields/Obrigatorio__c.field-meta.xml
<CustomField>
    <fullName>Obrigatorio__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indica se a pergunta deve ser respondida obrigatoriamente</description>
    <label>Obrigatório</label>
    <type>Checkbox</type>
</CustomField>

workspace-sf/force-app/main/default/objects/PerguntaQuestionario__c/fields/Pergunta__c.field-meta.xml
<CustomField>
    <fullName>Pergunta__c</fullName>
    <label>Pergunta</label>
    <referenceTo>Pergunta__c</referenceTo>
    <relationshipLabel>Perguntas do questionário</relationshipLabel>
    <relationshipName>PerguntasQuestionario</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/PerguntaQuestionario__c/fields/PerguntasOpcao__c.field-meta.xml
<CustomField>
    <fullName>PerguntasOpcao__c</fullName>
    <label>Perguntas por opção</label>
    <type>TextArea</type>
</CustomField>

workspace-sf/force-app/main/default/objects/PerguntaQuestionario__c/fields/ProximaPergunta__c.field-meta.xml
<CustomField>
    <fullName>ProximaPergunta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Próxima pergunta</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Questionario__c</field>
            <operation>equals</operation>
            <valueField>PerguntaQuestionario__c.Questionario__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PerguntaQuestionario__c</referenceTo>
    <relationshipName>PerguntasQuestionario</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/PerguntaQuestionario__c/fields/Questionario__c.field-meta.xml
<CustomField>
    <fullName>Questionario__c</fullName>
    <label>Questionário de risco</label>
    <referenceTo>Questionario__c</referenceTo>
    <relationshipLabel>Perguntas do questionário</relationshipLabel>
    <relationshipName>PerguntasQuestionario</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Questionario__c/Questionario__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar o cadastro dos questionários</description>
    <label>Questionário de Risco</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questionário de Risco</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/classes/PerguntaQuestionarioDAO.cls
/**
 * PerguntaQuestionarioDAO
 * @author Fernando Barcellos @ 20/12/2017
 *
 **/
 public class PerguntaQuestionarioDAO {
 	
 	private static final PerguntaQuestionarioDAO instance = new PerguntaQuestionarioDAO();
 	
 	public static PerguntaQuestionarioDAO getInstance() {
 		return instance;
 	}

 	private PerguntaQuestionarioDAO() { }

 	public PerguntaQuestionario__c buscarPerguntaQuestionario(String idPerguntaQuestionario) {
 		return [
 			SELECT
				Id,
				Name,
				Questionario__c,
				Questionario__r.Name,
				Pergunta__c,
				Pergunta__r.Name,
				Pergunta__r.TipoResposta__c,
				Pergunta__r.OpcoesResposta__c,
				Obrigatorio__c, // PLV-4797 INICIO/FIM SYS4B ODEMIR
				Numero__c,
				ProximaPergunta__c,
				PerguntasOpcao__c
			FROM
				PerguntaQuestionario__c
			WHERE
				Id =: idPerguntaQuestionario
				AND (ProximaPergunta__c = NULL OR ProximaPergunta__c = '')
			LIMIT 1
		];
 	}

 	//public List<PerguntaQuestionario__c> buscarTodasPerguntasQuestionario(String idQuestionario) {
	public List<PerguntaQuestionario__c> buscarTodasPerguntasQuestionario(String idquestionario) { //RVI-138 INICIO-FIM FIX01
 		return [
 			SELECT
 				Id,
 				Name,
 				Questionario__c,
 				Pergunta__c,
 				Pergunta__r.Name,
 				Numero__c,
 				ProximaPergunta__c,
 				PerguntasOpcao__c
 			FROM
 				PerguntaQuestionario__c
 			WHERE
 				//Questionario__c =: idQuestionario 
				Questionario__c =: idquestionario //RVI-138 INICIO-FIM FIX01
 			ORDER BY 
 				Numero__c ASC
 		];
 	}
}