workspace-sf/force-app/main/default/objects/Pergunta__c/Pergunta__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar o cadastro de perguntas</description>
    <label>Questão de Risco</label>
    <nameField>
        <label>Nome da Pergunta</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questões de Risco</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/Pergunta__c/fields/Pergunta__c.field-meta.xml
<CustomField>
    <fullName>Pergunta__c</fullName>
    <label>Pergunta</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Pergunta__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rascunho</fullName>
                <default>true</default>
                <label>Rascunho</label>
            </value>
            <value>
                <fullName>Ativo</fullName>
            </value>
            <value>
                <fullName>Inativo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/Pergunta__c/fields/TipoResposta__c.field-meta.xml
<CustomField>
    <fullName>TipoResposta__c</fullName>
    <label>Tipo de dado da resposta</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Booleano</fullName>
            </value>
            <value>
                <fullName>Data</fullName>
            </value>
            <value>
                <fullName>Opção</fullName>
                <label>Lista Fixa</label>
            </value>
            <value>
                <fullName>Moeda</fullName>
            </value>
            <value>
                <fullName>Número</fullName>
            </value>
            <value>
                <fullName>Texto</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/PerguntaQuestionario__c/PerguntaQuestionario__c.object-meta.xml
<CustomObject>
    <description>Objeto de relacionamento entre o questionário e a pergunta</description>
    <label>Pergunta do questionário de risco</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número da pergunta do questionário</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Perguntas do questionário de risco</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/PerguntaQuestionario__c/fields/Pergunta__c.field-meta.xml
<CustomField>
    <fullName>Pergunta__c</fullName>
    <label>Pergunta</label>
    <referenceTo>Pergunta__c</referenceTo>
    <relationshipLabel>Perguntas do questionário</relationshipLabel>
    <relationshipName>PerguntasQuestionario</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/RespostaQuestionario__c/RespostaQuestionario__c.object-meta.xml
<CustomObject>
    <description>Objeto de relacionamento entre a pergunta e a resposta.</description>
    <label>Resposta do questionário</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Respostas do questionário</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/RespostaQuestionario__c/fields/PerguntaQuestionario__c.field-meta.xml
<CustomField>
    <fullName>PerguntaQuestionario__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pergunta do questionário</label>
    <referenceTo>PerguntaQuestionario__c</referenceTo>
    <relationshipLabel>Respostas do questionário</relationshipLabel>
    <relationshipName>RespostasQuestionario</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/RespostaQuestionario__c/fields/Resposta__c.field-meta.xml
<CustomField>
    <fullName>Resposta__c</fullName>
    <label>Resposta</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

workspace-sf/force-app/main/default/objects/RespostaQuestionario__c/fields/SeguradoProposta__c.field-meta.xml
<CustomField>
    <fullName>SeguradoProposta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Segurado da proposta</label>
    <referenceTo>SeguradoProposta__c</referenceTo>
    <relationshipLabel>Respostas do questionário</relationshipLabel>
    <relationshipName>RespostasQuestionario</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/RespostaQuestionario__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aberto</fullName>
            </value>
            <value>
                <fullName>Fechado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/SeguradoProposta__c/SeguradoProposta__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar os segurados da proposta</description>
    <label>Segurado da proposta</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Segurados da proposta</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/classes/QuestionarioAnaliseRiscoTest.cls
/**
 * Created by Alessandro Ponte on 28/06/2018.
 */

@IsTest
private class QuestionarioAnaliseRiscoTest {

  // @TestSetup
  // static void testSetup(){
  //   TestDataFactory.gerarDadosSetup();
  //   TestDataFactory.gerarProposta();
  // }

  // @IsTest
  // static void testBuscarListVidaProposta() {

  //   Quote proposta = [SELECT Id FROM Quote];

  //   Test.startTest();    
  //   List<SeguradoProposta__c> listVidaProposta = QuestionarioAnaliseRiscoController.buscarListVidaProposta(proposta.Id); 
  //   System.assert(listVidaProposta.size() > 0);    
  //   Test.stopTest();
  // }

  // @IsTest
  // static void testBuscarPerguntas(){
  //   Quote proposta = [SELECT Id FROM Quote];

  //   Test.startTest();
  //   String listPerguntasQuestionarioString = QuestionarioAnaliseRiscoController.buscarPerguntas(proposta.Id);
  //   List<QuestionarioAnaliseRiscoController.WrapperQuestionario> listWrapperQuestionario = (List<QuestionarioAnaliseRiscoController.WrapperQuestionario>) JSON.deserialize(listPerguntasQuestionarioString, List<QuestionarioAnaliseRiscoController.WrapperQuestionario>.class);

  //   System.assert(listWrapperQuestionario.size() > 0);

  //   Test.stopTest();
  // }

  // @IsTest
  // static void testSalvarRespostaQuestionario(){
  //   PerguntaQuestionario__c perguntaQuestionario = [SELECT Id FROM PerguntaQuestionario__c WHERE Pergunta__r.TipoResposta__c = 'Data'];    
  //   SeguradoProposta__c vidaProposta = [SELECT Id FROM SeguradoProposta__c];
  //   RespostaQuestionario__c respostaQuestionario = new RespostaQuestionario__c(
  //       PerguntaQuestionario__c = perguntaQuestionario.Id,
  //       SeguradoProposta__c = vidaProposta.Id,
  //       Resposta__c = String.valueOf(System.today()),
  //       Status__c = 'Aberto'
  //   );

  //   Test.startTest();
  //   List<RespostaQuestionario__c> listRespostaQuestionarios = QuestionarioAnaliseRiscoController.salvarRespostaQuestionario(new List<RespostaQuestionario__c>{respostaQuestionario});
  //   System.assert(listRespostaQuestionarios.size() > 0);
  //   System.assert(listRespostaQuestionarios[0].Id != null);

  //   Test.stopTest();
  // }
}