workspace-sf/force-app/main/default/objects/Pergunta__c/Pergunta__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar o cadastro de perguntas</description>
    <label>Questão de Risco</label>
    <nameField>
        <label>Nome da Pergunta</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questões de Risco</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/Pergunta__c/fields/OpcoesResposta__c.field-meta.xml
<CustomField>
    <fullName>OpcoesResposta__c</fullName>
    <inlineHelpText>Colocar os valores separados por ;</inlineHelpText>
    <label>Opções da lista</label>
    <type>TextArea</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Pergunta__c/fields/Pergunta__c.field-meta.xml
<CustomField>
    <fullName>Pergunta__c</fullName>
    <label>Pergunta</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Pergunta__c/fields/TipoResposta__c.field-meta.xml
<CustomField>
    <fullName>TipoResposta__c</fullName>
    <label>Tipo de dado da resposta</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Booleano</fullName>
            </value>
            <value>
                <fullName>Data</fullName>
            </value>
            <value>
                <fullName>Opção</fullName>
                <label>Lista Fixa</label>
            </value>
            <value>
                <fullName>Moeda</fullName>
            </value>
            <value>
                <fullName>Número</fullName>
            </value>
            <value>
                <fullName>Texto</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/PerguntaQuestionario__c/PerguntaQuestionario__c.object-meta.xml
<CustomObject>
    <description>Objeto de relacionamento entre o questionário e a pergunta</description>
    <label>Pergunta do questionário de risco</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número da pergunta do questionário</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Perguntas do questionário de risco</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/PerguntaQuestionario__c/fields/Pergunta__c.field-meta.xml
<CustomField>
    <fullName>Pergunta__c</fullName>
    <label>Pergunta</label>
    <referenceTo>Pergunta__c</referenceTo>
    <relationshipLabel>Perguntas do questionário</relationshipLabel>
    <relationshipName>PerguntasQuestionario</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/PerguntaQuestionario__c/fields/PerguntasOpcao__c.field-meta.xml
<CustomField>
    <fullName>PerguntasOpcao__c</fullName>
    <label>Perguntas por opção</label>
    <type>TextArea</type>
</CustomField>

workspace-sf/force-app/main/default/objects/PerguntaQuestionario__c/fields/Questionario__c.field-meta.xml
<CustomField>
    <fullName>Questionario__c</fullName>
    <label>Questionário de risco</label>
    <referenceTo>Questionario__c</referenceTo>
    <relationshipLabel>Perguntas do questionário</relationshipLabel>
    <relationshipName>PerguntasQuestionario</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Questionario__c/Questionario__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar o cadastro dos questionários</description>
    <label>Questionário de Risco</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questionário de Risco</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/classes/DependenciaPerguntasController.cls
/**
 * DependenciaPerguntasController
 * @author Fernando Barcellos @ 19/12/2017
 *
 **/
public with sharing class DependenciaPerguntasController {

	@AuraEnabled
	public static String buscarPerguntasQuestionario2(String idPerguntaQuestionario) {
		String resposta = '';
		Map<Object, Object> mapResposta = new Map<Object, Object>();

		PerguntaQuestionario__c perguntaQuestionario = PerguntaQuestionarioDAO.getInstance().buscarPerguntaQuestionario(idPerguntaQuestionario);
		if (perguntaQuestionario == null) {
			throw new AuraHandledException('NSFW name detected.');
		}
		String tipoResposta = perguntaQuestionario.Pergunta__r.TipoResposta__c;

		if (tipoResposta == 'Opção') {
			List<PerguntaQuestionario__c> todasPerguntasQuestionario = PerguntaQuestionarioDAO.getInstance().buscarTodasPerguntasQuestionario(perguntaQuestionario.Questionario__c);
			List<String> perguntasQuestionario = new List<String>();

			// ver opções possíveis
			mapResposta.put('opcoes', perguntaQuestionario.Pergunta__r.OpcoesResposta__c.split(';'));

			// ver se já existe 
			if (perguntaQuestionario.PerguntasOpcao__c != null) {
				String[] perguntasOpcao = perguntaQuestionario.PerguntasOpcao__c.split(';\r\n');
				System.debug('::: perguntasOpcao: ' + JSON.serialize(perguntasOpcao));

				Map<String, String> mapOpcaoResposta = new Map<String, String>();
				for (String po : perguntasOpcao) {
					try {
						mapOpcaoResposta.put(po.split('\\|')[0].trim(), po.split('\\|')[1].trim());
					}
					catch(Exception e) {
						System.debug('::: e.getMessage(): ' + e.getMessage());
					}
				}

				if (mapOpcaoResposta.size() > 0) {
					mapResposta.put('opcoesSelecionadas', mapOpcaoResposta);
				}
			}
			
			for (PerguntaQuestionario__c pq : todasPerguntasQuestionario) {
				perguntasQuestionario.add(pq.Pergunta__r.Name);
			}
			mapResposta.put('perguntas', perguntasQuestionario);
			System.debug('::: mapResposta: ' + mapResposta);

			resposta = JSON.serializePretty(mapResposta);
		}
		else {
			throw new AuraHandledException('NSFW name detected.');
			resposta = '';
		}
		
		return resposta;
	}

	@AuraEnabled
	public static void atualizarDados(String dados, String idPerguntaQuestionario) {
		System.debug(idPerguntaQuestionario);
		List<OpcaoTO> opcoes = (List<OpcaoTO>)JSON.deserialize(dados, List<OpcaoTO>.class);

		List<String> lstPerguntasOpcao = new List<String>();

		for (OpcaoTO opcao : opcoes) {
			lstPerguntasOpcao.add(opcao.etiquetaOpcao + '|' + opcao.perguntaSelecionada);
			//System.debug('::: opcao.etiquetaOpcao: ' + opcao.etiquetaOpcao);
			//System.debug('::: opcao.perguntaSelecionada: ' + opcao.perguntaSelecionada);
		}

		PerguntaQuestionario__c pq = PerguntaQuestionarioDAO.getInstance().buscarPerguntaQuestionario(idPerguntaQuestionario);
		pq.PerguntasOpcao__c = String.join(lstPerguntasOpcao, ';\r\n') + ';';
		update pq;

		//System.debug('::: pq.PerguntasOpcao__c: ' + pq.PerguntasOpcao__c);


		//System.debug(opcoes);
	}

	public class OpcaoTO {
		public String etiquetaOpcao { get; set; }
		public String valorOpcao { get; set; }
		public String perguntaSelecionada { get; set; }
		public Long idx { get; set; }
	}
}