workspace-sf/force-app/main/default/objects/ContratanteOrcamento__c/ContratanteOrcamento__c.object-meta.xml
<CustomObject>
    <description>Objeto responsável por armazenar o cadastro dos contratantes do orçamento</description>
    <label>Contratante do orçamento</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contratantes do orçamento</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/GrupoOrcamento__c/GrupoOrcamento__c.object-meta.xml
<CustomObject>
    <description>Objeto responsável por armazenar o cadastro dos grupos de segurados do orçamento</description>
    <label>Grupo do orçamento</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grupos do orçamento</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/GrupoOrcamento__c/fields/ContratanteOrcamento__c.field-meta.xml
<CustomField>
    <fullName>ContratanteOrcamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contratante do orçamento</label>
    <referenceTo>ContratanteOrcamento__c</referenceTo>
    <relationshipLabel>Grupos do orçamento</relationshipLabel>
    <relationshipName>GruposOrcamento</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/classes/grupoOrcamentoFactory.cls
/**
 * @author AVX - Leonardo Camacho
 * @date 2019-10-17
 * @description: Grupo do Orçamento Factory Class
 * Criada para a história: PLV_2826 - Criar orçamento sem conta
 */

@isTest
public class grupoOrcamentoFactory extends SObjectFactory{

	private static GrupoOrcamento__c staticRecord;
    
    private static GrupoOrcamento__c getRecordStatic(ContratanteOrcamento__c contratante){
        
		if(staticRecord == null){
			staticRecord = new GrupoOrcamento__c(
				ContratanteOrcamento__c = contratante.Id,
                Name = 'TesteGrupoOrcamento'
            );
		}
		return staticRecord;
	}
    
    public grupoOrcamentoFactory() {

		this(
        	(ContratanteOrcamento__c) new ContratanteOrcamentoFactory().createRecord()
        );
	}

	public grupoOrcamentoFactory(ContratanteOrcamento__c contratante) {

		super(getRecordStatic(contratante));
	}
}