workspace-sf/force-app/main/default/objects/ContratanteOrcamento__c/ContratanteOrcamento__c.object-meta.xml
<CustomObject>
    <description>Objeto responsável por armazenar o cadastro dos contratantes do orçamento</description>
    <label>Contratante do orçamento</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contratantes do orçamento</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/CriticaOrcamento__c/CriticaOrcamento__c.object-meta.xml
<CustomObject>
    <description>Objeto responsável por armazenar as analises de aceitação geradas pelo ODM ou pelo Sinapse</description>
    <label>Crítica do orçamento</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número da crítica</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Críticas do orçamento</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/Endereco__c/Endereco__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar os endereços das contas</description>
    <label>Endereço</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Endereços</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/GarantiaContratanteOrcamento__c/GarantiaContratanteOrcamento__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar as garantias do contratante do orçamento</description>
    <label>Garantia do contratante do orçamento</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Garantias do contratante do orçamento</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/GarantiaContratanteOrcamento__c/fields/ContratanteOrcamento__c.field-meta.xml
<CustomField>
    <fullName>ContratanteOrcamento__c</fullName>
    <label>Contratante do orçamento</label>
    <referenceTo>ContratanteOrcamento__c</referenceTo>
    <relationshipLabel>Garantias do contratante do orçamento</relationshipLabel>
    <relationshipName>GarantiasContratanteOrcamento</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaGrupoOrcamento__c/GarantiaGrupoOrcamento__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar as garantias do grupo do orçamento</description>
    <label>Garantia do grupo do orçamento</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Garantias do grupo do orçamento</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/GarantiaGrupoOrcamento__c/fields/GrupoOrcamento__c.field-meta.xml
<CustomField>
    <fullName>GrupoOrcamento__c</fullName>
    <label>Grupo do orçamento</label>
    <referenceTo>GrupoOrcamento__c</referenceTo>
    <relationshipLabel>Garantias do grupo do orçamento</relationshipLabel>
    <relationshipName>GruposGarantiaOrcamento</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaOrcamento__c/GarantiaOrcamento__c.object-meta.xml
<CustomObject>
    <description>Objeto de relacionamento entre a garantia e a oportunidade.</description>
    <label>Garantia do orçamento</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Garantias do orçamento</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/GarantiaSeguradoOrcamento__c/GarantiaSeguradoOrcamento__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar as garantias do segurado do orçamento</description>
    <label>Garantia do segurado do orçamento</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Garantias do segurado do orçamento</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/GarantiaSeguradoOrcamento__c/fields/SeguradoOrcamento__c.field-meta.xml
<CustomField>
    <fullName>SeguradoOrcamento__c</fullName>
    <label>Segurado do orçamento</label>
    <referenceTo>SeguradoOrcamento__c</referenceTo>
    <relationshipLabel>Garantias do segurado do orçamento</relationshipLabel>
    <relationshipName>GarantiasSeguradoOrcamento</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GrupoOrcamento__c/GrupoOrcamento__c.object-meta.xml
<CustomObject>
    <description>Objeto responsável por armazenar o cadastro dos grupos de segurados do orçamento</description>
    <label>Grupo do orçamento</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grupos do orçamento</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/GrupoOrcamento__c/fields/ContratanteOrcamento__c.field-meta.xml
<CustomField>
    <fullName>ContratanteOrcamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contratante do orçamento</label>
    <referenceTo>ContratanteOrcamento__c</referenceTo>
    <relationshipLabel>Grupos do orçamento</relationshipLabel>
    <relationshipName>GruposOrcamento</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/RemuneracaoOrcamento__c/RemuneracaoOrcamento__c.object-meta.xml
<CustomObject>
    <description>Objeto de relacionamento entre a oportunidade e o tipo de remuneração.</description>
    <label>Remuneração do orçamento</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Remunerações do orçamento</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/SeguradoOrcamento__c/SeguradoOrcamento__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar os segurados do orçamento</description>
    <label>Segurado do orçamento</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Nome</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Segurados do orçamento</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/SeguradoOrcamento__c/fields/GrupoOrcamento__c.field-meta.xml
<CustomField>
    <fullName>GrupoOrcamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Grupo do orçamento</label>
    <referenceTo>GrupoOrcamento__c</referenceTo>
    <relationshipLabel>Segurados do orçamento</relationshipLabel>
    <relationshipName>SeguradosOrcamento</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/classes/Orcamento.cls
/**************************************************************************************************************************************************************************
 * 
 *  Classe estrutural de Orcamento
 *
 **************************************************************************************************************************************************************************/
public class Orcamento {
	public OrcamentoWrapper orcamentoWrapper {get; set;}
	
	public Orcamento(){
		this.orcamentoWrapper = new OrcamentoWrapper();
	}

	public class OrcamentoWrapper {

		public Opportunity sfOrcamento {get; set;}
		public List<ContratanteWrapper> contratantesWrapper {get; set;}
		public List<RemuneracaoOrcamentoWrapper> RemuneracaoOrcamentoWrapper {get; set;}
		public List<GarantiaWrapper> garantiasWrapper { get; set; }
		public List<CriticaOrcamento__c> criticas { get; set; }
		public RetornoWrapper retornoWrapper { get; set; }

		public OrcamentoWrapper(){
			this.sfOrcamento = new Opportunity();
			this.garantiasWrapper = new List<GarantiaWrapper>();
			this.contratantesWrapper = new List<Orcamento.ContratanteWrapper>();
			this.RemuneracaoOrcamentoWrapper = new List<Orcamento.RemuneracaoOrcamentoWrapper>();
			this.criticas = new List<CriticaOrcamento__c>();
			this.retornoWrapper = new RetornoWrapper();
		}
	}

	public class ContratanteWrapper {
		public ContratanteOrcamento__c sfContratante {get; set;}
		public PessoaWrapper pessoaWrapper {get; set;}
		public List<GrupoWrapper> gruposWrapper {get; set;}
		public List<GarantiaWrapper> garantiasWrapper { get; set; }
		public String chave { get; set;}

		public ContratanteWrapper(){
			this.sfContratante = new ContratanteOrcamento__c();
			this.pessoaWrapper = new PessoaWrapper();
			this.garantiasWrapper = new List<GarantiaWrapper>();
			this.gruposWrapper = new List<Orcamento.GrupoWrapper>();
		}
	}

	public class GrupoWrapper {
		public GrupoOrcamento__c sfGrupo {get; set;}
		public List<SeguradoWrapper> seguradosWrapper {get; set;}
		public List<GarantiaWrapper> garantiasWrapper { get; set; }
		public String chave { get; set;}

		public GrupoWrapper(){
			this.sfGrupo = new GrupoOrcamento__c();
			this.garantiasWrapper = new List<GarantiaWrapper>();
			this.seguradosWrapper = new List<Orcamento.SeguradoWrapper>();
		}
	}

	public class SeguradoWrapper {
		public SeguradoOrcamento__c sfSegurado {get; set;}
		public PessoaWrapper pessoaWrapper {get; set;}
		public List<GarantiaWrapper> garantiasWrapper { get; set; }
		public String chave { get; set;}

		public SeguradoWrapper(){
			this.sfSegurado = new SeguradoOrcamento__c();
			this.pessoaWrapper = new PessoaWrapper();
			this.garantiasWrapper = new List<GarantiaWrapper>();
		}
	}

	public class PessoaWrapper {
		public Account sfConta {get; set;}
		public List<Endereco__c> enderecos {get; set;}

		public PessoaWrapper(){
			this.sfConta = new Account();
			this.enderecos = new List<Endereco__c>();
		}
	}

	public class retornoWrapper{

		public String numeroApolice {get; set;}
		public String codigoEmpresa {get; set;}
		public String codigoSucursal {get; set;}
		public String codigoRamo {get; set;}
		public String tipoEndosso {get; set;}
		public RetornoOrcamentoRestTO.ValidacaoOrcamentoTO retorno  { get; set; }

		public retornoWrapper (){
			this.retorno = new RetornoOrcamentoRestTO.ValidacaoOrcamentoTO();
			this.retorno.devolutivas = new List<RetornoOrcamentoRestTO.DevolutivasTO>();
		}

	}

	public class RemuneracaoOrcamentoWrapper
	{
		public RemuneracaoOrcamento__c sfRemuneracaoOrcamento { get; set; }

		public String chave { get; set; }

		public RemuneracaoOrcamentoWrapper(){
			this.sfRemuneracaoOrcamento = new RemuneracaoOrcamento__c();
		}
	}

	public class GarantiaWrapper{

		public String sigla { get; set; }
		public GarantiaOrcamento__c sfGarantiaOrcamento { get; set; }
		public GarantiaContratanteOrcamento__c sfGarantiasContratanteOrcamento { get; set; }
		public GarantiaGrupoOrcamento__c sfGarantiaGrupoOrcamento { get; set; }
		public GarantiaSeguradoOrcamento__c sfGarantiaSeguradoOrcamento { get; set; }

	}

}