workspace-sf/force-app/main/default/objects/ContratanteOrcamento__c/ContratanteOrcamento__c.object-meta.xml
<CustomObject>
    <description>Objeto responsável por armazenar o cadastro dos contratantes do orçamento</description>
    <label>Contratante do orçamento</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contratantes do orçamento</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/ContratanteOrcamento__c/fields/Orcamento__c.field-meta.xml
<CustomField>
    <fullName>Orcamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Orçamento</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Contratantes do orçamento</relationshipLabel>
    <relationshipName>ContratantesOrcamento</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/ContratanteOrcamento__c/fields/PremioTotal__c.field-meta.xml
<CustomField>
    <fullName>PremioTotal__c</fullName>
    <label>Prêmio total</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Currency</type>
</CustomField>

workspace-sf/force-app/main/default/classes/ExpurgoContratanteOrcamento.cls
/**
 * Expurgo de dados para o Orçamento
 *  objeto: ContratanteOrcamento__c
 * caminho do objeto:
 *  ContratanteOrcamento__c
 *  > Opportunity
 * 
 * 17/02/2024
 */
public with sharing class ExpurgoContratanteOrcamento { 
 
    public List<ContratanteOrcamento__c> getDadosExpurgo(Integer qt) {
        List<ContratanteOrcamento__c> expList = new List<ContratanteOrcamento__c>(); 
        String query= 'SELECT Id '// , Name, PremioTotal__c, IsDeleted'
        +'FROM ContratanteOrcamento__c '
        +'WHERE Orcamento__r.Segmento__c = \'Massificados\' ';
    if (qt != 0) {
        query+= 'LIMIT :qt';
    }
    expList= Database.queryWithBinds(query, new Map<String,Object>{'qt' => qt}, AccessLevel.SYSTEM_MODE);
    System.debug(expList);
    return expList;
    }

    public void deleteDadosExpurgo(List<ContratanteOrcamento__c> expList) {
        // só pode executar o delete qdo não for teste pois está rodando com SeeAllData = true
        if (!Test.isRunningTest()) {
            delete (List<ContratanteOrcamento__c>)expList;
        }
    }
}