workspace-sf/force-app/main/default/objects/ContratanteOrcamento__c/ContratanteOrcamento__c.object-meta.xml
<CustomObject>
    <description>Objeto responsável por armazenar o cadastro dos contratantes do orçamento</description>
    <label>Contratante do orçamento</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contratantes do orçamento</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/ContratanteOrcamento__c/fields/CEP__c.field-meta.xml
<CustomField>
    <fullName>CEP__c</fullName>
    <label>CEP</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/ContratanteOrcamento__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contratantes do orçamento</relationshipLabel>
    <relationshipName>ContratantesOrcamento</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/ContratanteOrcamento__c/fields/Logradouro__c.field-meta.xml
<CustomField>
    <fullName>Logradouro__c</fullName>
    <label>Logradouro</label>
    <type>TextArea</type>
</CustomField>

workspace-sf/force-app/main/default/objects/ContratanteOrcamento__c/fields/TipoEndereco__c.field-meta.xml
<CustomField>
    <fullName>TipoEndereco__c</fullName>
    <label>Tipo de endereço</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Comercial</fullName>
            </value>
            <value>
                <fullName>Recado</fullName>
            </value>
            <value>
                <fullName>Residencial</fullName>
            </value>
            <value>
                <fullName>Veraneio</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/Endereco__c/Endereco__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar os endereços das contas</description>
    <label>Endereço</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Endereços</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/Endereco__c/fields/Bairro__c.field-meta.xml
<CustomField>
    <fullName>Bairro__c</fullName>
    <label>Bairro</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Endereco__c/fields/CEP__c.field-meta.xml
<CustomField>
    <fullName>CEP__c</fullName>
    <label>CEP</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Endereco__c/fields/Cidade__c.field-meta.xml
<CustomField>
    <fullName>Cidade__c</fullName>
    <label>Cidade</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Endereco__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Endereços</relationshipLabel>
    <relationshipName>Enderecos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Endereco__c/fields/EnderecoCobranca__c.field-meta.xml
<CustomField>
    <fullName>EnderecoCobranca__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Endereço de cobrança</label>
    <type>Checkbox</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Endereco__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AC</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AP</fullName>
            </value>
            <value>
                <fullName>AM</fullName>
            </value>
            <value>
                <fullName>BA</fullName>
            </value>
            <value>
                <fullName>CE</fullName>
            </value>
            <value>
                <fullName>DF</fullName>
            </value>
            <value>
                <fullName>ES</fullName>
            </value>
            <value>
                <fullName>GO</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MG</fullName>
            </value>
            <value>
                <fullName>PA</fullName>
            </value>
            <value>
                <fullName>PB</fullName>
            </value>
            <value>
                <fullName>PR</fullName>
            </value>
            <value>
                <fullName>PE</fullName>
            </value>
            <value>
                <fullName>PI</fullName>
            </value>
            <value>
                <fullName>RJ</fullName>
            </value>
            <value>
                <fullName>RN</fullName>
            </value>
            <value>
                <fullName>RS</fullName>
            </value>
            <value>
                <fullName>RO</fullName>
            </value>
            <value>
                <fullName>RR</fullName>
            </value>
            <value>
                <fullName>SC</fullName>
            </value>
            <value>
                <fullName>SP</fullName>
            </value>
            <value>
                <fullName>SE</fullName>
            </value>
            <value>
                <fullName>TO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/Endereco__c/fields/Logradouro__c.field-meta.xml
<CustomField>
    <fullName>Logradouro__c</fullName>
    <label>Logradouro</label>
    <type>TextArea</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Endereco__c/fields/MaisAtual__c.field-meta.xml
<CustomField>
    <fullName>MaisAtual__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Mais atual?</label>
    <type>Checkbox</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Endereco__c/fields/Numero__c.field-meta.xml
<CustomField>
    <fullName>Numero__c</fullName>
    <label>Número</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Endereco__c/fields/Pais__c.field-meta.xml
<CustomField>
    <fullName>Pais__c</fullName>
    <label>País</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Endereco__c/fields/TipoEndereco__c.field-meta.xml
<CustomField>
    <fullName>TipoEndereco__c</fullName>
    <label>Tipo de endereço</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Comercial</fullName>
            </value>
            <value>
                <fullName>Recado</fullName>
            </value>
            <value>
                <fullName>Residencial</fullName>
            </value>
            <value>
                <fullName>Veraneio</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/Endereco__c/fields/TipoLogradouro__c.field-meta.xml
<CustomField>
    <fullName>TipoLogradouro__c</fullName>
    <label>Tipo de logradouro</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Alameda</fullName>
            </value>
            <value>
                <fullName>Avenida</fullName>
            </value>
            <value>
                <fullName>Rua</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/Pais__c/Pais__c.object-meta.xml
<CustomObject>
    <description>Objeto responsável por armazenar os dados dos países</description>
    <label>País</label>
    <nameField>
        <label>Pais Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Países</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/classes/EnderecoBO.cls
/**
 * EnderecoBO
 * @author Fernando Barcellos @ 19/12/2017
 *
 **/
public class EnderecoBO {
	
	private static final EnderecoBO instance = new EnderecoBO();
	private static final EnderecoDAO dao = EnderecoDAO.getInstance();
	private static F5Service f5 = F5Service.getInstance();

	public static EnderecoBO getInstance() {
		return instance;
	}

	private EnderecoBO() { }

	public void desmarcarEnderecosAntigos(List<Endereco__c> lstEnderecos) {
		Set<Id> setIdsContas = new Set<Id>();
		Set<Id> setIdsEnderecosPrincipais = new Set<Id>();

		for (Endereco__c endereco : lstEnderecos) {
			if (endereco.MaisAtual__c == true && TriggerHelper.isChanged(endereco, 'MaisAtual__c')) { //PLV-2728 - Inicio/Fim - Adição de validação
				setIdsContas.add(endereco.Conta__c);
				setIdsEnderecosPrincipais.add(endereco.Id);
			}
		}

		if(setIdsContas.isEmpty()) return; //PLV-2728 - Inicio/Fim
		List<Endereco__c> lstEnderecosDesatualizados = dao.buscarEnderecosDesatualizados(setIdsContas);
		
		for (Endereco__c endereco : lstEnderecosDesatualizados) {
			if(!setIdsEnderecosPrincipais.contains(endereco.Id)){
				endereco.MaisAtual__c = false;
			}
		}
		TriggerHandler.bypass('EnderecoTriggerHandler');
		update lstEnderecosDesatualizados;
	}


	public List<ServiceTO.ListResultadoRetornoBuscaEndereco> buscarEndereco(String searchUf, String cep, String sufixo, String endereco, string cidade, string uf, string numero) 
	{
		List<ServiceTO.ListResultadoRetornoBuscaEndereco> LstRetorno = new List<ServiceTO.ListResultadoRetornoBuscaEndereco>();

		if(!String.isEmpty(searchUf)) 		// Executa busca do endereço pela UF
			LstRetorno = buscarEnderecoUF(searchUf);
		else if (!String.isEmpty(cep))		// Executa busca do endereço pelo CEP
			LstRetorno = buscarEnderecoCEP(cep, sufixo);
		else if (!String.isEmpty(endereco)) // Executa busca do endereço pelo Endereço
			LstRetorno = buscarEnderecoLogradouro(endereco, cidade, uf, numero);

		return LstRetorno;	
	}


	private List<ServiceTO.ListResultadoRetornoBuscaEndereco> buscarEnderecoUF(String uf) {
	
		ServiceTO.ObterCidadeUFTO tempDados = f5.buscarEnderecoPorUF(uf);

		List<ServiceTO.ListResultadoRetornoBuscaEndereco> LstRetorno = new List<ServiceTO.ListResultadoRetornoBuscaEndereco>();

		for (ServiceTO.ListenderecoGuiaPostalEBOTO endereco : tempDados.obterCidadeResponse.obterCidadeEBO.enderecoGuiaPostalEBO) 
		{
			ServiceTO.ListResultadoRetornoBuscaEndereco retorno = new ServiceTO.ListResultadoRetornoBuscaEndereco();

			retorno.codigoCidade     = endereco.codigoCidade;
			retorno.nomeCidade       = endereco.nomeCidade;
			retorno.unidadeFederativaCodigo = endereco.unidadeFederativaCodigo;
			retorno.cepCidade        = endereco.cepCidade;
			retorno.cepCidadeComplemento = endereco.cepComplementoCidade;

			LstRetorno.add(retorno);

		}

		return LstRetorno;

	}

	private List<ServiceTO.ListResultadoRetornoBuscaEndereco> buscarEnderecoCEP(String cep, String sufixo) {
	
		ServiceTO.ObterCidadeCEPTO tempDados = f5.buscarEnderecoPorCEP(cep, sufixo);
		List<ServiceTO.ListResultadoRetornoBuscaEndereco> 	LstRetorno = new List<ServiceTO.ListResultadoRetornoBuscaEndereco>();

		if(tempDados != null)
		{
			system.debug('HEHEHEHEHEHE' + tempDados);

			ServiceTO.ListResultadoRetornoBuscaEndereco retorno = new ServiceTO.ListResultadoRetornoBuscaEndereco();

			retorno.codigoLogradouro 		= tempDados.obterEnderecoPorCEPResponse.enderecosGuiaPostalEBO.enderecoGuiaPostalEBO.codigoLogradouro;
			retorno.tipoLogradouro   		= tempDados.obterEnderecoPorCEPResponse.enderecosGuiaPostalEBO.enderecoGuiaPostalEBO.enderecoCompleto.tipoLogradouro;
			retorno.nomelogradouro   		= tempDados.obterEnderecoPorCEPResponse.enderecosGuiaPostalEBO.enderecoGuiaPostalEBO.enderecoCompleto.logradouro;
			retorno.codigoCidade     		= tempDados.obterEnderecoPorCEPResponse.enderecosGuiaPostalEBO.enderecoGuiaPostalEBO.codigoCidade;
			retorno.nomeCidade       		= tempDados.obterEnderecoPorCEPResponse.enderecosGuiaPostalEBO.enderecoGuiaPostalEBO.enderecoCompleto.cidade;
			retorno.unidadeFederativaCodigo = tempDados.obterEnderecoPorCEPResponse.enderecosGuiaPostalEBO.enderecoGuiaPostalEBO.enderecoCompleto.uf;
			retorno.cepCidade        		= tempDados.obterEnderecoPorCEPResponse.enderecosGuiaPostalEBO.enderecoGuiaPostalEBO.cepCidade;
			retorno.cepCidadeComplemento 	= tempDados.obterEnderecoPorCEPResponse.enderecosGuiaPostalEBO.enderecoGuiaPostalEBO.cepComplementoCidade;
			retorno.codigoBairro     		= tempDados.obterEnderecoPorCEPResponse.enderecosGuiaPostalEBO.enderecoGuiaPostalEBO.codigoBairro;
			retorno.nomeBairro       		= tempDados.obterEnderecoPorCEPResponse.enderecosGuiaPostalEBO.enderecoGuiaPostalEBO.enderecoCompleto.bairro;
			retorno.cep              		= tempDados.obterEnderecoPorCEPResponse.enderecosGuiaPostalEBO.enderecoGuiaPostalEBO.enderecoCompleto.cep;
			retorno.cepcomplemento   		= tempDados.obterEnderecoPorCEPResponse.enderecosGuiaPostalEBO.enderecoGuiaPostalEBO.enderecoCompleto.complementocep;
			
			LstRetorno.add(retorno);
		}

		return LstRetorno;
	}


	private List<ServiceTO.ListResultadoRetornoBuscaEndereco> buscarEnderecoLogradouro(String endereco, string cidade, string uf, string numero) {
	
		ServiceTO.ObterCidadeLogradouroTO tempDados = f5.buscarEnderecoPorLogradouro(endereco, cidade, uf, numero);

		List<ServiceTO.ListResultadoRetornoBuscaEndereco> LstRetorno = new List<ServiceTO.ListResultadoRetornoBuscaEndereco>();


		for (ServiceTO.LstEnderecosDetalheTO det : tempDados.obterLogradourosPorLogradouroResponse.enderecosGuiaPostalLocal.enderecoGuiaPostalLocal)
		 {

			ServiceTO.ListResultadoRetornoBuscaEndereco retorno = new ServiceTO.ListResultadoRetornoBuscaEndereco();

			retorno.codigoLogradouro = det.codigoLogradouro;
			retorno.tipoLogradouro   = det.tipoLogradouro;
			retorno.nomelogradouro   = det.nomelogradouro;
			retorno.codigoCidade     = det.cidade.codigoCidadeLocalidade;
			retorno.nomeCidade       = det.cidade.nomeCidadeNoGuiaPostal;
			retorno.unidadeFederativaCodigo = det.unidadeFederacao.codigoUnidadeFederacao;
			retorno.cepCidade        = det.cidade.numeroCepLogradouro;
			retorno.cepCidadeComplemento = det.cidade.complementoCepCidade;
			retorno.codigoBairro     = det.bairro.codigoBairro;
			retorno.nomeBairro       = det.bairro.nomeBairro;

			LstRetorno.add(retorno);

		 } 

		return LstRetorno;

	}

	//Atualiza os campos de endereço de um segurado
	public void atualizarEnderecoSegurados(List<Endereco__c> enderecos){
		Set<Id> contasIds = new Set<Id>();
		Map<Id, List<Endereco__c>> enderecosConta = new Map<Id, List<Endereco__c>>();
		List<ContratanteOrcamento__c> seguradosOrcamentoAtualizar = new List<ContratanteOrcamento__c>();

		//Identifica todas as conta dos endereços
		for(Endereco__c endereco : enderecos){
			contasIds.add(endereco.Conta__c);

			if(!enderecosConta.containsKey(endereco.Conta__c)){
				enderecosConta.put(endereco.Conta__c, new List<Endereco__c>());				
			}

			enderecosConta.get(endereco.Conta__c).add(endereco);
		}

		//Através das contas, identifica os segurados que deverão ter os endereços atualizados
		for(Account conta : AccountBO.getInstance().buscarContasComFilhos(contasIds)){
			Endereco__c enderecoAtual = null;

			//Identifica endereço mais atual 
			for(Endereco__c endereco : enderecosConta.get(conta.Id)){
				if(endereco.MaisAtual__c){
					enderecoAtual = endereco;
					break;
				}
			}

			//Se for encontrado endereço mais atual, atualiza segurados realcionado a mesma conta
			if(enderecoAtual != null){
				String tipoEndereco =  String.isBlank(conta.Cpf__c) ? 'Comercial' : 'Residencial';

				for(ContratanteOrcamento__c segurado : conta.ContratantesOrcamento__r){
					segurado.TipoEndereco__c = tipoEndereco;
					segurado.Bairro__c = enderecoAtual.Bairro__c;
					segurado.CEP__c = enderecoAtual.CEP__c;
					segurado.Cidade__c = enderecoAtual.Cidade__c;
					segurado.Complemento__c = enderecoAtual.Complemento__c;
					segurado.Estado__c = enderecoAtual.Estado__c;
					segurado.Logradouro__c = enderecoAtual.Logradouro__c;
					segurado.NumeroEndereco__c = enderecoAtual.Numero__c;
					segurado.TipoLogradouro__c = enderecoAtual.TipoLogradouro__c;
						
					seguradosOrcamentoAtualizar.add(segurado);
				}
			}
		}

		if(!seguradosOrcamentoAtualizar.isEmpty()){
			update seguradosOrcamentoAtualizar;
		}
	}

	public List<Endereco__c> buscarEnderecosContas(Set<Id> idsContas) {
		return dao.buscarEnderecoContas(idsContas);
	}

	//PLV-2727 - Inicio
		public String montarIdExterno(Endereco__c endereco){
			//PLV-2728 - Inicio - Add toUpperCase() - FIX
			//PLV-2995 - INICIO - Ajuste no IdExterno de endereço para formar caso não venha os dados de logradouro
			String enredecoLogradouro = String.isNotBlank(endereco.Logradouro__c) ? endereco.Logradouro__c.toUpperCase() : '';
			String enderecoComplemento = String.isNotBlank(endereco.Complemento__c) ? endereco.Complemento__c.toUpperCase() : '';
			String enderecoTipo = String.isNotBlank(endereco.TipoEndereco__c) ? endereco.TipoEndereco__c.toUpperCase() : '';//PLV-4894 - INICIO/FIM - PEDRO AUGUSTO BRAZ - SYS4B
			//PLV-2995 - FIM
			//PLV-2728 - Fim - Add toUpperCase() - FIX
			return endereco.Conta__c+'-'+endereco.CEP__c+'-'+enredecoLogradouro+'-'+endereco.Numero__c+'-'+enderecoComplemento+'-'+enderecoTipo; //PLV-4894 - INICIO/FIM - PEDRO AUGUSTO BRAZ - SYS4B //PLV-2728 - Inicio/Fim - Add toUpperCase()
		}
	//PLV-2727 - Fim
     
    //PLV-3995 - INICIO
	public void validaEnderecoCobranca (List<Endereco__c> enderecoNewList, Map<Id,Endereco__c> enderecoOldMap){


		List<Endereco__c> enderecoList = new List<Endereco__c>();
		System.debug('  @@@ EndCobra :> ' + enderecoNewList);
		for( Endereco__c e : enderecoNewList )	if (e.EnderecoCobranca__c)	enderecoList.add(e);
		// if (enderecoList.isEmpty())	return;

		List<String> accIdList = new List<String>();
		for( Endereco__c e : enderecoList )	accIdList.add(e.Conta__c);

		Map<id,Account> accMap = new Map<id,Account>(buscaContasEnderecos(accIdList));

		List<account> accToUp = new List<account>();
		
		if(enderecoOldMap == null){
			for( Endereco__c e : enderecoList){
				Account acc = accMap.get(e.Conta__c);
				if(!acc.Enderecos__r.isEmpty())	e.addError('Apenas um endereço de cobrança pode ser definido por conta.');
				if(acc.Enderecos__r.isEmpty())	accToUp.add(adressToAcc(acc,e));
			}
		}

		if(enderecoOldMap != null){
			for( Endereco__c e : enderecoList){
				Account acc = accMap.get(e.Conta__c);
				if( (!acc.Enderecos__r.isEmpty() && acc.Enderecos__r.size() > 1 ) || 
					(!acc.Enderecos__r.isEmpty() && acc.Enderecos__r[0].Id != e.Id ))		e.addError('Apenas um endereço de cobrança pode ser definido por conta.');
				if(acc.Enderecos__r.isEmpty() || (acc.Enderecos__r[0].Id == e.Id) )		accToUp.add(adressToAcc(acc,e));
			}
		}
		if(!accToUp.isEmpty())	update accToUp;
	}

	public Account adressToAcc(Account acc, Endereco__c adress){
		acc.BillingCountry = adress.Pais__c;
		acc.BillingState = adress.Estado__c;
		acc.BillingCity = adress.Cidade__c;
		acc.BillingPostalCode = adress.CEP__c;
		acc.BillingStreet = adress.Logradouro__c;
		return acc;
	}

	
	public Map<id,Account> buscaContasEnderecos(List<String> accountList){
		return new Map<Id,Account>([
			SELECT 	Id, 
					(SELECT Id, EnderecoCobranca__c	 FROM Enderecos__r WHERE EnderecoCobranca__c = true)
			FROM 	Account
			WHERE 	Id IN :accountList
		]);
	}
	//PLV-3995 - FIM

}