workspace-sf/force-app/main/default/objects/ContratanteOrcamento__c/ContratanteOrcamento__c.object-meta.xml
<CustomObject>
    <description>Objeto responsável por armazenar o cadastro dos contratantes do orçamento</description>
    <label>Contratante do orçamento</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contratantes do orçamento</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/CriticaOrcamento__c/CriticaOrcamento__c.object-meta.xml
<CustomObject>
    <description>Objeto responsável por armazenar as analises de aceitação geradas pelo ODM ou pelo Sinapse</description>
    <label>Crítica do orçamento</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número da crítica</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Críticas do orçamento</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/GarantiaGrupoOrcamento__c/GarantiaGrupoOrcamento__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar as garantias do grupo do orçamento</description>
    <label>Garantia do grupo do orçamento</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Garantias do grupo do orçamento</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/GarantiaGrupoOrcamento__c/fields/GrupoOrcamento__c.field-meta.xml
<CustomField>
    <fullName>GrupoOrcamento__c</fullName>
    <label>Grupo do orçamento</label>
    <referenceTo>GrupoOrcamento__c</referenceTo>
    <relationshipLabel>Garantias do grupo do orçamento</relationshipLabel>
    <relationshipName>GruposGarantiaOrcamento</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaOrcamento__c/GarantiaOrcamento__c.object-meta.xml
<CustomObject>
    <description>Objeto de relacionamento entre a garantia e a oportunidade.</description>
    <label>Garantia do orçamento</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Garantias do orçamento</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/GarantiaSeguradoOrcamento__c/GarantiaSeguradoOrcamento__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar as garantias do segurado do orçamento</description>
    <label>Garantia do segurado do orçamento</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Garantias do segurado do orçamento</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/GarantiaSeguradoOrcamento__c/fields/SeguradoOrcamento__c.field-meta.xml
<CustomField>
    <fullName>SeguradoOrcamento__c</fullName>
    <label>Segurado do orçamento</label>
    <referenceTo>SeguradoOrcamento__c</referenceTo>
    <relationshipLabel>Garantias do segurado do orçamento</relationshipLabel>
    <relationshipName>GarantiasSeguradoOrcamento</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GrupoOrcamento__c/GrupoOrcamento__c.object-meta.xml
<CustomObject>
    <description>Objeto responsável por armazenar o cadastro dos grupos de segurados do orçamento</description>
    <label>Grupo do orçamento</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grupos do orçamento</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/GrupoOrcamento__c/fields/ContratanteOrcamento__c.field-meta.xml
<CustomField>
    <fullName>ContratanteOrcamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contratante do orçamento</label>
    <referenceTo>ContratanteOrcamento__c</referenceTo>
    <relationshipLabel>Grupos do orçamento</relationshipLabel>
    <relationshipName>GruposOrcamento</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/SeguradoOrcamento__c/SeguradoOrcamento__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar os segurados do orçamento</description>
    <label>Segurado do orçamento</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Nome</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Segurados do orçamento</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/SeguradoOrcamento__c/fields/GrupoOrcamento__c.field-meta.xml
<CustomField>
    <fullName>GrupoOrcamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Grupo do orçamento</label>
    <referenceTo>GrupoOrcamento__c</referenceTo>
    <relationshipLabel>Segurados do orçamento</relationshipLabel>
    <relationshipName>SeguradosOrcamento</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/classes/ExpurgoOrcamentoBatchTest.cls
/**
 * Classe de teste para os batchs de expurgo:
 *      ExpurgoGarantiaSeguradoOrcamentoBatch
 *      ExpurgoGarantiaGrupoOrcamentoBatch
 *      ExpurgoSeguradoOrcamentoBatch
 *      ExpurgoGarantiasContratanteOrcBatch
 *      ExpurgoGrupoOrcamentoBatch
 *      ExpurgoContratanteOrcamentoBatch
 */
@IsTest 
public with sharing class ExpurgoOrcamentoBatchTest {
    @TestSetup
    static void makeData(){
        // ExpurgoOrcamentoDataFactory.setupData();    
        // TestDataFactory com erro de inserção de registro
        // System.DmlException: Insert failed. First exception on row 0; first error: DUPLICATE_VALUE, valor duplicado encontrado: <unknown> duplica o valor no registro com ID: <unknown>: []
    }

    @IsTest 
    static void expurgoOrcamentoBatchesTest() {
        
        Test.startTest();

        // GarantiaSeguradoOrcamento__c
        ExpurgoGarantiaSeguradoOrcamentoBatch batchGarantiaSeguradoOrcamento= new ExpurgoGarantiaSeguradoOrcamentoBatch();
        Database.executeBatch(batchGarantiaSeguradoOrcamento, 1);

        // GarantiaGrupoOrcamento__c
        ExpurgoGarantiaGrupoOrcamentoBatch batchGarantiaGrupoOrcamento= new ExpurgoGarantiaGrupoOrcamentoBatch();
        Database.executeBatch(batchGarantiaGrupoOrcamento, 1);

        // SeguradoOrcamento__c
        ExpurgoSeguradoOrcamentoBatch batchSeguradoOrcamento= new ExpurgoSeguradoOrcamentoBatch();
        Database.executeBatch(batchSeguradoOrcamento, 1);

        // GrarantiasContratanteOrcamento__c
        ExpurgoGarantiasContratanteOrcBatch batchGarantiasContratanteOrc= new ExpurgoGarantiasContratanteOrcBatch();
        Database.executeBatch(batchGarantiasContratanteOrc, 1);

        // GrupoOrcamento__c
        ExpurgoGrupoOrcamentoBatch batchGrupoOrcamento= new ExpurgoGrupoOrcamentoBatch();
        Database.executeBatch(batchGrupoOrcamento, 1);

        // ContratanteOrcamento__c
        ExpurgoContratanteOrcamentoBatch batchContratanteOrcamento= new ExpurgoContratanteOrcamentoBatch();
        Database.executeBatch(batchContratanteOrcamento, 1);

        // GarantiaOrcamento__c
        ExpurgoGarantiaOrcamentoBatch batchGarantiaOrcamento= new ExpurgoGarantiaOrcamentoBatch();
        Database.executeBatch(batchGarantiaOrcamento, 1);

        // CriticaOrcamento__c
        ExpurgoCriticaOrcamentoBatch batchCriticaOrcamento= new ExpurgoCriticaOrcamentoBatch();
        Database.executeBatch(batchCriticaOrcamento, 1);

        Test.stopTest();
    }
}