workspace-sf/force-app/main/default/objects/RemuneracaoProduto__c/RemuneracaoProduto__c.object-meta.xml
<CustomObject>
    <description>Objeto de relacionamento entre o produto e o tipo de remuneração</description>
    <label>Remuneração do produto</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Remunerações do produto</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/RemuneracaoProduto__c/fields/LimiteMinimo__c.field-meta.xml
<CustomField>
    <fullName>LimiteMinimo__c</fullName>
    <label>Limite mínimo</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

workspace-sf/force-app/main/default/objects/RemuneracaoProduto__c/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Remunerações do produto</relationshipLabel>
    <relationshipName>RemuneracoesProduto</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/RemuneracaoProduto__c/fields/RemuneracaoProduto__c.field-meta.xml
<CustomField>
    <fullName>RemuneracaoProduto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Remuneração do produto</label>
    <referenceTo>RemuneracaoProduto__c</referenceTo>
    <relationshipLabel>Remunerações do produto</relationshipLabel>
    <relationshipName>RemuneracoesProduto</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/RemuneracaoProduto__c/fields/TipoEvento__c.field-meta.xml
<CustomField>
    <fullName>TipoEvento__c</fullName>
    <label>Tipo de evento</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Endosso</fullName>
            </value>
            <value>
                <fullName>Renovação</fullName>
            </value>
            <value>
                <fullName>Seguro novo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/RemuneracaoProduto__c/fields/TipoRemuneracao__c.field-meta.xml
<CustomField>
    <fullName>TipoRemuneracao__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tipo de remuneração</label>
    <referenceTo>TipoRemuneracao__c</referenceTo>
    <relationshipLabel>Remunerações do produto</relationshipLabel>
    <relationshipName>RemuneracoesProduto</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/RemuneracaoProduto__c/recordTypes/ProdutoComercial.recordType-meta.xml
<RecordType>
    <fullName>ProdutoComercial</fullName>
    <active>true</active>
    <label>Produto comercial</label>
</RecordType>

workspace-sf/force-app/main/default/objects/TipoRemuneracao__c/TipoRemuneracao__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar o cadastro dos tipos de remuneração</description>
    <label>Tipo de remuneração</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tipos de remuneração</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/TipoRemuneracao__c/fields/LimiteMaximo__c.field-meta.xml
<CustomField>
    <fullName>LimiteMaximo__c</fullName>
    <label>Limite máximo</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

workspace-sf/force-app/main/default/classes/RemuneracaoProdutoFactory.cls
/**
 * @author AVX - Leonardo Camacho
 * @date 2019-10-30
 * @description: RemuneracaoProduto__c Factory Class
 */
    
 @isTest
 public class RemuneracaoProdutoFactory extends SObjectFactory {

    private static RemuneracaoProduto__c staticRecord;

	private static RemuneracaoProduto__c getRecordStatic(TipoRemuneracao__c tipoRemuneracao, Product2 ProdutoComercial){

		if(staticRecord == null){
			staticRecord = new RemuneracaoProduto__c(
				Produto__c = ProdutoComercial.Id,
            	TipoRemuneracao__c = tipoRemuneracao.Id,
                LimiteMinimo__c = 1,
                LimiteMaximo__c = 45,
                TipoEvento__c = 'Endosso',
                Obrigatoria__c = true
                );
		}
		return staticRecord;
	}

	public RemuneracaoProdutoFactory(){

		this(
			(TipoRemuneracao__c) new TipoRemuneracaoFactory().createRecord(),
            (Product2) new ProdutoFactory.ProdutoComercial().createRecord()
		);
	}

	public RemuneracaoProdutoFactory(TipoRemuneracao__c tipoRemuneracao, Product2 ProdutoComercial) {

		super(getRecordStatic(tipoRemuneracao, ProdutoComercial));
	}
}