workspace-sf/force-app/main/default/objects/CanalCampanha__c/CanalCampanha__c.object-meta.xml
<CustomObject>
    <description>Objeto de relacionamento entre a campanha de incentivo e o canal</description>
    <label>Canal da campanha</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Canais da campanha</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/CanalCampanha__c/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto comercial</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Somente produto comercial.</errorMessage>
        <filterItems>
            <field>Product2.RecordType.Name</field>
            <operation>equals</operation>
            <value>Produto comercial</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Canais da campanha</relationshipLabel>
    <relationshipName>CanaisCampanha</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/classes/CanalCampanhaDAO.cls
/**
 * CanalCampanhaDAO
 * @author Fernando Barcellos @ 27/02/2018
 *
 **/
public class CanalCampanhaDAO {
	private static final CanalCampanhaDAO instancia = new CanalCampanhaDAO();

	private CanalCampanhaDAO() {	
	}

	public static CanalCampanhaDAO getInstance(){
		return instancia;
	}

	public List<CanalCampanha__c> buscarCanaisCampanhaPorId(Set<ID> setIds) {
		return [
			SELECT
				Id,
				Produto__c
			FROM
				CanalCampanha__c
			WHERE
				Id IN : setIds
		];
	}

}