workspace-sf/force-app/main/default/objects/CanalCampanha__c/CanalCampanha__c.object-meta.xml
<CustomObject>
    <description>Objeto de relacionamento entre a campanha de incentivo e o canal</description>
    <label>Canal da campanha</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Canais da campanha</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/CanalCampanha__c/fields/CanalDistribuicao__c.field-meta.xml
<CustomField>
    <fullName>CanalDistribuicao__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Canal de distribuição</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CanalDistribuicao__c.Status__c</field>
            <operation>equals</operation>
            <value>Ativo</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CanalDistribuicao__c</referenceTo>
    <relationshipLabel>Canais da campanha</relationshipLabel>
    <relationshipName>CanaisCampanha</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/CanalCampanha__c/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto comercial</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Somente produto comercial.</errorMessage>
        <filterItems>
            <field>Product2.RecordType.Name</field>
            <operation>equals</operation>
            <value>Produto comercial</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Canais da campanha</relationshipLabel>
    <relationshipName>CanaisCampanha</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/CanalDistribuicao__c/CanalDistribuicao__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar o cadastro dos canais de distribuição</description>
    <label>Canal de distribuição</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Canais de distribuição</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/ProdutoCanal__c/ProdutoCanal__c.object-meta.xml
<CustomObject>
    <description>Objeto de relacionamento entre o canal e o produto</description>
    <label>Produto do canal</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Produtos do canal</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/ProdutoCanal__c/fields/CanalDistribuicao__c.field-meta.xml
<CustomField>
    <fullName>CanalDistribuicao__c</fullName>
    <label>Canal de distribuição</label>
    <referenceTo>CanalDistribuicao__c</referenceTo>
    <relationshipLabel>Produtos do canal</relationshipLabel>
    <relationshipName>ProdutosCanal</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/ProdutoCanal__c/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto comercial</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.RecordType.Name</field>
            <operation>equals</operation>
            <value>Produto comercial</value>
        </filterItems>
        <filterItems>
            <field>Product2.Status__c</field>
            <operation>equals</operation>
            <value>Ativo</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Produtos comerciais</relationshipLabel>
    <relationshipName>ProdutosCanal</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/classes/CanalCampanhaBO.cls
/**
 * BO CanalCampanha__c
 * @author Fernando Barcellos @ 18/01/2018
 *
 **/
public class CanalCampanhaBO {
	private static final CanalCampanhaBO instance = new CanalCampanhaBO();
	
	public static CanalCampanhaBO getInstance() {
		return instance;
	}

	private CanalCampanhaBO() { }

	public void validarProdutoCanalDistribuicao(List<CanalCampanha__c> lstCanalCampanha) {
		for (CanalCampanha__c canalCampanha : lstCanalCampanha) {
			List<ProdutoCanal__c> produtosCanal = ProdutoCanalDAO.getInstance().buscarProdutoCanalPorCanalDistribuicao(canalCampanha.CanalDistribuicao__c);
			Set<Id> setIdsProdutos = new Set<Id>();
			for (ProdutoCanal__c produtoCanal : produtosCanal) {
				setIdsProdutos.add(produtoCanal.Produto__c);
			}
			if (!setIdsProdutos.contains(canalCampanha.Produto__c)) {
				canalCampanha.addError('Este produto não está no canal de distribuição.');
			}
		}
	}
}