workspace-sf/force-app/main/default/objects/CanalCampanha__c/CanalCampanha__c.object-meta.xml
<CustomObject>
    <description>Objeto de relacionamento entre a campanha de incentivo e o canal</description>
    <label>Canal da campanha</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Canais da campanha</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/CanalCampanha__c/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto comercial</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Somente produto comercial.</errorMessage>
        <filterItems>
            <field>Product2.RecordType.Name</field>
            <operation>equals</operation>
            <value>Produto comercial</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Canais da campanha</relationshipLabel>
    <relationshipName>CanaisCampanha</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Garantia__c/Garantia__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar o cadastro das garantias</description>
    <label>Garantia</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Garantias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/Garantia__c/fields/Sigla__c.field-meta.xml
<CustomField>
    <fullName>Sigla__c</fullName>
    <label>Sigla</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaCampanha__c/GarantiaCampanha__c.object-meta.xml
<CustomObject>
    <description>Objeto de relacionamento entre a garantia e a campanha.</description>
    <label>Garantia da campanha</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Garantias da campanha</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/GarantiaCampanha__c/fields/CanalCampanha__c.field-meta.xml
<CustomField>
    <fullName>CanalCampanha__c</fullName>
    <label>Canal da campanha</label>
    <referenceTo>CanalCampanha__c</referenceTo>
    <relationshipLabel>Garantias da campanha</relationshipLabel>
    <relationshipName>GarantiasCampanha</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaCampanha__c/fields/Garantia__c.field-meta.xml
<CustomField>
    <fullName>Garantia__c</fullName>
    <label>Garantia</label>
    <referenceTo>Garantia__c</referenceTo>
    <relationshipLabel>Garantias da campanha</relationshipLabel>
    <relationshipName>GarantiasCampanha</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaProduto__c/GarantiaProduto__c.object-meta.xml
<CustomObject>
    <description>Objeto de relacionamento entre os produtos e as garantias</description>
    <label>Garantia do produto</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Garantias do produto</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/GarantiaProduto__c/fields/Garantia__c.field-meta.xml
<CustomField>
    <fullName>Garantia__c</fullName>
    <label>Garantia</label>
    <referenceTo>Garantia__c</referenceTo>
    <relationshipLabel>Garantias do produto</relationshipLabel>
    <relationshipName>GarantiasProduto</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaProduto__c/fields/GarantiaLimitadora__c.field-meta.xml
<CustomField>
    <fullName>GarantiaLimitadora__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Garantia limitadora</label>
    <referenceTo>GarantiaProduto__c</referenceTo>
    <relationshipLabel>Garantias do produto</relationshipLabel>
    <relationshipName>GarantiasProduto</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaProduto__c/fields/GarantiaProduto__c.field-meta.xml
<CustomField>
    <fullName>GarantiaProduto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Garantia do produto</label>
    <referenceTo>GarantiaProduto__c</referenceTo>
    <relationshipLabel>Garantias do produto (Garantia do produto)</relationshipLabel>
    <relationshipName>GarantiasProdutoTecnico</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaProduto__c/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Garantias do produto</relationshipLabel>
    <relationshipName>GarantiasProduto</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/classes/GarantiaBO.cls
/**
 * Regras de Negócio do Objeto Garantia__c
 * @author Fernando Barcellos
 *
 **/
public class GarantiaBO {
	private static GarantiaBO classInstance;

	static {
		classInstance = new GarantiaBO();
	}

	private GarantiaBO() {
		
	}

	public static GarantiaBO getInstance() {
		return classInstance;
	}

	public List<Garantia__c> buscarGarantiasPorId(Set<Id> idsGarantias, Set<Id> idsProdutos) {
		return GarantiaDAO.getInstance().buscarGarantiasPorId(idsGarantias, idsProdutos);
	}

	public void validarGarantias(List<GarantiaCampanha__c> garantiasCampanhas) {
		Set<Id> idsCanalCampanha = new Set<Id>();
		Set<Id> idsGarantiasCampanha = new Set<Id>();

		for (GarantiaCampanha__c garantiaCampanha : garantiasCampanhas) {
			system.debug('garantiaCampanha ' + garantiaCampanha);
			idsCanalCampanha.add(garantiaCampanha.CanalCampanha__c);
			idsGarantiasCampanha.add(garantiaCampanha.Garantia__c);
		}

		// CANAIS CAMPANHA
		List<CanalCampanha__c> canaisCampanha = CanalCampanhaDAO.getInstance().buscarCanaisCampanhaPorId(idsCanalCampanha);
		Set<Id> idsProdutosCampanha = new Set<Id>();
		system.debug('canaisCampanha ' + canaisCampanha);
		for (CanalCampanha__c canalCampanha : canaisCampanha) {
			idsProdutosCampanha.add(canalCampanha.Produto__c);
		}
		system.debug('idsProdutosCampanha ' + idsProdutosCampanha);
		List<Garantia__c> garantias = buscarGarantiasPorId(idsGarantiasCampanha, idsProdutosCampanha);
		Map<Id, List<GarantiaProduto__c>> mapGarantiaProdutos = new Map<Id, List<GarantiaProduto__c>>();
		system.debug('garantias ' + garantias);
		for (Garantia__c gar : garantias) {
			List<GarantiaProduto__c> lstProdutos = new List<GarantiaProduto__c>();

			for (GarantiaProduto__c gp : gar.GarantiasProduto__r) {
				lstProdutos.add(gp);
			}

			mapGarantiaProdutos.put(gar.Id, lstProdutos);
		}

		// VALIDAÇÕES
		for (GarantiaCampanha__c garantiaCampanha : garantiasCampanhas) {
			List<GarantiaProduto__c> garantiasProduto = mapGarantiaProdutos.get(garantiaCampanha.Garantia__c);
			system.debug('garantiasProduto ' + garantiasProduto);
			Set<Id> idsGarantiasProdutoExistentes = new Set<Id>();
			Set<String> teste = new Set<String>();
			for (GarantiaProduto__c garantiaProduto : garantiasProduto) {
				system.debug('garantiaProduto ' + garantiaProduto);
				idsGarantiasProdutoExistentes.add(garantiaProduto.Garantia__c);
				teste.add(garantiaProduto.Garantia__c);
			}
			system.debug('idsGarantiasCampanha '+ idsGarantiasCampanha);
			system.debug('teste '+ teste);
			system.debug('idsGarantiasProdutoExistentes ' + idsGarantiasProdutoExistentes);
			// VALIDAÇÃO 1
			if (!idsGarantiasCampanha.containsAll(idsGarantiasProdutoExistentes) || idsGarantiasProdutoExistentes.size() == 0) {
				garantiaCampanha.addError('Garantia inexistente nas Garantias do produto.');
			}
		}
	}

	// POR062-1 - INICIO
	public Map<String, Garantia__c> mapearGarantiaPorCobertura(List<Garantia__c> garantias)
	{
		Map<String, Garantia__c> garantiaPorCobertura = new Map<String, Garantia__c>();
		for(Garantia__c garantia : garantias)
		{
			garantiaPorCobertura.put(garantia.Sigla__c, garantia);
		}
		return garantiaPorCobertura;
	}
	// POR062-1 - FIM
}