workspace-sf/force-app/main/default/objects/CondicaoCobranca__c/CondicaoCobranca__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar as condições de cobrança dos produtos</description>
    <label>Condição de cobrança</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Condições de cobrança</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/CondicaoCobranca__c/fields/FormaPagamento__c.field-meta.xml
<CustomField>
    <fullName>FormaPagamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Forma de pagamento</label>
    <referenceTo>FormaPagamento__c</referenceTo>
    <relationshipLabel>Condições de cobrança</relationshipLabel>
    <relationshipName>CondicoesCobranca</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/CondicaoCobranca__c/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Condições de cobrança</relationshipLabel>
    <relationshipName>CondicoesCobranca</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/CondicaoCobranca__c/fields/TipoPagamento__c.field-meta.xml
<CustomField>
    <fullName>TipoPagamento__c</fullName>
    <description>O Valor selecionado neste campo será enviado para o Portal identificando o formulário de pagamento que deverá ser exibido.</description>
    <inlineHelpText>Identifica o leiaute que será exibido na tela dos portais.</inlineHelpText>
    <label>Tipo pagamento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ADC</fullName>
            </value>
            <value>
                <fullName>Boleto</fullName>
            </value>
            <value>
                <fullName>CartaoCredito</fullName>
                <label>Cartão de crédito</label>
            </value>
            <value>
                <fullName>CartaoRecorrente</fullName>
                <isActive>false</isActive>
                <label>Cartão Recorrente</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/ContratanteProposta__c/ContratanteProposta__c.object-meta.xml
<CustomObject>
    <description>Objeto responsável por armazenar o cadastro dos contratantes da proposta</description>
    <label>Contratante da proposta</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contratantes da proposta</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/ContratanteProposta__c/fields/FormaPagamento__c.field-meta.xml
<CustomField>
    <fullName>FormaPagamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Forma de pagamento</label>
    <referenceTo>FormaPagamento__c</referenceTo>
    <relationshipLabel>Contratantes da proposta</relationshipLabel>
    <relationshipName>ContratantesProposta</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/ContratanteProposta__c/fields/Proposta__c.field-meta.xml
<CustomField>
    <fullName>Proposta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proposta</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Contratantes da proposta</relationshipLabel>
    <relationshipName>ContratantesProposta</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/ControleIntegracao__c/ControleIntegracao__c.object-meta.xml
<CustomObject>
    <description>Objeto responsável por conter os logs das integrações</description>
    <label>Controle de integração</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Controles de integração</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/ControleIntegracao__c/fields/CodigoIntegracao__c.field-meta.xml
<CustomField>
    <fullName>CodigoIntegracao__c</fullName>
    <label>Código da integração</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/ControleIntegracao__c/fields/DataCriacaoRegistro__c.field-meta.xml
<CustomField>
    <fullName>DataCriacaoRegistro__c</fullName>
    <label>Data de criação do registro</label>
    <type>Date</type>
</CustomField>

workspace-sf/force-app/main/default/objects/ControleIntegracao__c/fields/IdObjeto__c.field-meta.xml
<CustomField>
    <fullName>IdObjeto__c</fullName>
    <label>Id do objeto</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/ControleIntegracao__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pendente</fullName>
            </value>
            <value>
                <fullName>Em processamento</fullName>
            </value>
            <value>
                <fullName>Processado</fullName>
            </value>
            <value>
                <fullName>Erro</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/FormaPagamento__c/FormaPagamento__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar o cadastro das formas de pagamento</description>
    <label>Forma de pagamento</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Formas de pagamento</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/FormaPagamento__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <label>Código</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/classes/GravarPropostaControleIntegracao.cls
/**
 * @author AVX - Leonardo Camacho
 * @date 2019-12-10
 * @description: Classe criada por conta da história PLV_3134
 * para gravar o Id da proposta na tabela de controle de integração quando a proposta é contratada
 **/

public class GravarPropostaControleIntegracao {

        public static final GravarPropostaControleIntegracao instancia = new GravarPropostaControleIntegracao();

        public static GravarPropostaControleIntegracao getInstance(){
            return instancia;
        }

        public void inserirRegistroControleIntegracao(List<Quote> PropostasEntrada){
            
            List<ControleIntegracao__c> listControleIntegracao = new List<ControleIntegracao__c>();            
            Set<Id> setProdutos = new Set<Id>();
            Set<Id> setPropostas = new Set<Id>();
            Set<String> setFormaPagamento = new Set<String>{'51','52','53'};

            system.debug('setFormaPagamento: ' + setFormaPagamento);

             for(Quote proposta : PropostasEntrada){             
             
                if(proposta.tipo__c == 'Novo' && TriggerHelper.isChanged(proposta, 'Status') && proposta.Status == 'Contratada'){

                    setPropostas.add(proposta.id);
                    setProdutos.add(proposta.produto__c);                    
                }
            }

            if(setProdutos.isEmpty()) return;

            List<CondicaoCobranca__c> listTipoPagamento = [SELECT id, TipoPagamento__c, produto__c, produto__r.name 
                                                        FROM CondicaoCobranca__c
                                                        WHERE produto__c IN :setProdutos
                                                        AND TipoPagamento__c = 'ADC']; 


            if(listTipoPagamento.isEmpty()) return;


            List<contratanteProposta__c> listaContratantesProposta = [SELECT id, FormaPagamento__c, proposta__c
                                                                    FROM contratanteProposta__c 
                                                                    WHERE proposta__c IN : setPropostas
                                                                    AND formaPagamento__r.codigo__c IN : setFormaPagamento];

            if(listaContratantesProposta.isEmpty()) return;

            for(contratanteProposta__c contratanteProposta : listaContratantesProposta){
                            ControleIntegracao__c controleIntegracao = new ControleIntegracao__c(
                            CodigoIntegracao__c = '7',
                            IdObjeto__c = contratanteProposta.proposta__c,
                            DataCriacaoRegistro__c = System.today(),
                            Status__c = 'Pendente');

                            listControleIntegracao.add(controleIntegracao);
            }                   
            insert listControleIntegracao;
        }
}