workspace-sf/force-app/main/default/objects/ContratanteProposta__c/ContratanteProposta__c.object-meta.xml
<CustomObject>
    <description>Objeto responsável por armazenar o cadastro dos contratantes da proposta</description>
    <label>Contratante da proposta</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contratantes da proposta</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/FavorecidoRemuneracaoProposta__c/FavorecidoRemuneracaoProposta__c.object-meta.xml
<CustomObject>
    <label>Favorecido da Remuneração da Proposta</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Favorecido da Proposta</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Favorecidos da Remuneração da Proposta</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/FavorecidoRemuneracaoProposta__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Favorecidos_da_Proposta</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/FavorecidoRemuneracaoProposta__c/fields/RemuneracaoProposta__c.field-meta.xml
<CustomField>
    <fullName>RemuneracaoProposta__c</fullName>
    <label>Remuneração da proposta</label>
    <referenceTo>RemuneracaoProposta__c</referenceTo>
    <relationshipLabel>Favorecidos da Remuneração da Proposta</relationshipLabel>
    <relationshipName>FavorecidosRemuneracaodaProposta</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/FavorecidoRemuneracaoProposta__c/fields/Susep__c.field-meta.xml
<CustomField>
    <fullName>Susep__c</fullName>
    <label>Susep</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/FavorecidoRemuneracaoProposta__c/fields/SusepOficialCorretor__c.field-meta.xml
<CustomField>
    <fullName>SusepOficialCorretor__c</fullName>
    <label>Susep Oficial Corretor</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/FormaPagamento__c/FormaPagamento__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar o cadastro das formas de pagamento</description>
    <label>Forma de pagamento</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Formas de pagamento</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/GrupoProposta__c/GrupoProposta__c.object-meta.xml
<CustomObject>
    <description>Objeto responsável por armazenar o cadastro dos grupos de segurados da proposta</description>
    <label>Grupo da proposta</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grupos da proposta</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/GrupoProposta__c/fields/ContratanteProposta__c.field-meta.xml
<CustomField>
    <fullName>ContratanteProposta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contratante da proposta</label>
    <referenceTo>ContratanteProposta__c</referenceTo>
    <relationshipLabel>Grupos da proposta</relationshipLabel>
    <relationshipName>GruposProposta</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Pep__c/Pep__c.object-meta.xml
<CustomObject>
    <label>Pep</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Peps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/RemuneracaoProposta__c/RemuneracaoProposta__c.object-meta.xml
<CustomObject>
    <description>Objeto de relacionamento entre a proposta e o tipo de remuneração.</description>
    <label>Remuneração da proposta</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Remunerações da proposta</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/RemuneracaoProposta__c/fields/Proposta__c.field-meta.xml
<CustomField>
    <fullName>Proposta__c</fullName>
    <label>Proposta</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Remunerações da proposta</relationshipLabel>
    <relationshipName>RemuneracoesProposta</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/SeguradoProposta__c/SeguradoProposta__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar os segurados da proposta</description>
    <label>Segurado da proposta</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Segurados da proposta</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/SeguradoProposta__c/fields/bairroResidencial__c.field-meta.xml
<CustomField>
    <fullName>bairroResidencial__c</fullName>
    <label>Bairro Residencial</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/SeguradoProposta__c/fields/cepResidencial__c.field-meta.xml
<CustomField>
    <fullName>cepResidencial__c</fullName>
    <label>CEP Residencial</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/SeguradoProposta__c/fields/CidadeResidencial__c.field-meta.xml
<CustomField>
    <fullName>CidadeResidencial__c</fullName>
    <label>Cidade Residencial</label>
    <length>70</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/SeguradoProposta__c/fields/ComplementoResidencial__c.field-meta.xml
<CustomField>
    <fullName>ComplementoResidencial__c</fullName>
    <label>Complemento Residencial</label>
    <length>70</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/SeguradoProposta__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Segurados da proposta</relationshipLabel>
    <relationshipName>SeguradosProposta</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/SeguradoProposta__c/fields/FormaPagamento__c.field-meta.xml
<CustomField>
    <fullName>FormaPagamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Forma de pagamento</label>
    <referenceTo>FormaPagamento__c</referenceTo>
    <relationshipLabel>Segurados da proposta</relationshipLabel>
    <relationshipName>SeguradosProposta</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/SeguradoProposta__c/fields/GrupoProposta__c.field-meta.xml
<CustomField>
    <fullName>GrupoProposta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Grupo da proposta</label>
    <referenceTo>GrupoProposta__c</referenceTo>
    <relationshipLabel>Segurados da proposta</relationshipLabel>
    <relationshipName>SeguradosProposta</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/SeguradoProposta__c/fields/logradouroResidencial__c.field-meta.xml
<CustomField>
    <fullName>logradouroResidencial__c</fullName>
    <label>Logradouro Residencial</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/SeguradoProposta__c/fields/Numero__c.field-meta.xml
<CustomField>
    <fullName>Numero__c</fullName>
    <label>Número</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

workspace-sf/force-app/main/default/objects/SeguradoProposta__c/fields/numeroResidencial__c.field-meta.xml
<CustomField>
    <fullName>numeroResidencial__c</fullName>
    <label>Número residencial</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/SeguradoProposta__c/fields/paisResidencial__c.field-meta.xml
<CustomField>
    <fullName>paisResidencial__c</fullName>
    <label>País Residencial</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/SeguradoProposta__c/fields/UFResidencial__c.field-meta.xml
<CustomField>
    <fullName>UFResidencial__c</fullName>
    <label>UF Residencial</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/SeguradoProposta__c/fields/VigenciaFinal__c.field-meta.xml
<CustomField>
    <fullName>VigenciaFinal__c</fullName>
    <label>Vigência final</label>
    <type>Date</type>
</CustomField>

workspace-sf/force-app/main/default/objects/SeguradoProposta__c/fields/VigenciaInicial__c.field-meta.xml
<CustomField>
    <fullName>VigenciaInicial__c</fullName>
    <label>Vigência inicial</label>
    <type>Date</type>
</CustomField>

workspace-sf/force-app/main/default/classes/PropostaSeguroViagemController.cls
/********************************************************************************************************************
* Proposta de Seguro Viagem Controler
* @author Edgar Peralta - Globant
* @date 04/09/2020
* Classe criada por conta da história PLV-4345
*********************************************************************************************************************/
public with sharing class PropostaSeguroViagemController {
    public String nomeOpp											{get; set;}
    public List<Quote> Quote   										{get; set;}
    public List<FavorecidoRemuneracaoProposta__c> dadosCorrector	{get; set;}
    public Integer quoteSize										{get; set;}
    public Integer coberturasSize									{get; set;}
    public String periodoViagem                                     {get; set;}
    public List<seguradoProposta__c>  seguradoEndereco              {get; set;} //PLV - 4849 INICIO - FIM

    public PropostaSeguroViagemController(){
        this.nomeOpp = ApexPages.currentPage().getParameters().get('numProposta'); 
        this.Quote = getQuote(nomeOpp);    
        this.seguradoEndereco = getSeguradoEndereco(nomeOpp); //PLV - 4849 INICIO - FIM        
        if(Quote[0].Produto__r.Segmento__c != 'Viagem'){
            CalloutException e = new CalloutException();
            e.setMessage('Proposta informada não pertence ao segmento Viagem!');
            throw e;
        }
        quoteSize = Quote.size();
        coberturasSize = Quote[0].GarantiasProposta__r.size();
        this.dadosCorrector = getDadosCorrector(Quote[0].Id);
        this.periodoViagem = Quote[0].VigenciaInicial__c != null && Quote[0].VigenciaFinal__c !=null  ?  String.ValueOf(((this.Quote[0].VigenciaInicial__c).daysBetween(this.Quote[0].VigenciaFinal__c)+1)) +' dia(s)':''; 
    }
    private List<Quote> getQuote (String nomeOpp){
        return [SELECT ID, Name, ContactId, VigenciaFinal__c, VigenciaInicial__c, Origem__c, PaisesDestino__c,
                OpportunityId, DiasAnalise__c, FormaPagamento__r.Name, Account.Name, Account.BillingStreet, 
                Account.BillingPostalCode, Account.BillingCity, Account.BillingState, Account.BillingCountry,
                Account.Cpf__c, Account.Sexo__c, Account.PersonEmail, Account.PersonBirthdate, Account.Nacionalidade__c,
                Account.Pep__c, Account.Id, Opportunity.Numero__c, Produto__r.NumeroSusep__c, Produto__r.Name, Produto__r.Segmento__c,
                (SELECT ID, Name, Capital__c, CurrencyIsoCode, Garantia__r.name FROM GarantiasProposta__r) 
                FROM Quote 
                WHERE Name =: nomeOpp];
    }
    private List<FavorecidoRemuneracaoProposta__c> getDadosCorrector(String numeroOpp){
        return [SELECT conta__c, SusepOficialCorretor__c, Susep__c, conta__r.Phone, conta__r.Name, conta__r.Email__c
                FROM FavorecidoRemuneracaoProposta__c
                WHERE RemuneracaoProposta__r.Proposta__c =: numeroOpp];
    }
    //PLV - 4849 INICIO
    private List<seguradoProposta__c> getSeguradoEndereco (String nomeOpp){
        return [SELECT UFResidencial__c, paisResidencial__c, numeroResidencial__c, logradouroResidencial__c, ComplementoResidencial__c, CidadeResidencial__c, cepResidencial__c, bairroResidencial__c
                FROM seguradoProposta__c 
                WHERE GrupoProposta__r.ContratanteProposta__r.Proposta__r.Name =: nomeOpp ];
    }
    //PLV - 4849 FIM
}