workspace-sf/force-app/main/default/objects/ContratanteProposta__c/ContratanteProposta__c.object-meta.xml
<CustomObject>
    <description>Objeto responsável por armazenar o cadastro dos contratantes da proposta</description>
    <label>Contratante da proposta</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contratantes da proposta</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/ContratanteProposta__c/fields/Proposta__c.field-meta.xml
<CustomField>
    <fullName>Proposta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proposta</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Contratantes da proposta</relationshipLabel>
    <relationshipName>ContratantesProposta</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GrupoProposta__c/GrupoProposta__c.object-meta.xml
<CustomObject>
    <description>Objeto responsável por armazenar o cadastro dos grupos de segurados da proposta</description>
    <label>Grupo da proposta</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grupos da proposta</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/GrupoProposta__c/fields/ContratanteProposta__c.field-meta.xml
<CustomField>
    <fullName>ContratanteProposta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contratante da proposta</label>
    <referenceTo>ContratanteProposta__c</referenceTo>
    <relationshipLabel>Grupos da proposta</relationshipLabel>
    <relationshipName>GruposProposta</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/classes/ExpurgoGrupoProposta.cls
/**
 * Expurgo de dados para o Proposta
 *  objeto: GrupoProposta__c
 * caminho do objeto:
 *  > GrupoProposta__c
 *  > ContratanteProposta__c
 *  > Proposta__c
 * 
 * 28/02/2024
 */

public with sharing class ExpurgoGrupoProposta {

    public List<GrupoProposta__c> getDadosExpurgo(Integer qt) { 
        List<GrupoProposta__c> expList= new List<GrupoProposta__c>();
        String query= 'SELECT Id '
            +'FROM GrupoProposta__c '
            +'WHERE ContratanteProposta__r.Proposta__r.Segmento__c = \'Massificados\' ';
        if (qt != 0) {
            query+= 'LIMIT :qt';
        }
        expList= Database.queryWithBinds(query, new Map<String,Object>{'qt' => qt}, AccessLevel.SYSTEM_MODE);
        System.debug(expList);
        return expList;
    }

    public void deleteDadosExpurgo(List<GrupoProposta__c> expList) {
        if (!Test.isRunningTest()) {
           delete (List<GrupoProposta__c >)expList;
        }
    }
}