workspace-sf/force-app/main/default/objects/ContratanteProposta__c/ContratanteProposta__c.object-meta.xml
<CustomObject>
    <description>Objeto responsável por armazenar o cadastro dos contratantes da proposta</description>
    <label>Contratante da proposta</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contratantes da proposta</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/ContratanteProposta__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contratantes da proposta</relationshipLabel>
    <relationshipName>ContratantesProposta</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/ContratanteProposta__c/fields/Proposta__c.field-meta.xml
<CustomField>
    <fullName>Proposta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proposta</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Contratantes da proposta</relationshipLabel>
    <relationshipName>ContratantesProposta</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GrupoProposta__c/GrupoProposta__c.object-meta.xml
<CustomObject>
    <description>Objeto responsável por armazenar o cadastro dos grupos de segurados da proposta</description>
    <label>Grupo da proposta</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grupos da proposta</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/GrupoProposta__c/fields/ContratanteProposta__c.field-meta.xml
<CustomField>
    <fullName>ContratanteProposta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contratante da proposta</label>
    <referenceTo>ContratanteProposta__c</referenceTo>
    <relationshipLabel>Grupos da proposta</relationshipLabel>
    <relationshipName>GruposProposta</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/SeguradoProposta__c/SeguradoProposta__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar os segurados da proposta</description>
    <label>Segurado da proposta</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Segurados da proposta</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/SeguradoProposta__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Segurados da proposta</relationshipLabel>
    <relationshipName>SeguradosProposta</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/SeguradoProposta__c/fields/GrupoProposta__c.field-meta.xml
<CustomField>
    <fullName>GrupoProposta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Grupo da proposta</label>
    <referenceTo>GrupoProposta__c</referenceTo>
    <relationshipLabel>Segurados da proposta</relationshipLabel>
    <relationshipName>SeguradosProposta</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/classes/SeguradoPropostaBO.cls
/**************************************************************************************************************************************************************************
 *
 *	Classe responsável pelo negócio do objeto de SeguradoProposta__c
 *
 
 **************************************************************************************************************************************************************************/
public without sharing class SeguradoPropostaBO { //FNPVVEP-126 INICIO-FIM
	
	private static final SeguradoPropostaBO instance = new SeguradoPropostaBO();
	private static SeguradoPropostaDAO dao = SeguradoPropostaDAO.getInstance();
	public static SeguradoPropostaBO getInstance() { 
		return instance; 
	}

	private SeguradoPropostaBO() { }

	public class SeguradoPropostaException extends Exception {	}
	
	//Não permite incluir registros em SeguradoProposta__c, quando as contas associadas são repetidas
	public void validarVidasCpfRepetidosProposta(List<SeguradoProposta__c> vidasGrupoProposta){
		Set<Id> grupoPropostaIds = new Set<Id>();
		Set<Id> propostaIds = new Set<Id>();
		Map<Id, Id> propostaGrupo = new Map<Id, Id>();
		Map<Id, List<SeguradoProposta__c>> mapVidasProposta = new Map<Id, List<SeguradoProposta__c>>();
		
		//Identifica as propostas através dos grupos da proposta
		for(SeguradoProposta__c SeguradoProposta : vidasGrupoProposta){
			grupoPropostaIds.add(SeguradoProposta.GrupoProposta__c);
		}

		for(SeguradoProposta__c vida : dao.buscarGruposPropostaPorIds(grupoPropostaIds)){
			System.debug('entrou aquii ><:');
			propostaIds.add(vida.GrupoProposta__r.ContratanteProposta__r.Proposta__c);
			propostaGrupo.put(vida.GrupoProposta__c, vida.GrupoProposta__r.ContratanteProposta__r.Proposta__c);
		}
		System.debug('entrou aquii ><:');
		System.debug('grupoPropostaIds ><:' + grupoPropostaIds);

		//Após identificar propostas, fazer busca para poder recuperar todas as vidas pertinentes a uma proposta
		for(SeguradoProposta__c vida : dao.buscarGruposPropostaPorPropostaIds(propostaIds)){
			if(!mapVidasProposta.containsKey(vida.GrupoProposta__r.ContratanteProposta__r.Proposta__c)){
				mapVidasProposta.put(vida.GrupoProposta__r.ContratanteProposta__r.Proposta__c, new List<SeguradoProposta__c>());
			}

			mapVidasProposta.get(vida.GrupoProposta__r.ContratanteProposta__r.Proposta__c).add(vida);
		}

		//Realiza validação, checkando se a uma conta/cpf já existe em uma proposta
		System.debug('vidasGrupoProposta ><:' + vidasGrupoProposta);
		System.debug('propostaGrupo ><:' + propostaGrupo);
		for(SeguradoProposta__c SeguradoProposta : vidasGrupoProposta){
			//Recupera a id da proposta relacionada a um grupo
			Id propostaId = propostaGrupo.get(SeguradoProposta.GrupoProposta__c);
			System.debug('propostaId ><:' + propostaId);
			//Valida todas as vidas dessa prosposta
			for(SeguradoProposta__c vida : mapVidasProposta.get(propostaId)){
				if(SeguradoProposta.Id != vida.Id && SeguradoProposta.Conta__c == vida.Conta__c){
					SeguradoProposta.addError('CPF já existente para uma mesma proposta.');
					break;
				}
			}
		}
	}
}