workspace-sf/force-app/main/default/objects/ContratanteProposta__c/ContratanteProposta__c.object-meta.xml
<CustomObject>
    <description>Objeto responsável por armazenar o cadastro dos contratantes da proposta</description>
    <label>Contratante da proposta</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contratantes da proposta</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/ContratanteProposta__c/fields/VigenciaInicial__c.field-meta.xml
<CustomField>
    <fullName>VigenciaInicial__c</fullName>
    <label>Vigência inicial</label>
    <type>Date</type>
</CustomField>

workspace-sf/force-app/main/default/objects/DadosCorretor__c/DadosCorretor__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar dados dos corretores.</description>
    <label>Dados do corretor</label>
    <nameField>
        <label>Código do corretor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dados dos corretores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/DadosCorretor__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Principal</fullName>
            </value>
            <value>
                <fullName>Produção</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/FormaPagamento__c/FormaPagamento__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar o cadastro das formas de pagamento</description>
    <label>Forma de pagamento</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Formas de pagamento</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/FormaPagamento__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <label>Código</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/FormaPagamento__c/fields/RamoSeguro__c.field-meta.xml
<CustomField>
    <fullName>RamoSeguro__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ramo de seguro</label>
    <referenceTo>RamoSeguro__c</referenceTo>
    <relationshipLabel>Formas de pagamento</relationshipLabel>
    <relationshipName>FormasPagamento</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Garantia__c/Garantia__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar o cadastro das garantias</description>
    <label>Garantia</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Garantias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/Garantia__c/fields/Sigla__c.field-meta.xml
<CustomField>
    <fullName>Sigla__c</fullName>
    <label>Sigla</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Garantia__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Em análise</fullName>
            </value>
            <value>
                <fullName>Ativo</fullName>
            </value>
            <value>
                <fullName>Inativo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/Garantia__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TipoGarantia</valueSetName>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/Garantia__c/fields/VigenciaInicial__c.field-meta.xml
<CustomField>
    <fullName>VigenciaInicial__c</fullName>
    <label>Vigência inicial</label>
    <type>Date</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaProduto__c/GarantiaProduto__c.object-meta.xml
<CustomObject>
    <description>Objeto de relacionamento entre os produtos e as garantias</description>
    <label>Garantia do produto</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Garantias do produto</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/GarantiaProduto__c/fields/Garantia__c.field-meta.xml
<CustomField>
    <fullName>Garantia__c</fullName>
    <label>Garantia</label>
    <referenceTo>Garantia__c</referenceTo>
    <relationshipLabel>Garantias do produto</relationshipLabel>
    <relationshipName>GarantiasProduto</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaProduto__c/fields/GarantiaProduto__c.field-meta.xml
<CustomField>
    <fullName>GarantiaProduto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Garantia do produto</label>
    <referenceTo>GarantiaProduto__c</referenceTo>
    <relationshipLabel>Garantias do produto (Garantia do produto)</relationshipLabel>
    <relationshipName>GarantiasProdutoTecnico</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaProduto__c/fields/OrdemPrioridade__c.field-meta.xml
<CustomField>
    <fullName>OrdemPrioridade__c</fullName>
    <inlineHelpText>Refere-se a prioridade para utilização do ramo líder caso haja a escolha de mais de uma garantia na contratação.</inlineHelpText>
    <label>Ordem de prioridade ramo líder</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaProduto__c/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Garantias do produto</relationshipLabel>
    <relationshipName>GarantiasProduto</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaProduto__c/fields/RamoSeguro__c.field-meta.xml
<CustomField>
    <fullName>RamoSeguro__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ramo de seguro</label>
    <referenceTo>RamoSeguro__c</referenceTo>
    <relationshipLabel>Garantias do produto</relationshipLabel>
    <relationshipName>GarantiasProduto</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaProduto__c/fields/TipoCapital__c.field-meta.xml
<CustomField>
    <fullName>TipoCapital__c</fullName>
    <label>Tipo de capital</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Capital global</fullName>
            </value>
            <value>
                <fullName>Capital uniforme</fullName>
            </value>
            <value>
                <fullName>Escalonado por cargo</fullName>
            </value>
            <value>
                <fullName>Escalonado por faixa salarial</fullName>
            </value>
            <value>
                <fullName>Livre escolha de capital</fullName>
            </value>
            <value>
                <fullName>Múltiplo por prêmio pago</fullName>
            </value>
            <value>
                <fullName>Múltiplo salarial</fullName>
            </value>
            <value>
                <fullName>Sem Capital</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaProduto__c/fields/TipoGarantia__c.field-meta.xml
<CustomField>
    <fullName>TipoGarantia__c</fullName>
    <label>Tipo de garantia</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TipoGarantia</valueSetName>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaProduto__c/recordTypes/ProdutoComercial.recordType-meta.xml
<RecordType>
    <fullName>ProdutoComercial</fullName>
    <active>true</active>
    <label>Produto comercial</label>
</RecordType>

workspace-sf/force-app/main/default/objects/GarantiaProduto__c/recordTypes/ProdutoTecnico.recordType-meta.xml
<RecordType>
    <fullName>ProdutoTecnico</fullName>
    <active>true</active>
    <label>Produto técnico</label>
</RecordType>

workspace-sf/force-app/main/default/objects/Modalidade__c/Modalidade__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar as modalidades</description>
    <label>Modalidade</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Modalidades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/Modalidade__c/fields/CodigoEmpresa__c.field-meta.xml
<CustomField>
    <fullName>CodigoEmpresa__c</fullName>
    <formula>Empresa__r.CodigoEmpresa__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Código da empresa</label>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Modalidade__c/fields/Empresa__c.field-meta.xml
<CustomField>
    <fullName>Empresa__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empresa</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Modalidades</relationshipLabel>
    <relationshipName>Modalidades</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Modalidade__c/fields/IdExterno__c.field-meta.xml
<CustomField>
    <fullName>IdExterno__c</fullName>
    <externalId>true</externalId>
    <label>Id externo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Modalidade__c/fields/RamoSeguro__c.field-meta.xml
<CustomField>
    <fullName>RamoSeguro__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ramo de seguro</label>
    <referenceTo>RamoSeguro__c</referenceTo>
    <relationshipLabel>Modalidades</relationshipLabel>
    <relationshipName>Modalidades</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/RamoGarantia__c/RamoGarantia__c.object-meta.xml
<CustomObject>
    <description>Objeto de relacionamento entre a garantia e o ramo</description>
    <label>Ramo da garantia</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ramos da garantia</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/RamoGarantia__c/fields/Garantia__c.field-meta.xml
<CustomField>
    <fullName>Garantia__c</fullName>
    <label>Garantia</label>
    <referenceTo>Garantia__c</referenceTo>
    <relationshipName>RamosGarantia</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/RamoGarantia__c/fields/RamoSeguro__c.field-meta.xml
<CustomField>
    <fullName>RamoSeguro__c</fullName>
    <label>Ramo de seguro</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>RamoSeguro__c.Status__c</field>
            <operation>equals</operation>
            <value>Ativo</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>RamoSeguro__c</referenceTo>
    <relationshipLabel>Ramos da garantia</relationshipLabel>
    <relationshipName>RamosGarantia</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/RamoSeguro__c/RamoSeguro__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar o cadastro dos ramos de seguro</description>
    <label>Ramo de seguro</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ramos de seguro</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/RamoSeguro__c/fields/CodigoEmpresa__c.field-meta.xml
<CustomField>
    <fullName>CodigoEmpresa__c</fullName>
    <label>Código da empresa</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/RamoSeguro__c/fields/Empresa__c.field-meta.xml
<CustomField>
    <fullName>Empresa__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empresa</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>RamosSeguro</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/RamoSeguro__c/fields/IdExterno__c.field-meta.xml
<CustomField>
    <fullName>IdExterno__c</fullName>
    <externalId>true</externalId>
    <label>Id externo</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

workspace-sf/force-app/main/default/objects/RamoSeguro__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ativo</fullName>
            </value>
            <value>
                <fullName>Inativo</fullName>
            </value>
            <value>
                <fullName>Em análise</fullName>
                <default>true</default>
                <label>Em análise</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/classes/SeguradoProposta2TriggerHandlerTest.cls
@isTest
private class SeguradoProposta2TriggerHandlerTest {
	
        
// 	@testSetup 
// 	static void setup(){
//         TestDataFactory.gerarDadosSetup();

//         //testInsertGarantiaProposta();
// 	}

//     @isTest
//     public static void testInsertSeguradoProposta2(){
    	
//     	Account conta = new Account(
//             RecordTypeId = RecordTypeBO.buscarTipoRegistro('Account', 'PessoaFisica').Id,
//             LastName = 'Teste2',
//             Nacionalidade__c = 'Brasileira',
//             CPF__c = '99922211176',
//             Rg__c = '232323231',
//             DataExpedicao__c = Date.today(),
//             OrgaoExpedidor__c = '123132',
//             PersonBirthDate = Date.valueOf('1980-12-24'),
//             EstadoCivil__c = 'Solteiro (a)'
//         );
//         insert conta;

//         Opportunity oportunidade = new Opportunity(
//             Name = 'Teste Contrato',
//             StageName = 'Em criação',
//             RecordTypeId = RecordTypeBO.buscarTipoRegistro('Opportunity', 'VidaIndividual').Id,
//             AccountId = conta.Id,
//             CloseDate = Date.today()
//         );
//         insert oportunidade;

//         Product2 produtoTec = new Product2(
//                 Name = 'Nome Produto Teste Versao',
//                 Status__c = 'Em criação',
//                 ProductCode = '201700001',
//                 VigenciaInicial__c = System.today().addDays(3),
//                 TipoCapital__c = 'Capital uniforme',
//                 Segmento__c = 'Coletivo',
//                 TipoResponsavelPagamento__c = 'PAR',
//                 NumeroSusep__c = '12345',
//                 RecordTypeId = RecordTypeBO.buscarTipoRegistro('Product2', 'ProdutoTecnico').Id,
//                 Versao__c                       = 1,
//                 VersaoMaxima__c                 = true,
//                 VersaoRenovacao__c              = 'Versão atual'
//         );

//         insert produtoTec;

//         produtoTec.Status__c = 'Em ativação';
// 		produtoTec.NumeroSusep__c = '1234x';
// 		update produtoTec;

// 		produtoTec.Status__c = 'Ativo';
// 		update produtoTec;

//         Product2 produtoComercial = new Product2(
//                 ProdutoTecnico__c               = produtoTec.Id,
//                 Name                            = 'Nome Produto Teste Versao',
//                 Status__c                       = 'Em criação',
//                 ProductCode                     = '201700001',
//                 VigenciaInicial__c              = System.today(),
//                 VigenciaFinal__c                = System.today().addDays(1),
//                 TipoCapital__c                  = 'Capital uniforme',
//                 Segmento__c                     = 'Coletivo',
//                 TipoResponsavelPagamento__c     = 'PAR',
//                 LimiteTotalCarregamento__c      = 200,
//                 NumeroSusep__c                  = '12345',
//                 RecordTypeId                    = RecordTypeBO.buscarTipoRegistro('Product2', 'ProdutoComercial').Id,
//                 Versao__c                       = 1,
//                 VersaoMaxima__c                 = true,
//                 VersaoRenovacao__c              = 'Versão atual'
//         );
//         insert produtoComercial;

//         RamoSeguro__c ramoSeguro = new RamoSeguro__c(
//                 Name = 'VIDA',
//                 CodigoEmpresa__c = '214',
//                 Codigo__c = '2',
//                 IdExterno__c = '214_2',
//                 Empresa__c = conta.Id,
//                 Status__c = 'Ativo'
//         );
//         insert ramoSeguro;

//         Garantia__c garantia = new Garantia__c(
//                 VigenciaInicial__c = System.today(),
//                 Tipo__c = 'Cobertura',
//                 Sigla__c = 'CAP'
//         );
//         insert garantia;

//         RamoGarantia__c ramoGarantia = new RamoGarantia__c(
//                 Garantia__c = garantia.Id,
//                 RamoSeguro__c = ramoSeguro.Id
//         );
//         insert ramoGarantia;

//         GarantiaProduto__c garantiaProduto = new GarantiaProduto__c(
//                 Garantia__c = garantia.Id,
//                 Produto__c = produtoTec.Id,
//                 RamoSeguro__c = ramoSeguro.Id,
//                 OrdemPrioridade__c = 1,
//                 RecordTypeId = RecordTypeBO.buscarTipoRegistro('GarantiaProduto__c', 'ProdutoTecnico').Id,
//                 TipoGarantia__c = 'Cobertura',
//                 TipoCapital__c = 'Capital uniforme',
//                 CodigoPromocao__c = 'VI005',
//                 VersaoTitulo__c = '1'
//         );
//         insert garantiaProduto;

//         Modalidade__c modalidade = new Modalidade__c(
//                 RamoSeguro__c = ramoSeguro.Id,
//                 Name = 'Mod teste',
//                 Codigo__c = '0'
//         );
//         insert modalidade;

//         FormaPagamento__c formaPagamento = TestDataFactory.gerarFormaPagamento(ramoSeguro,modalidade,'Boleto','BOL');
//         DadosCorretor__c dadosCorretor = TestDataFactory.gerarDadosCorretor(conta);
//         Quote proposta = TestDataFactory.gerarPropostaObjeto(produtoComercial, ramoSeguro, conta, dadosCorretor, oportunidade, modalidade);

//         ContratanteProposta__c seguradoProposta = TestDataFactory.gerarSeguradoProposta(conta, proposta, formaPagamento);
//     	GrupoProposta__c grupoProposta = TestDataFactory.gerarGrupoProposta(seguradoProposta);
//     	SeguradoProposta2__c SeguradoProposta2 = TestDataFactory.gerarSeguradoProposta2(conta, grupoProposta, formaPagamento);

// 		SeguradoProposta2.Numero__c = 1;
// 		update SeguradoProposta2;

//     	System.assertEquals(true, (SeguradoProposta2 != null));


//     }
	
}