workspace-sf/force-app/main/default/objects/ContratanteProposta__c/ContratanteProposta__c.object-meta.xml
<CustomObject>
    <description>Objeto responsável por armazenar o cadastro dos contratantes da proposta</description>
    <label>Contratante da proposta</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contratantes da proposta</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/ContratanteProposta__c/fields/Proposta__c.field-meta.xml
<CustomField>
    <fullName>Proposta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proposta</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Contratantes da proposta</relationshipLabel>
    <relationshipName>ContratantesProposta</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/classes/ExpurgoContratanteProposta.cls
/**
 * Expurgo de dados para o Proposta
 *  objeto: ContratanteProposta__c 
 * caminho do objeto:
 *  > ContratanteProposta__c 
 *  > Proposta__c
 * 
 * 28/02/2024
 */

public with sharing class ExpurgoContratanteProposta {
    public List<ContratanteProposta__c> getDadosExpurgo(Integer qt) { 
        List<ContratanteProposta__c> expList= new List<ContratanteProposta__c>();
        String query= 'SELECT Id '
            +'FROM ContratanteProposta__c '
            +'WHERE Proposta__r.Segmento__c = \'Massificados\' ';
        if (qt != 0) {
            query+= 'LIMIT :qt';
        }
        expList= Database.queryWithBinds(query, new Map<String,Object>{'qt' => qt}, AccessLevel.SYSTEM_MODE);
        System.debug(expList);
        return expList;
    }

    public void deleteDadosExpurgo(List<ContratanteProposta__c> expList) {
        if (!Test.isRunningTest()) {
           delete (List<ContratanteProposta__c>)expList;
        }
    }
}