workspace-sf/force-app/main/default/objects/ContratanteProposta__c/ContratanteProposta__c.object-meta.xml
<CustomObject>
    <description>Objeto responsável por armazenar o cadastro dos contratantes da proposta</description>
    <label>Contratante da proposta</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contratantes da proposta</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/ContratanteProposta__c/fields/Proposta__c.field-meta.xml
<CustomField>
    <fullName>Proposta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proposta</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Contratantes da proposta</relationshipLabel>
    <relationshipName>ContratantesProposta</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaContratanteProposta__c/GarantiaContratanteProposta__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar as garantias do contratante da proposta</description>
    <label>Garantia do contratante da proposta</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Garantias do contratante da proposta</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/GarantiaContratanteProposta__c/fields/ContratanteProposta__c.field-meta.xml
<CustomField>
    <fullName>ContratanteProposta__c</fullName>
    <label>Contratante da proposta</label>
    <referenceTo>ContratanteProposta__c</referenceTo>
    <relationshipLabel>Garantias do contratante da proposta</relationshipLabel>
    <relationshipName>GarantiasContratanteProposta</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/classes/ExpurgoGarantiaContratanteProposta.cls
/**
 * Expurgo de dados para o Proposta
 *  objeto: GarantiaContratanteProposta__c 
 * caminho do objeto:
 *  > GarantiaContratanteProposta__c 
 *  > ContratanteProposta__c
 *  > Proposta__c
 * 
 * 28/02/2024
 */

public with sharing class ExpurgoGarantiaContratanteProposta {
   
    public List<GarantiaContratanteProposta__c> getDadosExpurgo(Integer qt) { 
        List<GarantiaContratanteProposta__c> expList= new List<GarantiaContratanteProposta__c>();
        String query= 'SELECT Id '
            +'FROM GarantiaContratanteProposta__c '
            +'WHERE ContratanteProposta__r.Proposta__r.Segmento__c = \'Massificados\' ';
        if (qt != 0) {
            query+= 'LIMIT :qt';
        }
        expList= Database.queryWithBinds(query, new Map<String,Object>{'qt' => qt}, AccessLevel.SYSTEM_MODE);
        System.debug(expList);
        return expList;
    }

    public void deleteDadosExpurgo(List<GarantiaContratanteProposta__c> expList) {
        if (!Test.isRunningTest()) {
           delete (List<GarantiaContratanteProposta__c>)expList;
        }
    }
}