workspace-sf/force-app/main/default/objects/ContratanteProposta__c/ContratanteProposta__c.object-meta.xml
<CustomObject>
    <description>Objeto responsável por armazenar o cadastro dos contratantes da proposta</description>
    <label>Contratante da proposta</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contratantes da proposta</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/Garantia__c/Garantia__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar o cadastro das garantias</description>
    <label>Garantia</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Garantias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/Garantia__c/fields/Sigla__c.field-meta.xml
<CustomField>
    <fullName>Sigla__c</fullName>
    <label>Sigla</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Garantia__c/fields/VigenciaInicial__c.field-meta.xml
<CustomField>
    <fullName>VigenciaInicial__c</fullName>
    <label>Vigência inicial</label>
    <type>Date</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaProduto__c/GarantiaProduto__c.object-meta.xml
<CustomObject>
    <description>Objeto de relacionamento entre os produtos e as garantias</description>
    <label>Garantia do produto</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Garantias do produto</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/GarantiaProduto__c/fields/Garantia__c.field-meta.xml
<CustomField>
    <fullName>Garantia__c</fullName>
    <label>Garantia</label>
    <referenceTo>Garantia__c</referenceTo>
    <relationshipLabel>Garantias do produto</relationshipLabel>
    <relationshipName>GarantiasProduto</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaProduto__c/fields/GarantiaProduto__c.field-meta.xml
<CustomField>
    <fullName>GarantiaProduto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Garantia do produto</label>
    <referenceTo>GarantiaProduto__c</referenceTo>
    <relationshipLabel>Garantias do produto (Garantia do produto)</relationshipLabel>
    <relationshipName>GarantiasProdutoTecnico</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaProduto__c/fields/LimiteMaximoCaracteristicaEspecial__c.field-meta.xml
<CustomField>
    <fullName>LimiteMaximoCaracteristicaEspecial__c</fullName>
    <label>Limite máximo de característica especial</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaProduto__c/fields/LimiteMinimoCaracteristicaEspecial__c.field-meta.xml
<CustomField>
    <fullName>LimiteMinimoCaracteristicaEspecial__c</fullName>
    <label>Limite mínimo de característica especial</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaProduto__c/fields/OrdemPrioridade__c.field-meta.xml
<CustomField>
    <fullName>OrdemPrioridade__c</fullName>
    <inlineHelpText>Refere-se a prioridade para utilização do ramo líder caso haja a escolha de mais de uma garantia na contratação.</inlineHelpText>
    <label>Ordem de prioridade ramo líder</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaProduto__c/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Garantias do produto</relationshipLabel>
    <relationshipName>GarantiasProduto</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaProduto__c/fields/TipoCaracteristicaEspecial__c.field-meta.xml
<CustomField>
    <fullName>TipoCaracteristicaEspecial__c</fullName>
    <label>Tipo de característica especial</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ano(s)</fullName>
            </value>
            <value>
                <fullName>Assessoria</fullName>
            </value>
            <value>
                <fullName>Cestas</fullName>
            </value>
            <value>
                <fullName>Dia(s)</fullName>
            </value>
            <value>
                <fullName>Mês(es)</fullName>
            </value>
            <value>
                <fullName>Permanência no exterior</fullName>
            </value>
            <value>
                <fullName>Quilos</fullName>
            </value>
            <value>
                <fullName>Semana(s)</fullName>
            </value>
            <value>
                <fullName>Semestre(s)</fullName>
            </value>
            <value>
                <fullName>Trimestre(s)</fullName>
            </value>
            <value>
                <fullName>Sorteio</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaProduto__c/recordTypes/ProdutoComercial.recordType-meta.xml
<RecordType>
    <fullName>ProdutoComercial</fullName>
    <active>true</active>
    <label>Produto comercial</label>
</RecordType>

workspace-sf/force-app/main/default/objects/GarantiaProposta__c/GarantiaProposta__c.object-meta.xml
<CustomObject>
    <description>Objeto de relacionamento entre a garantia e a proposta.</description>
    <label>Garantia da proposta</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Garantias da proposta</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/GarantiaProposta__c/fields/Garantia__c.field-meta.xml
<CustomField>
    <fullName>Garantia__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Garantia</label>
    <referenceTo>Garantia__c</referenceTo>
    <relationshipLabel>Garantias da proposta (Garantia)</relationshipLabel>
    <relationshipName>GarantiasProposta</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaProposta__c/fields/GarantiaProduto__c.field-meta.xml
<CustomField>
    <fullName>GarantiaProduto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Garantia do produto</label>
    <referenceTo>GarantiaProduto__c</referenceTo>
    <relationshipLabel>Garantias da proposta</relationshipLabel>
    <relationshipName>GarantiasProposta</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaProposta__c/fields/Proposta__c.field-meta.xml
<CustomField>
    <fullName>Proposta__c</fullName>
    <label>Proposta</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Garantias da proposta</relationshipLabel>
    <relationshipName>GarantiasProposta</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GrupoProposta__c/GrupoProposta__c.object-meta.xml
<CustomObject>
    <description>Objeto responsável por armazenar o cadastro dos grupos de segurados da proposta</description>
    <label>Grupo da proposta</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grupos da proposta</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/GrupoProposta__c/fields/ContratanteProposta__c.field-meta.xml
<CustomField>
    <fullName>ContratanteProposta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contratante da proposta</label>
    <referenceTo>ContratanteProposta__c</referenceTo>
    <relationshipLabel>Grupos da proposta</relationshipLabel>
    <relationshipName>GruposProposta</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/SeguradoProposta__c/SeguradoProposta__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar os segurados da proposta</description>
    <label>Segurado da proposta</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Segurados da proposta</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/SeguradoProposta__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Segurados da proposta</relationshipLabel>
    <relationshipName>SeguradosProposta</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/SeguradoProposta__c/fields/GrupoProposta__c.field-meta.xml
<CustomField>
    <fullName>GrupoProposta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Grupo da proposta</label>
    <referenceTo>GrupoProposta__c</referenceTo>
    <relationshipLabel>Segurados da proposta</relationshipLabel>
    <relationshipName>SeguradosProposta</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/SeguradoProposta__c/fields/NomeContatoEmergencia__c.field-meta.xml
<CustomField>
    <fullName>NomeContatoEmergencia__c</fullName>
    <label>Nome do contato de emergência</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/SeguradoProposta__c/fields/TelefoneContatoEmergencia__c.field-meta.xml
<CustomField>
    <fullName>TelefoneContatoEmergencia__c</fullName>
    <label>Telefone do contato de emergência</label>
    <type>Phone</type>
</CustomField>

workspace-sf/force-app/main/default/objects/SeguradoProposta__c/fields/VigenciaFinal__c.field-meta.xml
<CustomField>
    <fullName>VigenciaFinal__c</fullName>
    <label>Vigência final</label>
    <type>Date</type>
</CustomField>

workspace-sf/force-app/main/default/objects/SeguradoProposta__c/fields/VigenciaInicial__c.field-meta.xml
<CustomField>
    <fullName>VigenciaInicial__c</fullName>
    <label>Vigência inicial</label>
    <type>Date</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Traducao__mdt/Traducao__mdt.object-meta.xml
<CustomObject>
    <description>Grava todas as traduções de registros que podem ser usadas em codificação
Ex: PDF das Garantias da Apólice e do Voucher</description>
    <label>Tradução</label>
    <pluralLabel>Tradução</pluralLabel>
</CustomObject>

workspace-sf/force-app/main/default/objects/Traducao__mdt/fields/Idioma__c.field-meta.xml
<CustomField>
    <fullName>Idioma__c</fullName>
    <inlineHelpText>Idioma ao qual se refere a tradução</inlineHelpText>
    <label>Idioma</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>enUS</fullName>
                <default>true</default>
                <label>Inglês (EUA)</label>
            </value>
            <value>
                <fullName>esES</fullName>
                <label>Espanhol (Espanha)</label>
            </value>
            <value>
                <fullName>frFR</fullName>
                <label>Francês (França)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/Traducao__mdt/fields/Objeto__c.field-meta.xml
<CustomField>
    <fullName>Objeto__c</fullName>
    <label>Objeto</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Garantia</fullName>
                <default>true</default>
                <label>Garantia</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/classes/VoucherController.cls
/**
* @author Renato Matheus Simião
* @version 1.0
* @date 2019-12-03
* @description Classe de controle para a criação de Voucher em Proposta
*/
// PLV-2939 INICIO
// PLV-3395	INICIO
// PLV-3726 INICIO
public class VoucherController {	//PLV-4805 INICIO/FIM
    
    public String renderAs { get; private set; }
    public SeguradoProposta__c segurado { get; private set; }
    
    public List<GarantiaWrapper> lwGarantiaPTBR { get; private set; }
    public List<GarantiaWrapper> lwGarantiaENUS { get; private set; }
    public List<GarantiaWrapper> lwGarantiaESES { get; private set; }
    public List<GarantiaWrapper> lwGarantiaFRFR { get; private set; }
    public Quote proposta {get; private set;}    
    public List<GarantiaProduto__c> lGarantiaPrdodutoTecnico{get; private set;}
    public List<GarantiaProposta__c> lGarantiaProposta{get; private set;}
    public String dataEmissao {get; private set;}
    public String nProposta {get; private set;}
    public String nomeSegurado {get; private set;}
    public String vigenciaInicial {get; private set;}
    public String vigenciaFinal {get; private set;}
    public String vigencia {get; private set;}
    public String vigenciaIng {get; private set;}
    public String vigenciaFr {get; private set;}
    public String vigenciaEs {get; private set;}
    public String pessoaParaAvisar {get; private set;}
    public String telefonePessoaParaAvisar {get; private set;}
    public String nomePlano {get; private set;}

    //LECVPV 189 - INICIO
    public Boolean hasSocialName                {get; set;} 
    public String  nomeSocial                   {get; set;}
    //LECVPV 189 - FIM
    
    public VoucherController() {

        this.lwGarantiaPTBR = new List<GarantiaWrapper>();
        this.lwGarantiaENUS = new List<GarantiaWrapper>();
        this.lwGarantiaESES = new List<GarantiaWrapper>();
        this.lwGarantiaFRFR = new List<GarantiaWrapper>();
        
        
        Map<String,String> mPageParam = ApexPages.currentPage().getParameters();
        
        this.renderAs = mPageParam.containsKey('renderAs') ?  mPageParam.get('renderAs') : '';
        //PLV-3746 - INICIO
        String propostaId;
        if (!mPageParam.containsKey('propostaId') && !mPageParam.containsKey('token') && (ApexPages.currentPage().getParameters().get('numero') == null || ApexPages.currentPage().getParameters().get('numero') == '')) {
            return;
        }
        if(mPageParam.containsKey('propostaId')){
            propostaId = mPageParam.get('propostaId');
        }
        if(mPageParam.containsKey('token')){
            CryptoToken c = new CryptoToken();  
            String chave = mPageParam.get('token');
            system.debug('chave'+chave);
            chave = chave.replace(' ','+');
            String chaveDescript = c.decrypt(chave);
            String dadosDoc = chaveDescript;
            String[] trataChave = dadosDoc.split('\\|');
            propostaId = trataChave[0];
            system.debug('propostaId'+propostaId);
            
        }
        if(ApexPages.currentPage().getParameters().get('numero') != null && ApexPages.currentPage().getParameters().get('numero') != ''){
            segurado = [SELECT Id, GrupoProposta__r.ContratanteProposta__r.Proposta__c,
                        NomeContatoEmergencia__c, TelefoneContatoEmergencia__c,
                        GrupoProposta__r.ContratanteProposta__r.Proposta__r.Name,
                        GrupoProposta__r.ContratanteProposta__r.Proposta__r.Produto__r.Name,
                        GrupoProposta__r.ContratanteProposta__r.Proposta__r.NumeroPropostaUnico__c,
                        GrupoProposta__r.ContratanteProposta__r.Proposta__r.VigenciaInicial__c,
                        GrupoProposta__r.ContratanteProposta__r.Proposta__r.VigenciaFinal__c,
                        GrupoProposta__r.ContratanteProposta__r.Proposta__r.DataProtocolo__c,
                        GrupoProposta__r.ContratanteProposta__r.Proposta__r.Produto__r.ProdutoTecnico__c,
                        Conta__r.Name,
                        Conta__r.NomeSocial__c //LECVPV 189 - INICIO/FIM  
                        FROM SeguradoProposta__c
                        WHERE GrupoProposta__r.ContratanteProposta__r.Proposta__r.Name =: ApexPages.currentPage().getParameters().get('numero')];
        }else{
            segurado = [SELECT Id, GrupoProposta__r.ContratanteProposta__r.Proposta__c,
                        NomeContatoEmergencia__c, TelefoneContatoEmergencia__c,
                        GrupoProposta__r.ContratanteProposta__r.Proposta__r.Name,
                        GrupoProposta__r.ContratanteProposta__r.Proposta__r.Produto__r.Name,
                        GrupoProposta__r.ContratanteProposta__r.Proposta__r.NumeroPropostaUnico__c,
                        GrupoProposta__r.ContratanteProposta__r.Proposta__r.VigenciaInicial__c,
                        GrupoProposta__r.ContratanteProposta__r.Proposta__r.VigenciaFinal__c,
                        GrupoProposta__r.ContratanteProposta__r.Proposta__r.DataProtocolo__c,
                        GrupoProposta__r.ContratanteProposta__r.Proposta__r.Produto__r.ProdutoTecnico__c,
                        Conta__r.Name,
                        Conta__r.NomeSocial__c //LECVPV 189 - INICIO/FIM 
                        FROM SeguradoProposta__c
                        WHERE GrupoProposta__r.ContratanteProposta__r.Proposta__c = :propostaId];
        }
        //PLV-3746 - FIM
        
        //LECVPV 189 - INICIO
        this.hasSocialName = String.isEmpty(segurado.Conta__r.NomeSocial__c) ? false : true;
        this.nomeSocial = segurado.Conta__r.NomeSocial__c;
         //LECVPV 189 - FIM
        
        lGarantiaPrdodutoTecnico = [SELECT  Id, Garantia__c, Garantia__r.Name,Garantia__r.Sigla__c,OrdemPrioridade__c, LimiteMinimoCaracteristicaEspecial__c,
                                    LimiteMaximoCaracteristicaEspecial__c, TipoCaracteristicaEspecial__c
                                    FROM GarantiaProduto__c
                                    WHERE Produto__c =: segurado.GrupoProposta__r.ContratanteProposta__r.Proposta__r.Produto__r.ProdutoTecnico__c ORDER BY OrdemPrioridade__c ASC];

        lGarantiaProposta = [SELECT Id, Capital__c, Garantia__r.Name, Garantia__r.Sigla__c, CurrencyIsoCode //AV-824-INICIO/FIM
                             FROM   GarantiaProposta__c
                             WHERE   Proposta__c = :segurado.GrupoProposta__r.ContratanteProposta__r.Proposta__c];
        
        proposta = [SELECT Id, TipoViagem__c, Produto__r.GerarVoucher__c //PLV - 4440  INICIO/FIM adicionado gerarvoucher na query
                    FROM Quote
                    WHERE Id =: segurado.GrupoProposta__r.ContratanteProposta__r.Proposta__c];
        
        if(!proposta.Produto__r.GerarVoucher__c)return; //PLV - 4440  INICIO/FIM Ajuste gerarVoucher produto
        
        pessoaParaAvisar = 	segurado.NomeContatoEmergencia__c;
        nomePlano = segurado.GrupoProposta__r.ContratanteProposta__r.Proposta__r.Produto__r.Name;
        nProposta = (segurado.GrupoProposta__r.ContratanteProposta__r.Proposta__r.NumeroPropostaUnico__c).replace('-','/');
        nomeSegurado = segurado.Conta__r.Name;
        System.debug('nomeSegurado '+nomeSegurado);
        vigenciaInicial = (segurado.GrupoProposta__r.ContratanteProposta__r.Proposta__r.VigenciaInicial__c).format();
        vigenciaFinal = (segurado.GrupoProposta__r.ContratanteProposta__r.Proposta__r.VigenciaFinal__c).format();
        vigencia = vigenciaInicial+ ' - '+ vigenciaFinal;
        vigenciaIng = vigencia.replace('-', 'and');
        vigenciaFr = vigencia.replace('-', 'au');
        vigenciaEs = vigencia.replace('-', 'al');
        dataEmissao = segurado.GrupoProposta__r.ContratanteProposta__r.Proposta__r.DataProtocolo__c.format();
        // PLV-3703 INICIO
        // VIAG-288 INICIO
        System.debug('segurado.TelefoneContatoEmergencia__c '+segurado.TelefoneContatoEmergencia__c);
        if( !String.isBlank(segurado.TelefoneContatoEmergencia__c) ){
            System.debug('tel1'+segurado.TelefoneContatoEmergencia__c);
            String tel = segurado.TelefoneContatoEmergencia__c.replace('-','');
            String newTel ;
    
            if(tel.left(2) == '55' && (tel.length() == 12 || tel.length() == 13)) {
                if(tel.length() == 13){
                    newTel = tel.left(2);
                    newTel += ' (' + tel.mid(2,2) + ') ';
                    newTel += tel.mid(4, 5);
                    newTel += '-';
                    newTel += tel.right(4);
                } else if(tel.length() == 12) {
                    newTel = tel.left(2);
                    newTel += ' (' + tel.mid(2,2) + ') ';
                    newTel += tel.mid(4, 4);
                    newTel += '-';
                    newTel += tel.right(4);
                }
                newTel = '+'+newTel;
            } else{
                if( tel.length() == 10 ){
                    newTel = '(' + tel.left(2) + ') ';
                    newTel += tel.mid(2, 4);
                    newTel += '-';
                    newTel += tel.right(4);
                } else if( tel.length() == 11 ){
                    newTel = '(' + tel.left(2) + ') ';
                    newTel += tel.mid(2, 5);
                    newTel += '-';
                    newTel += tel.right(4);
                } else {
                    newTel = tel;
                }
            }
            telefonePessoaParaAvisar = newTel;
        }
        // VIAG-288 FIM
        // PLV-3703 FIM     
        // Map de Tradução organizado pelo idioma e a Sigla da Garantia: Map<Idioma__c, Map<DeveloperName,Traducao__mdt>>
        //PLV-5277 - INICIO
        Map<String,Map<String,Traducao__mdt>> mTraducao = new Map<String,Map<String,Traducao__mdt>>();
        for (Traducao__mdt traducao : [SELECT Id, DeveloperName, Idioma__c, Texto__c
                                       FROM Traducao__mdt
                                       WHERE Objeto__c = 'Garantia'
                                       ORDER BY Idioma__c, DeveloperName]) {
                                           
            if (!traducao.DeveloperName.contains('_')) continue;
            
            Map<String, Traducao__mdt> mSigla;
            if (mTraducao.containsKey(traducao.Idioma__c)) {
                mSigla = mTraducao.get(traducao.Idioma__c);
            } else {
                mSigla = new Map<String, Traducao__mdt>();
                mTraducao.put(traducao.Idioma__c, mSigla);
            }
            
            mSigla.put(traducao.DeveloperName.split('_').get(0), traducao);
        }        
        for (GarantiaProduto__c garantiaProduto : [SELECT  Id, Produto__r.Name, Produto__r.RecordType.DeveloperName, Garantia__c, Garantia__r.Name,OrdemPrioridade__c, LimiteMinimoCaracteristicaEspecial__c,
                                    LimiteMaximoCaracteristicaEspecial__c, TipoCaracteristicaEspecial__c,Garantia__r.Sigla__c 
                                                   FROM GarantiaProduto__c                                                   
                                                   WHERE Produto__r.Id =: segurado.GrupoProposta__r.ContratanteProposta__r.Proposta__r.Produto__r.Id
                                                   AND Produto__r.RecordType.DeveloperName = 'ProdutoComercial'
                                                   ORDER BY OrdemPrioridade__c ASC]) {
                                                                   
            this.lwGarantiaPTBR.add(new GarantiaWrapper(garantiaProduto, mTraducao, 'ptBR', lGarantiaProposta));
            this.lwGarantiaENUS.add(new GarantiaWrapper(garantiaProduto, mTraducao, 'enUS', lGarantiaProposta));
            this.lwGarantiaESES.add(new GarantiaWrapper(garantiaProduto, mTraducao, 'esES', lGarantiaProposta));
            this.lwGarantiaFRFR.add(new GarantiaWrapper(garantiaProduto, mTraducao, 'frFR', lGarantiaProposta));
        }
        //PLV-5277 - FIM        
    }
    public class GarantiaWrapper {
        
        public String descricao { get; set; }
        public String capital { get; set; }
        public GarantiaProduto__c garantiaProposta { get; set; }
        
        public GarantiaWrapper(GarantiaProduto__c pGarantiaProduto, Map<String,Map<String,Traducao__mdt>> pmTraducao, String pIdioma, List<GarantiaProposta__c> gp) {
            
            this.garantiaProposta = pGarantiaProduto;
            system.debug('SIGLA: '+pGarantiaProduto.Garantia__r.Sigla__c);
            if (pmTraducao.containsKey(pIdioma) && pmTraducao.get(pIdioma).containsKey(pGarantiaProduto.Garantia__r.Sigla__c)) {
                system.debug('entrou na traducao');
                this.descricao = pmTraducao.get(pIdioma).get(pGarantiaProduto.Garantia__r.Sigla__c).Texto__c;
            } else {
                system.debug('nao entrou na traduçao');
                this.descricao = garantiaProposta.Garantia__r.Name;
            }
            system.debug('GPsize: '+gp.size());
            system.debug('gp: '+gp);
            for(GarantiaProposta__c g: gp){
                system.debug('g.Garantia__c: '+g.Garantia__c);
                system.debug('pGarantiaProduto.Garantia__c: '+pGarantiaProduto.Garantia__c);
                if(g.Garantia__c == pGarantiaProduto.Garantia__c){
                    if(g.Capital__c != null && g.Capital__c >0){
                        
                        
                        capital = trataValores(g.Capital__c.format(), g.CurrencyIsoCode); //PLV-3884 - INICIO/FIM - Ajuste Moedas
                        /* PLV-5277 - INICIO */
                        if(pGarantiaProduto.TipoCaracteristicaEspecial__c != null){
                            if(pIdioma == 'enUS'){
                                 
                                capital = capital +'('
                                    +pGarantiaProduto.LimiteMaximoCaracteristicaEspecial__c+ ' '+
                                    +'Day(s))';
                            }else if(pIdioma =='esES'){
                                capital = capital +'('
                                    +pGarantiaProduto.LimiteMaximoCaracteristicaEspecial__c+ ' '+
                                    +'Día(s))';
                            }else if(pIdioma =='frFR'){
                                capital = capital +'('
                                    +pGarantiaProduto.LimiteMaximoCaracteristicaEspecial__c+ ' '+
                                    +'jour(s))';
                            }else{
                                
                                capital = capital +'('
                                    +pGarantiaProduto.LimiteMaximoCaracteristicaEspecial__c+ ' '+
                                    +pGarantiaProduto.TipoCaracteristicaEspecial__c+ ')';
                            }
                            
                        }
                        /* PLV-5277 - FIM */
                        break;
                    }
                    else{
                        if(pIdioma == 'enUS'){
                            capital = 'Yes';
                            break;
                        }else if(pIdioma =='esES'){
                            capital = 'Si';
                            break;
                        }else if(pIdioma =='frFR'){
                            capital = 'Oui';
                            break;
                        }else{
                            capital = 'Contratada';
                            break;
                        }

                    }
                } else{
                        if(pIdioma == 'enUS'){
                            capital = 'No';
                        }else if(pIdioma =='esES'){
                            capital = 'No';
                        }else if(pIdioma =='frFR'){
                            capital = 'Non';
                        }else{
                            capital = 'Não Contratada';
                        }
                }
            }
        }
    }
    public PageReference doAction(){
        return new PageReference('/');
    }
    //PLV-3884 - INICIO - Ajuste Moedas
    public static String trataValores(string valor, string moeda){
        if(valor.contains(',')){
            string v = valor.substring(valor.indexOf(','),valor.length());
            if(v.length() == 2){
                if(moeda == 'BRL'){
                    valor = 'R$ '+valor +'0'; 
                }else if(moeda == 'USD'){
                    valor = 'US$ '+valor +'0';
                }else If(moeda == 'EUR'){
                    valor = '€ '+valor +'0';
                }
            }
        }else{
            if(moeda == 'BRL'){
                valor = 'R$ '+valor+',00';
            }else if(moeda == 'USD'){
                valor = 'US$ '+valor+',00';
            }else If(moeda == 'EUR'){
                valor = '€ '+valor+',00';
            }            
        }
        
        return valor;
    }
    //PLV-3884 - FIM - Ajuste Moedas
    
}
// PLV-2939 FIM
// PLV-3395 FIM
// PLV-3726 FIM