workspace-sf/force-app/main/default/objects/ContratanteProposta__c/ContratanteProposta__c.object-meta.xml
<CustomObject>
    <description>Objeto responsável por armazenar o cadastro dos contratantes da proposta</description>
    <label>Contratante da proposta</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contratantes da proposta</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/ContratanteProposta__c/fields/Proposta__c.field-meta.xml
<CustomField>
    <fullName>Proposta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proposta</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Contratantes da proposta</relationshipLabel>
    <relationshipName>ContratantesProposta</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GrupoProposta__c/GrupoProposta__c.object-meta.xml
<CustomObject>
    <description>Objeto responsável por armazenar o cadastro dos grupos de segurados da proposta</description>
    <label>Grupo da proposta</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grupos da proposta</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/GrupoProposta__c/fields/ContratanteProposta__c.field-meta.xml
<CustomField>
    <fullName>ContratanteProposta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contratante da proposta</label>
    <referenceTo>ContratanteProposta__c</referenceTo>
    <relationshipLabel>Grupos da proposta</relationshipLabel>
    <relationshipName>GruposProposta</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/SeguradoProposta__c/SeguradoProposta__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar os segurados da proposta</description>
    <label>Segurado da proposta</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Segurados da proposta</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/SeguradoProposta__c/fields/GrupoProposta__c.field-meta.xml
<CustomField>
    <fullName>GrupoProposta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Grupo da proposta</label>
    <referenceTo>GrupoProposta__c</referenceTo>
    <relationshipLabel>Segurados da proposta</relationshipLabel>
    <relationshipName>SeguradosProposta</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/classes/ExpurgoSeguradoProposta.cls
/**
 * Expurgo de dados para o Proposta
 *  objeto: SeguradoProposta__c
 * caminho do objeto:
 *  > GrupoProposta__c
 *  > ContratanteProposta__c
 *  > Proposta__c
 * 
 * 28/02/2024
 */

public with sharing class ExpurgoSeguradoProposta {
    
    public List<SeguradoProposta__c> getDadosExpurgo(Integer qt) { 
        List<SeguradoProposta__c> expList= new List<SeguradoProposta__c>();
        String query= 'SELECT Id '
            +'FROM SeguradoProposta__c '
            +'WHERE GrupoProposta__r.ContratanteProposta__r.Proposta__r.Segmento__c = \'Massificados\' ';
        if (qt != 0) {
            query+= 'LIMIT :qt';
        }
        expList= Database.queryWithBinds(query, new Map<String,Object>{'qt' => qt}, AccessLevel.SYSTEM_MODE);
        System.debug(expList);
        return expList;
    }

    public void deleteDadosExpurgo(List<SeguradoProposta__c> expList) {
        if (!Test.isRunningTest()) {
           delete (List<SeguradoProposta__c>)expList;
        }
    }
}