workspace-sf/force-app/main/default/objects/FavorecidoRemuneracaoContrato__c/FavorecidoRemuneracaoContrato__c.object-meta.xml
<CustomObject>
    <label>Favorecido da Remuneração do Contrato</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Favorecido da Remuneração do Contrato</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Favorecidos da Remuneração do Contrato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/FavorecidoRemuneracaoContrato__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Favorecidos_do_Contrato</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/FavorecidoRemuneracaoContrato__c/fields/CorretorLider__c.field-meta.xml
<CustomField>
    <fullName>CorretorLider__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Corretor Lider</label>
    <type>Checkbox</type>
</CustomField>

workspace-sf/force-app/main/default/objects/FavorecidoRemuneracaoContrato__c/fields/RemuneracaoContrato__c.field-meta.xml
<CustomField>
    <fullName>RemuneracaoContrato__c</fullName>
    <label>Remuneração do contrato</label>
    <referenceTo>RemuneracaoContrato__c</referenceTo>
    <relationshipLabel>Favorecidos da Remuneração do Contrato</relationshipLabel>
    <relationshipName>FavorecidosContrato</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/RemuneracaoContrato__c/RemuneracaoContrato__c.object-meta.xml
<CustomObject>
    <description>Objeto de relacionamento entre o contrato e o tipo de remuneração.</description>
    <label>Remuneração do contrato</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Remunerações do contrato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/RemuneracaoContrato__c/fields/TipoRemuneracao__c.field-meta.xml
<CustomField>
    <fullName>TipoRemuneracao__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tipo de remuneração</label>
    <referenceTo>TipoRemuneracao__c</referenceTo>
    <relationshipLabel>Remunerações do contrato</relationshipLabel>
    <relationshipName>RemuneracoesContrato</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/TipoRemuneracao__c/TipoRemuneracao__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar o cadastro dos tipos de remuneração</description>
    <label>Tipo de remuneração</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tipos de remuneração</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/classes/PortoSeguroBoasVindasController.cls
//INICIO | PLV-4433-VI (Digital)
/*
*  @author Squad Avanxo 
*  @Descrição: Controller PortoSeguroBoasVindas
*/
public class PortoSeguroBoasVindasController {

    public Contract contrato {get;set;}
    public FavorecidoRemuneracaoContrato__c corretor {get;set;}
    public String errorMessage {get;set;}

    public PortoSeguroBoasVindasController(){
        this.getContrato();
        this.getCorretor();
    }

    private void getContrato(){
        String numeroContrato = ApexPages.currentPage().getParameters().get('numeroContrato'); 
        if(!string.isBlank(numeroContrato)){
            try{
                this.contrato = [SELECT Id, Account.Name, Account.PersonEmail, Account.PersonMobilePhone, NumeroApolice__c, (SELECT Id FROM RemuneracoesContrato__r WHERE TipoRemuneracao__r.Codigo__c = 'COR') FROM Contract WHERE Name =: numeroContrato];
            }
            catch(Exception ex){
                this.errorMessage = 'Número de contrato inválido';
            }
            
        }
        else{
            try{
                String token = ApexPages.currentPage().getParameters().get('token');
                token = token.replace(' ','+');
                CryptoToken c = new CryptoToken();                     
                String chaveDescript = c.decrypt(token);  
                String[] trataChave = chaveDescript.split('\\|');
                this.contrato = [SELECT Id, Account.Name, Account.PersonEmail, Account.PersonMobilePhone, NumeroApolice__c, (SELECT Id FROM RemuneracoesContrato__r WHERE TipoRemuneracao__r.Codigo__c = 'COR') FROM Contract WHERE Id =: Id.valueof(trataChave[0])];
            }
            catch(Exception ex){
                this.errorMessage = 'Token inválido';
            }
        }
    }

    private void getCorretor(){
        if(this.contrato != null && this.contrato.RemuneracoesContrato__r.size() > 0){
            this.corretor = [SELECT Id, Conta__r.Name, Conta__r.Phone, Conta__r.Email__c FROM FavorecidoRemuneracaoContrato__c
                        WHERE RemuneracaoContrato__c = : this.contrato.RemuneracoesContrato__r[0].Id AND CorretorLider__c = true];
        }
    }
}
//FIM | PLV-4433-VI (Digital)