workspace-sf/force-app/main/default/objects/ContratanteContrato__c/ContratanteContrato__c.object-meta.xml
<CustomObject>
    <description>Objeto responsável por armazenar o cadastro dos contratantes do contrato</description>
    <label>Contratante do contrato</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contratantes do contrato</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/ContratanteProposta__c/ContratanteProposta__c.object-meta.xml
<CustomObject>
    <description>Objeto responsável por armazenar o cadastro dos contratantes da proposta</description>
    <label>Contratante da proposta</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contratantes da proposta</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/GrupoContrato__c/GrupoContrato__c.object-meta.xml
<CustomObject>
    <description>Objeto responsável por armazenar os dados dos grupos de segurados do contrato</description>
    <label>Grupo do contrato</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grupos do contrato</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/GrupoContrato__c/fields/ContratanteContrato__c.field-meta.xml
<CustomField>
    <fullName>ContratanteContrato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contratante do contrato</label>
    <referenceTo>ContratanteContrato__c</referenceTo>
    <relationshipLabel>Grupos do contrato</relationshipLabel>
    <relationshipName>GruposContrato</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GrupoProposta__c/GrupoProposta__c.object-meta.xml
<CustomObject>
    <description>Objeto responsável por armazenar o cadastro dos grupos de segurados da proposta</description>
    <label>Grupo da proposta</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grupos da proposta</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/GrupoProposta__c/fields/ContratanteProposta__c.field-meta.xml
<CustomField>
    <fullName>ContratanteProposta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contratante da proposta</label>
    <referenceTo>ContratanteProposta__c</referenceTo>
    <relationshipLabel>Grupos da proposta</relationshipLabel>
    <relationshipName>GruposProposta</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GrupoRisco__c/GrupoRisco__c.object-meta.xml
<CustomObject>
    <label>Grupo de Risco</label>
    <nameField>
        <label>Nome do Grupo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grupos de Risco</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/SeguradoContrato__c/SeguradoContrato__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar os segurados do contrato</description>
    <label>Segurado do contrato</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Segurados do contrato</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/SeguradoContrato__c/fields/GrupoContrato__c.field-meta.xml
<CustomField>
    <fullName>GrupoContrato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Grupo do contrato</label>
    <referenceTo>GrupoContrato__c</referenceTo>
    <relationshipLabel>Segurados do contrato</relationshipLabel>
    <relationshipName>SeguradosContrato</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/SeguradoContrato__c/fields/GrupoRisco__c.field-meta.xml
<CustomField>
    <fullName>GrupoRisco__c</fullName>
    <label>Grupo de Risco</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/SeguradoProposta__c/SeguradoProposta__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar os segurados da proposta</description>
    <label>Segurado da proposta</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Segurados da proposta</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/SeguradoProposta__c/fields/GrupoProposta__c.field-meta.xml
<CustomField>
    <fullName>GrupoProposta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Grupo da proposta</label>
    <referenceTo>GrupoProposta__c</referenceTo>
    <relationshipLabel>Segurados da proposta</relationshipLabel>
    <relationshipName>SeguradosProposta</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/SeguradoProposta__c/fields/GrupoRisco__c.field-meta.xml
<CustomField>
    <fullName>GrupoRisco__c</fullName>
    <label>Grupo de risco</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/classes/UpdateGrupoRisco.cls
public class UpdateGrupoRisco implements
    Database.Batchable<sObject>, Database.Stateful {
    // instance member to retain state across transactions
    public Integer registrosLidos = 0;
    public Integer registrosProcessados = 0;

    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(
            'SELECT GrupoContrato__r.ContratanteContrato__r.Contrato__r.Proposta__r.NumeroProposta__c, Id, GrupoRisco__c ' +                                                                       +
            'FROM   SeguradoContrato__c '                                                                                  +
            'WHERE  GrupoContrato__r.ContratanteContrato__r.Contrato__r.Segmento__c = \'Individual\''
        );
    }
    public void execute(Database.BatchableContext bc, List<SeguradoContrato__c> scope){
        if (scope.size() == 0) {
            System.debug('Nenhum SeguradoContrato__c encontrado com os parâmetros informados');
            return;
        }

        Map<String, String> mapSeguradosContratos = new Map<String, String>();
        String numeroProposta;

        for (SeguradoContrato__c segCont : scope) {
            // numeroProposta = (String)segCont.getSobject('GrupoContrato__r.ContratanteContrato__r.Contrato__r.Proposta__r').get('NumeroProposta__c');
            numeroProposta = segCont.GrupoContrato__r.ContratanteContrato__r.Contrato__r.Proposta__r.NumeroProposta__c;
            mapSeguradosContratos.put(numeroProposta, segCont.Id);
            registrosLidos = registrosLidos + 1;
        }
        Set<String> propostas = mapSeguradosContratos.keySet();
        List<SeguradoProposta__c> listSeguradosPropostas = [ SELECT GrupoProposta__r.ContratanteProposta__r.Proposta__r.NumeroProposta__c,
                                                                    GrupoRisco__c
                                                             FROM   SeguradoProposta__c
                                                             WHERE  GrupoProposta__r.ContratanteProposta__r.Proposta__r.NumeroProposta__c 
                                                             IN     :propostas
                                                           ];
        if (listSeguradosPropostas.size() == 0) {
            System.debug('Nenhum SeguradoProposta__c encontrado com os Ids referentes a Proposta__c buscados via SeguradoContrato__c');
            return;
        }

        Map<String, String> mapSeguradosPropostas = new Map<String, String>();
        for (SeguradoProposta__c segProp : listSeguradosPropostas) {
            //numeroProposta = (String)segProp.getSobject('GrupoProposta__r.ContratanteProposta__r.Proposta__r').get('NumeroProposta__c');
            numeroProposta = segProp.GrupoProposta__r.ContratanteProposta__r.Proposta__r.NumeroProposta__c;
            mapSeguradosPropostas.put(numeroProposta, segProp.GrupoRisco__c);
        }
        for (SeguradoContrato__c segCont : scope) {
            //numeroProposta = (String)segCont.getSobject('GrupoContrato__r.ContratanteContrato__r.Contrato__r.Proposta__r').get('NumeroProposta__c');
            numeroProposta = segCont.GrupoContrato__r.ContratanteContrato__r.Contrato__r.Proposta__r.NumeroProposta__c;
            if (mapSeguradosContratos.get(numeroProposta) == null) {
                System.debug('Não Encontrado um ID de Segurado Contrato Para um Id de Proposta armazenado no mapSeguradosContratos');
                System.debug('Número Proposta = ' + numeroProposta);
                return;
            }
            if (segCont.Id == mapSeguradosContratos.get(numeroProposta)) {
                segCont.GrupoRisco__c = mapSeguradosPropostas.get(numeroProposta);
                registrosProcessados = registrosProcessados + 1;
            } else {
                System.debug('ID Segurado Contrato armazenado não corresponde ao Número da Proposta');
                System.debug('ID Segurado Contrato = ' + segCont.Id);
                return;
            }   
        }
        update scope;
    }

    public void finish(Database.BatchableContext bc){
        System.debug('Total Registros Lidos = ' + registrosLidos);
        System.debug('Total Registros `Processados = ' + registrosProcessados);
        if(registrosLidos == 0 || registrosProcessados == 0) {
            System.debug('Processamento Não Realizado com Sucesso');
            return;
        }
        AsyncApexJob job = [SELECT Id, Status, NumberOfErrors,
            JobItemsProcessed,
            TotalJobItems, CreatedBy.Email
            FROM AsyncApexJob
            WHERE Id = :bc.getJobId()];
        System.debug('Id Job AsyncApexJob = ' + job.Id);
        System.debug('Status Job AsyncApexJob = ' + job.Status);
        System.debug('Numero Erros Job AsyncApexJob = ' + job.NumberOfErrors);
    }
}