workspace-sf/force-app/main/default/objects/ContratanteContrato__c/ContratanteContrato__c.object-meta.xml
<CustomObject>
    <description>Objeto responsável por armazenar o cadastro dos contratantes do contrato</description>
    <label>Contratante do contrato</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contratantes do contrato</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/DadosCorretor__c/DadosCorretor__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar dados dos corretores.</description>
    <label>Dados do corretor</label>
    <nameField>
        <label>Código do corretor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dados dos corretores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/DadosCorretor__c/fields/NomeCorretor__c.field-meta.xml
<CustomField>
    <fullName>NomeCorretor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nome do corretor</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>CodigosCorretores</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/FavorecidoRemuneracaoContrato__c/FavorecidoRemuneracaoContrato__c.object-meta.xml
<CustomObject>
    <label>Favorecido da Remuneração do Contrato</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Favorecido da Remuneração do Contrato</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Favorecidos da Remuneração do Contrato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/FavorecidoRemuneracaoContrato__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Favorecidos_do_Contrato</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/FavorecidoRemuneracaoContrato__c/fields/CorretorLider__c.field-meta.xml
<CustomField>
    <fullName>CorretorLider__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Corretor Lider</label>
    <type>Checkbox</type>
</CustomField>

workspace-sf/force-app/main/default/objects/FavorecidoRemuneracaoContrato__c/fields/DadosCorretor__c.field-meta.xml
<CustomField>
    <fullName>DadosCorretor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dados do corretor</label>
    <referenceTo>DadosCorretor__c</referenceTo>
    <relationshipLabel>Favorecidos da Remuneração do Contrato</relationshipLabel>
    <relationshipName>FavorecidosRemuneracaoContrato</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/FavorecidoRemuneracaoContrato__c/fields/RemuneracaoContrato__c.field-meta.xml
<CustomField>
    <fullName>RemuneracaoContrato__c</fullName>
    <label>Remuneração do contrato</label>
    <referenceTo>RemuneracaoContrato__c</referenceTo>
    <relationshipLabel>Favorecidos da Remuneração do Contrato</relationshipLabel>
    <relationshipName>FavorecidosContrato</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Garantia__c/Garantia__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar o cadastro das garantias</description>
    <label>Garantia</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Garantias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/Garantia__c/fields/Sigla__c.field-meta.xml
<CustomField>
    <fullName>Sigla__c</fullName>
    <label>Sigla</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaSeguradoContrato__c/GarantiaSeguradoContrato__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar as garantias do segurado do contrato</description>
    <label>Garantia do segurado do contrato</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Garantias do segurado do contrato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/GarantiaSeguradoContrato__c/fields/Garantia__c.field-meta.xml
<CustomField>
    <fullName>Garantia__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Garantia</label>
    <referenceTo>Garantia__c</referenceTo>
    <relationshipLabel>Garantias do segurado do contrato (Garantia)</relationshipLabel>
    <relationshipName>GarantiasSeguradoContrato</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaSeguradoContrato__c/fields/SeguradoContrato__c.field-meta.xml
<CustomField>
    <fullName>SeguradoContrato__c</fullName>
    <label>Segurado do contrato</label>
    <referenceTo>SeguradoContrato__c</referenceTo>
    <relationshipLabel>Garantias do segurado do contrato</relationshipLabel>
    <relationshipName>GarantiasSeguradoContrato</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GrupoContrato__c/GrupoContrato__c.object-meta.xml
<CustomObject>
    <description>Objeto responsável por armazenar os dados dos grupos de segurados do contrato</description>
    <label>Grupo do contrato</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grupos do contrato</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/GrupoContrato__c/fields/ContratanteContrato__c.field-meta.xml
<CustomField>
    <fullName>ContratanteContrato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contratante do contrato</label>
    <referenceTo>ContratanteContrato__c</referenceTo>
    <relationshipLabel>Grupos do contrato</relationshipLabel>
    <relationshipName>GruposContrato</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/PagamentoGarantia__c/PagamentoGarantia__c.object-meta.xml
<CustomObject>
    <description>Registrar os pagamentos das garantias dentro da frente de Sinistro Vida.
Objeto Detalhe de Caso</description>
    <label>Garantia do Sinistro</label>
    <nameField>
        <label>Nome da Garantia do Sinistro</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Garantias do Sinistro</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/PagamentoGarantia__c/fields/Caso__c.field-meta.xml
<CustomField>
    <fullName>Caso__c</fullName>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>Pagamentos_de_garantia</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/PagamentoGarantia__c/fields/Garantia_do_segurado_do_contrato__c.field-meta.xml
<CustomField>
    <fullName>Garantia_do_segurado_do_contrato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Garantia do segurado do contrato</label>
    <referenceTo>GarantiaSeguradoContrato__c</referenceTo>
    <relationshipName>Pagamentos_de_garantia</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/PagamentoGarantia__c/fields/Saldo_da_reserva__c.field-meta.xml
<CustomField>
    <fullName>Saldo_da_reserva__c</fullName>
    <label>Saldo da reserva - Garantia</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

workspace-sf/force-app/main/default/objects/PagamentoGarantia__c/fields/Valor_Pago__c.field-meta.xml
<CustomField>
    <fullName>Valor_Pago__c</fullName>
    <label>Valor Pago - Garantia</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Parceiro__c/Parceiro__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar as informações dos parceiros da Porto</description>
    <label>Parceiro</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parceiros</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/Parceiro__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <formula>LPAD( Conta__r.IdExterno__c , 14, &quot;0&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Código de identificação do parceiro  - CNPJ da conta sem pontuação</inlineHelpText>
    <label>Código</label>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Parceiro__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Parceiros</relationshipLabel>
    <relationshipName>Parceiro</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/RemuneracaoContrato__c/RemuneracaoContrato__c.object-meta.xml
<CustomObject>
    <description>Objeto de relacionamento entre o contrato e o tipo de remuneração.</description>
    <label>Remuneração do contrato</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Remunerações do contrato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/RemuneracaoContrato__c/fields/Contrato__c.field-meta.xml
<CustomField>
    <fullName>Contrato__c</fullName>
    <label>Contrato</label>
    <referenceTo>Contract</referenceTo>
    <relationshipName>RemuneracoesContrato</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/RemuneracaoContrato__c/fields/TipoRemuneracao__c.field-meta.xml
<CustomField>
    <fullName>TipoRemuneracao__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tipo de remuneração</label>
    <referenceTo>TipoRemuneracao__c</referenceTo>
    <relationshipLabel>Remunerações do contrato</relationshipLabel>
    <relationshipName>RemuneracoesContrato</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/SeguradoContrato__c/SeguradoContrato__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar os segurados do contrato</description>
    <label>Segurado do contrato</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Segurados do contrato</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/SeguradoContrato__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Segurados do contrato (Conta)</relationshipLabel>
    <relationshipName>SeguradoContrato</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/SeguradoContrato__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <length>70</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/SeguradoContrato__c/fields/GrupoContrato__c.field-meta.xml
<CustomField>
    <fullName>GrupoContrato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Grupo do contrato</label>
    <referenceTo>GrupoContrato__c</referenceTo>
    <relationshipLabel>Segurados do contrato</relationshipLabel>
    <relationshipName>SeguradosContrato</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/TipoRemuneracao__c/TipoRemuneracao__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar o cadastro dos tipos de remuneração</description>
    <label>Tipo de remuneração</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tipos de remuneração</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/classes/CasoDAO.cls
/**************************************************************************************************************************************************************************
 *
 *  Classe responsável pela busca de dados de Caso
 *
 **************************************************************************************************************************************************************************/
public virtual class CasoDAO {
    
    private static final CasoDAO instancia = new CasoDAO();

  private CasoDAO() { }

  public static CasoDAO getInstance(){
    return instancia;
  }
  
    
    /*public List<Case> buscarSinistroPorId(Set<Id> Ids) {
    return [SELECT Id, AccountId, Dataocorrencia__c, Data_sinistro_avisado__c, Status,
                   Status_Dependente__c, NumeroSinistro__c,
                   Contrato__r.Parceria__c, Contrato__r.Parceria__r.Codigo__c,
                   Contrato__r.Produto__c, Contrato__r.Proposta__r.Origem__c,
                   Contrato__r.Proposta__r.QuoteNumber, Contrato__r.NumeroApolice__c,
                   Account.Cpf__c, Account.Name, CreatedDate, CaseNumber, Contrato__r.Parceiro__c,
                   (SELECT Id, Conta__r.Cpf__c, Conta__r.Name
                   FROM Beneficiarios_do_sinistro__r)
                   FROM Case
           WHERE Id IN :Ids ORDER BY Contrato__r.Parceria__c 
        ];  
  }*/
    //PLV-4938 - INICIO - PEDRO AUGUSTO BRAZ
    public List<Case> getCaseBySetId(Set<Id> Ids) {
      return [SELECT Id
                    , AccountId
                    , Dataocorrencia__c
                    , Data_sinistro_avisado__c
                    , Status
                    , Account.Cpf__c
                    , Account.Name
                    , CreatedDate
                    , CaseNumber
                    , Contrato__r.Parceiro__c
                    , Vitima__c
                    , Subject
                    , Description
                    , ContactId
                    , Type
                    , Data_pagamento__c // LECVP-317 - INICIO
                    , Invoice__c                   
                    , Contrato__r.TipoViagem__c
                    , Contrato__r.CodigoRamo__c  // LECVP-317 - FIM
                    , Valor_Pago__c // LECVP-344 - INICIO
                    , Saldo_da_reserva__c // LECVP-344 - FIM
                    FROM Case
            WHERE Id IN :Ids
          ];  
    }
    //PLV-4938 - FIM - PEDRO AUGUSTO BRAZ
     
    //contrato > remuneração >
   
    public Map<Id,FavorecidoRemuneracaoContrato__c> buscarCorretores(Set<Id> psContratoId) {

        Map<Id, FavorecidoRemuneracaoContrato__c> mFavRemunCont = new Map<Id, FavorecidoRemuneracaoContrato__c>();

        /* retirado por solicitação de mudança
         * for (RemuneracaoContrato__c remCont : [SELECT Id, Contrato__c, Conta__r.Email__c, DadosCorretor__r.Name, DadosCorretor__r.NomeCorretor__r.Name
                                                 FROM RemuneracaoContrato__c
                                                WHERE Lider__c = true
                                                  AND Contrato__c IN :psContratoId
                                                  AND TipoRemuneracao__r.Name = 'Corretagem']) {*/

        List<FavorecidoRemuneracaoContrato__c> favorecidos = [SELECT Id, RemuneracaoContrato__r.Contrato__c, DadosCorretor__r.Name, DadosCorretor__r.NomeCorretor__r.Email__c, DadosCorretor__r.NomeCorretor__r.PersonEmail, DadosCorretor__r.NomeCorretor__r.Name 
                                                              FROM FavorecidoRemuneracaoContrato__c 
                                                              // WHERE RemuneracaoContrato__r.TipoRemuneracao__r.Name = 'Corretagem' 
                                                              // AND CorretorLider__c = true 
                                                              // AND RemuneracaoContrato__r.Contrato__c IN :psContratoId
                                                              ];

        System.debug('XXX - FAVORECIDO: ' + JSON.serialize(favorecidos));
                                                  
    for (FavorecidoRemuneracaoContrato__c favRemCont : [SELECT Id, RemuneracaoContrato__r.Contrato__c, DadosCorretor__r.Name, DadosCorretor__r.NomeCorretor__r.Email__c, DadosCorretor__r.NomeCorretor__r.PersonEmail, DadosCorretor__r.NomeCorretor__r.Name 
                                          FROM FavorecidoRemuneracaoContrato__c 
                                          WHERE RemuneracaoContrato__r.TipoRemuneracao__r.Name = 'Corretagem' 
                                          AND CorretorLider__c = true 
                                          AND RemuneracaoContrato__r.Contrato__c IN :psContratoId]) {
                                                      
            mFavRemunCont.put(favRemCont.RemuneracaoContrato__r.Contrato__c, favRemCont);
        }

        return mFavRemunCont;
    }

    public Map<Id,Case> buscarCasosDaConta(Set<Id> psContaId){

      Map<Id,Case> mCases = new Map<Id,Case>();

      for(Case casosConta : [SELECT Id, CaseNumber, AccountId, Vitima__c, Dataocorrencia__c, RecordTypeId 
                            FROM Case 
                            WHERE AccountId IN :psContaId
                            AND Vitima__c != 'Filhos']){

        mCases.put(casosConta.Id, casosConta);
      }

      return mCases;
    }

    //Método alterado para a história PLV-1722
    public Map<Id, GarantiaSeguradoContrato__c> buscarContratos(Set<Id> psCasoId)
    {
        Map<Id, GarantiaSeguradoContrato__c> mSeguradoContrato = new Map<Id, GarantiaSeguradoContrato__c>(
            [SELECT SeguradoContrato__r.GrupoContrato__r.ContratanteContrato__r.Contrato__c, Garantia__c,SeguradoContrato__c, SeguradoContrato__r.Conta__r.Name
               FROM GarantiaSeguradoContrato__c
              WHERE Id IN :psCasoId]
        );
       
        return mSeguradoContrato;
    }

    //LECVP-317 - INICIO
    public List<PagamentoGarantia__c> buscarPgtoGarCasoSinCobCodRamo(Set<Id> casosId, String cobertura, String codigoRamo){
      List<PagamentoGarantia__c> pgtoGarantia = [
              SELECT 
                Id,
                Garantia_do_segurado_do_contrato__r.Garantia__r.Sigla__c,
                Caso__c,
                Caso__r.Type,
                Caso__r.Contrato__r.CodigoRamo__c,
                Caso__r.Contrato__r.TipoViagem__c 
              FROM
                PagamentoGarantia__c 
              WHERE
                Garantia_do_segurado_do_contrato__r.Garantia__r.Sigla__c = :cobertura 
              AND
                Caso__r.Contrato__r.CodigoRamo__c = :codigoRamo 
              AND
                Caso__c IN :casosId
              AND
                Caso__r.Type ='Sinistro'
            ];

            return pgtoGarantia;
    }
    //LECVP-317 - FIM  
}