workspace-sf/force-app/main/default/objects/ContratanteContrato__c/ContratanteContrato__c.object-meta.xml
<CustomObject>
    <description>Objeto responsável por armazenar o cadastro dos contratantes do contrato</description>
    <label>Contratante do contrato</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contratantes do contrato</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/ContratanteContrato__c/fields/Contrato__c.field-meta.xml
<CustomField>
    <fullName>Contrato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contrato</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Contratantes do contrato</relationshipLabel>
    <relationshipName>ContratantesContrato</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Garantia__c/Garantia__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar o cadastro das garantias</description>
    <label>Garantia</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Garantias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/GarantiaSeguradoContrato__c/GarantiaSeguradoContrato__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar as garantias do segurado do contrato</description>
    <label>Garantia do segurado do contrato</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Garantias do segurado do contrato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/GarantiaSeguradoContrato__c/fields/Garantia__c.field-meta.xml
<CustomField>
    <fullName>Garantia__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Garantia</label>
    <referenceTo>Garantia__c</referenceTo>
    <relationshipLabel>Garantias do segurado do contrato (Garantia)</relationshipLabel>
    <relationshipName>GarantiasSeguradoContrato</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaSeguradoContrato__c/fields/Nomenclatura_Pesquisa_Garantia_Segurado__c.field-meta.xml
<CustomField>
    <fullName>Nomenclatura_Pesquisa_Garantia_Segurado__c</fullName>
    <externalId>true</externalId>
    <label>CPF-Apólice-Garantia-</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaSeguradoContrato__c/fields/SeguradoContrato__c.field-meta.xml
<CustomField>
    <fullName>SeguradoContrato__c</fullName>
    <label>Segurado do contrato</label>
    <referenceTo>SeguradoContrato__c</referenceTo>
    <relationshipLabel>Garantias do segurado do contrato</relationshipLabel>
    <relationshipName>GarantiasSeguradoContrato</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GrupoContrato__c/GrupoContrato__c.object-meta.xml
<CustomObject>
    <description>Objeto responsável por armazenar os dados dos grupos de segurados do contrato</description>
    <label>Grupo do contrato</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grupos do contrato</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/GrupoContrato__c/fields/ContratanteContrato__c.field-meta.xml
<CustomField>
    <fullName>ContratanteContrato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contratante do contrato</label>
    <referenceTo>ContratanteContrato__c</referenceTo>
    <relationshipLabel>Grupos do contrato</relationshipLabel>
    <relationshipName>GruposContrato</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/SeguradoContrato__c/SeguradoContrato__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar os segurados do contrato</description>
    <label>Segurado do contrato</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Segurados do contrato</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/SeguradoContrato__c/fields/GrupoContrato__c.field-meta.xml
<CustomField>
    <fullName>GrupoContrato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Grupo do contrato</label>
    <referenceTo>GrupoContrato__c</referenceTo>
    <relationshipLabel>Segurados do contrato</relationshipLabel>
    <relationshipName>SeguradosContrato</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/classes/GarantiaSeguradoContratoTest.cls
@isTest
public class GarantiaSeguradoContratoTest {
	    
    @isTest
    public static void testeGarantiaSeguradoContratoPessoaFisica(){
        GarantiaSeguradoContrato__c vGSCTest = (GarantiaSeguradoContrato__c)new GarantiaSeguradoContratoFactory().createRecord();
        
        system.assert([SELECT Nomenclatura_Pesquisa_Garantia_Segurado__c 
                       FROM GarantiaSeguradoContrato__c 
                       WHERE Id = :vGSCTest.Id].Nomenclatura_Pesquisa_Garantia_Segurado__c != null);
    }

    @isTest
    public static void testeGarantiaSeguradoContratoPessoaJuridica(){

    	Account vAccPeJuri = (Account)new AccountFactory.PessoaJuridica().createRecord();
        GrupoContrato__c vGru = (GrupoContrato__c)new GrupoFactory().createRecord();
        
        SeguradoContrato__c vSegContratoTest1 = (SeguradoContrato__c)new SeguradoContratoFactory(vAccPeJuri, vGru).createRecord();

        Garantia__c vGarantia = (Garantia__c)new GarantiaFactory().createRecord();

        GarantiaSeguradoContrato__c vGSCTest1 = (GarantiaSeguradoContrato__c)new GarantiaSeguradoContratoFactory(vSegContratoTest1,vGarantia).createRecord();

        system.assert([SELECT Nomenclatura_Pesquisa_Garantia_Segurado__c 
                       FROM GarantiaSeguradoContrato__c 
                       WHERE Id = :vGSCTest1.Id].Nomenclatura_Pesquisa_Garantia_Segurado__c != null);
    }

    //PLV-5147 - FIX02 - INICIO
    @isTest
    public static void testeBuscaGarantiaSeguradoContrato(){

        ////Data Setup
        GarantiaSeguradoContrato__c vGSCTest = (GarantiaSeguradoContrato__c)new GarantiaSeguradoContratoFactory().createRecord();

        List<GarantiaSeguradoContrato__c> obj = [
            			SELECT id, SeguradoContrato__r.GrupoContrato__r.ContratanteContrato__r.Contrato__c
                       	FROM GarantiaSeguradoContrato__c WHERE Id = :vGSCTest.Id];
        Set<Id> ctrs = new Set<Id>{obj[0].SeguradoContrato__r.GrupoContrato__r.ContratanteContrato__r.Contrato__c};
        ////

        Test.startTest();
        List<GarantiaSeguradoContrato__c> lstRet = GarantiaSeguradoContratoDAO.getInstance().buscarGarantiaSeguradoContrado(ctrs);
		Test.stopTest();
        
        //Validação
        System.Assert(lstRet.size() > 0);
    }
    
    @isTest
    public static void testeBuscaGarantiaSeguradoContratoeEndosso(){

        //// Data Setup
        GarantiaSeguradoContrato__c vGSCTest = (GarantiaSeguradoContrato__c)new GarantiaSeguradoContratoFactory().createRecord();

        List<GarantiaSeguradoContrato__c> obj = [
            SELECT id, SeguradoContrato__r.GrupoContrato__r.ContratanteContrato__r.Contrato__c
               FROM GarantiaSeguradoContrato__c WHERE Id = :vGSCTest.Id];
        Contract ct = new Contract();
        ct.Id = obj[0].SeguradoContrato__r.GrupoContrato__r.ContratanteContrato__r.Contrato__c;
        ct.Name = ContratoFactory.EMPRESA + '-' + ContratoFactory.SUCURSAL + '-' + ContratoFactory.CODIGORAMO + '-' + ContratoFactory.NUMEROAPOLICE + '-0';
        update ct;
        ////
               
        Test.startTest();
        List<GarantiaSeguradoContrato__c> lstRet = GarantiaSeguradoContratoDAO.getInstance()
            .buscarGarantiaSeguradoContradoeEndosso(ContratoFactory.EMPRESA,
                                                   ContratoFactory.SUCURSAL,
                                                   ContratoFactory.CODIGORAMO,
                                                   ContratoFactory.NUMEROAPOLICE);
        Test.stopTest();
        
        //Validação
        System.Assert(lstRet.size() > 0);
        
        
    }
    //PLV-5147 - FIX02 - FIM
}