workspace-sf/force-app/main/default/objects/GrupoOrcamento__c/GrupoOrcamento__c.object-meta.xml
<CustomObject>
    <description>Objeto responsável por armazenar o cadastro dos grupos de segurados do orçamento</description>
    <label>Grupo do orçamento</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grupos do orçamento</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/SeguradoOrcamento__c/SeguradoOrcamento__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar os segurados do orçamento</description>
    <label>Segurado do orçamento</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Nome</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Segurados do orçamento</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/SeguradoOrcamento__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Segurados do orçamento</relationshipLabel>
    <relationshipName>SeguradosOrcamento</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/SeguradoOrcamento__c/fields/GrupoOrcamento__c.field-meta.xml
<CustomField>
    <fullName>GrupoOrcamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Grupo do orçamento</label>
    <referenceTo>GrupoOrcamento__c</referenceTo>
    <relationshipLabel>Segurados do orçamento</relationshipLabel>
    <relationshipName>SeguradosOrcamento</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/classes/seguradoOrcamentoFactory.cls
/**
 * @author AVX - Leonardo Camacho
 * @date 2019-02-27
 * @description: Segurado do Orçamento Factory Class
 * Criada para a história: PLV_2826 - Criar orçamento sem conta
 */

@isTest
public class seguradoOrcamentoFactory extends SObjectFactory{

	private static SeguradoOrcamento__c staticRecord;
    
    private static SeguradoOrcamento__c getRecordStatic(Account contaPessoal, GrupoOrcamento__c grupo){
        Date dataVigenciaInicial = Date.newInstance(2013, 03, 12);
        Date dataVigenciaFinal = Date.newInstance(2020, 03, 12);
        
		if(staticRecord == null){
			staticRecord = new SeguradoOrcamento__c(
                Conta__c = contaPessoal.Id,
                GrupoOrcamento__c = grupo.Id                
            );
		}
		return staticRecord;
	}
    
    public seguradoOrcamentoFactory() {

		this(
        	(Account) new AccountFactory.PessoaFisica().createRecord(),
            (GrupoOrcamento__c) new grupoOrcamentoFactory().createRecord()
        );
	}

	public seguradoOrcamentoFactory(Account contaPessoal, GrupoOrcamento__c grupo) {

		super(getRecordStatic(contaPessoal, grupo));
	}
}