workspace-sf/force-app/main/default/objects/GarantiaGrupoOrcamento__c/GarantiaGrupoOrcamento__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar as garantias do grupo do orçamento</description>
    <label>Garantia do grupo do orçamento</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Garantias do grupo do orçamento</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/RemuneracaoOrcamento__c/RemuneracaoOrcamento__c.object-meta.xml
<CustomObject>
    <description>Objeto de relacionamento entre a oportunidade e o tipo de remuneração.</description>
    <label>Remuneração do orçamento</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Remunerações do orçamento</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/RemuneracaoOrcamento__c/fields/TipoRemuneracao__c.field-meta.xml
<CustomField>
    <fullName>TipoRemuneracao__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tipo de remuneração</label>
    <referenceTo>TipoRemuneracao__c</referenceTo>
    <relationshipLabel>Remunerações do orçamento</relationshipLabel>
    <relationshipName>RemuneracoesOportunidade</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Roteamento__c/Roteamento__c.object-meta.xml
<CustomObject>
    <description>Objeto de relacionamento entre a oportunidade e os registros para roteamento.</description>
    <label>Roteamento</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Roteamentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/Roteamento__c/fields/Orcamento__c.field-meta.xml
<CustomField>
    <fullName>Orcamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Orçamento</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Roteamentos</relationshipLabel>
    <relationshipName>Roteamentos</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/TipoRemuneracao__c/TipoRemuneracao__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar o cadastro dos tipos de remuneração</description>
    <label>Tipo de remuneração</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tipos de remuneração</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/classes/OrcamentoTest.cls
/**
 * Testes Orçamento
 * @author Fernando Barcellos @ 19/04/2018
 *
 **/
@isTest
private class OrcamentoTest {
	@testSetup
	static void testSetup() {
		TestDataFactory.gerarDadosSetup();
		// PLV-2312-28 INICIO
		TestDataFactory.gerarOrcamento(false);
		// PLV-2312-28 FIM
	}

	@isTest
	static void testBurcarOportunidadePorRoteamentoId() {
		Roteamento__c roteamento = [SELECT Id, Orcamento__c FROM Roteamento__c LIMIT 1];
		Test.startTest();
		Opportunity orcamento = BackgroundConsoleController.burcarOportunidadePorRoteamentoId(roteamento.Id);
		Test.stopTest();
		System.assert(orcamento != null);
	}

	@isTest
	static void testarComponenteInfoComplementares() {
		// Busca o orcamento para o teste
		Opportunity orcamento = [SELECT Id FROM Opportunity];
		orcamento.Name = 'Novo Orcamento';

		// Trabalha uma garantia do Grupo do orcamento para atualizar
		List<SObject> listSObjects = new List<SObject>();
		List<GarantiaGrupoOrcamento__c> listGarantiaGrupoOrcamento = [SELECT Id,Capital__c FROM GarantiaGrupoOrcamento__c];
		GarantiaGrupoOrcamento__c garantiaGrupoOrcamento = (GarantiaGrupoOrcamento__c) listGarantiaGrupoOrcamento[0];
		garantiaGrupoOrcamento.Capital__c = 9876.98;
		listSObjects.addAll(listGarantiaGrupoOrcamento);

		Test.startTest();

		// roda o buscarGarantiasOrcamento
		String jsonString = ComplementoOrcamentoController.buscarGarantiasOrcamento(orcamento.Id);
		OrcamentoTO orcamentoTO = (OrcamentoTO) JSON.deserialize(jsonString, OrcamentoTO.class);

		// Roda o atualizarGarantiasDoGrupoDoOrcamento
		ComplementoOrcamentoController.atualizarGarantiasDoGrupoDoOrcamento(listSObjects, orcamento.Id);
		GarantiaGrupoOrcamento__c garantiaGrupoOrcamento2 = [SELECT Id, Capital__c FROM GarantiaGrupoOrcamento__c WHERE Id =: listGarantiaGrupoOrcamento[0].Id LIMIT 1];

		// Roda o atualizaOportunidade
		OpportunityBO.getInstance().atualizaOportunidade(orcamento);

		// Valida buscarGarantiasOrcamento
		System.assert(orcamentoTO.oferta.calculo.precificacao.coberturas.size() > 0);
		// Valida atualizarGarantiasDoGrupoDoOrcamento
		System.assert(garantiaGrupoOrcamento2.Capital__c == 9876.98);

		Opportunity orcamento2 = [SELECT Id, DataCalculo__c FROM Opportunity WHERE Id =: orcamento.Id];
		System.assert(orcamento2.DataCalculo__c == System.today());
		// Valida atualizaOportunidade
		Opportunity orcamentoAtualizado = [SELECT Id,Name FROM Opportunity];
		System.assert(orcamentoAtualizado.Name == 'Novo Orcamento');

		Test.stopTest();
	}

	@isTest
	static void testValidarCalcularOrcamentoSemRemuneracaoOrcamentoObrigatoria() {
		Opportunity orcamento = [SELECT Id,Produto__c,(SELECT Id FROM RemuneracoesOrcamento__r) FROM Opportunity LIMIT 1];
		String mensagemEsperada = 'Remuneração obrigatória não informada no orçamento!';

		List<RemuneracaoOrcamento__c> listRemuneracaoOrcamento = orcamento.RemuneracoesOrcamento__r;
		delete listRemuneracaoOrcamento;

		TipoRemuneracao__c tipoRemuneracao = [SELECT Id FROM TipoRemuneracao__c WHERE Name ='COMISSÃO' LIMIT 1];
		RemuneracaoOrcamento__c remuneracaoOrcamento  = TestDataFactory.gerarRemuneracaoOrcamento(orcamento,tipoRemuneracao);

		Test.startTest();
		String msgRetorno = ComplementoOrcamentoController.validarCalcularOrcamento(orcamento.Id);
		Test.stopTest();

		// Valida se nao retornou mensagem de erro
		System.assertEquals(mensagemEsperada,msgRetorno);
	}

	@isTest
	static void testAtualizarOportunidade() {
		Opportunity orcamento = [SELECT Id, Name FROM Opportunity LIMIT 1];
		orcamento.Name = 'Novo nome';
		Test.startTest();
		BackgroundConsoleController.atualizarOportunidade(orcamento);
		Test.stopTest();
		Opportunity orcamentoAtualizado = [SELECT Id, Name FROM Opportunity LIMIT 1];
		System.assert(orcamentoAtualizado.Name == 'Novo nome');
	}
}