workspace-sf/force-app/main/default/objects/PagamentoGarantia__c/PagamentoGarantia__c.object-meta.xml
<CustomObject>
    <description>Registrar os pagamentos das garantias dentro da frente de Sinistro Vida.
Objeto Detalhe de Caso</description>
    <label>Garantia do Sinistro</label>
    <nameField>
        <label>Nome da Garantia do Sinistro</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Garantias do Sinistro</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/PagamentoGarantia__c/fields/Caso__c.field-meta.xml
<CustomField>
    <fullName>Caso__c</fullName>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>Pagamentos_de_garantia</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/classes/GarantiaSinistroDAO.cls
//PLV-5316 INÍCIO
public without sharing class GarantiaSinistroDAO {

	private static final GarantiaSinistroDAO instance = new GarantiaSinistroDAO();

	public static GarantiaSinistroDAO getInstance() {
		return instance;
	}

    public Id caseId {get;set;}

    public class GarantiaDAO { public Id caseId { get; set; } }
    
    public List<PagamentoGarantia__c> getGarantiaSinistro(){ 
        return [SELECT Id, Name, Caso__c FROM PagamentoGarantia__c WHERE Caso__c =: caseId];
    }
}
//PLV-5316 FIM