workspace-sf/force-app/main/default/objects/BeneficiarioSeguradoProposta__c/BeneficiarioSeguradoProposta__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar os beneficiários da proposta</description>
    <label>Beneficiário do segurado da proposta</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Beneficiários dos segurados da proposta</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/BeneficiarioSeguradoProposta__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Beneficiários dos segurados da proposta</relationshipLabel>
    <relationshipName>BeneficSeguradosProposta</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/BeneficiarioSeguradoProposta__c/fields/CpfCnpj__c.field-meta.xml
<CustomField>
    <fullName>CpfCnpj__c</fullName>
    <label>CPF / CNPJ</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/BeneficiarioSeguradoProposta__c/fields/GrauParentesco__c.field-meta.xml
<CustomField>
    <fullName>GrauParentesco__c</fullName>
    <label>Grau de parentesco</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>GrauParentesco</valueSetName>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/BeneficiarioSeguradoProposta__c/fields/Participacao__c.field-meta.xml
<CustomField>
    <fullName>Participacao__c</fullName>
    <label>Participação</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

workspace-sf/force-app/main/default/objects/BeneficiarioSeguradoProposta__c/fields/Pep__c.field-meta.xml
<CustomField>
    <fullName>Pep__c</fullName>
    <label>PEP?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sim</fullName>
            </value>
            <value>
                <fullName>RelacionamentoProximo</fullName>
                <label>Relacionamento próximo</label>
            </value>
            <value>
                <fullName>Nao</fullName>
                <label>Não</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/BeneficiarioSeguradoProposta__c/fields/SeguradoProposta__c.field-meta.xml
<CustomField>
    <fullName>SeguradoProposta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Segurado da proposta</label>
    <referenceTo>SeguradoProposta__c</referenceTo>
    <relationshipLabel>Beneficiários dos segurados da proposta</relationshipLabel>
    <relationshipName>BeneficiariosSeguradosProposta</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/BeneficiarioSeguradoProposta__c/fields/TipoBeneficiario__c.field-meta.xml
<CustomField>
    <fullName>TipoBeneficiario__c</fullName>
    <label>Tipo de beneficiário</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nome do beneficiário</fullName>
            </value>
            <value>
                <fullName>Herdeiros legais, conforme artigo 792 do código civil.</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/CanalDistribuicao__c/CanalDistribuicao__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar o cadastro dos canais de distribuição</description>
    <label>Canal de distribuição</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Canais de distribuição</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/CanalDistribuicao__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Em criação</fullName>
                <default>true</default>
                <label>Em criação</label>
            </value>
            <value>
                <fullName>Em aprovação</fullName>
            </value>
            <value>
                <fullName>Em revisão</fullName>
            </value>
            <value>
                <fullName>Em ativação</fullName>
            </value>
            <value>
                <fullName>Ativo</fullName>
            </value>
            <value>
                <fullName>Inativo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/ContadorCodigo__c/ContadorCodigo__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Contador Código</label>
</CustomObject>

workspace-sf/force-app/main/default/objects/ContratanteProposta__c/ContratanteProposta__c.object-meta.xml
<CustomObject>
    <description>Objeto responsável por armazenar o cadastro dos contratantes da proposta</description>
    <label>Contratante da proposta</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contratantes da proposta</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/ContratanteProposta__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contratantes da proposta</relationshipLabel>
    <relationshipName>ContratantesProposta</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/ContratanteProposta__c/fields/Proposta__c.field-meta.xml
<CustomField>
    <fullName>Proposta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proposta</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Contratantes da proposta</relationshipLabel>
    <relationshipName>ContratantesProposta</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/DadosCorretor__c/DadosCorretor__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar dados dos corretores.</description>
    <label>Dados do corretor</label>
    <nameField>
        <label>Código do corretor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dados dos corretores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/DadosCorretor__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Principal</fullName>
            </value>
            <value>
                <fullName>Produção</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/GrupoProposta__c/GrupoProposta__c.object-meta.xml
<CustomObject>
    <description>Objeto responsável por armazenar o cadastro dos grupos de segurados da proposta</description>
    <label>Grupo da proposta</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grupos da proposta</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/GrupoProposta__c/fields/ContratanteProposta__c.field-meta.xml
<CustomField>
    <fullName>ContratanteProposta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contratante da proposta</label>
    <referenceTo>ContratanteProposta__c</referenceTo>
    <relationshipLabel>Grupos da proposta</relationshipLabel>
    <relationshipName>GruposProposta</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Modalidade__c/Modalidade__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar as modalidades</description>
    <label>Modalidade</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Modalidades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/Modalidade__c/fields/Empresa__c.field-meta.xml
<CustomField>
    <fullName>Empresa__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empresa</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Modalidades</relationshipLabel>
    <relationshipName>Modalidades</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Modalidade__c/fields/RamoSeguro__c.field-meta.xml
<CustomField>
    <fullName>RamoSeguro__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ramo de seguro</label>
    <referenceTo>RamoSeguro__c</referenceTo>
    <relationshipLabel>Modalidades</relationshipLabel>
    <relationshipName>Modalidades</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Pep__c/Pep__c.object-meta.xml
<CustomObject>
    <label>Pep</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Peps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/Pep__c/fields/BeneficiarioSeguradoProposta__c.field-meta.xml
<CustomField>
    <fullName>BeneficiarioSeguradoProposta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Beneficiário do segurado da proposta</label>
    <referenceTo>BeneficiarioSeguradoProposta__c</referenceTo>
    <relationshipLabel>Peps</relationshipLabel>
    <relationshipName>Peps</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/RamoSeguro__c/RamoSeguro__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar o cadastro dos ramos de seguro</description>
    <label>Ramo de seguro</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ramos de seguro</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/RamoSeguro__c/fields/Empresa__c.field-meta.xml
<CustomField>
    <fullName>Empresa__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empresa</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>RamosSeguro</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/RamoSeguro__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ativo</fullName>
            </value>
            <value>
                <fullName>Inativo</fullName>
            </value>
            <value>
                <fullName>Em análise</fullName>
                <default>true</default>
                <label>Em análise</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/SeguradoProposta__c/SeguradoProposta__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar os segurados da proposta</description>
    <label>Segurado da proposta</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Segurados da proposta</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/SeguradoProposta__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Segurados da proposta</relationshipLabel>
    <relationshipName>SeguradosProposta</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/SeguradoProposta__c/fields/GrauParentesco__c.field-meta.xml
<CustomField>
    <fullName>GrauParentesco__c</fullName>
    <label>Grau de Parentesco</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>COMPANHEIRO</fullName>
            </value>
            <value>
                <fullName>CÔNJUGE</fullName>
            </value>
            <value>
                <fullName>ENTEADO</fullName>
            </value>
            <value>
                <fullName>FILHO</fullName>
            </value>
            <value>
                <fullName>PAIMAE</fullName>
                <label>PAI MAE</label>
            </value>
            <value>
                <fullName>OUTROS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/SeguradoProposta__c/fields/GrupoProposta__c.field-meta.xml
<CustomField>
    <fullName>GrupoProposta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Grupo da proposta</label>
    <referenceTo>GrupoProposta__c</referenceTo>
    <relationshipLabel>Segurados da proposta</relationshipLabel>
    <relationshipName>SeguradosProposta</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/SeguradoProposta__c/fields/VigenciaFinal__c.field-meta.xml
<CustomField>
    <fullName>VigenciaFinal__c</fullName>
    <label>Vigência final</label>
    <type>Date</type>
</CustomField>

workspace-sf/force-app/main/default/classes/GerarEndossoViagemMsgPageControllerTest.cls
/********************************************************************************************************************
* Gerar Endosso Viagem Mensagem Controler Test
* @author Squad_Globant
* @date 29/06/2021
* Classe criada por conta da história PLV-5063
*********************************************************************************************************************/
@IsTest
public class GerarEndossoViagemMsgPageControllerTest {
   
    @IsTest
    public static void GerarEndossoViagemMsgPageControllerTest(){
        
        Account conta = new Account(
			RecordTypeId = RecordTypeBO.buscarTipoRegistro('Account', 'PessoaFisica').Id,
			LastName = 'Teste',
			Nacionalidade__c = 'Brasileira',
			CPF__c = '00478394659',
			Rg__c = '232323231',
			DataExpedicao__c = Date.today(),
			OrgaoExpedidor__c = '123132',
			PersonBirthDate = (Date.today()-7300),
			EstadoCivil__c = 'Solteiro (a)'
		);
		insert conta;

		Opportunity oportunidade = new Opportunity(
			Name = 'Teste Contrato',
			StageName = 'Em criação',
			RecordTypeId = RecordTypeBO.buscarTipoRegistro('Opportunity', 'VidaIndividual').Id,
			AccountId = conta.Id,
			CloseDate = Date.today()
		);
		insert oportunidade;

		//TKCL-246 FIX05 INICIO
        ContadorCodigo__c contadorTecnico = (ContadorCodigo__c) new ContadorCodigoFactory.ProdutoTecnico().createRecord();
        ContadorCodigo__c contadorComercial = (ContadorCodigo__c) new ContadorCodigoFactory.ProdutoComercial().createRecord();

        RamoSeguro__c ramoSeguro = (RamoSeguro__c) new RamoSeguroFactory(conta).createRecord();
        DadosCorretor__c dadosCorretor = (DadosCorretor__c) new DadosCorretorFactory(conta).createRecord();
        CanalDistribuicao__c canalDistribuicao = (CanalDistribuicao__c) new CanalDistribuicaoFactory().createRecord(); 

        Modalidade__c modalidade = (Modalidade__c) new ModalidadeFactory(ramoSeguro).createRecord();
        
        Product2 produtoTecnico = (Product2) new ProdutoFactory.ProdutoTecnico().createRecord();
        produtoTecnico.Status__c = 'Em ativação';
        produtoTecnico.NumeroSusep__c = '123';
        produtoTecnico.VersaoRenovacao__c = 'Versão atual';
        update produtoTecnico;
        produtoTecnico.Status__c = 'Ativo';
        produtoTecnico.ProductCode = '49';
        produtoTecnico.Segmento__c = 'Individual';
        update produtoTecnico;
        Product2 produtoComercial = (Product2) new ProdutoFactory.ProdutoComercial(produtoTecnico).createRecord();
        produtoComercial.Status__c = 'Ativo';
        produtoComercial.ProductCode = 'APTLMKT';
        produtoComercial.Segmento__c = 'Individual';
        produtoComercial.CodigoPrecificaProduto__c = 'APTLMKT';
        update produtoComercial;
        //TKCL-246 FIX05 FIM

		Quote proposta = new Quote(
			Name= 'Teste Contrato',
			OpportunityId=oportunidade.Id,
			DataProtocolo__c = Date.today(),
			DataCalculo__c =  Date.today(),
			Empresa__c = conta.Id,
			ExpirationDate = Date.today(),
			Produto__c = produtoComercial.id //TKCL-246 FIX05 INICIO/FIM
		);
		insert proposta;

		ContratanteProposta__c segurado = new ContratanteProposta__c(
			conta__c = conta.Id,
			Proposta__c = proposta.Id,
			Tipo__c = 'Principal'
		);
		insert segurado;

		GrupoProposta__c grupo = new GrupoProposta__c(
			Name = 'Teste',
			QuantidadeVidas__c = 1,
			ContratanteProposta__c = segurado.Id
		);
		insert grupo;

		SeguradoProposta__c vida = new SeguradoProposta__c(
			Conta__c = conta.Id,
			GrupoProposta__c = grupo.Id
		);
		insert vida;

		// PLV-5098 FIX01 INICIO
		/*BeneficiarioSeguradoProposta__c beneficiario = new BeneficiarioSeguradoProposta__c(
			SeguradoProposta__c = vida.Id,
			CpfCnpj__c = '00478394659',
			Nome__c = 'Teste Contrato',
			TipoBeneficiario__c = 'Nome do beneficiário',
			GrauParentesco__c = 'Pai',
			Participacao__c = 100,
			Pep__c = 'Não'
		);
		insert beneficiario;

		BeneficiarioSeguradoProposta__c beneficiario2 = new BeneficiarioSeguradoProposta__c(
			SeguradoProposta__c = vida.Id,
			CpfCnpj__c = '99235310075',
			Nome__c = 'Teste Contrato',
			TipoBeneficiario__c = 'Nome do beneficiário',
			GrauParentesco__c = 'Pai',
			Participacao__c = 100,
			Pep__c = 'Não'
		);
        insert beneficiario2;*/
		// PLV-5098 FIX01 FIM
        
        Quote proposta1 = [SELECT Id FROM Quote WHERE Name = 'Teste Contrato'];
		Opportunity oportunidade1 = [SELECT Id FROM Opportunity WHERE Name = 'Teste Contrato'];
		List<Account> conta1 = [SELECT id FROM Account WHERE LastName = 'Teste'];
		
		Contract contrato = new Contract(
			Name = '111',
			Oportunidade__c = oportunidade1.Id,
			Proposta__c = proposta1.Id,
            Tipo__c = 'Novo',
            Status = 'Emitido',
			AccountId = conta1[0].Id,
            VigenciaFinal__c=System.today().addDays(360)              
		);        
        insert contrato;
        
        ApexPages.StandardController sc = new ApexPages.StandardController(contrato);
        GerarEndossoViagemMsgPageController gera = new GerarEndossoViagemMsgPageController(sc);        
        PageReference pageRef = Page.GerarEndossoViagemMensagem;
        String mensagem = 'A quantidade de dias do endosso de extensão de viagem é superior à permitida pelo produto contratado.';         
        pageRef.getParameters().put('idContrato',contrato.Id);
        pageRef.getParameters().put('mensagem',mensagem);  
        
        Test.setCurrentPage(pageRef); 
        Test.startTest();        
        gera.redirectEndossoViagem(); 
        Test.stopTest();
        contrato = [SELECT Id, Name, Status FROM Contract WHERE Id =: contrato.Id];        
        System.assert(contract.Status != null);
    }
}