workspace-sf/force-app/main/default/objects/BeneficiarioSeguradoProposta__c/BeneficiarioSeguradoProposta__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar os beneficiários da proposta</description>
    <label>Beneficiário do segurado da proposta</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Beneficiários dos segurados da proposta</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/BeneficiarioSeguradoProposta__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Beneficiários dos segurados da proposta</relationshipLabel>
    <relationshipName>BeneficSeguradosProposta</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/BeneficiarioSeguradoProposta__c/fields/CpfCnpj__c.field-meta.xml
<CustomField>
    <fullName>CpfCnpj__c</fullName>
    <label>CPF / CNPJ</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/BeneficiarioSeguradoProposta__c/fields/CpfPep__c.field-meta.xml
<CustomField>
    <fullName>CpfPep__c</fullName>
    <label>CPF da PEP</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/BeneficiarioSeguradoProposta__c/fields/GrauParentesco__c.field-meta.xml
<CustomField>
    <fullName>GrauParentesco__c</fullName>
    <label>Grau de parentesco</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>GrauParentesco</valueSetName>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/BeneficiarioSeguradoProposta__c/fields/GrauParentescoPep__c.field-meta.xml
<CustomField>
    <fullName>GrauParentescoPep__c</fullName>
    <label>Grau de parentesco da PEP</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>GrauParentesco</valueSetName>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/BeneficiarioSeguradoProposta__c/fields/ImprimirCertificadoSeguro__c.field-meta.xml
<CustomField>
    <fullName>ImprimirCertificadoSeguro__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Imprimir no certificado de seguro?</label>
    <type>Checkbox</type>
</CustomField>

workspace-sf/force-app/main/default/objects/BeneficiarioSeguradoProposta__c/fields/MotivoSemCpfCnpj__c.field-meta.xml
<CustomField>
    <fullName>MotivoSemCpfCnpj__c</fullName>
    <label>Motivo sem CPF / CNPJ</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Estrangeiro com visto temporário</fullName>
            </value>
            <value>
                <fullName>Não desejo informar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/BeneficiarioSeguradoProposta__c/fields/NomePessoaPep__c.field-meta.xml
<CustomField>
    <fullName>NomePessoaPep__c</fullName>
    <label>Nome da pessoa PEP</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/BeneficiarioSeguradoProposta__c/fields/Participacao__c.field-meta.xml
<CustomField>
    <fullName>Participacao__c</fullName>
    <label>Participação</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

workspace-sf/force-app/main/default/objects/BeneficiarioSeguradoProposta__c/fields/Pep__c.field-meta.xml
<CustomField>
    <fullName>Pep__c</fullName>
    <label>PEP?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sim</fullName>
            </value>
            <value>
                <fullName>RelacionamentoProximo</fullName>
                <label>Relacionamento próximo</label>
            </value>
            <value>
                <fullName>Nao</fullName>
                <label>Não</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/BeneficiarioSeguradoProposta__c/fields/SeguradoProposta__c.field-meta.xml
<CustomField>
    <fullName>SeguradoProposta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Segurado da proposta</label>
    <referenceTo>SeguradoProposta__c</referenceTo>
    <relationshipLabel>Beneficiários dos segurados da proposta</relationshipLabel>
    <relationshipName>BeneficiariosSeguradosProposta</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/BeneficiarioSeguradoProposta__c/fields/TipoBeneficiario__c.field-meta.xml
<CustomField>
    <fullName>TipoBeneficiario__c</fullName>
    <label>Tipo de beneficiário</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nome do beneficiário</fullName>
            </value>
            <value>
                <fullName>Herdeiros legais, conforme artigo 792 do código civil.</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/Pep__c/Pep__c.object-meta.xml
<CustomObject>
    <label>Pep</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Peps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/Pep__c/fields/BeneficiarioSeguradoProposta__c.field-meta.xml
<CustomField>
    <fullName>BeneficiarioSeguradoProposta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Beneficiário do segurado da proposta</label>
    <referenceTo>BeneficiarioSeguradoProposta__c</referenceTo>
    <relationshipLabel>Peps</relationshipLabel>
    <relationshipName>Peps</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Pep__c/recordTypes/seguradoProposta.recordType-meta.xml
<RecordType>
    <fullName>seguradoProposta</fullName>
    <active>true</active>
    <label>seguradoProposta</label>
</RecordType>

workspace-sf/force-app/main/default/objects/SeguradoProposta__c/SeguradoProposta__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar os segurados da proposta</description>
    <label>Segurado da proposta</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Segurados da proposta</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/SeguradoProposta__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Segurados da proposta</relationshipLabel>
    <relationshipName>SeguradosProposta</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/SeguradoProposta__c/fields/GrauParentesco__c.field-meta.xml
<CustomField>
    <fullName>GrauParentesco__c</fullName>
    <label>Grau de Parentesco</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>COMPANHEIRO</fullName>
            </value>
            <value>
                <fullName>CÔNJUGE</fullName>
            </value>
            <value>
                <fullName>ENTEADO</fullName>
            </value>
            <value>
                <fullName>FILHO</fullName>
            </value>
            <value>
                <fullName>PAIMAE</fullName>
                <label>PAI MAE</label>
            </value>
            <value>
                <fullName>OUTROS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/classes/BeneficiarioSeguradoPropostaBO.cls
/**
 * BeneficiarioSeguradoPropostaBO
 * @author Eric Tunú @ 21/06/2018
 *
 **/
public with sharing class BeneficiarioSeguradoPropostaBO 
{
	public static final String mensagemErro = 'Soma dos percentuais dos beneficiários deve ser igual a 100%';
	public static final String mensagemValidacao = 'Percentual de participação não informado, igual ou menor que zero.';

	private static final BeneficiarioSeguradoPropostaBO instance = new BeneficiarioSeguradoPropostaBO();
	public static BeneficiarioSeguradoPropostaBO getInstance() { return instance; }
	private BeneficiarioSeguradoPropostaBO() { }

/*---- LOSADA: rotina descontinuada
	public void validaPercentalParticipacao(List<BeneficiarioSeguradoProposta__c> lstNew)
	{
		System.debug('BeneficiarioSeguradoPropostaBO >> validaPercentalParticipacao >> Lista de beneficiarios:  '  + lstNew);
		Set<String> 						 setIdsSegurado		= new Set<String>();
		Map<String, BeneficiarioSeguradoProposta__c> mapBeneficiarios	= new Map<String, BeneficiarioSeguradoProposta__c>();
		List<BeneficiarioSeguradoProposta__c> 		 lstOld	 			= new List<BeneficiarioSeguradoProposta__c>();
		
		Map<String, List<BeneficiarioSeguradoProposta__c>> mapBeneficiariosAgrupados = new Map<String, List<BeneficiarioSeguradoProposta__c>>();

		for(BeneficiarioSeguradoProposta__c beneficiario : lstNew)
		{
			if(beneficiario.TipoBeneficiario__c == 'Nome do beneficiário')
			{
				if(beneficiario.Participacao__c == null)
					beneficiario.addError(mensagemValidacao);
					
				if(beneficiario.Participacao__c <= 0)
					beneficiario.addError(mensagemValidacao);

				if(!setIdsSegurado.contains(beneficiario.SeguradoProposta__c))
					setIdsSegurado.add(beneficiario.SeguradoProposta__c);
			}
		}

		lstOld = BeneficiarioSeguradoPropostaDAO.getInstance().buscarBeneficiariosSeguradoProposta(setIdsSegurado);
		//tratas os registros em caso de update
		if(!lstOld.isEmpty())
		{
			system.debug('old:  ' + lstOld);
			for(BeneficiarioSeguradoProposta__c beneficiario : lstOld)
			{
				// if(!String.isBlank(beneficiario.Id))
				// {
					if(beneficiario.TipoBeneficiario__c == 'Nome do beneficiário')
						mapBeneficiarios.put(beneficiario.Id, beneficiario);
				//}
			}

			system.debug('new:  ' + lstNew);
			for(BeneficiarioSeguradoProposta__c beneficiario : lstNew)
			{
				BeneficiarioSeguradoProposta__c itemDuplicado = mapBeneficiarios.get(beneficiario.Id);
				if(itemDuplicado != null)
				{
					if(beneficiario.TipoBeneficiario__c == 'Nome do beneficiário')
						mapBeneficiarios.remove(beneficiario.Id);
				}
			}
		}

		system.debug('map:  ' + mapBeneficiarios.values());

		//agrupa beneficiarios por Seguradoproposta
		for(String SeguradopropsotaId : setIdsSegurado)
		{
			//valida se os beneficiarios de cada Segurado proposta ultrapassaram os 100 % de 
			Decimal limite = 100;
			List<BeneficiarioSeguradoProposta__c> lstTemp = new List<BeneficiarioSeguradoProposta__c>();
			for(BeneficiarioSeguradoProposta__c beneficiario : mapBeneficiarios.values())
			{
				if(beneficiario.SeguradoProposta__c == SeguradopropsotaId)
					lstTemp.add(beneficiario);
			}

			for(BeneficiarioSeguradoProposta__c beneficiario : lstTemp)
				limite = limite - beneficiario.Participacao__c;
				
			if(limite > 0)
			{
				lstTemp = new List<BeneficiarioSeguradoProposta__c>();
				for(BeneficiarioSeguradoProposta__c beneficiario : lstNew)
				{
					if(beneficiario.SeguradoProposta__c == SeguradopropsotaId)
						lstTemp.add(beneficiario);
				}

				boolean ultrapassouLimite = false;
				system.debug('lstTemp ' + lstTemp);
				for(BeneficiarioSeguradoProposta__c beneficiario : lstTemp)
				{
					if(beneficiario.Participacao__c == null)
						beneficiario.addError(mensagemValidacao);
					else
					{
						system.debug('limite ' + limite);
						system.debug('participação beneficiario; ' + beneficiario.Participacao__c);
						limite = limite - beneficiario.Participacao__c;
						if(limite < 0)
							ultrapassouLimite = true;
					}
				}

				if(ultrapassouLimite)
				{
					system.debug('ultrapassouLimite' + limite);
					for(BeneficiarioSeguradoProposta__c beneficiario : lstTemp)
						beneficiario.addError(mensagemErro);
				}				
			}
			else
			{
				system.debug('Limite '  + limite);
				lstTemp = new List<BeneficiarioSeguradoProposta__c>();
				for(BeneficiarioSeguradoProposta__c beneficiario : lstNew)
				{
					if(beneficiario.SeguradoProposta__c == SeguradopropsotaId)
						lstTemp.add(beneficiario);
				}

				for(BeneficiarioSeguradoProposta__c beneficiario : lstTemp)
					beneficiario.addError(mensagemErro);
			}
		}
	}
*/
	public BeneficiarioSeguradoProposta__c incluirBeneficiariosSeguradoProposta(Account Conta, Id SeguradoGrupo, String tipoBeneficiario, boolean imprimirCertificadoSeguro, Decimal participacao )
	{
		BeneficiarioSeguradoProposta__c beneficiario = new BeneficiarioSeguradoProposta__c();

		beneficiario.Conta__c 						= Conta.Id;
		beneficiario.SeguradoProposta__c 			= SeguradoGrupo;
		beneficiario.Pep__c 						= 'Nao';//Conta.Pep__c == 'null' ? 'Nao' : Conta.Pep__c;
		beneficiario.CpfCnpj__c 					= Conta.CPF__C == null ? Conta.CNPJ__c.replace('.','').replace('-','').replace('/','') : Conta.CPF__C.replace('.','').replace('-','').replace('/','');
		beneficiario.Nome__c 						= Conta.Name;
		beneficiario.CurrencyIsoCode 				= Conta.CurrencyIsoCode;
		beneficiario.TipoBeneficiario__c 			= tipoBeneficiario;
		beneficiario.ImprimirCertificadoSeguro__c 	= imprimirCertificadoSeguro;
		beneficiario.Participacao__c 				= participacao;
		beneficiario.GrauParentesco__c 				= 'Prestamista';
		// beneficiario.NomePessoaPep__c 				= Conta.NomePessoaPep__c;
		// beneficiario.CpfPep__c 						= Conta.CpfPep__c;
		// beneficiario.GrauParentescoPep__c 			= Conta.GrauParentescoPep__c;
		// beneficiario.MotivoSemCpfCnpj__c 			= Conta.MotivoSemCpfCnpj__c;

		return beneficiario;
	}
	

	public class BeneficiarioSeguradoPropostaException extends Exception {	}
}