workspace-sf/force-app/main/default/objects/ContadorCodigo__c/ContadorCodigo__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Contador Código</label>
</CustomObject>

workspace-sf/force-app/main/default/objects/ContadorCodigo__c/fields/Numero__c.field-meta.xml
<CustomField>
    <fullName>Numero__c</fullName>
    <label>Número</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Garantia__c/Garantia__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar o cadastro das garantias</description>
    <label>Garantia</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Garantias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/Garantia__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Em análise</fullName>
            </value>
            <value>
                <fullName>Ativo</fullName>
            </value>
            <value>
                <fullName>Inativo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/Garantia__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TipoGarantia</valueSetName>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/Garantia__c/fields/VigenciaInicial__c.field-meta.xml
<CustomField>
    <fullName>VigenciaInicial__c</fullName>
    <label>Vigência inicial</label>
    <type>Date</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaProduto__c/GarantiaProduto__c.object-meta.xml
<CustomObject>
    <description>Objeto de relacionamento entre os produtos e as garantias</description>
    <label>Garantia do produto</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Garantias do produto</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/GarantiaProduto__c/fields/CapitalRiscos__c.field-meta.xml
<CustomField>
    <fullName>CapitalRiscos__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Capital por riscos?</label>
    <type>Checkbox</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaProduto__c/fields/Garantia__c.field-meta.xml
<CustomField>
    <fullName>Garantia__c</fullName>
    <label>Garantia</label>
    <referenceTo>Garantia__c</referenceTo>
    <relationshipLabel>Garantias do produto</relationshipLabel>
    <relationshipName>GarantiasProduto</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaProduto__c/fields/GarantiaProduto__c.field-meta.xml
<CustomField>
    <fullName>GarantiaProduto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Garantia do produto</label>
    <referenceTo>GarantiaProduto__c</referenceTo>
    <relationshipLabel>Garantias do produto (Garantia do produto)</relationshipLabel>
    <relationshipName>GarantiasProdutoTecnico</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaProduto__c/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Garantias do produto</relationshipLabel>
    <relationshipName>GarantiasProduto</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaProduto__c/fields/TipoCapital__c.field-meta.xml
<CustomField>
    <fullName>TipoCapital__c</fullName>
    <label>Tipo de capital</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Capital global</fullName>
            </value>
            <value>
                <fullName>Capital uniforme</fullName>
            </value>
            <value>
                <fullName>Escalonado por cargo</fullName>
            </value>
            <value>
                <fullName>Escalonado por faixa salarial</fullName>
            </value>
            <value>
                <fullName>Livre escolha de capital</fullName>
            </value>
            <value>
                <fullName>Múltiplo por prêmio pago</fullName>
            </value>
            <value>
                <fullName>Múltiplo salarial</fullName>
            </value>
            <value>
                <fullName>Sem Capital</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaProduto__c/fields/TipoGarantia__c.field-meta.xml
<CustomField>
    <fullName>TipoGarantia__c</fullName>
    <label>Tipo de garantia</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TipoGarantia</valueSetName>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaProduto__c/recordTypes/ProdutoComercial.recordType-meta.xml
<RecordType>
    <fullName>ProdutoComercial</fullName>
    <active>true</active>
    <label>Produto comercial</label>
</RecordType>

workspace-sf/force-app/main/default/objects/GarantiaProduto__c/recordTypes/ProdutoTecnico.recordType-meta.xml
<RecordType>
    <fullName>ProdutoTecnico</fullName>
    <active>true</active>
    <label>Produto técnico</label>
</RecordType>

workspace-sf/force-app/main/default/objects/Risco__c/Risco__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar o cadastro dos riscos</description>
    <label>Risco</label>
    <nameField>
        <label>Risco</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Riscos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/Risco__c/fields/Tabela__c.field-meta.xml
<CustomField>
    <fullName>Tabela__c</fullName>
    <label>Tabela</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Adicional de parto para garantia DIT</fullName>
            </value>
            <value>
                <fullName>Danos Corporais (Parciais) - Órgãos e Estruturas Corporais</fullName>
            </value>
            <value>
                <fullName>Diárias por Incapacidade Temporária</fullName>
            </value>
            <value>
                <fullName>Invalidez Permanente - Diversos</fullName>
            </value>
            <value>
                <fullName>Invalidez Permanente - Invalidez Permanente</fullName>
            </value>
            <value>
                <fullName>Invalidez Permanente - Membros Inferiores</fullName>
            </value>
            <value>
                <fullName>Invalidez Permanente - Membros Superiores</fullName>
            </value>
            <value>
                <fullName>Invalidez Permanente Total - Invalidez Total Permanente</fullName>
            </value>
            <value>
                <fullName>Majoração - Vida Individual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/RiscoGarantia__c/RiscoGarantia__c.object-meta.xml
<CustomObject>
    <description>Objeto de relacionamento entre as garantias e os riscos</description>
    <label>Risco da garantia</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Riscos da garantia</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/RiscoGarantia__c/fields/GarantiaProduto__c.field-meta.xml
<CustomField>
    <fullName>GarantiaProduto__c</fullName>
    <label>Garantia do produto</label>
    <referenceTo>GarantiaProduto__c</referenceTo>
    <relationshipLabel>Riscos da garantia</relationshipLabel>
    <relationshipName>RiscosGarantia</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/RiscoGarantia__c/fields/Risco__c.field-meta.xml
<CustomField>
    <fullName>Risco__c</fullName>
    <label>Risco</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.TabelaRisco__c</field>
            <operation>equals</operation>
            <valueField>Risco__c.Tabela__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Risco__c</referenceTo>
    <relationshipLabel>Riscos da garantia</relationshipLabel>
    <relationshipName>RiscosGarantia</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/RiscoGarantia__c/fields/RiscoGarantia__c.field-meta.xml
<CustomField>
    <fullName>RiscoGarantia__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Risco da garantia</label>
    <referenceTo>RiscoGarantia__c</referenceTo>
    <relationshipLabel>Riscos da garantia</relationshipLabel>
    <relationshipName>RiscosGarantia</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/RiscoGarantia__c/fields/TabelaRisco__c.field-meta.xml
<CustomField>
    <fullName>TabelaRisco__c</fullName>
    <label>Tabela de risco</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Adicional de parto para garantia DIT</fullName>
            </value>
            <value>
                <fullName>Danos Corporais (Parciais) - Órgãos e Estruturas Corporais</fullName>
            </value>
            <value>
                <fullName>Diárias por Incapacidade Temporária</fullName>
            </value>
            <value>
                <fullName>Invalidez Permanente - Diversos</fullName>
            </value>
            <value>
                <fullName>Invalidez Permanente - Invalidez Permanente</fullName>
            </value>
            <value>
                <fullName>Invalidez Permanente - Membros Inferiores</fullName>
            </value>
            <value>
                <fullName>Invalidez Permanente - Membros Superiores</fullName>
            </value>
            <value>
                <fullName>Invalidez Permanente Total - Invalidez Permanente Total</fullName>
            </value>
            <value>
                <fullName>Majoração - Vida Individual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/RiscoGarantia__c/recordTypes/ProdutoComercial.recordType-meta.xml
<RecordType>
    <fullName>ProdutoComercial</fullName>
    <active>true</active>
    <label>Produto comercial</label>
</RecordType>

workspace-sf/force-app/main/default/objects/RiscoGarantia__c/recordTypes/ProdutoTecnico.recordType-meta.xml
<RecordType>
    <fullName>ProdutoTecnico</fullName>
    <active>true</active>
    <label>Produto técnico</label>
</RecordType>

workspace-sf/force-app/main/default/classes/RiscoTest.cls
@isTest
private class RiscoTest {
	
	@testSetup
	private static void setup() {
		List<ContadorCodigo__c> contadoresProduto = new List<ContadorCodigo__c>{
			new ContadorCodigo__c(Name='ProdutoTecnico', Numero__c = 0),
			new ContadorCodigo__c(Name='ProdutoComercial', Numero__c = 0)
		};
		insert contadoresProduto;
	}
	
	@isTest
	static void testeAtivacaoDesativacaoCapitalRiscoGarantia() {
		Product2 produto = new Product2();
		produto.Name = 'Nome Produto 00';
		produto.Status__c = 'Em criação';
		produto.ProductCode = '2070000';
		produto.TipoResponsavelPagamento__c = 'SEG';
		insert produto;

		Garantia__c garantia = new Garantia__c();
		garantia.VigenciaInicial__c = System.today();
		garantia.Tipo__c = 'Benefício';
		insert garantia;

		//Insere garantia do produto e verifica situacao da flag de capital de risco
		GarantiaProduto__c garantiaProduto = new GarantiaProduto__c();
		garantiaProduto.Garantia__c = garantia.Id;
		garantiaProduto.Produto__c = produto.Id;
		garantiaProduto.TipoGarantia__c = 'Benefício';
		garantiaProduto.TipoCapital__c = 'Capital uniforme';
		insert garantiaProduto;

		garantiaProduto = [Select Id, CapitalRiscos__c From GarantiaProduto__c Where Id =: garantiaProduto.Id];
		System.assertEquals(garantiaProduto.CapitalRiscos__c, false);

		//Insere risco da garantia e verifica situacao da flag de capital de risco
		Risco__c risco = new Risco__c(Tabela__c = 'Majoração - Vida individual', Name = 'Risco 1');
		insert risco;

		RiscoGarantia__c riscoGarantia = new RiscoGarantia__c(Risco__c = risco.Id, GarantiaProduto__c = garantiaProduto.Id, TabelaRisco__c = 'Majoração - Vida individual');
		insert riscoGarantia;

		garantiaProduto = [Select Id, CapitalRiscos__c From GarantiaProduto__c Where Id =: garantiaProduto.Id];
		System.assertEquals(garantiaProduto.CapitalRiscos__c, true);

		//Exclui risco da garantia e verifica situacao da flag de capital de risco
		delete riscoGarantia;

		garantiaProduto = [Select Id, CapitalRiscos__c From GarantiaProduto__c Where Id =: garantiaProduto.Id];
		System.assertEquals(garantiaProduto.CapitalRiscos__c, false);
	}
}