workspace-sf/force-app/main/default/objects/ContadorCodigo__c/ContadorCodigo__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Contador Código</label>
</CustomObject>

workspace-sf/force-app/main/default/objects/ContratanteContrato__c/ContratanteContrato__c.object-meta.xml
<CustomObject>
    <description>Objeto responsável por armazenar o cadastro dos contratantes do contrato</description>
    <label>Contratante do contrato</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contratantes do contrato</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/ContratanteContrato__c/fields/FormaPagamento__c.field-meta.xml
<CustomField>
    <fullName>FormaPagamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Forma de pagamento</label>
    <referenceTo>FormaPagamento__c</referenceTo>
    <relationshipLabel>Contratantes do contrato</relationshipLabel>
    <relationshipName>ContratantesContrato</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/ContratanteContrato__c/fields/VigenciaInicial__c.field-meta.xml
<CustomField>
    <fullName>VigenciaInicial__c</fullName>
    <label>Vigência Inicial</label>
    <type>Date</type>
</CustomField>

workspace-sf/force-app/main/default/objects/FormaPagamento__c/FormaPagamento__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar o cadastro das formas de pagamento</description>
    <label>Forma de pagamento</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Formas de pagamento</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/FormaPagamento__c/fields/RamoSeguro__c.field-meta.xml
<CustomField>
    <fullName>RamoSeguro__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ramo de seguro</label>
    <referenceTo>RamoSeguro__c</referenceTo>
    <relationshipLabel>Formas de pagamento</relationshipLabel>
    <relationshipName>FormasPagamento</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Garantia__c/Garantia__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar o cadastro das garantias</description>
    <label>Garantia</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Garantias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/Garantia__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Em análise</fullName>
            </value>
            <value>
                <fullName>Ativo</fullName>
            </value>
            <value>
                <fullName>Inativo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/Garantia__c/fields/VigenciaInicial__c.field-meta.xml
<CustomField>
    <fullName>VigenciaInicial__c</fullName>
    <label>Vigência inicial</label>
    <type>Date</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaProduto__c/GarantiaProduto__c.object-meta.xml
<CustomObject>
    <description>Objeto de relacionamento entre os produtos e as garantias</description>
    <label>Garantia do produto</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Garantias do produto</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/GarantiaProduto__c/fields/FormaPagamento__c.field-meta.xml
<CustomField>
    <fullName>FormaPagamento__c</fullName>
    <label>Forma de pagamento</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Parcelado</fullName>
            </value>
            <value>
                <fullName>Imediata</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaProduto__c/fields/Garantia__c.field-meta.xml
<CustomField>
    <fullName>Garantia__c</fullName>
    <label>Garantia</label>
    <referenceTo>Garantia__c</referenceTo>
    <relationshipLabel>Garantias do produto</relationshipLabel>
    <relationshipName>GarantiasProduto</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaProduto__c/fields/GarantiaProduto__c.field-meta.xml
<CustomField>
    <fullName>GarantiaProduto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Garantia do produto</label>
    <referenceTo>GarantiaProduto__c</referenceTo>
    <relationshipLabel>Garantias do produto (Garantia do produto)</relationshipLabel>
    <relationshipName>GarantiasProdutoTecnico</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaProduto__c/fields/RamoSeguro__c.field-meta.xml
<CustomField>
    <fullName>RamoSeguro__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ramo de seguro</label>
    <referenceTo>RamoSeguro__c</referenceTo>
    <relationshipLabel>Garantias do produto</relationshipLabel>
    <relationshipName>GarantiasProduto</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaProduto__c/fields/VigenciaGarantia__c.field-meta.xml
<CustomField>
    <fullName>VigenciaGarantia__c</fullName>
    <label>Vigência da Garantia</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mesma da apólice</fullName>
            </value>
            <value>
                <fullName>Contratação até fim da apólice</fullName>
            </value>
            <value>
                <fullName>Contratação até início da apólice</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaProduto__c/recordTypes/ProdutoComercial.recordType-meta.xml
<RecordType>
    <fullName>ProdutoComercial</fullName>
    <active>true</active>
    <label>Produto comercial</label>
</RecordType>

workspace-sf/force-app/main/default/objects/GarantiaProduto__c/recordTypes/ProdutoTecnico.recordType-meta.xml
<RecordType>
    <fullName>ProdutoTecnico</fullName>
    <active>true</active>
    <label>Produto técnico</label>
</RecordType>

workspace-sf/force-app/main/default/objects/GarantiaSeguradoContrato__c/GarantiaSeguradoContrato__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar as garantias do segurado do contrato</description>
    <label>Garantia do segurado do contrato</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Garantias do segurado do contrato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/GarantiaSeguradoContrato__c/fields/Garantia__c.field-meta.xml
<CustomField>
    <fullName>Garantia__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Garantia</label>
    <referenceTo>Garantia__c</referenceTo>
    <relationshipLabel>Garantias do segurado do contrato (Garantia)</relationshipLabel>
    <relationshipName>GarantiasSeguradoContrato</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaSeguradoContrato__c/fields/GarantiaProduto__c.field-meta.xml
<CustomField>
    <fullName>GarantiaProduto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Garantia do produto</label>
    <referenceTo>GarantiaProduto__c</referenceTo>
    <relationshipLabel>Garantias do segurado do contrato</relationshipLabel>
    <relationshipName>GarantiasSeguradoContrato</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaSeguradoContrato__c/fields/SeguradoContrato__c.field-meta.xml
<CustomField>
    <fullName>SeguradoContrato__c</fullName>
    <label>Segurado do contrato</label>
    <referenceTo>SeguradoContrato__c</referenceTo>
    <relationshipLabel>Garantias do segurado do contrato</relationshipLabel>
    <relationshipName>GarantiasSeguradoContrato</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GrupoContrato__c/GrupoContrato__c.object-meta.xml
<CustomObject>
    <description>Objeto responsável por armazenar os dados dos grupos de segurados do contrato</description>
    <label>Grupo do contrato</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grupos do contrato</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/GrupoContrato__c/fields/ContratanteContrato__c.field-meta.xml
<CustomField>
    <fullName>ContratanteContrato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contratante do contrato</label>
    <referenceTo>ContratanteContrato__c</referenceTo>
    <relationshipLabel>Grupos do contrato</relationshipLabel>
    <relationshipName>GruposContrato</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Parceiro__c/Parceiro__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar as informações dos parceiros da Porto</description>
    <label>Parceiro</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parceiros</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/Parceiro__c/fields/FormaPagamento__c.field-meta.xml
<CustomField>
    <fullName>FormaPagamento__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Forma de pagamento</label>
    <referenceTo>FormaPagamento__c</referenceTo>
    <relationshipLabel>Parceiros</relationshipLabel>
    <relationshipName>Parceiros</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Parceiro__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Em Criação</fullName>
                <default>true</default>
                <label>Em Criação</label>
            </value>
            <value>
                <fullName>Ativo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/RamoGarantia__c/RamoGarantia__c.object-meta.xml
<CustomObject>
    <description>Objeto de relacionamento entre a garantia e o ramo</description>
    <label>Ramo da garantia</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ramos da garantia</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/RamoGarantia__c/fields/Garantia__c.field-meta.xml
<CustomField>
    <fullName>Garantia__c</fullName>
    <label>Garantia</label>
    <referenceTo>Garantia__c</referenceTo>
    <relationshipName>RamosGarantia</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/RamoGarantia__c/fields/RamoSeguro__c.field-meta.xml
<CustomField>
    <fullName>RamoSeguro__c</fullName>
    <label>Ramo de seguro</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>RamoSeguro__c.Status__c</field>
            <operation>equals</operation>
            <value>Ativo</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>RamoSeguro__c</referenceTo>
    <relationshipLabel>Ramos da garantia</relationshipLabel>
    <relationshipName>RamosGarantia</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/RamoSeguro__c/RamoSeguro__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar o cadastro dos ramos de seguro</description>
    <label>Ramo de seguro</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ramos de seguro</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/RamoSeguro__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ativo</fullName>
            </value>
            <value>
                <fullName>Inativo</fullName>
            </value>
            <value>
                <fullName>Em análise</fullName>
                <default>true</default>
                <label>Em análise</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/SeguradoContrato__c/SeguradoContrato__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar os segurados do contrato</description>
    <label>Segurado do contrato</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Segurados do contrato</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/SeguradoContrato__c/fields/FormaPagamento__c.field-meta.xml
<CustomField>
    <fullName>FormaPagamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Forma de pagamento</label>
    <referenceTo>FormaPagamento__c</referenceTo>
    <relationshipLabel>Segurados do contrato</relationshipLabel>
    <relationshipName>SeguradosContrato</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/SeguradoContrato__c/fields/GrupoContrato__c.field-meta.xml
<CustomField>
    <fullName>GrupoContrato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Grupo do contrato</label>
    <referenceTo>GrupoContrato__c</referenceTo>
    <relationshipLabel>Segurados do contrato</relationshipLabel>
    <relationshipName>SeguradosContrato</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/SeguradoContrato__c/fields/VIgenciaFinal__c.field-meta.xml
<CustomField>
    <fullName>VIgenciaFinal__c</fullName>
    <label>VIgência final</label>
    <type>Date</type>
</CustomField>

workspace-sf/force-app/main/default/classes/CasoWizardPlusControllerTest.cls
/****
@description Classe de Teste para a Classe CasoWizardControllerPlus
@author Pedro Braz - Sys4b
@date 16/06/2021
@Classe referente a historia PLV-4938  
*****/

@isTest
public class CasoWizardPlusControllerTest {

	@isTest
	static void validarCasoWizardController() {
		Account conta = (Account) new AccountFactory.PessoaFisica().createRecord();
		Garantia__c garantia = (Garantia__c) new GarantiaFactory().createRecord();

		ContadorCodigo__c contCodigoTec = (ContadorCodigo__c) new ContadorCodigoFactory.ProdutoTecnico().createRecord();
        ContadorCodigo__c contCodigoCom = (ContadorCodigo__c) new ContadorCodigoFactory.ProdutoComercial().createRecord();
        Product2 produtoTecnico = (Product2) new ProdutoFactory.ProdutoTecnico().createRecord();
        produtoTecnico.Status__c = 'Em ativação';
        produtoTecnico.NumeroSusep__c = '123';
        produtoTecnico.VersaoRenovacao__c = 'Versão atual';
        update produtoTecnico;
        produtoTecnico.Status__c = 'Ativo';
        update produtoTecnico;
        
        Product2 produtoComercial = (Product2) new ProdutoFactory.ProdutoComercial(produtoTecnico).createRecord();

        FormaPagamento__c formaPagamento = (FormaPagamento__c) new FormaPagamentoFactory().createRecord();
        Parceiro__c parceiro = (Parceiro__c) new ParceiroFactory(conta, formaPagamento).createRecord();

		Contract contrato = (Contract) new ContratoFactory.ContratoFactoryComParam(conta, produtoComercial, parceiro).createRecord();
        contrato.Endosso__c = '0';
        contrato.NumeroApolice__c = '1234';
        update contrato;

        ContratanteContrato__c contratante = (ContratanteContrato__c) new ContratanteFactory(contrato).createRecord();
        GrupoContrato__c grupo = (GrupoContrato__c) new GrupoFactory(contratante).createRecord();
		SeguradoContrato__c segurado = (SeguradoContrato__c) new SeguradoContratoFactory(conta, grupo).createRecord();
		GarantiaSeguradoContrato__c garanSegCont = (GarantiaSeguradoContrato__c) new GarantiaSeguradoContratoFactory(segurado, garantia).createRecord();
        segurado.VigenciaInicial__c = system.today();
        segurado.VigenciaFinal__c = system.today().addMonths(1);
        update segurado;

		RamoSeguro__c ramoSeguro = (RamoSeguro__c) new RamoSeguroFactory(conta).createRecord();
        RamoGarantia__c ramoGarantia = (RamoGarantia__c) new RamoGarantiaFactory(garantia, ramoSeguro).createRecord();
        GarantiaProduto__c garanProdTec = (GarantiaProduto__c) new GarantiaProdutoFactory.GarantiaProdutoTec(garantia, produtoTecnico, ramoSeguro).createRecord();
        GarantiaProduto__c garanProdCom = (GarantiaProduto__c) new GarantiaProdutoFactory.GarantiaProdutoCom(produtoComercial, garantia, garanProdTec, ramoSeguro).createRecord();

		garanSegCont.GarantiaProduto__c = garanProdCom.Id;
		update garanSegCont;

		garanProdCom.VigenciaGarantia__c = 'Contratação até fim da apólice';
		update garanProdCom;

		Case caso = (Case) new CasoFactory.AtendimentoSinistro(conta).createRecord();

		Case caso2 = (Case) new CasoFactory.AtendimentoBeneficio(conta).createRecord();

		Test.startTest();
			List<String> retornos1 = CasoWizardPlusController.validarpreenchimento('123');

			caso.Dataocorrencia__c = null;
			update caso;
			List<String> retornos2 = CasoWizardPlusController.validarpreenchimento(caso.id);

			caso.Dataocorrencia__c = System.today();
			caso.Type = '';
			update caso;
        
			List<String> retornos3 = CasoWizardPlusController.validarpreenchimento(caso.id);

			caso.Type = 'Benefício';
			caso.Vitima__c = '';
			update caso;
			List<String> retornos4 = CasoWizardPlusController.validarpreenchimento(caso.id);

			caso.Type = 'Sinistro';
			update caso;
			List<String> retornos5 = CasoWizardPlusController.validarpreenchimento(caso.id);
			
			String retornoAgg = CasoWizardPlusController.pesquisacontratos(caso.Id, 'Acidente');
            
            CasoWizardPlusController.setError('TESTE');
			List<Case> retornos6 = CasoWizardPlusController.validarSinistroDuplicado(caso.Id, 'Acidente');

         //PLV-5469 - INICIO
         
            caso.Type = 'Sinistro';
            caso.Dataocorrencia__c = system.today().addMonths(-1);
            update caso;
         
            segurado.VigenciaInicial__c = system.today().addMonths(-2);
            segurado.VigenciaFinal__c = system.today().addMonths(-1);
            update segurado;
            
			List<String> retornos7 = CasoWizardPlusController.validarpreenchimento(caso.id);
            SYSTEM.debug('segurado.VigenciaInicial__c'+ segurado.VigenciaFinal__c+ ' e  caso.Dataocorrencia__c = '+ caso.Dataocorrencia__c );
        
        //PLV-5469 - FIM
        
            //CasoWizardPlusController.retornoTO pRetoro = (CasoWizardPlusController.retornoTO) JSON.deserializeUntyped(retornoAgg);
        
			Map<String,Object> mapParse = (Map<String,Object>) JSON.deserializeUntyped(retornoAgg);
         	List<CasoWizardPlusController.garantiaTO> listGarantiaTO = (List<CasoWizardPlusController.garantiaTO>) JSON.deserialize(JSON.serialize(mapParse.get('garantias')),List<CasoWizardPlusController.garantiaTO>.class);
            List<CasoWizardPlusController.contratoTO> listContratoTO = (List<CasoWizardPlusController.contratoTO>) JSON.deserialize(JSON.serialize(mapParse.get('contratos')),List<CasoWizardPlusController.contratoTO>.class);

            if(listGarantiaTO!=null && listGarantiaTO.size()>0){
                listGarantiaTO[0].selecionado = true;
            }


            Map<String, Object> pJSON = new Map<String, Object>();
            pJSON.put('recordId',caso.Id);
            pJSON.put('contratos',listContratoTO);
            pJSON.put('garantiasOriginais',listGarantiaTO);
            pJSON.put('garantiasModificadas',listGarantiaTO);
            pJSON.put('tipoEvento','Acidente');
            
            String requestSTR = '';
            
            CasoWizardPlusController.criaCasoSinistroPlus(JSON.serialize(pJSON));
       
		Test.stopTest();
    }
 //PLV-5469 - INICIO
    @isTest
	static void validarCasoVigenciaFinalMaiorIgualDataocorrencia() {
		Account conta = (Account) new AccountFactory.PessoaFisica().createRecord();
		Garantia__c garantia = (Garantia__c) new GarantiaFactory().createRecord();

		ContadorCodigo__c contCodigoTec = (ContadorCodigo__c) new ContadorCodigoFactory.ProdutoTecnico().createRecord();
        ContadorCodigo__c contCodigoCom = (ContadorCodigo__c) new ContadorCodigoFactory.ProdutoComercial().createRecord();
        Product2 produtoTecnico = (Product2) new ProdutoFactory.ProdutoTecnico().createRecord();
        produtoTecnico.Status__c = 'Em ativação';
        produtoTecnico.NumeroSusep__c = '123';
        produtoTecnico.VersaoRenovacao__c = 'Versão atual';
        update produtoTecnico;
        produtoTecnico.Status__c = 'Ativo';
        update produtoTecnico;
        
        Product2 produtoComercial = (Product2) new ProdutoFactory.ProdutoComercial(produtoTecnico).createRecord();

        FormaPagamento__c formaPagamento = (FormaPagamento__c) new FormaPagamentoFactory().createRecord();
        Parceiro__c parceiro = (Parceiro__c) new ParceiroFactory(conta, formaPagamento).createRecord();

		Contract contrato = (Contract) new ContratoFactory.ContratoFactoryComParam(conta, produtoComercial, parceiro).createRecord();
        contrato.Endosso__c = '1';
        contrato.NumeroApolice__c = '1234';
        update contrato;

        ContratanteContrato__c contratante = (ContratanteContrato__c) new ContratanteFactory(contrato).createRecord();
        GrupoContrato__c grupo = (GrupoContrato__c) new GrupoFactory(contratante).createRecord();
		SeguradoContrato__c segurado = (SeguradoContrato__c) new SeguradoContratoFactory(conta, grupo).createRecord();
		GarantiaSeguradoContrato__c garanSegCont = (GarantiaSeguradoContrato__c) new GarantiaSeguradoContratoFactory(segurado, garantia).createRecord();
        segurado.VigenciaInicial__c = system.today().addMonths(-2);
        segurado.VIgenciaFinal__c = system.today().addMonths(-1);
        update segurado;

		RamoSeguro__c ramoSeguro = (RamoSeguro__c) new RamoSeguroFactory(conta).createRecord();
        RamoGarantia__c ramoGarantia = (RamoGarantia__c) new RamoGarantiaFactory(garantia, ramoSeguro).createRecord();
        GarantiaProduto__c garanProdTec = (GarantiaProduto__c) new GarantiaProdutoFactory.GarantiaProdutoTec(garantia, produtoTecnico, ramoSeguro).createRecord();
        GarantiaProduto__c garanProdCom = (GarantiaProduto__c) new GarantiaProdutoFactory.GarantiaProdutoCom(produtoComercial, garantia, garanProdTec, ramoSeguro).createRecord();

		garanSegCont.GarantiaProduto__c = garanProdCom.Id;
		update garanSegCont;

		garanProdCom.VigenciaGarantia__c = 'Contratação até fim da apólice';
		update garanProdCom;
		Case caso = (Case) new CasoFactory.AtendimentoSinistro(conta).createRecord();

        Test.startTest();
			List<String> retornos1 = CasoWizardPlusController.validarpreenchimento('123');
			caso.Dataocorrencia__c = system.today().addMonths(-1);
			caso.Type = 'Sinistro';
			update caso;
        
			List<String> retornos3 = CasoWizardPlusController.validarpreenchimento(caso.id);

			String retornoAgg = CasoWizardPlusController.pesquisacontratos(caso.Id, 'Acidente');
                   
			Map<String,Object> mapParse = (Map<String,Object>) JSON.deserializeUntyped(retornoAgg);
         	List<CasoWizardPlusController.garantiaTO> listGarantiaTO = (List<CasoWizardPlusController.garantiaTO>) JSON.deserialize(JSON.serialize(mapParse.get('garantias')),List<CasoWizardPlusController.garantiaTO>.class);
            List<CasoWizardPlusController.contratoTO> listContratoTO = (List<CasoWizardPlusController.contratoTO>) JSON.deserialize(JSON.serialize(mapParse.get('contratos')),List<CasoWizardPlusController.contratoTO>.class);

            if(listGarantiaTO!=null && listGarantiaTO.size()>0){
                listGarantiaTO[0].selecionado = true;
            }

            Map<String, Object> pJSON = new Map<String, Object>();
            pJSON.put('recordId',caso.Id);
            pJSON.put('contratos',listContratoTO);
            pJSON.put('garantiasOriginais',listGarantiaTO);
            pJSON.put('garantiasModificadas',listGarantiaTO);
            pJSON.put('tipoEvento','Acidente');
            
            String requestSTR = '';
            
            CasoWizardPlusController.criaCasoSinistroPlus(JSON.serialize(pJSON));
       
		Test.stopTest();
    }
    
    @isTest
	static void validarCasoVigenciaInicialMaiorIgualDataocorrencia() {
		Account conta = (Account) new AccountFactory.PessoaFisica().createRecord();
		Garantia__c garantia = (Garantia__c) new GarantiaFactory().createRecord();

		ContadorCodigo__c contCodigoTec = (ContadorCodigo__c) new ContadorCodigoFactory.ProdutoTecnico().createRecord();
        ContadorCodigo__c contCodigoCom = (ContadorCodigo__c) new ContadorCodigoFactory.ProdutoComercial().createRecord();
        Product2 produtoTecnico = (Product2) new ProdutoFactory.ProdutoTecnico().createRecord();
        produtoTecnico.Status__c = 'Em ativação';
        produtoTecnico.NumeroSusep__c = '123';
        produtoTecnico.VersaoRenovacao__c = 'Versão atual';
        update produtoTecnico;
        produtoTecnico.Status__c = 'Ativo';
        update produtoTecnico;
        
        Product2 produtoComercial = (Product2) new ProdutoFactory.ProdutoComercial(produtoTecnico).createRecord();

        FormaPagamento__c formaPagamento = (FormaPagamento__c) new FormaPagamentoFactory().createRecord();
        Parceiro__c parceiro = (Parceiro__c) new ParceiroFactory(conta, formaPagamento).createRecord();

		Contract contrato = (Contract) new ContratoFactory.ContratoFactoryComParam(conta, produtoComercial, parceiro).createRecord();
        contrato.Endosso__c = '1';
        contrato.NumeroApolice__c = '1234';
        update contrato;

        ContratanteContrato__c contratante = (ContratanteContrato__c) new ContratanteFactory(contrato).createRecord();
        GrupoContrato__c grupo = (GrupoContrato__c) new GrupoFactory(contratante).createRecord();
		SeguradoContrato__c segurado = (SeguradoContrato__c) new SeguradoContratoFactory(conta, grupo).createRecord();
		GarantiaSeguradoContrato__c garanSegCont = (GarantiaSeguradoContrato__c) new GarantiaSeguradoContratoFactory(segurado, garantia).createRecord();
        segurado.VigenciaInicial__c = system.today().addMonths(-2);
        segurado.VIgenciaFinal__c = system.today().addMonths(-1);
        update segurado;

		RamoSeguro__c ramoSeguro = (RamoSeguro__c) new RamoSeguroFactory(conta).createRecord();
        RamoGarantia__c ramoGarantia = (RamoGarantia__c) new RamoGarantiaFactory(garantia, ramoSeguro).createRecord();
        GarantiaProduto__c garanProdTec = (GarantiaProduto__c) new GarantiaProdutoFactory.GarantiaProdutoTec(garantia, produtoTecnico, ramoSeguro).createRecord();
        GarantiaProduto__c garanProdCom = (GarantiaProduto__c) new GarantiaProdutoFactory.GarantiaProdutoCom(produtoComercial, garantia, garanProdTec, ramoSeguro).createRecord();

		garanSegCont.GarantiaProduto__c = garanProdCom.Id;
		update garanSegCont;

		garanProdCom.VigenciaGarantia__c = 'Contratação até fim da apólice';
		update garanProdCom;
		Case caso = (Case) new CasoFactory.AtendimentoSinistro(conta).createRecord();

        Test.startTest();
			List<String> retornos1 = CasoWizardPlusController.validarpreenchimento('123');
			caso.Dataocorrencia__c = system.today().addMonths(-2);
			caso.Type = 'Sinistro';
			update caso;
        
			List<String> retornos3 = CasoWizardPlusController.validarpreenchimento(caso.id);

			String retornoAgg = CasoWizardPlusController.pesquisacontratos(caso.Id, 'Acidente');
                   
			Map<String,Object> mapParse = (Map<String,Object>) JSON.deserializeUntyped(retornoAgg);
         	List<CasoWizardPlusController.garantiaTO> listGarantiaTO = (List<CasoWizardPlusController.garantiaTO>) JSON.deserialize(JSON.serialize(mapParse.get('garantias')),List<CasoWizardPlusController.garantiaTO>.class);
            List<CasoWizardPlusController.contratoTO> listContratoTO = (List<CasoWizardPlusController.contratoTO>) JSON.deserialize(JSON.serialize(mapParse.get('contratos')),List<CasoWizardPlusController.contratoTO>.class);

            if(listGarantiaTO!=null && listGarantiaTO.size()>0){
                listGarantiaTO[0].selecionado = true;
            }

            Map<String, Object> pJSON = new Map<String, Object>();
            pJSON.put('recordId',caso.Id);
            pJSON.put('contratos',listContratoTO);
            pJSON.put('garantiasOriginais',listGarantiaTO);
            pJSON.put('garantiasModificadas',listGarantiaTO);
            pJSON.put('tipoEvento','Acidente');
            
            String requestSTR = '';
            
            CasoWizardPlusController.criaCasoSinistroPlus(JSON.serialize(pJSON));
       
		Test.stopTest();
    }
    //PLV-5469 - FIM
    
}