workspace-sf/force-app/main/default/objects/ContadorCodigo__c/ContadorCodigo__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Contador Código</label>
</CustomObject>

workspace-sf/force-app/main/default/objects/ContadorCodigo__c/fields/Numero__c.field-meta.xml
<CustomField>
    <fullName>Numero__c</fullName>
    <label>Número</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

workspace-sf/force-app/main/default/objects/RemuneracaoOrcamento__c/RemuneracaoOrcamento__c.object-meta.xml
<CustomObject>
    <description>Objeto de relacionamento entre a oportunidade e o tipo de remuneração.</description>
    <label>Remuneração do orçamento</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Remunerações do orçamento</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/RemuneracaoOrcamento__c/fields/TipoRemuneracao__c.field-meta.xml
<CustomField>
    <fullName>TipoRemuneracao__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tipo de remuneração</label>
    <referenceTo>TipoRemuneracao__c</referenceTo>
    <relationshipLabel>Remunerações do orçamento</relationshipLabel>
    <relationshipName>RemuneracoesOportunidade</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/RemuneracaoProdutoParceiro__c/RemuneracaoProdutoParceiro__c.object-meta.xml
<CustomObject>
    <description>Objeto de relacionamento entre o parceiro e o tipo de remuneração.</description>
    <label>Remuneração do produto do parceiro</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Remunerações do produto do parceiro</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/RemuneracaoProdutoParceiro__c/fields/TipoRemuneracao__c.field-meta.xml
<CustomField>
    <fullName>TipoRemuneracao__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tipo de remuneração</label>
    <referenceTo>TipoRemuneracao__c</referenceTo>
    <relationshipName>RemuneracoesProdutoParceiro</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/TipoRemuneracao__c/TipoRemuneracao__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar o cadastro dos tipos de remuneração</description>
    <label>Tipo de remuneração</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tipos de remuneração</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/classes/RemuneracaoFacadeTest.cls
@isTest
public class RemuneracaoFacadeTest {
	@testSetup
    public static void setup(){
        
    }
    @isTest
    public static void testCriarRemuneracao(){
        Account conta = (Account) new AccountFactory.PessoaFisica().createRecord();
        //correcao ambientes inicio
        ContadorCodigo__c cont = new ContadorCodigo__c();
        cont.Name = 'ProdutoTecnico';
        cont.Numero__c = 1000000000;
        insert cont;
        //correcao ambientes fim

        Map<String, Account> mapAccount = new Map<String, Account>();
        mapAccount.put('1', conta);
        
        Product2 produtoTecnico = (Product2) new ProdutoFactory.ProdutoTecnico().createRecord();
        produtoTecnico.NumeroSusep__c = '123';
        produtoTecnico.VersaoRenovacao__c = 'Versão atual';
        produtoTecnico.Status__c = 'Ativo';
        update produtoTecnico;
        
        Product2 produtoComercial = (Product2) new ProdutoFactory.ProdutoComercial(produtoTecnico).createRecord();
        produtoComercial.Status__c = 'Ativo';
        update produtoComercial;
        
        Opportunity orcamento = (Opportunity) new OrcamentoFactory.VidaIndividual(produtoComercial, conta).createRecord();
        
        TipoRemuneracao__c newTipoRemuneracao = new TipoRemuneracao__c();
        Map<String, TipoRemuneracao__c> mapTipoRemuneracao = new Map<String, TipoRemuneracao__c>();
        mapTipoRemuneracao.put('1', newTipoRemuneracao);
        
        RemuneracaoProdutoParceiro__c newRemuneracao = new RemuneracaoProdutoParceiro__c();
        //newRemuneracao.TipoRemuneracao__c = newTipoRemuneracao.Id;
        List<RemuneracaoProdutoParceiro__c> lstRemuneracao = new List<RemuneracaoProdutoParceiro__c>();
        lstRemuneracao.add(newRemuneracao);
        EmissaoTO.RemuneracaoTO remuneracao = new EmissaoTO.RemuneracaoTO();
        //remuneracao.tipoRemuneracao = 'teste';
        List<EmissaoTO.RemuneracaoTO> lstRemuneracaoTO = new List<EmissaoTO.RemuneracaoTO>();
        
        //List<RemuneracaoOrcamento__c> newRemuneracaoOrcamento = RemuneracaoFacade.criaRemuneracaoOrcamento('', lstRemuneracaoTO, orcamento.Id, lstRemuneracao, mapAccount, mapTipoRemuneracao);
    }
}