workspace-sf/force-app/main/default/objects/Endereco__c/Endereco__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar os endereços das contas</description>
    <label>Endereço</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Endereços</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/Endereco__c/fields/Bairro__c.field-meta.xml
<CustomField>
    <fullName>Bairro__c</fullName>
    <label>Bairro</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Endereco__c/fields/CEP__c.field-meta.xml
<CustomField>
    <fullName>CEP__c</fullName>
    <label>CEP</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Endereco__c/fields/Cidade__c.field-meta.xml
<CustomField>
    <fullName>Cidade__c</fullName>
    <label>Cidade</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Endereco__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Endereços</relationshipLabel>
    <relationshipName>Enderecos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Endereco__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AC</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AP</fullName>
            </value>
            <value>
                <fullName>AM</fullName>
            </value>
            <value>
                <fullName>BA</fullName>
            </value>
            <value>
                <fullName>CE</fullName>
            </value>
            <value>
                <fullName>DF</fullName>
            </value>
            <value>
                <fullName>ES</fullName>
            </value>
            <value>
                <fullName>GO</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MG</fullName>
            </value>
            <value>
                <fullName>PA</fullName>
            </value>
            <value>
                <fullName>PB</fullName>
            </value>
            <value>
                <fullName>PR</fullName>
            </value>
            <value>
                <fullName>PE</fullName>
            </value>
            <value>
                <fullName>PI</fullName>
            </value>
            <value>
                <fullName>RJ</fullName>
            </value>
            <value>
                <fullName>RN</fullName>
            </value>
            <value>
                <fullName>RS</fullName>
            </value>
            <value>
                <fullName>RO</fullName>
            </value>
            <value>
                <fullName>RR</fullName>
            </value>
            <value>
                <fullName>SC</fullName>
            </value>
            <value>
                <fullName>SP</fullName>
            </value>
            <value>
                <fullName>SE</fullName>
            </value>
            <value>
                <fullName>TO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/Endereco__c/fields/Logradouro__c.field-meta.xml
<CustomField>
    <fullName>Logradouro__c</fullName>
    <label>Logradouro</label>
    <type>TextArea</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Endereco__c/fields/MaisAtual__c.field-meta.xml
<CustomField>
    <fullName>MaisAtual__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Mais atual?</label>
    <type>Checkbox</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Endereco__c/fields/Numero__c.field-meta.xml
<CustomField>
    <fullName>Numero__c</fullName>
    <label>Número</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Endereco__c/fields/Pais__c.field-meta.xml
<CustomField>
    <fullName>Pais__c</fullName>
    <label>País</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Endereco__c/fields/TipoEndereco__c.field-meta.xml
<CustomField>
    <fullName>TipoEndereco__c</fullName>
    <label>Tipo de endereço</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Comercial</fullName>
            </value>
            <value>
                <fullName>Recado</fullName>
            </value>
            <value>
                <fullName>Residencial</fullName>
            </value>
            <value>
                <fullName>Veraneio</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/Endereco__c/fields/TipoLogradouro__c.field-meta.xml
<CustomField>
    <fullName>TipoLogradouro__c</fullName>
    <label>Tipo de logradouro</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Alameda</fullName>
            </value>
            <value>
                <fullName>Avenida</fullName>
            </value>
            <value>
                <fullName>Rua</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/Pais__c/Pais__c.object-meta.xml
<CustomObject>
    <description>Objeto responsável por armazenar os dados dos países</description>
    <label>País</label>
    <nameField>
        <label>Pais Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Países</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/classes/EnderecoFactory.cls
/**
 * @author AVX - Daniel Zampieri
 * @date 2019-09-26
 * @description Endereco__c Factory Class
 */
@isTest
public class EnderecoFactory extends SObjectFactory{
    private static Endereco__c staticRecord;

	private static Endereco__c getRecordStatic(Account conta){

		if(staticRecord == null){
			staticRecord = new Endereco__c(
                CEP__c = '01001-001',
                Bairro__c = 'Centro',
                Logradouro__c = 'Praça da Sé',
                Cidade__c = 'São Paulo',
                Numero__c = '1',
                TipoEndereco__c = 'Recado',
                TipoLogradouro__c = 'Rua',
                Estado__c = 'SP',
                Pais__c = 'Brasil',
                Complemento__c = 'Casa 1',
                Conta__c = conta.Id,
                MaisAtual__c = true
            );
		}
		return staticRecord;
	}

    public EnderecoFactory() {

        this(
            (Account) new AccountFactory.PessoaFisica().createRecord()
        );
    }

    public EnderecoFactory(Account conta) {

        super(getRecordStatic(conta));
    }

}