workspace-sf/force-app/main/default/objects/MeioComercializacao__mdt/MeioComercializacao__mdt.object-meta.xml
<CustomObject>
    <label>Meio de comercialização</label>
    <pluralLabel>Meios de comercialização</pluralLabel>
</CustomObject>

workspace-sf/force-app/main/default/objects/MeioComercializacao__mdt/fields/PersisteValidacoes__c.field-meta.xml
<CustomField>
    <fullName>PersisteValidacoes__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Persiste Validações</label>
    <type>Checkbox</type>
</CustomField>

workspace-sf/force-app/main/default/classes/CustomMetadataTypesDAO.cls
public with sharing class CustomMetadataTypesDAO 
{
	private static CustomMetadataTypesDAO instance = new CustomMetadataTypesDAO();
	public static CustomMetadataTypesDAO getInstance(){	return instance; }
	public CustomMetadataTypesDAO() {}

	public List<MeioComercializacao__mdt> obtemMeiosComercializacaoValidacoes()
	{
		return 
		[ 
			SELECT 
				MasterLabel, 
				DeveloperName,
				PersisteValidacoes__c 
			FROM 
				MeioComercializacao__mdt 
			WHERE 
				PersisteValidacoes__c = :true
		];
	}
}