workspace-sf/force-app/main/default/objects/ParametroVigencia__c/ParametroVigencia__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar os parâmetros de vigência de um produto</description>
    <label>Parâmetro de vigência</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parâmetros de vigência</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/ParametroVigencia__c/fields/IndiceReajuste__c.field-meta.xml
<CustomField>
    <fullName>IndiceReajuste__c</fullName>
    <label>Índice de reajuste</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>IGP-M</fullName>
            </value>
            <value>
                <fullName>IPCA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/ParametroVigencia__c/fields/ModeloResgate__c.field-meta.xml
<CustomField>
    <fullName>ModeloResgate__c</fullName>
    <label>Modelo de resgate</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Percentual do capital</fullName>
            </value>
            <value>
                <fullName>Valor de prêmio pago</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/ParametroVigencia__c/fields/ParametroVigencia__c.field-meta.xml
<CustomField>
    <fullName>ParametroVigencia__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parâmetro de vigência</label>
    <referenceTo>ParametroVigencia__c</referenceTo>
    <relationshipLabel>Parâmetros de vigência</relationshipLabel>
    <relationshipName>ParametrosVigencia</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/ParametroVigencia__c/fields/Periodicidade__c.field-meta.xml
<CustomField>
    <fullName>Periodicidade__c</fullName>
    <label>Periodicidade</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Dias</fullName>
            </value>
            <value>
                <fullName>Anos</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/ParametroVigencia__c/fields/PeriodoCoberturaMaximo__c.field-meta.xml
<CustomField>
    <fullName>PeriodoCoberturaMaximo__c</fullName>
    <label>Período de cobertura máximo</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

workspace-sf/force-app/main/default/objects/ParametroVigencia__c/fields/PeriodoCoberturaMinimo__c.field-meta.xml
<CustomField>
    <fullName>PeriodoCoberturaMinimo__c</fullName>
    <label>Período de cobertura mínimo</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

workspace-sf/force-app/main/default/objects/ParametroVigencia__c/fields/PeriodoMaximoVigencia__c.field-meta.xml
<CustomField>
    <fullName>PeriodoMaximoVigencia__c</fullName>
    <label>Período máximo de vigência</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

workspace-sf/force-app/main/default/objects/ParametroVigencia__c/fields/PeriodoMinimoVigencia__c.field-meta.xml
<CustomField>
    <fullName>PeriodoMinimoVigencia__c</fullName>
    <label>Período mínimo de vigência</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

workspace-sf/force-app/main/default/objects/ParametroVigencia__c/fields/PrazoAplicacaoReajuste__c.field-meta.xml
<CustomField>
    <fullName>PrazoAplicacaoReajuste__c</fullName>
    <inlineHelpText>Em anos</inlineHelpText>
    <label>Prazo para aplicação de reajuste</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/ParametroVigencia__c/fields/PrazoMinimoCancelamento__c.field-meta.xml
<CustomField>
    <fullName>PrazoMinimoCancelamento__c</fullName>
    <inlineHelpText>Em anos</inlineHelpText>
    <label>Prazo mínimo de cancelamento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/ParametroVigencia__c/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Parâmetros de vigência</relationshipLabel>
    <relationshipName>ParametrosVigencia</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/ParametroVigencia__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Determinado</fullName>
            </value>
            <value>
                <fullName>Periódico</fullName>
            </value>
            <value>
                <fullName>Vitalício</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/ParametroVigencia__c/fields/TipoPeriodo__c.field-meta.xml
<CustomField>
    <fullName>TipoPeriodo__c</fullName>
    <label>Tipo de período</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Anos</fullName>
            </value>
            <value>
                <fullName>Dias</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/classes/ParametroVigenciaBO.cls
/**
 * BO ParametroVigencia
 * @author Fernando Barcellos @ 17/05/2018
 *
 **/
public class ParametroVigenciaBO {

    private static final Integer DIAS_POR_ANO = 365;
    private static final String DIAS = 'Dias';
    private static final String ANOS = 'Anos';
    private static final String TIPO_DETERMINADO = 'Determinado';
    private static final String TIPO_PERIODICO = 'Periódico';
    private static final String TIPO_VITALICIO = 'Vitalício';

    private static ParametroVigenciaBO classInstance;

    static {
        classInstance = new ParametroVigenciaBO();
    }

    private ParametroVigenciaBO() {
        
    }

    public static ParametroVigenciaBO getInstance() {
        return classInstance;
    }

    /**
     * Validação de acordo com o Tipo__c
     * @author Fernando Barcellos @ 17/05/2018
     * 
     */
    public void validarParametros(List<ParametroVigencia__c> parametrosVigencia) {
        List<ParametroVigencia__c> parametrosComerciais = new List<ParametroVigencia__c>();
        List<ParametroVigencia__c> parametrosTecnicos = new List<ParametroVigencia__c>();
        
        Set<Id> idsParametrosVigenciaTecnicos = new Set<Id>();

        for(ParametroVigencia__c param0 : parametrosVigencia) {
            if (param0.ParametroVigencia__c != null) {
                parametrosComerciais.add(param0);
                idsParametrosVigenciaTecnicos.add(param0.ParametroVigencia__c);
            }
            else {
                parametrosTecnicos.add(param0);
            }
        }

        // Parâmetros de vigência técnico para usar na validação dos batentes
        Map<Id, ParametroVigencia__c> parametrosVigenciaTecnico = new Map<Id, ParametroVigencia__c>(ParametroVigenciaDAO.getInstance().buscarParametrosVigencia(idsParametrosVigenciaTecnicos));

        // Validações para a criação de registro do tipo produto comercial
        for(ParametroVigencia__c param1 : parametrosComerciais) {
            ParametroVigencia__c paramTecnico = parametrosVigenciaTecnico.get(param1.ParametroVigencia__c);

            if (param1.Produto__c == null) {
                param1.addError('O produto não pode ser alterado.');
            }

            if (param1.Tipo__c != paramTecnico.Tipo__c) {
                param1.addError('O tipo de parâmetro de vigência não pode ser alterado.');
            }

            if (param1.Tipo__c == TIPO_DETERMINADO) {
                Decimal prazoMinimoTecnico = paramTecnico.PeriodoMinimoVigencia__c == null ? 0 : paramTecnico.PeriodoMinimoVigencia__c;
                Decimal prazoMaximoTecnico = paramTecnico.PeriodoMaximoVigencia__c == null ? 0 : paramTecnico.PeriodoMaximoVigencia__c;

                if (param1.TipoPeriodo__c != paramTecnico.TipoPeriodo__c) {
                    if (param1.TipoPeriodo__c == DIAS) {
                        prazoMinimoTecnico *= DIAS_POR_ANO;
                        prazoMaximoTecnico *= DIAS_POR_ANO;
                    }
                    else {
                        prazoMinimoTecnico /= DIAS_POR_ANO;
                        prazoMaximoTecnico /= DIAS_POR_ANO;
                    }
                }
                
                if (param1.PeriodoMinimoVigencia__c > prazoMinimoTecnico) {
                    param1.addError('Período mínimo de vigência acima do limite técnico.');
                }

                if (param1.PeriodoMaximoVigencia__c > prazoMaximoTecnico) {
                    param1.addError('Período máximo de vigência acima do limite técnico.');
                }
            }
            else if (param1.Tipo__c == TIPO_PERIODICO) {
                //PeriodoCoberturaMinimo__c, PeriodoCoberturaMaximo__c, Periodicidade__c
                Decimal periodoCoberturaMinimo = paramTecnico.PeriodoCoberturaMinimo__c == null ? 0 : paramTecnico.PeriodoCoberturaMinimo__c;
                Decimal periodoCoberturaMaximo = paramTecnico.PeriodoCoberturaMaximo__c == null ? 0 : paramTecnico.PeriodoCoberturaMaximo__c;

                if (param1.Periodicidade__c != paramTecnico.Periodicidade__c) {
                    if (param1.Periodicidade__c == DIAS) {
                        periodoCoberturaMinimo *= DIAS_POR_ANO;
                        periodoCoberturaMaximo *= DIAS_POR_ANO;
                    }
                    else {
                        periodoCoberturaMinimo /= DIAS_POR_ANO;
                        periodoCoberturaMaximo /= DIAS_POR_ANO;
                    }
                }

                if (param1.PeriodoCoberturaMinimo__c > periodoCoberturaMinimo) {
                    param1.addError('Período de cobertura mínimo está acima do limite técnico.');
                }
                else if (param1.PeriodoCoberturaMaximo__c > periodoCoberturaMaximo) {
                    param1.addError('Período de cobertura máximo está acima do limite técnico.');
                }
            }
            else if (param1.Tipo__c == TIPO_VITALICIO) {
                //ModeloResgate__c, PrazoAplicacaoReajuste__c, PrazoMinimoCancelamento__c, IndiceReajuste__c
                if (param1.ModeloResgate__c != paramTecnico.ModeloResgate__c) {
                    param1.addError('Modelo de resgate diferente do parâmetro técnico.');
                }
                else if (param1.PrazoAplicacaoReajuste__c != paramTecnico.PrazoAplicacaoReajuste__c) {
                    param1.addError('Prazo para aplicação de reajuste diferente do parâmetro técnico.');
                }
                else if (param1.PrazoMinimoCancelamento__c != paramTecnico.PrazoMinimoCancelamento__c) {
                    param1.addError('Prazo mínimo de cancelamento diferente do parâmetro técnico.');
                }
                else if (param1.IndiceReajuste__c != paramTecnico.IndiceReajuste__c) {
                    param1.addError('Índice de reajuste diferente do parâmetro técnico.');
                }
            }
        }

        // Validações para a criação de registro do tipo produto técnico
        for(ParametroVigencia__c param2 : parametrosTecnicos) {
            if (param2.Tipo__c == TIPO_DETERMINADO) {

                if ((param2.PeriodoMinimoVigencia__c == null || param2.PeriodoMaximoVigencia__c == null) && param2.TipoPeriodo__c == null) {
                    param2.addError('Obrigatório preencher o tipo de período, o período máximo e mínimo de vigência.');
                }
            }
            else if (param2.Tipo__c == TIPO_PERIODICO) {
                //PeriodoCoberturaMinimo__c, PeriodoCoberturaMaximo__c, Periodicidade__c
                if (param2.PeriodoCoberturaMinimo__c == null && param2.PeriodoCoberturaMaximo__c == null && param2.Periodicidade__c == null) {
                    param2.addError('Obrigatório preencher os períodos de cobertura mínimo e máximo e periodicidade.');
                }
            }
        }
    }
}