workspace-sf/force-app/main/default/objects/ParametroVigencia__c/ParametroVigencia__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar os parâmetros de vigência de um produto</description>
    <label>Parâmetro de vigência</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parâmetros de vigência</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/ParametroVigencia__c/fields/ParametroVigencia__c.field-meta.xml
<CustomField>
    <fullName>ParametroVigencia__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parâmetro de vigência</label>
    <referenceTo>ParametroVigencia__c</referenceTo>
    <relationshipLabel>Parâmetros de vigência</relationshipLabel>
    <relationshipName>ParametrosVigencia</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/ParametroVigencia__c/fields/PeriodoMaximoInadimplencia__c.field-meta.xml
<CustomField>
    <fullName>PeriodoMaximoInadimplencia__c</fullName>
    <description>Campo para verificar em dias o Período máximo de inadimplência. Localizado na section &quot;Informações de periódico&quot;</description>
    <inlineHelpText>Em dias</inlineHelpText>
    <label>Período máximo de inadimplência</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

workspace-sf/force-app/main/default/objects/ParametroVigencia__c/fields/PeriodoMaximoVigencia__c.field-meta.xml
<CustomField>
    <fullName>PeriodoMaximoVigencia__c</fullName>
    <label>Período máximo de vigência</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

workspace-sf/force-app/main/default/objects/ParametroVigencia__c/fields/PeriodoMinimoVigencia__c.field-meta.xml
<CustomField>
    <fullName>PeriodoMinimoVigencia__c</fullName>
    <label>Período mínimo de vigência</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

workspace-sf/force-app/main/default/objects/ParametroVigencia__c/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Parâmetros de vigência</relationshipLabel>
    <relationshipName>ParametrosVigencia</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/ParametroVigencia__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Determinado</fullName>
            </value>
            <value>
                <fullName>Periódico</fullName>
            </value>
            <value>
                <fullName>Vitalício</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/ParametroVigencia__c/fields/TipoPeriodo__c.field-meta.xml
<CustomField>
    <fullName>TipoPeriodo__c</fullName>
    <label>Tipo de período</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Anos</fullName>
            </value>
            <value>
                <fullName>Dias</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/ParametroVigencia__c/fields/ValidadeOrcamento__c.field-meta.xml
<CustomField>
    <fullName>ValidadeOrcamento__c</fullName>
    <inlineHelpText>Leve em consideração o dia atual + a quantidade de dias informada nesse campo</inlineHelpText>
    <label>Validade do Orçamento</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

workspace-sf/force-app/main/default/objects/ParametroVigencia__c/fields/ValidadeProposta__c.field-meta.xml
<CustomField>
    <fullName>ValidadeProposta__c</fullName>
    <inlineHelpText>Em dias</inlineHelpText>
    <label>Validade da Proposta</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

workspace-sf/force-app/main/default/objects/ParametroVigencia__c/recordTypes/ProdutoComercial.recordType-meta.xml
<RecordType>
    <fullName>ProdutoComercial</fullName>
    <active>true</active>
    <label>Produto comercial</label>
</RecordType>

workspace-sf/force-app/main/default/objects/ParametroVigencia__c/recordTypes/ProdutoTecnico.recordType-meta.xml
<RecordType>
    <fullName>ProdutoTecnico</fullName>
    <active>true</active>
    <label>Produto técnico</label>
</RecordType>

workspace-sf/force-app/main/default/classes/ParametroVigenciaFactory.cls
//PLV-3460 Fix 5 - INICIO - Ajuste factory
//PLV-2673- Inicio
/**
 * @author AVX - Matheus Gomes
 * @date 2019-09-11
 * @description Factory Parâmetro de Vigência - PLV-2673
 */
@isTest
public class ParametroVigenciaFactory{
    
    private static Map<String,ParametroVigencia__c> mStaticRecord = new Map<String,ParametroVigencia__c>();
    
    //---------------------------------------Comercial------------------------------------------------

    public static ParametroVigencia__c getRecordParametroComercial(Product2 produto) {
      
      if(!mStaticRecord.containsKey('ParametroComercial')){

        Recordtype REC_ID_ACCOUNT = RecordTypeBO.buscarTipoRegistro('ParametroVigencia__c', 'ProdutoComercial');

        mStaticRecord.put('ParametroComercial', new ParametroVigencia__c(
          Produto__c = produto.Id,
                  ValidadeOrcamento__c = 30,
                  ValidadeProposta__c = 30,
                  PeriodoMaximoInadimplencia__c = 90,
                  TipoPeriodo__c = 'Anos',
                  PeriodoMaximoVigencia__c = 12,
                  PeriodoMinimoVigencia__c = 1,
          Tipo__c = 'Determinado'));
      }
		return mStaticRecord.get('ParametroComercial');
    }
    
    public class ParametroVigenciaComercial extends SObjectFactory{
      
      public ParametroVigenciaComercial() {

        this(
              (Product2) new ProdutoFactory.ProdutoComercial().createRecord()
            );
      }
    
      public ParametroVigenciaComercial(Product2 produto) {
    
        super(getRecordParametroComercial(produto));
      }
    }

    //---------------------------------------Tecnico------------------------------------------------

    public static ParametroVigencia__c getRecordParametroTecnico(Product2 produto) {
      
      if(!mStaticRecord.containsKey('ParametroTecnico')){

        Recordtype REC_ID_ACCOUNT = RecordTypeBO.buscarTipoRegistro('ParametroVigencia__c', 'ProdutoTecnico');

        mStaticRecord.put('ParametroTecnico', new ParametroVigencia__c(
          Produto__c = produto.Id,
                  ValidadeOrcamento__c = 30,
                  ValidadeProposta__c = 30,
                  PeriodoMaximoInadimplencia__c = 90,
                  TipoPeriodo__c = 'Anos',
                  PeriodoMaximoVigencia__c = 12,
                  PeriodoMinimoVigencia__c = 1,
          Tipo__c = 'Determinado'));
      }
		return mStaticRecord.get('ParametroTecnico');
    }
    
    public class ParametroVigenciaTecnico extends SObjectFactory{
      
      public ParametroVigenciaTecnico() {

        this(
              (Product2) new ProdutoFactory.ProdutoTecnico().createRecord()
            );
      }
    
      public ParametroVigenciaTecnico(Product2 produto) {
    
        super(getRecordParametroTecnico(produto));
      }
    }
}
//PLV-2673- Fim
//PLV-3460 Fix 5 - FIM