workspace-sf/force-app/main/default/objects/Profissao__c/Profissao__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar o cadastro das profissões</description>
    <label>Profissão</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Profissões</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/Profissao__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <externalId>true</externalId>
    <label>Código ocupação</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Profissao__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Em análise</fullName>
                <default>true</default>
                <label>Em análise</label>
            </value>
            <value>
                <fullName>Ativo</fullName>
            </value>
            <value>
                <fullName>Inativo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/classes/ProfissaoDAO.cls
/**
 * Camada de abstração de dados do objeto Profissao__c
 * @author Fernando Barcellos @ 05/12/2017
 *
 **/
public class ProfissaoDAO {
	private static ProfissaoDAO classInstance;

	static {
		classInstance = new ProfissaoDAO();
	}

	private ProfissaoDAO() { }

	public static ProfissaoDAO getInstance() {
		return classInstance;
	}

	public List<Profissao__c> buscarProfissoesPorStatus(String status) {
		return buscarProfissoesPorStatus(new Set<String>{ status });
	}

	public List<Profissao__c> buscarProfissoesPorStatus(Set<String> setStatus) {
		return [
			SELECT
				Id,
				Name,
				Codigo__c,
				Status__c
			FROM 
				Profissao__c
			WHERE
				Status__c IN : setStatus
		];
	}

	public List<Profissao__c> buscarProfisoesAtivasPorCodigo(Set<String> codigos) {
		return [
			SELECT 
				Id,
				Name,
				Codigo__c,
				Status__c
			FROM
				Profissao__c
			WHERE
				Status__c =: 'Ativo'
				AND Codigo__c IN : codigos
		];
	}

	//INICIO | PLV-1586-29-v1
	public List<Profissao__c> buscarProfissoesTodas() {
		return [
			SELECT 
				Id,
				Name,
				Codigo__c,
				Status__c
			FROM
				Profissao__c
		];
	}
	//FIM | PLV-1586-29-v1

	//PLV-2495 - INICIO
	public List<Profissao__c> buscarProfissoesNaoExistentesNoWS(Set<String> IdsExterno) {
		return [
			SELECT 
				Id,
				Name,
				Codigo__c,
				Status__c
			FROM
				Profissao__c
			WHERE
				IdExterno__c NOT IN :IdsExterno
		];
	}
	//PLV-2495 - FINAL

}