workspace-sf/force-app/main/default/objects/GrupoContrato__c/GrupoContrato__c.object-meta.xml
<CustomObject>
    <description>Objeto responsável por armazenar os dados dos grupos de segurados do contrato</description>
    <label>Grupo do contrato</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grupos do contrato</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/SeguradoContrato__c/SeguradoContrato__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar os segurados do contrato</description>
    <label>Segurado do contrato</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Segurados do contrato</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/SeguradoContrato__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Segurados do contrato (Conta)</relationshipLabel>
    <relationshipName>SeguradoContrato</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/SeguradoContrato__c/fields/GrupoContrato__c.field-meta.xml
<CustomField>
    <fullName>GrupoContrato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Grupo do contrato</label>
    <referenceTo>GrupoContrato__c</referenceTo>
    <relationshipLabel>Segurados do contrato</relationshipLabel>
    <relationshipName>SeguradosContrato</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/SeguradoContrato__c/fields/VIgenciaFinal__c.field-meta.xml
<CustomField>
    <fullName>VIgenciaFinal__c</fullName>
    <label>VIgência final</label>
    <type>Date</type>
</CustomField>

workspace-sf/force-app/main/default/classes/SeguradoContratoFactory.cls
/**
 * @author AVX - Daniel Zampieri
 * @date 2019-02-27
 * @description Segurado do Contrato Factory Class
 */

@isTest
public class SeguradoContratoFactory extends SObjectFactory{
	private static SeguradoContrato__c staticRecord;
    
    private static SeguradoContrato__c getRecordStatic(Account contaPessoal, GrupoContrato__c grupo){
        //PLV-3658 - INICIO
        Date dataVigenciaInicial = System.today().addDays(-5);
        Date dataVigenciaFinal = System.today().addDays(5);
        //PLV-3658 - FIM
        
		if(staticRecord == null){
			staticRecord = new SeguradoContrato__c(
                Conta__c = contaPessoal.Id,
                GrupoContrato__c = grupo.Id,
                VigenciaInicial__c = dataVigenciaInicial,
                VIgenciaFinal__c = dataVigenciaFinal
            );
		}
		return staticRecord;
	}
    
    public SeguradoContratoFactory() {

		this(
        	(Account) new AccountFactory.PessoaFisica().createRecord(),
            (GrupoContrato__c) new GrupoFactory().createRecord()
        );
	}

	public SeguradoContratoFactory(Account contaPessoal, GrupoContrato__c grupo) {

		super(getRecordStatic(contaPessoal, grupo));
	}
}