workspace-sf/force-app/main/default/objects/AcordoComercial__c/AcordoComercial__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar os acordos comerciais com os canais</description>
    <label>Acordo comercial</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Acordos comerciais</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/AcordoComercial__c/fields/CanalDistribuicao__c.field-meta.xml
<CustomField>
    <fullName>CanalDistribuicao__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Canal de distribuição</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CanalDistribuicao__c.Status__c</field>
            <operation>equals</operation>
            <value>Ativo</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CanalDistribuicao__c</referenceTo>
    <relationshipLabel>Acordos comerciais</relationshipLabel>
    <relationshipName>AcordosComerciais</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/CanalDistribuicao__c/CanalDistribuicao__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar o cadastro dos canais de distribuição</description>
    <label>Canal de distribuição</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Canais de distribuição</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/ProdutoAcordo__c/ProdutoAcordo__c.object-meta.xml
<CustomObject>
    <description>Objeto de relacionamento entre o acordo e o produto.</description>
    <label>Produto do acordo</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Produtos do acordo</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/ProdutoAcordo__c/fields/AcordoComercial__c.field-meta.xml
<CustomField>
    <fullName>AcordoComercial__c</fullName>
    <label>Acordo comercial</label>
    <referenceTo>AcordoComercial__c</referenceTo>
    <relationshipLabel>Produtos do acordo</relationshipLabel>
    <relationshipName>Produtos_do_acordo</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/ProdutoAcordo__c/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Produtos do acordo</relationshipLabel>
    <relationshipName>ProdutosAcordo</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/classes/AcordoComercialDAO.cls
/**************************************************************************************************************************************************************************
 * 
 *	Classe responsável pela buscade dados do objeto de AcordoComercial__c
 *
 **************************************************************************************************************************************************************************/
public class AcordoComercialDAO {
	private static final AcordoComercialDAO instancia = new AcordoComercialDAO();

	private AcordoComercialDAO() {	
	}

	public static AcordoComercialDAO getInstance(){
		return instancia;
	}

	public List<AcordoComercial__c> buscarAcordoComercialPorId(Set<Id> acordoComercialIds){
		return [
			Select
				Id,
				CanalDistribuicao__c
			From	
				AcordoComercial__c	
			Where
				Id IN :acordoComercialIds
		];
	}

	public List<ProdutoAcordo__c> buscarProdutosAcordoPorAcordoId(Set<Id> acordoComercialIds){
		return [
			Select
				Id
			From	
				ProdutoAcordo__c	
			Where
				AcordoComercial__c IN :acordoComercialIds
		];
	}

	public List<ProdutoAcordo__c> buscarProdutosPorProductCode(Set<String> setProductCode){
        return [
                SELECT
                        Id,
                        AcordoComercial__c,
                        Produto__r.VersaoMaxima__c,
												Produto__r.Versao__c,
                        Produto__r.ProductCode,
						Produto__r.CodigoPrecificaProduto__c // PLV-5331 INÍCIO / FIM 
                FROM
                        ProdutoAcordo__c
                WHERE
                        Produto__r.ProductCode =: setProductCode
        ];
    }
}