workspace-sf/force-app/main/default/objects/AcordoComercial__c/AcordoComercial__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar os acordos comerciais com os canais</description>
    <label>Acordo comercial</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Acordos comerciais</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/AcordoComercial__c/fields/CanalDistribuicao__c.field-meta.xml
<CustomField>
    <fullName>CanalDistribuicao__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Canal de distribuição</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CanalDistribuicao__c.Status__c</field>
            <operation>equals</operation>
            <value>Ativo</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CanalDistribuicao__c</referenceTo>
    <relationshipLabel>Acordos comerciais</relationshipLabel>
    <relationshipName>AcordosComerciais</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/CanalDistribuicao__c/CanalDistribuicao__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar o cadastro dos canais de distribuição</description>
    <label>Canal de distribuição</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Canais de distribuição</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/classes/CanalDistribuicaoBO.cls
/**************************************************************************************************************************************************************************
 * 
 *	Classe responsável pelo negócio do objeto de AcordoComercial__c
 *
 **************************************************************************************************************************************************************************/
public class CanalDistribuicaoBO {
	private static final CanalDistribuicaoBO instancia = new CanalDistribuicaoBO();
	private static CanalDistribuicaoDAO dao = CanalDistribuicaoDAO.getInstance();

	private CanalDistribuicaoBO() {	
	}

	public static CanalDistribuicaoBO getInstance(){
		return instancia;
	}

	/**
	 * Busca os canais de distribuição juntamente com o seus filhos
	 *
	 */
	 public List<CanalDistribuicao__c> buscarCanalDistribuicaoComFilhos(Set<Id> canalDistribuicaoIds){
		return dao.buscarCanalDistribuicaoComFilhos(canalDistribuicaoIds);
	}
}