workspace-sf/force-app/main/default/objects/DadosCorretor__c/DadosCorretor__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar dados dos corretores.</description>
    <label>Dados do corretor</label>
    <nameField>
        <label>Código do corretor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dados dos corretores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/DadosCorretor__c/fields/SusepOficialCorretor__c.field-meta.xml
<CustomField>
    <fullName>SusepOficialCorretor__c</fullName>
    <label>Susep Oficial</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/FavorecidoRemuneracaoProposta__c/FavorecidoRemuneracaoProposta__c.object-meta.xml
<CustomObject>
    <label>Favorecido da Remuneração da Proposta</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Favorecido da Proposta</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Favorecidos da Remuneração da Proposta</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/FavorecidoRemuneracaoProposta__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Favorecidos_da_Proposta</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/FavorecidoRemuneracaoProposta__c/fields/DadosCorretor__c.field-meta.xml
<CustomField>
    <fullName>DadosCorretor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dados do corretor</label>
    <referenceTo>DadosCorretor__c</referenceTo>
    <relationshipLabel>Favorecidos da Remuneração da Proposta</relationshipLabel>
    <relationshipName>FavorecidosRemuneracaoProposta</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/FavorecidoRemuneracaoProposta__c/fields/Papel__c.field-meta.xml
<CustomField>
    <fullName>Papel__c</fullName>
    <label>Papel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Corretor</fullName>
            </value>
            <value>
                <fullName>Agenciador</fullName>
            </value>
            <value>
                <fullName>Parceiro</fullName>
            </value>
            <value>
                <fullName>Prestador</fullName>
            </value>
            <value>
                <fullName>RepresentanteSeguros</fullName>
                <label>Representante de Seguros</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/FavorecidoRemuneracaoProposta__c/fields/RemuneracaoProposta__c.field-meta.xml
<CustomField>
    <fullName>RemuneracaoProposta__c</fullName>
    <label>Remuneração da proposta</label>
    <referenceTo>RemuneracaoProposta__c</referenceTo>
    <relationshipLabel>Favorecidos da Remuneração da Proposta</relationshipLabel>
    <relationshipName>FavorecidosRemuneracaodaProposta</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/FavorecidoRemuneracaoProposta__c/fields/Susep__c.field-meta.xml
<CustomField>
    <fullName>Susep__c</fullName>
    <label>Susep</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/FavorecidoRemuneracaoProposta__c/fields/SusepEmissao__c.field-meta.xml
<CustomField>
    <fullName>SusepEmissao__c</fullName>
    <label>Susep Emissão</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/FavorecidoRemuneracaoProposta__c/fields/SusepOficialCorretor__c.field-meta.xml
<CustomField>
    <fullName>SusepOficialCorretor__c</fullName>
    <label>Susep Oficial Corretor</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/RemuneracaoOrcamento__c/RemuneracaoOrcamento__c.object-meta.xml
<CustomObject>
    <description>Objeto de relacionamento entre a oportunidade e o tipo de remuneração.</description>
    <label>Remuneração do orçamento</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Remunerações do orçamento</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/RemuneracaoOrcamento__c/fields/Oportunidade__c.field-meta.xml
<CustomField>
    <fullName>Oportunidade__c</fullName>
    <label>Orçamento</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Remunerações do orçamento</relationshipLabel>
    <relationshipName>RemuneracoesOrcamento</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/RemuneracaoOrcamento__c/fields/Percentual__c.field-meta.xml
<CustomField>
    <fullName>Percentual__c</fullName>
    <label>Percentual</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

workspace-sf/force-app/main/default/objects/RemuneracaoOrcamento__c/fields/TipoRemuneracao__c.field-meta.xml
<CustomField>
    <fullName>TipoRemuneracao__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tipo de remuneração</label>
    <referenceTo>TipoRemuneracao__c</referenceTo>
    <relationshipLabel>Remunerações do orçamento</relationshipLabel>
    <relationshipName>RemuneracoesOportunidade</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/RemuneracaoProdutoParceiro__c/RemuneracaoProdutoParceiro__c.object-meta.xml
<CustomObject>
    <description>Objeto de relacionamento entre o parceiro e o tipo de remuneração.</description>
    <label>Remuneração do produto do parceiro</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Remunerações do produto do parceiro</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/RemuneracaoProdutoParceiro__c/fields/Percentual__c.field-meta.xml
<CustomField>
    <fullName>Percentual__c</fullName>
    <label>Percentual</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

workspace-sf/force-app/main/default/objects/RemuneracaoProdutoParceiro__c/fields/TipoRemuneracao__c.field-meta.xml
<CustomField>
    <fullName>TipoRemuneracao__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tipo de remuneração</label>
    <referenceTo>TipoRemuneracao__c</referenceTo>
    <relationshipName>RemuneracoesProdutoParceiro</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/RemuneracaoProposta__c/RemuneracaoProposta__c.object-meta.xml
<CustomObject>
    <description>Objeto de relacionamento entre a proposta e o tipo de remuneração.</description>
    <label>Remuneração da proposta</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Remunerações da proposta</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/RemuneracaoProposta__c/fields/Papel__c.field-meta.xml
<CustomField>
    <fullName>Papel__c</fullName>
    <label>Papel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agenciador</fullName>
            </value>
            <value>
                <fullName>Corretor</fullName>
            </value>
            <value>
                <fullName>Parceiro</fullName>
            </value>
            <value>
                <fullName>Prestador</fullName>
            </value>
            <value>
                <fullName>Representante de Seguros</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/RemuneracaoProposta__c/fields/Participacao__c.field-meta.xml
<CustomField>
    <fullName>Participacao__c</fullName>
    <label>Participação</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

workspace-sf/force-app/main/default/objects/RemuneracaoProposta__c/fields/Proposta__c.field-meta.xml
<CustomField>
    <fullName>Proposta__c</fullName>
    <label>Proposta</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Remunerações da proposta</relationshipLabel>
    <relationshipName>RemuneracoesProposta</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/RemuneracaoProposta__c/fields/TipoRemuneracao__c.field-meta.xml
<CustomField>
    <fullName>TipoRemuneracao__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tipo de remuneração</label>
    <referenceTo>TipoRemuneracao__c</referenceTo>
    <relationshipLabel>Remunerações da proposta</relationshipLabel>
    <relationshipName>RemuneracoesProposta</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/TipoRemuneracao__c/TipoRemuneracao__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar o cadastro dos tipos de remuneração</description>
    <label>Tipo de remuneração</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tipos de remuneração</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/classes/RemuneracaoFacade.cls
public class RemuneracaoFacade 
{
	private final String                    PESSOA_FISICA                  = 'FIS';
    private final String                    PESSOA_JURIDICA                = 'JUR';
	private final String                    PAPEL_CORRETOR                 = 'COR';
    private final String                    PAPEL_AGENCIADOR               = 'AGE';
    private final String                    PAPEL_REPRESENTANTE            = 'REP';
    private final String                    PAPEL_ASSESSORIA               = 'ASS';
    private final String                    ORIGEM_CRITICA_ODM             = 'ODM';
    private final String                    ORIGEM_CRITICA_SINAPSE         = 'Sinapse';
    private final String                    STATUS_CRITICA_PENDENTE        = 'Pendente';

    private final Map<String, String> mapPapeis = new Map<String, String> { 'REP' => 'RepresentanteSeguros', 'COR' => 'Corretor', 'PRE'  => 'Prestador', 'AGE'  => 'Agenciador', 'PAR'  => 'Parceiro' };

	private static final RemuneracaoFacade classInstance;
    static { classInstance = new RemuneracaoFacade(); }
    private RemuneracaoFacade() {}
    public static RemuneracaoFacade getInstance() { return classInstance; }

    public List<RemuneracaoOrcamento__c> criaRemuneracaoOrcamento(String meioComercializacao, List<EmissaoTO.RemuneracaoTO> remuneracoes, Id idOrcamento, List<RemuneracaoProdutoParceiro__c> listaRemuneracaoParceiro, Map<String, Account> mapContas, Map<String, TipoRemuneracao__c> mapTiposRemuneracao)
    {
        List<RemuneracaoOrcamento__c> remuneracoesOrcamento = new List<RemuneracaoOrcamento__c>();

        for(RemuneracaoProdutoParceiro__c remPar : listaRemuneracaoParceiro)
        {
            system.debug('criaRemuneracaoOrcamento >> remPar' + remPar);
            RemuneracaoOrcamento__c  remuneracaoSF  = new RemuneracaoOrcamento__c();
            remuneracaoSF.Oportunidade__c           = idOrcamento;
            remuneracaoSF.TipoRemuneracao__c        = remPar.TipoRemuneracao__c;
            remuneracaoSF.Percentual__c             = remPar.Percentual__c;

            remuneracoesOrcamento.add(remuneracaoSF);
        }   
        
        return remuneracoesOrcamento;
    }


    // monta uma lista  de remunerações da proposta baseado no peyload recebido via integração
    public List<RemuneracaoProposta__c> criaRemuneracaoProposta(List<EmissaoTO.RemuneracaoTO> remuneracoes, Id idProposta, Map<String, TipoRemuneracao__c> mapTiposRemuneracao)
    {
        List<RemuneracaoProposta__c> remuneracoesProposta = new List<RemuneracaoProposta__c>();

        for(EmissaoTO.RemuneracaoTO remuneracao : remuneracoes)
        {
            TipoRemuneracao__c tipoRem = mapTiposRemuneracao.get(remuneracao.tipoRemuneracao);

            if(tipoRem == null)
                throw new PropostaException('Tipo remuneracao não encontrada: (' + remuneracao.tipoRemuneracao + ')');

            system.debug('criaRemuneracaoProposta >> tipoRemuneracao: ' + tipoRem);
            RemuneracaoProposta__c remuneracaoSF = new RemuneracaoProposta__c();
            remuneracaoSF.TipoRemuneracao__c     = tipoRem.Id;
            remuneracaoSF.Proposta__c            = idProposta;
            remuneracaoSF.Percentual__c          = remuneracao.percentual;

            remuneracao.ojSFProposta = remuneracaoSF;
            remuneracoesProposta.add(remuneracaoSF);
            
        }
        system.debug('criaRemuneracaoProposta >> remuneracoesProposta: ' + remuneracoesProposta);
        return remuneracoesProposta;
    } 

    // PLV-2352-29 INICIO
    // monta uma lista  de remunerações da proposta 
    // Ccria os favorecidos da remunerãçao da proposta de acordo com os favorecidos da remuneração baseado no peyload recebido via integração
    public List<FavorecidoRemuneracaoProposta__c> criaFavorecidosRemuneracaoProposta(List<EmissaoTO.RemuneracaoTO> remuneracoes, Map<String, Account> mapContas, Map<String, DadosCorretor__c> mapDadosCorretor, Map<String, Account> mapContasNaoAtualizar)
    {

        List<FavorecidoRemuneracaoProposta__c> favorecidosProposta = new List<FavorecidoRemuneracaoProposta__c>();

        for(EmissaoTO.RemuneracaoTO remuneracao : remuneracoes)
        {
            for(EmissaoTO.FavorecidoTO favorecido : remuneracao.favorecidos)
            {
                FavorecidoRemuneracaoProposta__c favorecidoSf = new FavorecidoRemuneracaoProposta__c();
                String idExternoRef;
                Account conta;
                DadosCorretor__c dadosCorretor;

                if(favorecido.pessoa.tipo == PESSOA_JURIDICA)
                    idExternoRef = favorecido.pessoa.dadosPessoaJuridica.numeroCnpj + favorecido.pessoa.dadosPessoaJuridica.ordemCnpj + favorecido.pessoa.dadosPessoaJuridica.digitoCnpj;
                else if(favorecido.pessoa.tipo == PESSOA_FISICA)
                    idExternoRef = favorecido.pessoa.dadosPessoaFisica.numeroCpf + favorecido.pessoa.dadosPessoaFisica.digitoCpf;

                conta = mapContas.get(idExternoRef);
                if(conta != null){
                    favorecidoSf.Conta__c  = conta.Id;
                    mapContasNaoAtualizar.put(conta.IdExterno__c, conta);

                }
                // PLV-2352-29 FIM

                dadosCorretor = mapDadosCorretor.get(favorecido.susep);
                //PLV-5235 - FIX01 - INICIO
                if(dadosCorretor != null) {
                    favorecidoSF.DadosCorretor__c = dadosCorretor.Id;
                    favorecidoSF.SusepOficialCorretor__c = dadosCorretor.SusepOficialCorretor__c; 
                }
                else {
                    favorecidoSF.SusepOficialCorretor__c = favorecido.susepOficialCorretor;
                }
                //PLV-5235 - FIX01 - FIM
                
                FavorecidoSf.RemuneracaoProposta__c = remuneracao.ojSFProposta.Id;
                favorecidoSF.Papel__c = mapPapeis.get(favorecido.papel);
                favorecidoSF.Participacao__c = favorecido.participacao;
                favorecidoSF.CorretorLider__c = favorecido.corretorLider == true ? true: false;
                favorecidoSF.Susep__c = favorecido.susep;
                favorecidoSF.SusepEmissao__c = favorecido.susepEmissao;
                //favorecidoSF.SusepOficialCorretor__c = favorecido.susepOficialCorretor; //PLV-5235 - INICIO/FIM
                //favorecidoSF.SusepOficialCorretor__c = dadosCorretor.SusepOficialCorretor__c; //PLV-5235 - INICIO/FIM   //PLV-5235 - FIX01 - INICIO/FIM
                favorecidoSF.SusepOrcamento__c = favorecido.susepOrcamento;
                favorecidosProposta.add(favorecidoSf);
            }
        }

        return favorecidosProposta;
    } 

	public class PropostaException extends Exception {}
}