workspace-sf/force-app/main/default/objects/DadosCorretor__c/DadosCorretor__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar dados dos corretores.</description>
    <label>Dados do corretor</label>
    <nameField>
        <label>Código do corretor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dados dos corretores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/DadosCorretor__c/fields/CodigoSucursalDestinoCheque__c.field-meta.xml
<CustomField>
    <fullName>CodigoSucursalDestinoCheque__c</fullName>
    <label>Código sucursal destino cheque</label>
    <type>TextArea</type>
</CustomField>

workspace-sf/force-app/main/default/objects/DadosCorretor__c/fields/NomeCorretor__c.field-meta.xml
<CustomField>
    <fullName>NomeCorretor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nome do corretor</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>CodigosCorretores</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/DadosCorretor__c/fields/SucursalDestinoCheque__c.field-meta.xml
<CustomField>
    <fullName>SucursalDestinoCheque__c</fullName>
    <label>Sucursal destino cheque</label>
    <type>TextArea</type>
</CustomField>

workspace-sf/force-app/main/default/objects/DadosCorretor__c/fields/SucursalVinculo__c.field-meta.xml
<CustomField>
    <fullName>SucursalVinculo__c</fullName>
    <label>Sucursal de vínculo</label>
    <type>TextArea</type>
</CustomField>

workspace-sf/force-app/main/default/objects/DadosCorretor__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Principal</fullName>
            </value>
            <value>
                <fullName>Produção</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/StageDadosCorretor__c/StageDadosCorretor__c.object-meta.xml
<CustomObject>
    <label>Stage Dados Corretor</label>
    <nameField>
        <label>StageDadosCorretor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stage Dados Corretores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/classes/StageDadosCorretorBatch.cls
//INICIO | PLV-2179-27- remover duplicidade
global class StageDadosCorretorBatch implements Database.Batchable<sObject> {
	
	global StageDadosCorretorBatch() { }
	
	global Database.QueryLocator start(Database.BatchableContext BC) {
		System.debug('ESTOU NO RETORNO DA QUERY');
		Database.QueryLocator retorno = Database.getQueryLocator( [SELECT Name, CodigoSucursalDestinoCheque__c, NomeCorretor__c, SucursalVinculo__c, SucursalDestinoCheque__c, Tipo__c, CreatedDate FROM DadosCorretor__c ORDER BY CreatedDate DESC] );
		System.debug('QUERY retorno' + retorno);
		return retorno;
	}

   	global void execute(Database.BatchableContext BC, List<DadosCorretor__c> lista) {
		System.debug('ESTOU NO EXECUTE DO BATCH');

		List<StageDadosCorretor__c> stage = new List<StageDadosCorretor__c>();
		for(DadosCorretor__c item : lista)
		{
			StageDadosCorretor__c stageItem = new StageDadosCorretor__c();
			stageItem.Name = item.Name;
			stage.add(stageItem);
		}

		System.debug('itens '+ stage.size());

		insert stage;
	}
	
	global void finish(Database.BatchableContext BC) {
		System.debug('ESTOU NO FINISH DO BATCH');
		Database.executeBatch(new DadosCorretorBatch());
	}
	
}
//FIM | PLV-2179-27- remover duplicidade