workspace-sf/force-app/main/default/objects/DadosCorretor__c/DadosCorretor__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar dados dos corretores.</description>
    <label>Dados do corretor</label>
    <nameField>
        <label>Código do corretor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dados dos corretores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/FavorecidoRemuneracao__c/FavorecidoRemuneracao__c.object-meta.xml
<CustomObject>
    <description>Objeto de relacionamento entre a conta e remuneração do parceiro</description>
    <label>Favorecido da remuneração</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Favorecidos da remuneração</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/FavorecidoRemuneracao__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>FavorecidosRemuneracao</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/FavorecidoRemuneracao__c/fields/DadosCorretor__c.field-meta.xml
<CustomField>
    <fullName>DadosCorretor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Código susep do corretor na Cia</inlineHelpText>
    <label>Dados do corretor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Conta__c</field>
            <operation>equals</operation>
            <valueField>DadosCorretor__c.NomeCorretor__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>DadosCorretor__c</referenceTo>
    <relationshipLabel>Favorecidos da remuneração</relationshipLabel>
    <relationshipName>FavorecidosRemuneracao</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/FavorecidoRemuneracao__c/fields/InformacaoBancaria__c.field-meta.xml
<CustomField>
    <fullName>InformacaoBancaria__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Informação bancária</label>
    <referenceTo>InformacaoBancaria__c</referenceTo>
    <relationshipLabel>Favorecidos da remuneração</relationshipLabel>
    <relationshipName>FavorecidosRemuneracao</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/FavorecidoRemuneracao__c/fields/Papel__c.field-meta.xml
<CustomField>
    <fullName>Papel__c</fullName>
    <label>Papel</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Corretor</fullName>
            </value>
            <value>
                <fullName>Agenciador</fullName>
            </value>
            <value>
                <fullName>Parceiro</fullName>
            </value>
            <value>
                <fullName>Prestador</fullName>
            </value>
            <value>
                <fullName>RepresentanteSeguros</fullName>
                <label>Representante de Seguros</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/FavorecidoRemuneracao__c/fields/RemuneracaoProdutoParceiro__c.field-meta.xml
<CustomField>
    <fullName>RemuneracaoProdutoParceiro__c</fullName>
    <label>Remuneração do produto do parceiro</label>
    <referenceTo>RemuneracaoProdutoParceiro__c</referenceTo>
    <relationshipLabel>Favorecidos da remuneração</relationshipLabel>
    <relationshipName>FavorecidosRemuneracao</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/FormaPagamento__c/FormaPagamento__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar o cadastro das formas de pagamento</description>
    <label>Forma de pagamento</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Formas de pagamento</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/InformacaoBancaria__c/InformacaoBancaria__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar as informações bancárias das contas</description>
    <label>Informação bancária</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Informações bancárias</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/InformacaoBancaria__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>InformacoesBancarias</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/InformacaoBancaria__c/fields/IdExterno__c.field-meta.xml
<CustomField>
    <fullName>IdExterno__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Id externo</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

workspace-sf/force-app/main/default/objects/InformacaoBancaria__c/fields/Papel__c.field-meta.xml
<CustomField>
    <fullName>Papel__c</fullName>
    <label>Papel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agenciador</fullName>
            </value>
            <value>
                <fullName>Parceiro</fullName>
            </value>
            <value>
                <fullName>Prestador</fullName>
            </value>
            <value>
                <fullName>Segurado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/InformacaoBancaria__c/fields/VigenciaInicial__c.field-meta.xml
<CustomField>
    <fullName>VigenciaInicial__c</fullName>
    <label>Vigência Inicial</label>
    <type>Date</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Parceiro__c/Parceiro__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar as informações dos parceiros da Porto</description>
    <label>Parceiro</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parceiros</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/Parceiro__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Parceiros</relationshipLabel>
    <relationshipName>Parceiro</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Parceiro__c/fields/FormaPagamento__c.field-meta.xml
<CustomField>
    <fullName>FormaPagamento__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Forma de pagamento</label>
    <referenceTo>FormaPagamento__c</referenceTo>
    <relationshipLabel>Parceiros</relationshipLabel>
    <relationshipName>Parceiros</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Parceiro__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Em Criação</fullName>
                <default>true</default>
                <label>Em Criação</label>
            </value>
            <value>
                <fullName>Ativo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/ProdutoParceiro__c/ProdutoParceiro__c.object-meta.xml
<CustomObject>
    <description>Objeto de relacionamento entre o parceiro e o produto</description>
    <label>Produto do parceiro</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número do Produto do Parceiro</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Produtos do parceiro</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/ProdutoParceiro__c/fields/Parceiro__c.field-meta.xml
<CustomField>
    <fullName>Parceiro__c</fullName>
    <label>Parceiro</label>
    <referenceTo>Parceiro__c</referenceTo>
    <relationshipLabel>Produtos do parceiro</relationshipLabel>
    <relationshipName>ProdutosParceiro</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/ProdutoParceiro__c/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Produtos do parceiro</relationshipLabel>
    <relationshipName>ProdutosParceiro</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/RemuneracaoProduto__c/RemuneracaoProduto__c.object-meta.xml
<CustomObject>
    <description>Objeto de relacionamento entre o produto e o tipo de remuneração</description>
    <label>Remuneração do produto</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Remunerações do produto</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/RemuneracaoProduto__c/fields/LimiteMinimo__c.field-meta.xml
<CustomField>
    <fullName>LimiteMinimo__c</fullName>
    <label>Limite mínimo</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

workspace-sf/force-app/main/default/objects/RemuneracaoProduto__c/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Remunerações do produto</relationshipLabel>
    <relationshipName>RemuneracoesProduto</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/RemuneracaoProduto__c/fields/RemuneracaoProduto__c.field-meta.xml
<CustomField>
    <fullName>RemuneracaoProduto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Remuneração do produto</label>
    <referenceTo>RemuneracaoProduto__c</referenceTo>
    <relationshipLabel>Remunerações do produto</relationshipLabel>
    <relationshipName>RemuneracoesProduto</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/RemuneracaoProduto__c/fields/TipoRemuneracao__c.field-meta.xml
<CustomField>
    <fullName>TipoRemuneracao__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tipo de remuneração</label>
    <referenceTo>TipoRemuneracao__c</referenceTo>
    <relationshipLabel>Remunerações do produto</relationshipLabel>
    <relationshipName>RemuneracoesProduto</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/RemuneracaoProduto__c/recordTypes/ProdutoComercial.recordType-meta.xml
<RecordType>
    <fullName>ProdutoComercial</fullName>
    <active>true</active>
    <label>Produto comercial</label>
</RecordType>

workspace-sf/force-app/main/default/objects/RemuneracaoProduto__c/recordTypes/ProdutoTecnico.recordType-meta.xml
<RecordType>
    <fullName>ProdutoTecnico</fullName>
    <active>true</active>
    <label>Produto técnico</label>
</RecordType>

workspace-sf/force-app/main/default/objects/RemuneracaoProdutoParceiro__c/RemuneracaoProdutoParceiro__c.object-meta.xml
<CustomObject>
    <description>Objeto de relacionamento entre o parceiro e o tipo de remuneração.</description>
    <label>Remuneração do produto do parceiro</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Remunerações do produto do parceiro</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/RemuneracaoProdutoParceiro__c/fields/ProdutoParceiro__c.field-meta.xml
<CustomField>
    <fullName>ProdutoParceiro__c</fullName>
    <label>Produto do parceiro</label>
    <referenceTo>ProdutoParceiro__c</referenceTo>
    <relationshipLabel>Remunerações do produto do parceiro</relationshipLabel>
    <relationshipName>RemuneracoesProdutoParceiro</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/RemuneracaoProdutoParceiro__c/fields/TipoRemuneracao__c.field-meta.xml
<CustomField>
    <fullName>TipoRemuneracao__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tipo de remuneração</label>
    <referenceTo>TipoRemuneracao__c</referenceTo>
    <relationshipName>RemuneracoesProdutoParceiro</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/TipoRemuneracao__c/TipoRemuneracao__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar o cadastro dos tipos de remuneração</description>
    <label>Tipo de remuneração</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tipos de remuneração</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/classes/BotaoAtivarParceiroControllerTest.cls
/**
 * Created by Alessandro Ponte on 20/09/2018.
 */

@IsTest
private class BotaoAtivarParceiroControllerTest {
    @TestSetup
    static void testSetup(){
        TestDataFactory.gerarDadosSetup();
        TestDataFactory.gerarProdutoComercialAtivo(false);

         // PLV-4472 INICIO
        Account contaParceiro = new Account(Name = 'ParceiroTeste', IdExterno__c = '74586138825', Cnpj__c = '08.370.609/0001-64');
        insert contaParceiro;

        Account contaCorretor = new Account(Name = 'ContaCorretor', Papel__c = 'Corretor', IdExterno__c = '38012786532', Cnpj__c = '38.579.897/0001-22' );
        insert contaCorretor;
         // PLV-4472 FIM

        FormaPagamento__c formaPagamento = TestDataFactory.gerarFormaPagamento();
        Parceiro__c parceiro = TestDataFactory.gerarParceiro(contaParceiro,formaPagamento);
    }

    @IsTest
    static void testParceiroJaAtivado(){

        Parceiro__c parceiro = [SELECT Id FROM Parceiro__c LIMIT 1];
        parceiro.Status__c = 'Ativo';
        update parceiro;

        RetornoAcaoBotaoTO retorno = ParceiroBO.getInstance().ativarParceiro(parceiro.Id);

        // Espera a mensagem de que o parceiro já está ativo
        System.assert( retorno.mensagens.contains('Parceiro já esta Ativo!') );

    }

    @IsTest
    static void testParceiroSemProdutoComercial(){

        Parceiro__c parceiro = [SELECT Id FROM Parceiro__c LIMIT 1];
        RetornoAcaoBotaoTO retorno = ParceiroBO.getInstance().ativarParceiro(parceiro.Id);

        System.assert( retorno.mensagens.contains('Relacionar pelo menos um produto comercial ao parceiro') );

    }

    @IsTest
    static void testParceiroComProdutoTecnico(){

        Parceiro__c parceiro = [SELECT Id FROM Parceiro__c LIMIT 1];
        Product2 produtoTecnico = [SELECT Id FROM Product2 WHERE RecordType.DeveloperName = 'ProdutoTecnico'];


        ProdutoParceiro__c produtoParceiro = TestDataFactory.gerarProdutoParceiro(parceiro, produtoTecnico);

        parceiro = [SELECT Id, (SELECT Id,Produto__r.ProductCode FROM ProdutosParceiro__r) FROM Parceiro__c LIMIT 1];


        RetornoAcaoBotaoTO retorno = ParceiroBO.getInstance().ativarParceiro(parceiro.Id);

        System.assert( retorno.mensagens.contains('Produto ' + parceiro.ProdutosParceiro__r[0].Produto__r.ProductCode + ' não é um produto comercial!') );

    }

    @IsTest
    static void testParceiroSemRemuneracao(){

        Parceiro__c parceiro = [SELECT Id FROM Parceiro__c LIMIT 1];
        Product2 produtoComercial = [ SELECT Id, ProductCode FROM Product2 WHERE RecordType.DeveloperName = 'ProdutoComercial' LIMIT 1 ];

        ProdutoParceiro__c produtoParceiro = TestDataFactory.gerarProdutoParceiro(parceiro, produtoComercial);

        RetornoAcaoBotaoTO retorno = ParceiroBO.getInstance().ativarParceiro(parceiro.Id);

        System.debug('retorno --------------------- ' + retorno);

        System.assert( retorno.mensagens.contains('Remuneracao no parceiro não cadastrada para o Produto ' + produtoComercial.ProductCode) );

    }

    @IsTest
    static void testParceiroComProdutoInativo(){

        Parceiro__c parceiro = [SELECT Id FROM Parceiro__c LIMIT 1];
        Product2 produtoComercial = [ SELECT Id, ProductCode, (SELECT Id,TipoRemuneracao__c,TipoRemuneracao__r.Id FROM RemuneracoesProduto__r) FROM Product2 WHERE RecordType.DeveloperName = 'ProdutoComercial' LIMIT 1 ];
        produtoComercial.Status__c = 'Em criação';
        update produtoComercial;

        ProdutoParceiro__c produtoParceiro = TestDataFactory.gerarProdutoParceiro(parceiro, produtoComercial);

        RemuneracaoProdutoParceiro__c remuneracaoProdutoParceiro =
            TestDataFactory.gerarRemuneracaoProdutoParceiro(produtoComercial.RemuneracoesProduto__r[0].TipoRemuneracao__r,produtoParceiro,100);

        RetornoAcaoBotaoTO retorno = ParceiroBO.getInstance().ativarParceiro(parceiro.Id);

        System.assert( retorno.mensagens.contains('Produto ' +  produtoComercial.ProductCode + ' não está ativo e/ou vigente') );

    }

    @IsTest
    static void testParceiroComProdutoSemVigencia(){

        Parceiro__c parceiro = [SELECT Id FROM Parceiro__c LIMIT 1];
        Product2 produtoComercial = [ SELECT Id, ProductCode, (SELECT Id,TipoRemuneracao__c,TipoRemuneracao__r.Id FROM RemuneracoesProduto__r) FROM Product2 WHERE RecordType.DeveloperName = 'ProdutoComercial' LIMIT 1 ];
        // PLV-3673  -  INICIO
        produtoComercial.VigenciaInicial__c = system.today().addDays(2);
        produtoComercial.VigenciaFinal__c = system.today().addDays(30);
        // PLV-3673  -  FIM
        produtoComercial.Status__c = 'Ativo';
        update produtoComercial;

        ProdutoParceiro__c produtoParceiro = TestDataFactory.gerarProdutoParceiro(parceiro, produtoComercial);

        RemuneracaoProdutoParceiro__c remuneracaoProdutoParceiro =
            TestDataFactory.gerarRemuneracaoProdutoParceiro(produtoComercial.RemuneracoesProduto__r[0].TipoRemuneracao__r,produtoParceiro,100);

        RetornoAcaoBotaoTO retorno = ParceiroBO.getInstance().ativarParceiro(parceiro.Id);

        System.assert( retorno.mensagens.contains('Produto ' +  produtoComercial.ProductCode + ' não está ativo e/ou vigente') );

    }

    @IsTest
    static void testParceiroComRemuneracaoNaoPermitida(){

        Parceiro__c parceiro = [SELECT Id FROM Parceiro__c LIMIT 1];
        Product2 produtoComercial = [ SELECT Id, ProductCode, (SELECT Id, TipoRemuneracao__c, TipoRemuneracao__r.Id, TipoRemuneracao__r.Name FROM RemuneracoesProduto__r) FROM Product2 WHERE RecordType.DeveloperName = 'ProdutoComercial' LIMIT 1 ];

        ProdutoParceiro__c produtoParceiro = TestDataFactory.gerarProdutoParceiro(parceiro, produtoComercial);
        TipoRemuneracao__c tipoRemuneracao = TestDataFactory.gerarTipoRemuneracao('PRO-LABORE', 5, 50, 'Integral');

        RemuneracaoProdutoParceiro__c remuneracaoProdutoParceiro =
            TestDataFactory.gerarRemuneracaoProdutoParceiro(tipoRemuneracao, produtoParceiro, 100);
        remuneracaoProdutoParceiro = [SELECT Id,TipoRemuneracao__c,TipoRemuneracao__r.Name FROM RemuneracaoProdutoParceiro__c WHERE Id =: remuneracaoProdutoParceiro.Id];

        RetornoAcaoBotaoTO retorno = ParceiroBO.getInstance().ativarParceiro(parceiro.Id);

        System.assert( retorno.mensagens.contains('Remuneração ' + remuneracaoProdutoParceiro.TipoRemuneracao__r.Name + ' não permitida pelo produto') );

    }

    @IsTest
    static void testParceiroSemFavorecidos(){

        Parceiro__c parceiro = [SELECT Id FROM Parceiro__c LIMIT 1];
        Product2 produtoComercial = [ SELECT Id, ProductCode, (SELECT Id, TipoRemuneracao__c, TipoRemuneracao__r.Id, TipoRemuneracao__r.Name FROM RemuneracoesProduto__r) FROM Product2 WHERE RecordType.DeveloperName = 'ProdutoComercial' LIMIT 1 ];

        ProdutoParceiro__c produtoParceiro = TestDataFactory.gerarProdutoParceiro(parceiro, produtoComercial);

        RemuneracaoProdutoParceiro__c remuneracaoProdutoParceiro =
            TestDataFactory.gerarRemuneracaoProdutoParceiro(produtoComercial.RemuneracoesProduto__r[0].TipoRemuneracao__r, produtoParceiro, 100);
        remuneracaoProdutoParceiro = [SELECT Id,TipoRemuneracao__c,TipoRemuneracao__r.Name FROM RemuneracaoProdutoParceiro__c WHERE Id =: remuneracaoProdutoParceiro.Id];

        RetornoAcaoBotaoTO retorno = ParceiroBO.getInstance().ativarParceiro(parceiro.Id);

        System.assert( retorno.mensagens.contains('Informar os favorecidos da Remuneração ' + remuneracaoProdutoParceiro.TipoRemuneracao__r.Name) );

    }

    @IsTest
    static void testParceiroSemLiderCorretagem(){

        Parceiro__c parceiro = [SELECT Id FROM Parceiro__c LIMIT 1];
        Product2 produtoComercial = [ SELECT Id, ProductCode, (SELECT Id, TipoRemuneracao__c, TipoRemuneracao__r.Id, TipoRemuneracao__r.Name FROM RemuneracoesProduto__r) FROM Product2 WHERE RecordType.DeveloperName = 'ProdutoComercial' LIMIT 1 ];

        ProdutoParceiro__c produtoParceiro = TestDataFactory.gerarProdutoParceiro(parceiro, produtoComercial);

        RemuneracaoProdutoParceiro__c remuneracaoProdutoParceiro =
            TestDataFactory.gerarRemuneracaoProdutoParceiro(produtoComercial.RemuneracoesProduto__r[0].TipoRemuneracao__r, produtoParceiro, 100);
        remuneracaoProdutoParceiro = [SELECT Id,TipoRemuneracao__c,TipoRemuneracao__r.Name FROM RemuneracaoProdutoParceiro__c WHERE Id =: remuneracaoProdutoParceiro.Id];
        Account conta = [SELECT Id,Name FROM Account WHERE Papel__c = 'Corretor' LIMIT 1];

        DadosCorretor__c dadosCorretor = TestDataFactory.gerarDadosCorretor(conta);
        InformacaoBancaria__c informacaoBancaria = TestDataFactory.gerarInformacaoBancaria(conta);
        FavorecidoRemuneracao__c favorecidoRemuneracao = TestDataFactory.gerarFavorecidoRemuneracao(conta, 100.00,'Corretor', false, remuneracaoProdutoParceiro,dadosCorretor, informacaoBancaria);

        RetornoAcaoBotaoTO retorno = ParceiroBO.getInstance().ativarParceiro(parceiro.Id);

        System.assert( retorno.mensagens.contains('Informar um líder para a remuneração de corretagem') );

    }

    @IsTest
    static void testParceiroComMaisDeUmLiderCorretagem(){

        Parceiro__c parceiro = [SELECT Id FROM Parceiro__c LIMIT 1];
        Product2 produtoComercial = [ SELECT Id, ProductCode, (SELECT Id, TipoRemuneracao__c, TipoRemuneracao__r.Id, TipoRemuneracao__r.Name FROM RemuneracoesProduto__r) FROM Product2 WHERE RecordType.DeveloperName = 'ProdutoComercial' LIMIT 1 ];

        ProdutoParceiro__c produtoParceiro = TestDataFactory.gerarProdutoParceiro(parceiro, produtoComercial);

        RemuneracaoProdutoParceiro__c remuneracaoProdutoParceiro =
            TestDataFactory.gerarRemuneracaoProdutoParceiro(produtoComercial.RemuneracoesProduto__r[0].TipoRemuneracao__r, produtoParceiro, 100);
        remuneracaoProdutoParceiro = [SELECT Id,TipoRemuneracao__c,TipoRemuneracao__r.Name FROM RemuneracaoProdutoParceiro__c WHERE Id =: remuneracaoProdutoParceiro.Id];
        Account conta = [SELECT Id,Name FROM Account WHERE Papel__c = 'Corretor' LIMIT 1];

        DadosCorretor__c dadosCorretor = TestDataFactory.gerarDadosCorretor(conta);
        InformacaoBancaria__c informacaoBancaria = TestDataFactory.gerarInformacaoBancaria(conta);

        FavorecidoRemuneracao__c favorecidoRemuneracao = TestDataFactory.gerarFavorecidoRemuneracao(conta, 90.00, 'Corretor', true, remuneracaoProdutoParceiro,dadosCorretor, informacaoBancaria);
        FavorecidoRemuneracao__c favorecidoRemuneracao2 = TestDataFactory.gerarFavorecidoRemuneracao(conta, 10.00, 'Corretor', true, remuneracaoProdutoParceiro,dadosCorretor, informacaoBancaria);

        RetornoAcaoBotaoTO retorno = ParceiroBO.getInstance().ativarParceiro(parceiro.Id);

        System.assert( retorno.mensagens.contains('Informar somente um líder para a remuneração de corretagem') );

    }

    @IsTest
    static void testParceiroComFavorecidoComPapelInvalido(){

        Parceiro__c parceiro = [SELECT Id FROM Parceiro__c LIMIT 1];
        Product2 produtoComercial = [ SELECT Id, ProductCode, (SELECT Id, TipoRemuneracao__c, TipoRemuneracao__r.Id, TipoRemuneracao__r.Name FROM RemuneracoesProduto__r) FROM Product2 WHERE RecordType.DeveloperName = 'ProdutoComercial' LIMIT 1 ];

        ProdutoParceiro__c produtoParceiro = TestDataFactory.gerarProdutoParceiro(parceiro, produtoComercial);

        RemuneracaoProdutoParceiro__c remuneracaoProdutoParceiro =
            TestDataFactory.gerarRemuneracaoProdutoParceiro(produtoComercial.RemuneracoesProduto__r[0].TipoRemuneracao__r, produtoParceiro, 100);
        remuneracaoProdutoParceiro = [SELECT Id,TipoRemuneracao__c,TipoRemuneracao__r.Name FROM RemuneracaoProdutoParceiro__c WHERE Id =: remuneracaoProdutoParceiro.Id];

        Account conta = [SELECT Id,Name,Papel__c FROM Account WHERE Papel__c = 'Corretor'];
        DadosCorretor__c dadosCorretor = TestDataFactory.gerarDadosCorretor(conta);

        InformacaoBancaria__c informacaoBancaria = TestDataFactory.gerarInformacaoBancaria(conta);

        FavorecidoRemuneracao__c favorecidoRemuneracao = TestDataFactory.gerarFavorecidoRemuneracao(conta, 90.00, 'Corretor', true, remuneracaoProdutoParceiro, dadosCorretor, informacaoBancaria);
        FavorecidoRemuneracao__c favorecidoRemuneracao2 = TestDataFactory.gerarFavorecidoRemuneracao(conta, 10.00, 'Agenciador', false, remuneracaoProdutoParceiro, null, informacaoBancaria);

        favorecidoRemuneracao2 = [SELECT Id,Conta__c,Conta__r.Name FROM FavorecidoRemuneracao__c  WHERE Id =: favorecidoRemuneracao2.Id];

        RetornoAcaoBotaoTO retorno = ParceiroBO.getInstance().ativarParceiro(parceiro.Id);

        System.assert( retorno.mensagens.contains('Papel do favorecido(a) ' + favorecidoRemuneracao2.Conta__r.Name + ' não vínculado a conta!') );

    }

    @IsTest
    static void testParceiroComParticipacaoMaiorQue100(){

        Parceiro__c parceiro = [SELECT Id FROM Parceiro__c LIMIT 1];
        Product2 produtoComercial = [ SELECT Id, ProductCode, (SELECT Id, TipoRemuneracao__c, TipoRemuneracao__r.Id, TipoRemuneracao__r.Name FROM RemuneracoesProduto__r) FROM Product2 WHERE RecordType.DeveloperName = 'ProdutoComercial' LIMIT 1 ];

        ProdutoParceiro__c produtoParceiro = TestDataFactory.gerarProdutoParceiro(parceiro, produtoComercial);

        RemuneracaoProdutoParceiro__c remuneracaoProdutoParceiro =
            TestDataFactory.gerarRemuneracaoProdutoParceiro(produtoComercial.RemuneracoesProduto__r[0].TipoRemuneracao__r, produtoParceiro, 100);
        remuneracaoProdutoParceiro = [SELECT Id,TipoRemuneracao__c,TipoRemuneracao__r.Name FROM RemuneracaoProdutoParceiro__c WHERE Id =: remuneracaoProdutoParceiro.Id];
        Account conta = [SELECT Id,Name FROM Account WHERE Papel__c = 'Corretor' LIMIT 1];

        DadosCorretor__c dadosCorretor = TestDataFactory.gerarDadosCorretor(conta);
        InformacaoBancaria__c informacaoBancaria = TestDataFactory.gerarInformacaoBancaria(conta);

        FavorecidoRemuneracao__c favorecidoRemuneracao = TestDataFactory.gerarFavorecidoRemuneracao(conta, 90.00, 'Corretor', true, remuneracaoProdutoParceiro, dadosCorretor, informacaoBancaria);
        FavorecidoRemuneracao__c favorecidoRemuneracao2 = TestDataFactory.gerarFavorecidoRemuneracao(conta, 20.00, 'Corretor', false, remuneracaoProdutoParceiro, dadosCorretor, informacaoBancaria);

        RetornoAcaoBotaoTO retorno = ParceiroBO.getInstance().ativarParceiro(parceiro.Id);

        System.assert( retorno.mensagens.contains('A somatória do percentual dos favorecidos da remuneração ' + remuneracaoProdutoParceiro.TipoRemuneracao__r.Name + ' é diferente de 100%') );

    }

    @IsTest
    static void testParceiroComRemuneracaoForaDosLimites(){

        Parceiro__c parceiro = [SELECT Id FROM Parceiro__c LIMIT 1];
        Product2 produtoComercial = [ SELECT Id, ProductCode, (SELECT Id, TipoRemuneracao__c, TipoRemuneracao__r.Id, TipoRemuneracao__r.Name, TipoRemuneracao__r.LimiteMinimo__c FROM RemuneracoesProduto__r) FROM Product2 WHERE RecordType.DeveloperName = 'ProdutoComercial' LIMIT 1 ];

        ProdutoParceiro__c produtoParceiro = TestDataFactory.gerarProdutoParceiro(parceiro, produtoComercial);

        RemuneracaoProdutoParceiro__c remuneracaoProdutoParceiro =
            TestDataFactory.gerarRemuneracaoProdutoParceiro(produtoComercial.RemuneracoesProduto__r[0].TipoRemuneracao__r, produtoParceiro, 1.0);
        remuneracaoProdutoParceiro = [SELECT Id,TipoRemuneracao__c,TipoRemuneracao__r.Name FROM RemuneracaoProdutoParceiro__c WHERE Id =: remuneracaoProdutoParceiro.Id];
        Account conta = [SELECT Id,Name FROM Account WHERE Papel__c = 'Corretor' LIMIT 1];

        DadosCorretor__c dadosCorretor = TestDataFactory.gerarDadosCorretor(conta);
        InformacaoBancaria__c informacaoBancaria = TestDataFactory.gerarInformacaoBancaria(conta);

        FavorecidoRemuneracao__c favorecidoRemuneracao = TestDataFactory.gerarFavorecidoRemuneracao(conta, 80.00, 'Corretor', true, remuneracaoProdutoParceiro, dadosCorretor, informacaoBancaria);
        FavorecidoRemuneracao__c favorecidoRemuneracao2 = TestDataFactory.gerarFavorecidoRemuneracao(conta, 20.00, 'Corretor', false, remuneracaoProdutoParceiro, dadosCorretor, informacaoBancaria);

        RetornoAcaoBotaoTO retorno = ParceiroBO.getInstance().ativarParceiro(parceiro.Id);

        System.assert( retorno.mensagens.contains('Percentual da remuneração ' + remuneracaoProdutoParceiro.TipoRemuneracao__r.Name + ' fora dos limites') );

    }

    @IsTest
    static void TestParceiroAtivado (){
        Parceiro__c parceiro = [SELECT Id FROM Parceiro__c LIMIT 1];
        Product2 produtoComercial = [ SELECT Id, ProductCode, (SELECT Id, TipoRemuneracao__c, TipoRemuneracao__r.Id, TipoRemuneracao__r.Name, TipoRemuneracao__r.LimiteMinimo__c FROM RemuneracoesProduto__r) FROM Product2 WHERE RecordType.DeveloperName = 'ProdutoComercial' LIMIT 1 ];

        ProdutoParceiro__c produtoParceiro = TestDataFactory.gerarProdutoParceiro(parceiro, produtoComercial);

        RemuneracaoProdutoParceiro__c remuneracaoProdutoParceiro =
            TestDataFactory.gerarRemuneracaoProdutoParceiro(produtoComercial.RemuneracoesProduto__r[0].TipoRemuneracao__r, produtoParceiro, 10.0);
        remuneracaoProdutoParceiro = [SELECT Id,TipoRemuneracao__c,TipoRemuneracao__r.Name FROM RemuneracaoProdutoParceiro__c WHERE Id =: remuneracaoProdutoParceiro.Id];
        Account conta = [SELECT Id,Name FROM Account WHERE Papel__c = 'Corretor' LIMIT 1];

        DadosCorretor__c dadosCorretor = TestDataFactory.gerarDadosCorretor(conta);
        InformacaoBancaria__c informacaoBancaria = TestDataFactory.gerarInformacaoBancaria(conta);

        FavorecidoRemuneracao__c favorecidoRemuneracao = TestDataFactory.gerarFavorecidoRemuneracao(conta, 80.00, 'Corretor', true, remuneracaoProdutoParceiro, dadosCorretor, informacaoBancaria);
        FavorecidoRemuneracao__c favorecidoRemuneracao2 = TestDataFactory.gerarFavorecidoRemuneracao(conta, 20.00, 'Corretor', false, remuneracaoProdutoParceiro, dadosCorretor, informacaoBancaria);

        Test.startTest();

        RetornoAcaoBotaoTO retorno = (RetornoAcaoBotaoTO)JSON.deserialize(BotaoAtivarParceiroController.ativarParceiro(parceiro.Id),RetornoAcaoBotaoTO.class);

        System.assert( retorno.mensagens.contains('Parceiro ativado com sucesso!') );
    }
}