workspace-sf/force-app/main/default/objects/DadosCorretor__c/DadosCorretor__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar dados dos corretores.</description>
    <label>Dados do corretor</label>
    <nameField>
        <label>Código do corretor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dados dos corretores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/Modalidade__c/Modalidade__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar as modalidades</description>
    <label>Modalidade</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Modalidades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/Modalidade__c/fields/RamoSeguro__c.field-meta.xml
<CustomField>
    <fullName>RamoSeguro__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ramo de seguro</label>
    <referenceTo>RamoSeguro__c</referenceTo>
    <relationshipLabel>Modalidades</relationshipLabel>
    <relationshipName>Modalidades</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/RamoSeguro__c/RamoSeguro__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar o cadastro dos ramos de seguro</description>
    <label>Ramo de seguro</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ramos de seguro</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/RamoSeguro__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ativo</fullName>
            </value>
            <value>
                <fullName>Inativo</fullName>
            </value>
            <value>
                <fullName>Em análise</fullName>
                <default>true</default>
                <label>Em análise</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/classes/PropostaVencimentoScheduleTest.cls
// PLV-4337 - INICIO
/*
*  @author: Squad Avanxo 
*  @description: Schedule Batch para vencer as propostas - CLASSE DE TESTE
*/
@isTest
public class PropostaVencimentoScheduleTest {
 
    @TestSetup
    static void setup(){
        TestDataFactory.gerarDadosSetup();
    }

    @isTest
    public static void validarSchedule(){
        Account conta = ( Account ) new AccountFactory.PessoaFisica().createRecord();
        RamoSeguro__c ramoSeguro = ( RamoSeguro__c ) new RamoSeguroFactory( conta ).createRecord();
        DadosCorretor__c dadosCorretor = ( DadosCorretor__c ) new DadosCorretorFactory( conta ).createRecord();
        Modalidade__c modalidade = ( Modalidade__c ) new ModalidadeFactory( ramoSeguro ).createRecord();

        Product2 produtoTecnico = ( Product2 ) new ProdutoFactory.ProdutoTecnico().createRecord();
        produtoTecnico.Status__c = 'Em ativação';
        produtoTecnico.NumeroSusep__c = '123';
        produtoTecnico.VersaoRenovacao__c = 'Versão atual';
        update produtoTecnico;
        produtoTecnico.Status__c = 'Ativo';
        update produtoTecnico;
        Product2 produtoComercial = ( Product2 ) new ProdutoFactory.ProdutoComercial( produtoTecnico ).createRecord();

        Opportunity orcamento = ( Opportunity ) new OrcamentoFactory.VidaIndividual( produtoComercial, conta ).createRecord();

        Quote proposta = ( Quote ) new PropostaFactory( produtoComercial, ramoSeguro, conta, dadosCorretor, orcamento, modalidade).createRecord();
        proposta.DataVencimento__c = System.today() - 1;
        update proposta;
        
        System.debug( 'PropostaVencimentoScheduleTest - Data de Vencimento: ' + proposta.DataVencimento__c );
        
        Test.startTest();
        
        PropostaVencimentoSchedule classe = new PropostaVencimentoSchedule();
        
        Test.stopTest();
    }
}
// PLV-4337 - FIM