workspace-sf/force-app/main/default/objects/DadosCorretor__c/DadosCorretor__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar dados dos corretores.</description>
    <label>Dados do corretor</label>
    <nameField>
        <label>Código do corretor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dados dos corretores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/DadosCorretor__c/fields/CodigoSucursalDestinoCheque__c.field-meta.xml
<CustomField>
    <fullName>CodigoSucursalDestinoCheque__c</fullName>
    <label>Código sucursal destino cheque</label>
    <type>TextArea</type>
</CustomField>

workspace-sf/force-app/main/default/objects/DadosCorretor__c/fields/NomeCorretor__c.field-meta.xml
<CustomField>
    <fullName>NomeCorretor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nome do corretor</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>CodigosCorretores</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/DadosCorretor__c/fields/SucursalDestinoCheque__c.field-meta.xml
<CustomField>
    <fullName>SucursalDestinoCheque__c</fullName>
    <label>Sucursal destino cheque</label>
    <type>TextArea</type>
</CustomField>

workspace-sf/force-app/main/default/objects/DadosCorretor__c/fields/SucursalVinculo__c.field-meta.xml
<CustomField>
    <fullName>SucursalVinculo__c</fullName>
    <label>Sucursal de vínculo</label>
    <type>TextArea</type>
</CustomField>

workspace-sf/force-app/main/default/objects/DadosCorretor__c/fields/SusepOficialCorretor__c.field-meta.xml
<CustomField>
    <fullName>SusepOficialCorretor__c</fullName>
    <label>Susep Oficial</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/DadosCorretor__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Principal</fullName>
            </value>
            <value>
                <fullName>Produção</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/classes/DadosCorretorDAO.cls
public with sharing class DadosCorretorDAO 
{
	private static final DadosCorretorDAO instancia = new DadosCorretorDAO();
    private DadosCorretorDAO(){}
    public static DadosCorretorDAO getInstance(){ return instancia; }

	public List<DadosCorretor__c> buscarCorretorPorSusep (Set<String> setSuseps)
	{
		return 
		[
			Select 
				Id, 
				Name,
				CodigoSucursalDestinoCheque__c,
				NomeCorretor__c,
				SucursalVinculo__c,
				SucursalDestinoCheque__c,
				Tipo__c
				, SusepOficialCorretor__c //PLV-5235 - INICIO/FIM
			From 
				DadosCorretor__c 
			Where 
				Name IN: setSuseps
		];
	}
	
	//INICIO | PLV-2179-27- remover duplicidade
	public List<DadosCorretor__c> listarDadosCorretorPorCodigo(Set<String> setNames)
	{
		return 
		[
			SELECT 
				Name, 
				CodigoSucursalDestinoCheque__c, 
				NomeCorretor__c, 
				SucursalVinculo__c, 
				SucursalDestinoCheque__c, 
				Tipo__c, 
				CreatedDate 
			FROM 
				DadosCorretor__c 
			WHERE 
				Name IN: setNames
            ORDER BY 
				CreatedDate DESC
		];
	}
	//FIM | PLV-2179-27- remover duplicidade
}