workspace-sf/force-app/main/default/objects/DadosCorretor__c/DadosCorretor__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar dados dos corretores.</description>
    <label>Dados do corretor</label>
    <nameField>
        <label>Código do corretor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dados dos corretores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/DadosCorretor__c/fields/NomeCorretor__c.field-meta.xml
<CustomField>
    <fullName>NomeCorretor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nome do corretor</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>CodigosCorretores</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/DadosCorretor__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Principal</fullName>
            </value>
            <value>
                <fullName>Produção</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/FavorecidoRemuneracaoProposta__c/FavorecidoRemuneracaoProposta__c.object-meta.xml
<CustomObject>
    <label>Favorecido da Remuneração da Proposta</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Favorecido da Proposta</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Favorecidos da Remuneração da Proposta</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/FavorecidoRemuneracaoProposta__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Favorecidos_da_Proposta</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/FavorecidoRemuneracaoProposta__c/fields/DadosCorretor__c.field-meta.xml
<CustomField>
    <fullName>DadosCorretor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dados do corretor</label>
    <referenceTo>DadosCorretor__c</referenceTo>
    <relationshipLabel>Favorecidos da Remuneração da Proposta</relationshipLabel>
    <relationshipName>FavorecidosRemuneracaoProposta</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/FavorecidoRemuneracaoProposta__c/fields/Papel__c.field-meta.xml
<CustomField>
    <fullName>Papel__c</fullName>
    <label>Papel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Corretor</fullName>
            </value>
            <value>
                <fullName>Agenciador</fullName>
            </value>
            <value>
                <fullName>Parceiro</fullName>
            </value>
            <value>
                <fullName>Prestador</fullName>
            </value>
            <value>
                <fullName>RepresentanteSeguros</fullName>
                <label>Representante de Seguros</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/FavorecidoRemuneracaoProposta__c/fields/RemuneracaoProposta__c.field-meta.xml
<CustomField>
    <fullName>RemuneracaoProposta__c</fullName>
    <label>Remuneração da proposta</label>
    <referenceTo>RemuneracaoProposta__c</referenceTo>
    <relationshipLabel>Favorecidos da Remuneração da Proposta</relationshipLabel>
    <relationshipName>FavorecidosRemuneracaodaProposta</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/FavorecidoRemuneracaoProposta__c/fields/Susep__c.field-meta.xml
<CustomField>
    <fullName>Susep__c</fullName>
    <label>Susep</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/RemuneracaoProposta__c/RemuneracaoProposta__c.object-meta.xml
<CustomObject>
    <description>Objeto de relacionamento entre a proposta e o tipo de remuneração.</description>
    <label>Remuneração da proposta</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Remunerações da proposta</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/RemuneracaoProposta__c/fields/Papel__c.field-meta.xml
<CustomField>
    <fullName>Papel__c</fullName>
    <label>Papel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agenciador</fullName>
            </value>
            <value>
                <fullName>Corretor</fullName>
            </value>
            <value>
                <fullName>Parceiro</fullName>
            </value>
            <value>
                <fullName>Prestador</fullName>
            </value>
            <value>
                <fullName>Representante de Seguros</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/RemuneracaoProposta__c/fields/Participacao__c.field-meta.xml
<CustomField>
    <fullName>Participacao__c</fullName>
    <label>Participação</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

workspace-sf/force-app/main/default/objects/RemuneracaoProposta__c/fields/Proposta__c.field-meta.xml
<CustomField>
    <fullName>Proposta__c</fullName>
    <label>Proposta</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Remunerações da proposta</relationshipLabel>
    <relationshipName>RemuneracoesProposta</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/RemuneracaoProposta__c/fields/TipoRemuneracao__c.field-meta.xml
<CustomField>
    <fullName>TipoRemuneracao__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tipo de remuneração</label>
    <referenceTo>TipoRemuneracao__c</referenceTo>
    <relationshipLabel>Remunerações da proposta</relationshipLabel>
    <relationshipName>RemuneracoesProposta</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/TransferenciaCorretagem__c/TransferenciaCorretagem__c.object-meta.xml
<CustomObject>
    <description>Objeto que armazernará os dados relativos às transferências de corretagem.</description>
    <label>Transferência de Corretagem</label>
    <nameField>
        <displayFormat>TC{000000}</displayFormat>
        <label>Código da Transferência</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transferências de Corretagens</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/TransferenciaCorretagem__c/fields/ContratoTransferido__c.field-meta.xml
<CustomField>
    <fullName>ContratoTransferido__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contrato cuja susep será transferida.</description>
    <inlineHelpText>Escolha o Contrato para a transferência de susep (deixe em branco caso tenha marcado o campo Transferir Carteira)</inlineHelpText>
    <label>Contrato</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contract.CodigoCorretor__c</field>
            <operation>equals</operation>
            <valueField>$Source.SusepOriginal__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Transferências de Corretagens</relationshipLabel>
    <relationshipName>DadosContratoTransferido</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/TransferenciaCorretagem__c/fields/PercPriCoCorretor__c.field-meta.xml
<CustomField>
    <fullName>PercPriCoCorretor__c</fullName>
    <description>Percentual para o primeiro co-corretor</description>
    <inlineHelpText>Participação Susep Co-corretagem</inlineHelpText>
    <label>Participação (%)</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

workspace-sf/force-app/main/default/objects/TransferenciaCorretagem__c/fields/PercQuaCoCorretor__c.field-meta.xml
<CustomField>
    <fullName>PercQuaCoCorretor__c</fullName>
    <description>Percentual para o quarto co-corretor</description>
    <inlineHelpText>Participação Susep Co-corretagem</inlineHelpText>
    <label>Participação (%)</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

workspace-sf/force-app/main/default/objects/TransferenciaCorretagem__c/fields/PercQuiCoCorretor__c.field-meta.xml
<CustomField>
    <fullName>PercQuiCoCorretor__c</fullName>
    <description>Percentual para o quinto co-corretor</description>
    <inlineHelpText>Participação Susep Co-corretagem</inlineHelpText>
    <label>Participação (%)</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

workspace-sf/force-app/main/default/objects/TransferenciaCorretagem__c/fields/PercSegCoCorretor__c.field-meta.xml
<CustomField>
    <fullName>PercSegCoCorretor__c</fullName>
    <description>Percentual para o segundo co-corretor</description>
    <inlineHelpText>Participação Susep Co-corretagem</inlineHelpText>
    <label>Participação (%)</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

workspace-sf/force-app/main/default/objects/TransferenciaCorretagem__c/fields/PercSusepLider__c.field-meta.xml
<CustomField>
    <fullName>PercSusepLider__c</fullName>
    <description>Percentual para o corretor (Líder)</description>
    <inlineHelpText>Participação Susep Líder</inlineHelpText>
    <label>Participação (%)</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

workspace-sf/force-app/main/default/objects/TransferenciaCorretagem__c/fields/PercTerCoCorretor__c.field-meta.xml
<CustomField>
    <fullName>PercTerCoCorretor__c</fullName>
    <description>Percentual para o terceiro co-corretor</description>
    <inlineHelpText>Participação Susep Co-corretagem</inlineHelpText>
    <label>Participação (%)</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

workspace-sf/force-app/main/default/objects/TransferenciaCorretagem__c/fields/SusepAtual__c.field-meta.xml
<CustomField>
    <fullName>SusepAtual__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Susep para a qual o contrato será transferido.</description>
    <inlineHelpText>Escolha a nova susep</inlineHelpText>
    <label>Transferir para corretor líder</label>
    <referenceTo>DadosCorretor__c</referenceTo>
    <relationshipName>DadosCorretorAtual</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/TransferenciaCorretagem__c/fields/SusepOriginal__c.field-meta.xml
<CustomField>
    <fullName>SusepOriginal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Armazena a susep original do contrato.</description>
    <inlineHelpText>Corretor atual do contrato</inlineHelpText>
    <label>Código do corretor atual</label>
    <referenceTo>DadosCorretor__c</referenceTo>
    <relationshipLabel>Transferências de Corretagens</relationshipLabel>
    <relationshipName>DadosCorretorOriginal</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/TransferenciaCorretagem__c/fields/SusepPriCoCorretagem__c.field-meta.xml
<CustomField>
    <fullName>SusepPriCoCorretagem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Primeira susep de Co-corretagem</description>
    <inlineHelpText>Primeiro Co-corretor</inlineHelpText>
    <label>Transferir co-corretagem para</label>
    <referenceTo>DadosCorretor__c</referenceTo>
    <relationshipName>Transferencias_de_Corretagens</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/TransferenciaCorretagem__c/fields/SusepQuaCoCorretagem__c.field-meta.xml
<CustomField>
    <fullName>SusepQuaCoCorretagem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Quarta susep de Co-corretagem</description>
    <inlineHelpText>Quarto Co-corretor</inlineHelpText>
    <label>Transferir co-corretagem para</label>
    <referenceTo>DadosCorretor__c</referenceTo>
    <relationshipName>Transferencias_de_Corretagens3</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/TransferenciaCorretagem__c/fields/SusepQuiCoCorretagem__c.field-meta.xml
<CustomField>
    <fullName>SusepQuiCoCorretagem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Quinta susep de Co-corretagem</description>
    <inlineHelpText>Quinto Co-corretor</inlineHelpText>
    <label>Transferir co-corretagem para</label>
    <referenceTo>DadosCorretor__c</referenceTo>
    <relationshipName>Transferencias_de_Corretagens4</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/TransferenciaCorretagem__c/fields/SusepSegCoCorretagem__c.field-meta.xml
<CustomField>
    <fullName>SusepSegCoCorretagem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Segunda susep de Co-corretagem</description>
    <inlineHelpText>Segundo Co-corretor</inlineHelpText>
    <label>Transferir co-corretagem para</label>
    <referenceTo>DadosCorretor__c</referenceTo>
    <relationshipName>Transferencias_de_Corretagens1</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/TransferenciaCorretagem__c/fields/SusepTerCoCorretagem__c.field-meta.xml
<CustomField>
    <fullName>SusepTerCoCorretagem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Terceira susep de Co-corretagem</description>
    <inlineHelpText>Terceiro Co-corretor</inlineHelpText>
    <label>Transferir co-corretagem para</label>
    <referenceTo>DadosCorretor__c</referenceTo>
    <relationshipName>Transferencias_de_Corretagens2</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/TransferenciaCorretagem__c/fields/TransferirCarteira__c.field-meta.xml
<CustomField>
    <fullName>TransferirCarteira__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indica se serão tranferidos todos os contratos para nova susep ou apenas um único.</description>
    <inlineHelpText>Marque para transferir todos os contratos</inlineHelpText>
    <label>Transferir Carteira</label>
    <type>Checkbox</type>
</CustomField>

workspace-sf/force-app/main/default/classes/AtualizaPropOrcamentoCtr.cls
/**
 * @description       : Métodos usados para realizar a lógica do BatchAtualizaPropostaOrcamento - RVI-265
 * @author            : Kevin Vogado e Matheus Meneses (GLOBANT)
 * @last modified on  : 24-08-2023
 * @last modified by  : Bruno Filipe
**/

public with sharing class AtualizaPropOrcamentoCtr {

    public static Map<String, String> camposToPut = new Map<String, String>{
        'PercSusepLider__c'    => 'SusepAtual__c',
        'PercPriCoCorretor__c' => 'SusepPriCoCorretagem__c',
        'PercSegCoCorretor__c' => 'SusepSegCoCorretagem__c',
        'PercTerCoCorretor__c' => 'SusepTerCoCorretagem__c',
        'PercQuaCoCorretor__c' => 'SusepQuaCoCorretagem__c',
        'PercQuiCoCorretor__c' => 'SusepQuiCoCorretagem__c'
    };
    
    public static List<String> camposSusep = new List<String>{
        'SusepAtual__c', 
        'SusepPriCoCorretagem__c', 
        'SusepSegCoCorretagem__c', 
        'SusepTerCoCorretagem__c', 
        'SusepQuaCoCorretagem__c', 
        'SusepQuiCoCorretagem__c'
    };

    public static void criarFavorecidoProposta(TransferenciaCorretagem__c tc, List<RemuneracaoProposta__c> remuneracoes, Map<String, Decimal> campoTransferenciaCorretagemMap, List<FavorecidoRemuneracaoProposta__c> favRelatedToProposta ) {
        Map<String, Object> camposPopulados = tc.getPopulatedFieldsAsMap();

        for(String key : camposPopulados.keySet()){
            if(camposToPut.containsKey(key)){
                campoTransferenciaCorretagemMap.put(camposToPut.get(key), (Decimal) camposPopulados.get(key));
            }
        }

        for(String campo : camposSusep){

            if(camposPopulados.containsKey(campo)){

                DadosCorretor__c dados = (DadosCorretor__c) camposPopulados.get(campo.replace('__c', '__r'));

                Boolean isLider = campo == 'SusepAtual__c' ? true : false; 

                FavorecidoRemuneracaoProposta__c favorecido = new FavorecidoRemuneracaoProposta__c(
                    DadosCorretor__c = dados.Id,
                    Susep__c = dados.Name,
                    Papel__c = 'Corretor',
                    Participacao__c = campoTransferenciaCorretagemMap.get(campo),
                    Conta__c = dados.NomeCorretor__c,
                    CorretorLider__c = isLider
                );

                for (RemuneracaoProposta__c remuneracao : remuneracoes) {
                    favorecido.RemuneracaoProposta__c = remuneracao.Id;
                    break;
                }
       
                favRelatedToProposta.add(favorecido);
            }
        }
    }

    public static Map<Id, List<RemuneracaoProposta__c>> getRemuneracaoMappedByProposta(List<FavorecidoRemuneracaoProposta__c> favRelatedToProposta){

        Map<Id, List<RemuneracaoProposta__c>> remuneracaoMappedByProposta = new Map<Id, List<RemuneracaoProposta__c>>();

        for(FavorecidoRemuneracaoProposta__c fv : favRelatedToProposta){
            
            remuneracaoMappedByProposta.put(
                fv.RemuneracaoProposta__r.Proposta__c,
                new List<RemuneracaoProposta__c>()
            );
    
            remuneracaoMappedByProposta.get(fv.RemuneracaoProposta__r.Proposta__c).add(fv.RemuneracaoProposta__r);
        }

        return remuneracaoMappedByProposta;
    }

    public static Map<Id, List<TransferenciaCorretagem__c>> getTransferenciaIndexedByContract(List<TransferenciaCorretagem__c> transferencias){

        Map<Id, List<TransferenciaCorretagem__c>> transferenciaIndexedByContract = new Map<Id, List<TransferenciaCorretagem__c>>();

        for (TransferenciaCorretagem__c tc : transferencias) {
            if(tc != null){
                if (tc.ContratoTransferido__c != null) { 
                    if (!transferenciaIndexedByContract.containsKey(tc.ContratoTransferido__c)) {
                        transferenciaIndexedByContract.put(tc.ContratoTransferido__c, new List<TransferenciaCorretagem__c>());
                    }
                    transferenciaIndexedByContract.get(tc.ContratoTransferido__c).add(tc);
                }
            }
        }
    
        return transferenciaIndexedByContract;
    }   

    public static Map<Id, List<FavorecidoRemuneracaoProposta__c>> getFavorecidosMappedByProposta (Set<Id> idsPropostas){
        Map<Id, List<FavorecidoRemuneracaoProposta__c>> favorecidosMappedByProposta = new Map<Id, List<FavorecidoRemuneracaoProposta__c>>();

        for(FavorecidoRemuneracaoProposta__c favorecido : [SELECT Id, Name, Susep__c, RemuneracaoProposta__c, RemuneracaoProposta__r.Name, Conta__r.Name, RemuneracaoProposta__r.Proposta__c, RemuneracaoProposta__r.Proposta__r.Opportunity.CodigoCorretor__r.Name
                FROM FavorecidoRemuneracaoProposta__c
                WHERE RemuneracaoProposta__r.Proposta__c IN : idsPropostas
                AND RemuneracaoProposta__r.TipoRemuneracao__r.Name = 'CORRETAGEM'
            ])
        {
            System.debug('Entrou no for do getFavorecidosMappedByProposta');
            Id propostaId = favorecido.RemuneracaoProposta__r.Proposta__c;

            // if(!favorecidosMappedByProposta.containsKey(propostaId)) {
            //     favorecidosMappedByProposta.put(propostaId, new List<FavorecidoRemuneracaoProposta__c>());
            // }
            
            if(!favorecidosMappedByProposta.containsKey(propostaId) && favorecidosMappedByProposta != null) {
                favorecidosMappedByProposta.put(propostaId, new List<FavorecidoRemuneracaoProposta__c>());
            }

            // favorecidosMappedByProposta.get(propostaId).add(favorecido);
            System.debug('getFavorecidosMappedByProposta favorecido.Susep__c '+ favorecido.Susep__c);
            System.debug('getFavorecidosMappedByProposta favorecido.RemuneracaoProposta__r.Proposta__r.Opportunity.CodigoCorretor__r.Name ' +favorecido.RemuneracaoProposta__r.Proposta__r.Opportunity.CodigoCorretor__r.Name);
            if(favorecido.Susep__c == favorecido.RemuneracaoProposta__r.Proposta__r.Opportunity.CodigoCorretor__r.Name){
                favorecidosMappedByProposta.get(propostaId).add(favorecido); 
                System.debug('favorecido.Susep__c');
            }

        }
        return favorecidosMappedByProposta;
    }
    
    public static Map<String, List<TransferenciaCorretagem__c>> getTransfIndexedBySusepName(List<TransferenciaCorretagem__c> transfCarteira){

        Map<String, List<TransferenciaCorretagem__c>> transfIndexedByContract =  new Map<String, List<TransferenciaCorretagem__c>>();

        for(TransferenciaCorretagem__c tc : transfCarteira){
            if(tc.TransferirCarteira__c == true){

                if(!transfIndexedByContract.containsKey(tc.SusepOriginal__r.Name)){
                    transfIndexedByContract.put(tc.SusepOriginal__r.Name, new List<TransferenciaCorretagem__c>());
                }

                transfIndexedByContract.get(tc.SusepOriginal__r.Name).add(tc);
            }
        }

        return transfIndexedByContract;
    }

    public static void removeContentDocumentLink(Set<Id> idsSobject){

        if(idsSobject == null || idsSobject.isEmpty()){
            return;
        }

        String query = 'SELECT Id, LinkedEntityId, ContentDocumentId, IsDeleted FROM ContentDocumentLink WHERE LinkedEntityId IN (';

        for(Id id : idsSobject){
            query += '\'' + String.escapeSingleQuotes(id) + '\',';
            System.debug('query > ' + query);
        }
        
        query = query.removeEnd(',') + ')';
        System.debug('query >> ' + query);

        List<ContentDocumentLink> contentDocLinks = Database.query(query);
        System.debug('contentDocLinks >>' + contentDocLinks);
        
        if(!contentDocLinks.isEmpty()){
            delete contentDocLinks;
        }                                                                        
    }

    public static void atualizarDescricaoOportunidade(TransferenciaCorretagem__c tc, Opportunity orcamento ){
        Map<String, Object> camposPopulados = tc.getPopulatedFieldsAsMap();

        for(String campo : camposSusep) {
            if(camposPopulados.containsKey(campo)){
                DadosCorretor__c dados = (DadosCorretor__c) camposPopulados.get(campo.replace('__c', '__r'));
                orcamento.CodigoCorretor__c = dados.Id;
            }
            break;    
        }
    }

    public void insertFavRemuneracaoProposta(List<TransferenciaCorretagem__c> transferencias){

        Set<Id> oppyIds = new Set<Id>();
        Set<Id> quoteIds = new Set<Id>();
        Set<Id> quoteIdCorreta = new Set<Id>();
        Set<Id> contratoRenovado = new Set<Id>();
        Set<Id> contratosTransfCarteira= new Set<Id>();

        List<String> suseps = new List<String>();
        List<Opportunity> orcamentoToUpdateCarteira = new List<Opportunity>();
        List<Opportunity> orcamentoToUpdateIndividual = new List<Opportunity>();
        List<FavorecidoRemuneracaoProposta__c> inserirFavorecidos = new list<FavorecidoRemuneracaoProposta__c>();
        List<FavorecidoRemuneracaoProposta__c> lstfavDeleteIndividual = new list<FavorecidoRemuneracaoProposta__c>();

        Map<Id, Opportunity> mapUpdOppCarteira = new Map<Id, Opportunity>();
        Map<Id, Opportunity> mapUpdOppIndividual = new Map<Id, Opportunity>();
        Map<Id, Opportunity> orcamentoIndexByProp = new Map<Id, Opportunity>();
        Map<String, Decimal> campoTransferenciaCorretagemMap = new Map<String, Decimal>();
        Map<Id, FavorecidoRemuneracaoProposta__c> mapDeleteFavorecidoRemProp = new Map<Id, FavorecidoRemuneracaoProposta__c>();

        List<Quote> propostas = [SELECT Id, CodigoCorretor__c, CodigoCorretor__r.Name, ContratoRenovado__c, Status, Tipo__c, OpportunityId, Opportunity.CodigoCorretor__c, Opportunity.CodigoCorretor__r.Name, Opportunity.ContratoRenovado__c,
                                (SELECT Id, Name FROM RemuneracoesProposta__r)
                                  FROM Quote
                                  WHERE Status = 'Em análise' 
                                  AND Tipo__c = 'Renovacao'
                                  AND LiberarContratoRenovacao__c = true];

        if(!propostas.isEmpty()){
            for(Quote qt : propostas){
                quoteIds.add(qt.Id);

                oppyIds.add(qt.OpportunityId);
                
                contratoRenovado.add(qt.ContratoRenovado__c);
            }
        }
    
        List<Contract> lstContratos = [SELECT Id, Proposta__r.Tipo__c, Proposta__r.ContratoRenovado__c, Proposta__r.Name, CodigoCorretor__r.Name, (SELECT Id, ContratoTransferido__c FROM DadosContratoTransferido__r) 
        FROM Contract WHERE Id IN :contratoRenovado];
        
        id contractId;
        Id contratoTransferidoId;
        for(Contract contract : lstContratos){
            contractId = contract.Id;
            
            List<TransferenciaCorretagem__c> TransferenciaCorretagem = contract.DadosContratoTransferido__r;
            for (TransferenciaCorretagem__c dadosContratoTransferido : TransferenciaCorretagem) {
                contratoTransferidoId = dadosContratoTransferido.ContratoTransferido__c;
                System.debug('Contrato Transferido => ' + contratoTransferidoId);
            } 
            if(contractId != contratoTransferidoId){    
                contratosTransfCarteira.add(contract.Id);
                System.debug('Contratos => ' + contratosTransfCarteira);
            }
        }

        Map<Id, Opportunity> lstopprtunityListOpp = new Map<Id, Opportunity>(
            [SELECT Id, CodigoCorretor__c, CodigoCorretor__r.Name 
            FROM Opportunity 
            WHERE Id IN :oppyIds AND StageName = 'Disponível para contratação']
        );

        for(Quote prop : propostas){
           for(Id orcamentoId : lstopprtunityListOpp.keySet()) {
                if(prop.OpportunityId == orcamentoId){
                    orcamentoIndexByProp.put(prop.Id, lstopprtunityListOpp.get(orcamentoId));
                }
           }
        }

        System.debug('Transferências => '+ transferencias);
        Map<String, List<TransferenciaCorretagem__c>> transfCarteiraBySusepName = getTransfIndexedBySusepName(transferencias);

        Map<Id, List<TransferenciaCorretagem__c>> transfIndexByContract = getTransferenciaIndexedByContract(transferencias);

        Map<Id, List<FavorecidoRemuneracaoProposta__c>> favorecidosMappedByProposta = getFavorecidosMappedByProposta(quoteIds);
        System.debug('favorecidosMappedByProposta Danilo '+favorecidosMappedByProposta);
        System.debug('propostas Danilo '+propostas);
        for(Quote qt : propostas){

            List<FavorecidoRemuneracaoProposta__c> favRelatedToProposta = favorecidosMappedByProposta.get(qt.Id);
                        
            Map<Id, List<RemuneracaoProposta__c>> remuneracaoMappedByProposta = getRemuneracaoMappedByProposta(favRelatedToProposta);
                        
            List<RemuneracaoProposta__c> remuneracoes = remuneracaoMappedByProposta.get(qt.Id);
            System.debug('favRelatedToProposta '+ favRelatedToProposta);
            for(FavorecidoRemuneracaoProposta__c frc : favRelatedToProposta){
                if(frc.Susep__c != null){
                    suseps.add(frc.Susep__c);
                }
            }
            
            quoteIdCorreta.add(qt.Id);
            
            if(!transfIndexByContract.isEmpty() && transfIndexByContract.containsKey(qt.ContratoRenovado__c)){

                List<TransferenciaCorretagem__c> transf = transfIndexByContract.get(qt.ContratoRenovado__c);
                System.debug('suseps >>'+ suseps);
                System.debug('transf >>'+ transf);
                for(TransferenciaCorretagem__c tc : transf){
                    if(suseps.contains(tc.CodCor__c)){
                        System.debug('Contrato Renovado - Individual => '+qt.ContratoRenovado__c);

                        lstfavDeleteIndividual.addAll(favRelatedToProposta);
                        favRelatedToProposta.clear();  
                        
                        criarFavorecidoProposta(tc, remuneracoes, campoTransferenciaCorretagemMap, favRelatedToProposta);   
                        System.debug('Cria Remunerações - Individual => ' + remuneracoes + 'Cria Favorecidos - Individual => '+ favRelatedToProposta);

                        inserirFavorecidos.addAll(favRelatedToProposta);
                        System.debug('Add Favorecidos - Individual => ' + inserirFavorecidos);
                        
                        Opportunity orcamento = orcamentoIndexByProp.get(qt.Id);
                        if(orcamento != null){
                            atualizarDescricaoOportunidade(tc, orcamento); 
                            orcamentoToUpdateIndividual.add(orcamento);
                            System.debug('Add Orcamento - Individual => ' + orcamentoToUpdateIndividual);
                        }
                    }
                }   
            }

            if(transfCarteiraBySusepName != null){
                
                for(String nameSusep: transfCarteiraBySusepName.keySet()){

                    if(suseps.contains(nameSusep)){

                        List<TransferenciaCorretagem__c> transfCarteira = transfCarteiraBySusepName.get(nameSusep);
                        
                        for(TransferenciaCorretagem__c tc : transfCarteira){
                            
                            System.debug('Contratos com Transferencia - Fora do If => '+contratosTransfCarteira);
                            if( tc.SusepOriginal__r.Name.equals(qt.CodigoCorretor__r.Name) &&  
                                tc.SusepOriginal__r.Name.equals(qt.Opportunity.CodigoCorretor__r.Name) &&
                                contratosTransfCarteira.contains(qt.ContratoRenovado__c) && 
                                contratosTransfCarteira.contains(qt.Opportunity.ContratoRenovado__c) &&
                                qt.ContratoRenovado__c != contratoTransferidoId) { 

                                System.debug('Transferência - Carteira => '+transfCarteira);
                                System.debug('Contrato Renovado - Carteira => '+qt.ContratoRenovado__c);
                                
                                lstfavDeleteIndividual.addAll(favRelatedToProposta);
                                favRelatedToProposta.clear();  
                                    
                                criarFavorecidoProposta(tc, remuneracoes, campoTransferenciaCorretagemMap, favRelatedToProposta);
                                System.debug('Cria Remunerações - Carteira => ' + remuneracoes + 'Cria Favorecido - Carteira => '+ favRelatedToProposta);
                                
                                inserirFavorecidos.addAll(favRelatedToProposta);
                                System.debug('favRelatedToProposta: ' + System.JSON.serializePretty(favRelatedToProposta)) ;
                                System.debug('Add Favorecido - Carteira => ' + inserirFavorecidos); 

                                Opportunity orcamento = orcamentoIndexByProp.get(qt.Id);
                                if(orcamento != null){
                                    atualizarDescricaoOportunidade(tc, orcamento);     
                                    orcamentoToUpdateCarteira.add(orcamento);
                                    System.debug('Add Orçamento - Carteira => ' + orcamentoToUpdateCarteira);
                                }
                            }    
                        }
                    }
                }
            }
            System.debug('JSON - Favorecido => ' + JSON.serialize(favRelatedToProposta));  
        }

        removeContentDocumentLink(quoteIdCorreta);

        mapUpdOppIndividual.putAll(orcamentoToUpdateIndividual);
        System.debug('Update Orçamento - Individual => ' + mapUpdOppIndividual.values());  
        
        if(mapUpdOppIndividual.size()>0) {
            update mapUpdOppIndividual.values();
        }

        mapUpdOppCarteira.putAll(orcamentoToUpdateCarteira);
        System.debug('Update Orçamento - Carteira => ' + mapUpdOppCarteira.values());  
        if(mapUpdOppCarteira.size()>0) {
            update mapUpdOppCarteira.values();
        }

        mapDeleteFavorecidoRemProp.putAll(lstfavDeleteIndividual);
        if(mapDeleteFavorecidoRemProp.size()>0){
            System.debug('Delete Favorecido - Original => ' + mapDeleteFavorecidoRemProp);  
            delete mapDeleteFavorecidoRemProp.values();
        }
        
        if(!inserirFavorecidos.isEmpty()){
            System.debug('Insert Favorecido => ' + inserirFavorecidos); 
            insert inserirFavorecidos;
        }

        QuoteBO.gerarPDFPropostaSync(new List<Id>(quoteIdCorreta));
        
        System.debug('New PDF - Proposta Renovação => ' + quoteIdCorreta);  
    }
}