workspace-sf/force-app/main/default/objects/DadosCorretor__c/DadosCorretor__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar dados dos corretores.</description>
    <label>Dados do corretor</label>
    <nameField>
        <label>Código do corretor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dados dos corretores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/FavorecidoRemuneracaoContrato__c/FavorecidoRemuneracaoContrato__c.object-meta.xml
<CustomObject>
    <label>Favorecido da Remuneração do Contrato</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Favorecido da Remuneração do Contrato</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Favorecidos da Remuneração do Contrato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/FavorecidoRemuneracaoContrato__c/fields/CorretorLider__c.field-meta.xml
<CustomField>
    <fullName>CorretorLider__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Corretor Lider</label>
    <type>Checkbox</type>
</CustomField>

workspace-sf/force-app/main/default/objects/FavorecidoRemuneracaoContrato__c/fields/DadosCorretor__c.field-meta.xml
<CustomField>
    <fullName>DadosCorretor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dados do corretor</label>
    <referenceTo>DadosCorretor__c</referenceTo>
    <relationshipLabel>Favorecidos da Remuneração do Contrato</relationshipLabel>
    <relationshipName>FavorecidosRemuneracaoContrato</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/FavorecidoRemuneracaoContrato__c/fields/RemuneracaoContrato__c.field-meta.xml
<CustomField>
    <fullName>RemuneracaoContrato__c</fullName>
    <label>Remuneração do contrato</label>
    <referenceTo>RemuneracaoContrato__c</referenceTo>
    <relationshipLabel>Favorecidos da Remuneração do Contrato</relationshipLabel>
    <relationshipName>FavorecidosContrato</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/RemuneracaoContrato__c/RemuneracaoContrato__c.object-meta.xml
<CustomObject>
    <description>Objeto de relacionamento entre o contrato e o tipo de remuneração.</description>
    <label>Remuneração do contrato</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Remunerações do contrato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/classes/FavorecidoRemuneracaoContratoFactory.cls
/**
 * @author AVX - Daniel Zampieri
 * @date 2019-03-06
 * @description FavorecidoRemuneracaoContrato__c Factory Class
 */
@isTest
public class FavorecidoRemuneracaoContratoFactory extends SObjectFactory{
	private static FavorecidoRemuneracaoContrato__c staticRecord;

	private static FavorecidoRemuneracaoContrato__c getRecordStatic(RemuneracaoContrato__c remCont, DadosCorretor__c dadosCorretor){

		if(staticRecord == null){
			staticRecord = new FavorecidoRemuneracaoContrato__c(
				DadosCorretor__c = dadosCorretor.Id,
            	RemuneracaoContrato__c = remCont.Id,
            	CorretorLider__c = true);
		}
		return staticRecord;
	}

	public FavorecidoRemuneracaoContratoFactory(){

		this(
			(RemuneracaoContrato__c) new RemuneracaoContratoFactory().createRecord(),
			(DadosCorretor__c) new DadosCorretorFactory().createRecord()
		);
	}

	public FavorecidoRemuneracaoContratoFactory(RemuneracaoContrato__c remCont, DadosCorretor__c dadosCorretor) {

		super(getRecordStatic(remCont, dadosCorretor));
	}
}