workspace-sf/force-app/main/default/objects/DadosCorretor__c/DadosCorretor__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar dados dos corretores.</description>
    <label>Dados do corretor</label>
    <nameField>
        <label>Código do corretor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dados dos corretores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/Modalidade__c/Modalidade__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar as modalidades</description>
    <label>Modalidade</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Modalidades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/Modalidade__c/fields/RamoSeguro__c.field-meta.xml
<CustomField>
    <fullName>RamoSeguro__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ramo de seguro</label>
    <referenceTo>RamoSeguro__c</referenceTo>
    <relationshipLabel>Modalidades</relationshipLabel>
    <relationshipName>Modalidades</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/ParametroVigencia__c/ParametroVigencia__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar os parâmetros de vigência de um produto</description>
    <label>Parâmetro de vigência</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parâmetros de vigência</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/ParametroVigencia__c/fields/ParametroVigencia__c.field-meta.xml
<CustomField>
    <fullName>ParametroVigencia__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parâmetro de vigência</label>
    <referenceTo>ParametroVigencia__c</referenceTo>
    <relationshipLabel>Parâmetros de vigência</relationshipLabel>
    <relationshipName>ParametrosVigencia</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/ParametroVigencia__c/fields/PeriodoMaximoInadimplencia__c.field-meta.xml
<CustomField>
    <fullName>PeriodoMaximoInadimplencia__c</fullName>
    <description>Campo para verificar em dias o Período máximo de inadimplência. Localizado na section &quot;Informações de periódico&quot;</description>
    <inlineHelpText>Em dias</inlineHelpText>
    <label>Período máximo de inadimplência</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

workspace-sf/force-app/main/default/objects/ParametroVigencia__c/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Parâmetros de vigência</relationshipLabel>
    <relationshipName>ParametrosVigencia</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/ParametroVigencia__c/fields/ValidadeOrcamento__c.field-meta.xml
<CustomField>
    <fullName>ValidadeOrcamento__c</fullName>
    <inlineHelpText>Leve em consideração o dia atual + a quantidade de dias informada nesse campo</inlineHelpText>
    <label>Validade do Orçamento</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

workspace-sf/force-app/main/default/objects/ParametroVigencia__c/recordTypes/ProdutoComercial.recordType-meta.xml
<RecordType>
    <fullName>ProdutoComercial</fullName>
    <active>true</active>
    <label>Produto comercial</label>
</RecordType>

workspace-sf/force-app/main/default/objects/ParametroVigencia__c/recordTypes/ProdutoTecnico.recordType-meta.xml
<RecordType>
    <fullName>ProdutoTecnico</fullName>
    <active>true</active>
    <label>Produto técnico</label>
</RecordType>

workspace-sf/force-app/main/default/objects/RamoSeguro__c/RamoSeguro__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar o cadastro dos ramos de seguro</description>
    <label>Ramo de seguro</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ramos de seguro</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/RamoSeguro__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ativo</fullName>
            </value>
            <value>
                <fullName>Inativo</fullName>
            </value>
            <value>
                <fullName>Em análise</fullName>
                <default>true</default>
                <label>Em análise</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/classes/PropostaDataVencimentoBatchTest.cls
// PLV-4337 - INICIO
/*
*  @author: Squad Avanxo 
*  @description: Batch para setar as datas de vencimento das propostas - CLASSE DE TESTE
*/
@isTest
public class PropostaDataVencimentoBatchTest {

    @TestSetup
    static void setup() {
        TestDataFactory.gerarDadosSetup();
    }

    @isTest
    public static void validarSchedule() {
        validarSchedule( System.today().addDays( 5 ) );
    }

    @isTest
    public static void validarSchedule2() {
        validarSchedule( null );
    }

    private static void validarSchedule( Date dataVencimento ) {
        Account conta = ( Account ) new AccountFactory.PessoaFisica().createRecord();
        RamoSeguro__c ramoSeguro = ( RamoSeguro__c ) new RamoSeguroFactory( conta ).createRecord();
        DadosCorretor__c dadosCorretor = ( DadosCorretor__c ) new DadosCorretorFactory( conta ).createRecord();
        Modalidade__c modalidade = ( Modalidade__c ) new ModalidadeFactory( ramoSeguro ).createRecord();

        Product2 produtoTecnico = ( Product2 ) new ProdutoFactory.ProdutoTecnico().createRecord();
        produtoTecnico.Status__c = 'Em ativação';
        produtoTecnico.NumeroSusep__c = '123';
        produtoTecnico.VersaoRenovacao__c = 'Versão atual';
        update produtoTecnico;
        produtoTecnico.Status__c = 'Ativo';
        update produtoTecnico;
        Product2 produtoComercial = ( Product2 ) new ProdutoFactory.ProdutoComercial( produtoTecnico ).createRecord();
        
        ParametroVigencia__c parametroVigencia = new ParametroVigencia__c();
        parametroVigencia.Produto__c = produtoComercial.Id;
        parametroVigencia.ValidadeOrcamento__c = 4;
        parametroVigencia.PeriodoMaximoInadimplencia__c = 30;
        insert parametroVigencia;

        Opportunity orcamento = ( Opportunity ) new OrcamentoFactory.VidaIndividual( produtoComercial, conta ).createRecord();
        orcamento.DataVencimento__c = dataVencimento;
        update orcamento;

        List< Quote > propostas = new List< Quote >();
        propostas.add( PropostaFactory.get( produtoComercial, ramoSeguro, conta, dadosCorretor, orcamento, modalidade, '18-00006768', '67708896000140' ) );
        propostas.add( PropostaFactory.get( produtoComercial, ramoSeguro, conta, dadosCorretor, orcamento, modalidade, '18-00006769', '67708896000141' ) );
        insert propostas;
        propostas[0].DataVencimento__c = null;
        propostas[1].DataVencimento__c = null;
        update propostas;
        
        Test.startTest();
        
        Database.executebatch( new PropostaDataVencimentoBatch(), 50 );
   
        Test.stopTest();
    }
}
// PLV-4337 - FIM