workspace-sf/force-app/main/default/objects/EmpresaPortoCAP__mdt/EmpresaPortoCAP__mdt.object-meta.xml
<CustomObject>
    <description>Empresa para consulta títulos PortoCAP</description>
    <label>Empresa PortoCAP</label>
    <pluralLabel>Empresas PortoCAP</pluralLabel>
</CustomObject>

workspace-sf/force-app/main/default/objects/EmpresaPortoCAP__mdt/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <label>CNPJ</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaContrato__c/GarantiaContrato__c.object-meta.xml
<CustomObject>
    <description>Objeto de relacionamento entre a garantia e o contrato.</description>
    <label>Garantia do contrato</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Garantias do contrato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/GarantiaContrato__c/fields/GarantiaProduto__c.field-meta.xml
<CustomField>
    <fullName>GarantiaProduto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Garantia do produto</label>
    <referenceTo>GarantiaProduto__c</referenceTo>
    <relationshipLabel>Garantias do contrato</relationshipLabel>
    <relationshipName>Garantias_do_contrato</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaContrato__c/fields/VersaoTitulo__c.field-meta.xml
<CustomField>
    <fullName>VersaoTitulo__c</fullName>
    <label>Versão do título</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaProduto__c/GarantiaProduto__c.object-meta.xml
<CustomObject>
    <description>Objeto de relacionamento entre os produtos e as garantias</description>
    <label>Garantia do produto</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Garantias do produto</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/GarantiaProduto__c/fields/CodigoPromocao__c.field-meta.xml
<CustomField>
    <fullName>CodigoPromocao__c</fullName>
    <description>Picklist obrigatória se o campo Sorteio no campo tipo de característica especial, for selecionado.</description>
    <inlineHelpText>Cod.167 - Vida 01 Sorteio
Cod.171 - Vida 02 Sorteios
Cod.168 - Vida 04 Sorteios
Cod.VI010 - Vida 1 Sorteio
Cod.VI011 – Vida 3 Sorteios</inlineHelpText>
    <label>Código da promoção</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>167</fullName>
            </value>
            <value>
                <fullName>168</fullName>
            </value>
            <value>
                <fullName>171</fullName>
            </value>
            <value>
                <fullName>VITST</fullName>
            </value>
            <value>
                <fullName>VI010</fullName>
            </value>
            <value>
                <fullName>VI011</fullName>
            </value>
            <value>
                <fullName>VI005</fullName>
                <isActive>false</isActive>
                <label>VI005</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaProduto__c/fields/GarantiaProduto__c.field-meta.xml
<CustomField>
    <fullName>GarantiaProduto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Garantia do produto</label>
    <referenceTo>GarantiaProduto__c</referenceTo>
    <relationshipLabel>Garantias do produto (Garantia do produto)</relationshipLabel>
    <relationshipName>GarantiasProdutoTecnico</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/classes/GarantiaContratoFacade.cls
/**
 * GarnatiaContrato Facade
 *
 **/
public class GarantiaContratoFacade {

    private static final GarantiaContratoFacade classInstance;

    static {
        classInstance = new GarantiaContratoFacade();
    }

    private GarantiaContratoFacade() {}

    public static GarantiaContratoFacade getInstance() {
        return classInstance;
    }

    public void consultarTituloPortoCap() {
    	System.debug('Inicio');

        try {

            Set<String> lstPromocoes = new Set<String>();

            // processa dados por código de promoção
            for(AggregateResult groupResultPromocao : GarantiaProdutoDAO.getInstance().buscarGarantiasProdutoPorProdutoCapByGroup())
            {
                System.debug('Montando parametro: ' + String.valueOf(groupResultPromocao.get('CodigoPromocao__c')));

                lstPromocoes.add(String.valueOf(groupResultPromocao.get('CodigoPromocao__c')));
            }

            montarParamtros(lstPromocoes);

        }
        catch(Exception e) {
            System.debug(e.getLineNumber() + ': ' + e.getMessage());
            throw new GarantiaContratoException(e.getLineNumber() + ': ' + e);
        }

        return;
    }

    private void montarParamtros(Set<String> lstPromocoes)
    {
        Map<String, dadosEnvioTO> mapParametros = new Map<String, dadosEnvioTO>();

        //--- monta dados de parametros por promoção
        for(GarantiaProduto__c objGarantiaProduto : GarantiaProdutoDAO.getInstance().buscarGarantiasProdutoPorProdutoCap(lstPromocoes))
        {
            for(GarantiaContrato__c objGarantiaContrato : objGarantiaProduto.Garantias_do_contrato__r)
            {
                if(!mapParametros.containsKey(objGarantiaProduto.CodigoPromocao__c + objGarantiaContrato.VersaoTitulo__c))
                {
                    dadosEnvioTO dadosEnvio = new dadosEnvioTO();
                    
                    dadosEnvio.codPromocao      = objGarantiaProduto.CodigoPromocao__c;
                    dadosEnvio.codVersao        = objGarantiaContrato.VersaoTitulo__c;

                    mapParametros.put(objGarantiaProduto.CodigoPromocao__c + objGarantiaContrato.VersaoTitulo__c, dadosEnvio);   
                }
            }
        }

        //--- prepara json de parametros de envio para o serviço
        Integer contador = 0;
        List<GarantiaContratoTO.DadosPortoCap> lstDadosPortoCap = new List<GarantiaContratoTO.DadosPortoCap>();

        EmpresaPortoCAP__mdt empresaPortoCap = new EmpresaPortoCAP__mdt();

        empresaPortoCap = MetadataDAO.getInstance().buscarEmpresaPortoCap();        

        for (String key : mapParametros.keySet())
        {
            dadosEnvioTO dadosEnvio = new dadosEnvioTO();
            GarantiaContratoTO.DadosPortoCap parametro = new GarantiaContratoTO.DadosPortoCap();             

            dadosEnvio = mapParametros.get(key);

            parametro.Nr_cnpj       = empresaPortoCap.CNPJ__c;
            parametro.Cd_promocao   = dadosEnvio.codPromocao;
            if(dadosEnvio.codVersao != null)
                parametro.cd_versao     = Integer.valueOf(dadosEnvio.codVersao);

            lstDadosPortoCap.add(parametro);
            contador++;            
        }

        System.debug('Executa Qeueable Principal - No. Parametros: ' + contador);
        System.enqueueJob(new QueueableProcessaPortoCap(lstDadosPortoCap));

    }

    public class dadosEnvioTO
    {
        public String codPromocao  { get; set; }
        public String codVersao { get; set; }
    }

    public class GarantiaContratoException extends Exception {}
}