workspace-sf/force-app/main/default/objects/CriticaParceiro__c/CriticaParceiro__c.object-meta.xml
<CustomObject>
    <description>Objeto responsável por armazenar as críticas do parceiro</description>
    <label>Crítica do parceiro</label>
    <nameField>
        <label>Código</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Críticas do parceiro</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/CriticaParceiro__c/fields/CodigoCriticaMotorRegras__c.field-meta.xml
<CustomField>
    <fullName>CodigoCriticaMotorRegras__c</fullName>
    <label>Código da Crítica no Motor de Regras</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

workspace-sf/force-app/main/default/objects/CriticaParceiro__c/fields/IdentificacaoCampo__c.field-meta.xml
<CustomField>
    <fullName>IdentificacaoCampo__c</fullName>
    <label>Identificação do Campo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/CriticaParceiro__c/fields/Parceiro__c.field-meta.xml
<CustomField>
    <fullName>Parceiro__c</fullName>
    <label>Parceiro</label>
    <referenceTo>Parceiro__c</referenceTo>
    <relationshipName>CriticasParceiro</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/CriticaParceiro__c/fields/Rotulo__c.field-meta.xml
<CustomField>
    <fullName>Rotulo__c</fullName>
    <label>Rótulo</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/CriticaParceiro__c/fields/TipoRegistro__c.field-meta.xml
<CustomField>
    <fullName>TipoRegistro__c</fullName>
    <label>Tipo de Registro</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Parceiro__c/Parceiro__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar as informações dos parceiros da Porto</description>
    <label>Parceiro</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parceiros</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/Parceiro__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <formula>LPAD( Conta__r.IdExterno__c , 14, &quot;0&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Código de identificação do parceiro  - CNPJ da conta sem pontuação</inlineHelpText>
    <label>Código</label>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/classes/CriticaParceiroDAO.cls
public with sharing class CriticaParceiroDAO 
{
	private static final CriticaParceiroDAO instancia = new CriticaParceiroDAO();
	private CriticaParceiroDAO(){}
	public static CriticaParceiroDAO getInstance(){ return instancia; }

	public List<CriticaParceiro__c> buscarCriticasParceiro(Set<String> setIdsParceiros)
	{
		return 
		[
			SELECT
				Id,
				Rotulo__c,
				CodigoCriticaMotorRegras__c,
				IdentificacaoCampo__c,
				Mensagem__c,
				Name,
				Parceiro__c,
				Parceiro__r.Codigo__c,
				TipoRegistro__c
			FROM
				CriticaParceiro__c
			WHERE
				Parceiro__r.Codigo__c =: setIdsParceiros
		];
	}
}