workspace-sf/force-app/main/default/objects/Continente__mdt/Continente__mdt.object-meta.xml
<CustomObject>
    <label>Continente</label>
    <pluralLabel>Continentes</pluralLabel>
</CustomObject>

workspace-sf/force-app/main/default/objects/GarantiaProduto__c/GarantiaProduto__c.object-meta.xml
<CustomObject>
    <description>Objeto de relacionamento entre os produtos e as garantias</description>
    <label>Garantia do produto</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Garantias do produto</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/GarantiaProduto__c/fields/GarantiaProduto__c.field-meta.xml
<CustomField>
    <fullName>GarantiaProduto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Garantia do produto</label>
    <referenceTo>GarantiaProduto__c</referenceTo>
    <relationshipLabel>Garantias do produto (Garantia do produto)</relationshipLabel>
    <relationshipName>GarantiasProdutoTecnico</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Municipio__c/Municipio__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar o cadastro dos municípios</description>
    <label>Município</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Municípios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/Municipio__c/fields/Uf__c.field-meta.xml
<CustomField>
    <fullName>Uf__c</fullName>
    <label>UF</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AC</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AP</fullName>
            </value>
            <value>
                <fullName>AM</fullName>
            </value>
            <value>
                <fullName>BA</fullName>
            </value>
            <value>
                <fullName>CE</fullName>
            </value>
            <value>
                <fullName>DF</fullName>
            </value>
            <value>
                <fullName>ES</fullName>
            </value>
            <value>
                <fullName>GO</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MG</fullName>
            </value>
            <value>
                <fullName>PA</fullName>
            </value>
            <value>
                <fullName>PB</fullName>
            </value>
            <value>
                <fullName>PR</fullName>
            </value>
            <value>
                <fullName>PE</fullName>
            </value>
            <value>
                <fullName>PI</fullName>
            </value>
            <value>
                <fullName>RJ</fullName>
            </value>
            <value>
                <fullName>RN</fullName>
            </value>
            <value>
                <fullName>RS</fullName>
            </value>
            <value>
                <fullName>RO</fullName>
            </value>
            <value>
                <fullName>RR</fullName>
            </value>
            <value>
                <fullName>SC</fullName>
            </value>
            <value>
                <fullName>SP</fullName>
            </value>
            <value>
                <fullName>SE</fullName>
            </value>
            <value>
                <fullName>TO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/Pais_OLD__mdt/Pais_OLD__mdt.object-meta.xml
<CustomObject>
    <label>País</label>
    <pluralLabel>Paises</pluralLabel>
</CustomObject>

workspace-sf/force-app/main/default/objects/Pais_OLD__mdt/fields/Continente__c.field-meta.xml
<CustomField>
    <fullName>Continente__c</fullName>
    <label>Continente</label>
    <referenceTo>Continente__mdt</referenceTo>
    <relationshipLabel>Paises</relationshipLabel>
    <relationshipName>Paises</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Territorio__c/Territorio__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar o cadastro dos territórios dos produtos e das garantias</description>
    <label>Território</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Territórios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/Territorio__c/fields/Continente__c.field-meta.xml
<CustomField>
    <fullName>Continente__c</fullName>
    <label>Continente</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Territorio__c/fields/GarantiaProduto__c.field-meta.xml
<CustomField>
    <fullName>GarantiaProduto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Garantia do produto</label>
    <referenceTo>GarantiaProduto__c</referenceTo>
    <relationshipLabel>Territórios</relationshipLabel>
    <relationshipName>TerritoriosGarantia</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Territorio__c/fields/Municipio__c.field-meta.xml
<CustomField>
    <fullName>Municipio__c</fullName>
    <label>Município</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Territorio__c/fields/Territorio__c.field-meta.xml
<CustomField>
    <fullName>Territorio__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Território</label>
    <referenceTo>Territorio__c</referenceTo>
    <relationshipLabel>Territórios</relationshipLabel>
    <relationshipName>Territorios</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Territorio__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Globo terrestre</fullName>
            </value>
            <value>
                <fullName>Continente</fullName>
            </value>
            <value>
                <fullName>País</fullName>
            </value>
            <value>
                <fullName>Estado</fullName>
            </value>
            <value>
                <fullName>Município</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/classes/TerritorioBO.cls
/**************************************************************************************************************************************************************************
 * 
 *	Classe responsável pelo negócio do objeto de Territorio__c
 *
 **************************************************************************************************************************************************************************/
public  class TerritorioBO {
	private static final TerritorioBO instancia = new TerritorioBO();
	private TerritorioDAO dao = TerritorioDAO.getInstance();

	private TerritorioBO() {
	}

	public static TerritorioBO getInstance(){
		return instancia;
	}

	 /**
     * Gera map contendo a relação de prefixos e o seus respectivos SObject
     *
     * @return Map<String, String> - Map contendo os prefixos/objeto
     */
    public Map<String, String> gerarMapPrefixoSobject(){
		Map<String, Schema.SObjectType> globalDescribe  = Schema.getGlobalDescribe();

    	Map<String, String> prefixosSobject = new Map<String, String>();
    	prefixosSobject.put(globalDescribe.get('Product2').getDescribe().getKeyPrefix(), 'Product2');
    	prefixosSobject.put(globalDescribe.get('GarantiaProduto__c').getDescribe().getKeyPrefix(), 'GarantiaProduto__c');
    	
        return prefixosSobject;
    }

	 /**
     * Gera lista de CustomPickListOptionTO com os valores dos tipos de garantia
     *
     * @return List<CustomPickListOptionTO> - Lista contendo os tipos
     */
    public List<CustomPickListOptionTO> gerarListaOpcoesTipos(){
    	List<CustomPickListOptionTO> opcoesTipo = new List<CustomPickListOptionTO>();

    	for(Schema.PicklistEntry pick : Territorio__c.Tipo__c.getDescribe().getPicklistValues()){
    		opcoesTipo.add(new CustomPickListOptionTO(pick.getLabel(), pick.getLabel()));
    	}

        return opcoesTipo;
    }

     /**
     * Gera lista de CustomPickListOptionTO com os valores dos continentes
     *
     * @return List<CustomPickListOptionTO> - Lista contendo os continentes
     */
    public List<CustomPickListOptionTO> gerarListaOpcoesContinentes(){
    	List<CustomPickListOptionTO> opcoesContinente = new List<CustomPickListOptionTO>();

    	for(Continente__mdt continente : MetadataDAO.getInstance().listarContinentes()){
    		opcoesContinente.add(new CustomPickListOptionTO(continente.MasterLabel, continente.MasterLabel));
    	}

        return opcoesContinente;
    }

    /**
     * Gera lista de CustomPickListOptionTO com os valores dos estados
     *
     * @return List<CustomPickListOptionTO> - Lista contendo os estados
     */
    public List<CustomPickListOptionTO> gerarListaOpcoesEstados(){
    	List<CustomPickListOptionTO> opcoesUF = new List<CustomPickListOptionTO>();

    	for(Schema.PicklistEntry pick : Municipio__c.Uf__c.getDescribe().getPicklistValues()){
    		opcoesUF.add(new CustomPickListOptionTO(pick.getLabel(), pick.getLabel()));
    	}

        return opcoesUF;
    }

    /**
     * Gera lista de CustomPickListOptionTO com os valores dos municipios
     *
     * @return List<CustomPickListOptionTO> - Lista contendo os municipios
     */
    public List<CustomPickListOptionTO> gerarListaOpcoesMunicipios(String estados){
        List<CustomPickListOptionTO> opcoesMunicipios = new List<CustomPickListOptionTO>();
        Set<String> setEstados = new Set<String>();
        setEstados.addAll(estados.split(';'));

        for(Municipio__c municipio : MunicipioBO.getInstance().buscarMunicipiosPorEstados(setEstados)){
            opcoesMunicipios.add(new CustomPickListOptionTO(municipio.Uf__c + ' - ' + municipio.Name, municipio.Name));
        }               

        return opcoesMunicipios;
    }

    /**
     * Gera map de CustomPickListOptionTO com os valores dos paises por continente
     *
     * @return Map<String, List<CustomPickListOptionTO>> - Map contendo a relação continente/paises
     */
    public Map<String, List<CustomPickListOptionTO>> gerarListaOpcoesPaises(){
        Map<String, List<CustomPickListOptionTO>> mapOpcoesPais = new Map<String, List<CustomPickListOptionTO>>();

        for(Pais_OLD__mdt pais : MetadataDAO.getInstance().listarPaises()){
            if(!mapOpcoesPais.containsKey(pais.Continente__r.MasterLabel)){
                mapOpcoesPais.put(pais.Continente__r.MasterLabel, new List<CustomPickListOptionTO>());
            }

            mapOpcoesPais.get(pais.Continente__r.MasterLabel).add(new CustomPickListOptionTO(pais.MasterLabel, pais.MasterLabel));
        }

        return mapOpcoesPais;
    }

    /**
     * Gera list de CustomPickListOptionTO com os valores dos paises
     *
     * @return List<CustomPickListOptionTO> - list contendo os paises
     */
    public List<CustomPickListOptionTO> gerarListaOpcoesPaises(String continentes){
        List<CustomPickListOptionTO> opcoesPais = new List<CustomPickListOptionTO>();

        for(String continente : continentes.split(';')){
            for(Pais_OLD__mdt pais : MetadataDAO.getInstance().buscarPaises(continente)){
                opcoesPais.add(new CustomPickListOptionTO(pais.MasterLabel, pais.MasterLabel));
            }
        }

        return opcoesPais;
    }

    /**
     * Realiza as buscas dos territorios de acordo com o tipo de objeto pai
     *
     * @param   sObjectPaiId  - id do objeto pai do território
     * @param   nomeSObjectPai  - nome do objeto pai
     * @return  List<Territorio__c> - Lista contendo os territorios da garantia
     */
    public List<Territorio__c> buscarTerritorios(Id sObjectPaiId, String nomeSObjectPai){
    	List<Territorio__c> territorios = new List<Territorio__c>();

    	if(nomeSObjectPai == 'GarantiaProduto__c'){
    		territorios = dao.buscarTerritoriosGarantia(sObjectPaiId);
    	}
    	else if(nomeSObjectPai == 'Product2'){
    		territorios = dao.buscarTerritoriosProduto(sObjectPaiId);
    	}

    	return territorios;
    }

    /**
     * Salva as informações de territorio da garantia passadas por parametro
     *
     * @param   territoriosGarantia  - lista de Territorio__c para serem salvas
     */
    public void salvar (List<Territorio__c> territoriosGarantia){
		try{

			upsert territoriosGarantia;
			System.debug('OK');
		}
		catch(Exception e){
			System.debug(e.getMessage());
		}
    }
}