workspace-sf/force-app/main/default/objects/RemuneracaoContrato__c/RemuneracaoContrato__c.object-meta.xml
<CustomObject>
    <description>Objeto de relacionamento entre o contrato e o tipo de remuneração.</description>
    <label>Remuneração do contrato</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Remunerações do contrato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/RemuneracaoContrato__c/fields/Contrato__c.field-meta.xml
<CustomField>
    <fullName>Contrato__c</fullName>
    <label>Contrato</label>
    <referenceTo>Contract</referenceTo>
    <relationshipName>RemuneracoesContrato</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/RemuneracaoContrato__c/fields/TipoRemuneracao__c.field-meta.xml
<CustomField>
    <fullName>TipoRemuneracao__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tipo de remuneração</label>
    <referenceTo>TipoRemuneracao__c</referenceTo>
    <relationshipLabel>Remunerações do contrato</relationshipLabel>
    <relationshipName>RemuneracoesContrato</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/TipoRemuneracao__c/TipoRemuneracao__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar o cadastro dos tipos de remuneração</description>
    <label>Tipo de remuneração</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tipos de remuneração</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/classes/RemuneracaoContratoFactory.cls
/**
 * @author AVX - Daniel Zampieri
 * @date 2019-03-06
 * @description RemuneracaoContrato__c Factory Class
 */
@isTest
public class RemuneracaoContratoFactory extends SObjectFactory{
	private static RemuneracaoContrato__c staticRecord;

	private static RemuneracaoContrato__c getRecordStatic(TipoRemuneracao__c tipoRemuneracao, Contract contrato){

		if(staticRecord == null){
			staticRecord = new RemuneracaoContrato__c(
				Contrato__c = contrato.Id,
            	TipoRemuneracao__c = tipoRemuneracao.Id);
		}
		return staticRecord;
	}

	public RemuneracaoContratoFactory(){

		this(
			(TipoRemuneracao__c) new TipoRemuneracaoFactory().createRecord(),
			(Contract) new ContratoFactory.ContratoFactorySemParam().createRecord()
		);
	}

	public RemuneracaoContratoFactory(TipoRemuneracao__c tipoRemuneracao, Contract contrato) {

		super(getRecordStatic(tipoRemuneracao, contrato));
	}
}