workspace-sf/force-app/main/default/objects/BeneficiarioGarantia__c/BeneficiarioGarantia__c.object-meta.xml
<CustomObject>
    <description>Registrar os beneficiários de cada pagamento de garantia. 
Objeto Detalhe do Pagamento de Garantia.</description>
    <label>Beneficiario da Garantia</label>
    <nameField>
        <displayFormat>BG-{0000}</displayFormat>
        <label>Nome de Beneficiario da Garantia</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Beneficiarios da Garantia</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/BeneficiarioGarantia__c/fields/Pagamento_de_garantia__c.field-meta.xml
<CustomField>
    <fullName>Pagamento_de_garantia__c</fullName>
    <label>Pagamento de garantia</label>
    <referenceTo>PagamentoGarantia__c</referenceTo>
    <relationshipLabel>Beneficiarios da Garantia</relationshipLabel>
    <relationshipName>Beneficiarios_Garantia</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/BeneficiarioGarantia__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pendente</fullName>
                <default>true</default>
                <label>Pendente</label>
            </value>
            <value>
                <fullName>Aguardando pagamento</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
            <value>
                <fullName>Liberado</fullName>
            </value>
            <value>
                <fullName>Pago</fullName>
            </value>
            <value>
                <fullName>Serviço prestado</fullName>
            </value>
            <value>
                <fullName>Serviço não prestado</fullName>
            </value>
            <value>
                <fullName>Erro</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/CredencialOAuth2__mdt/CredencialOAuth2__mdt.object-meta.xml
<CustomObject>
    <label>Credencial OAuth 2</label>
    <pluralLabel>Credenciais OAuth 2</pluralLabel>
</CustomObject>

workspace-sf/force-app/main/default/objects/CredencialOAuth2__mdt/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Status</label>
    <type>Checkbox</type>
</CustomField>

workspace-sf/force-app/main/default/objects/PagamentoGarantia__c/PagamentoGarantia__c.object-meta.xml
<CustomObject>
    <description>Registrar os pagamentos das garantias dentro da frente de Sinistro Vida.
Objeto Detalhe de Caso</description>
    <label>Garantia do Sinistro</label>
    <nameField>
        <label>Nome da Garantia do Sinistro</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Garantias do Sinistro</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/Servico__mdt/Servico__mdt.object-meta.xml
<CustomObject>
    <description>Metadado responsável por disponilizar o endpoints dos serviços Porto</description>
    <label>Serviço</label>
    <pluralLabel>Serviços</pluralLabel>
</CustomObject>

workspace-sf/force-app/main/default/classes/pagamentosrecentescontroller.cls
public class pagamentosrecentescontroller {
    
@AuraEnabled
    public static String consultapagamentos(String recordId) 
    {
       List<Object> LstObject2Heroku = new List<Object>();
       LstObject2Heroku = [SELECT Id
       	  				   FROM BeneficiarioGarantia__c
                           WHERE Pagamento_de_garantia__r.Id =: recordId];

       Http h = new Http();
    
       String body = JSON.serialize(LstObject2Heroku);
       CredencialOAuth2__mdt  credencial = MetadataDAO.getInstance().buscarCredencial('VidaCloudApi');
       Servico__mdt servico = MetadataDAO.getInstance().buscarServico('Consulta_Pagamento');
       String Token;
        
       if(!test.isrunningtest()){ Token = HerokuService.getInstance().gerarTokenOAuth2('VidaCloudApi');
       }else{
          Token = 'faketesttoken';
       }
        
       // Instantiate a new HTTP request, specify the method (GET) as well as the endpoint
       HttpRequest req = new HttpRequest();
       req.setMethod('POST');
       req.setHeader('Content-Type', 'application/json');

       if(!Test.isRunningTest()){
       req.setHeader('Authorization', Token);
       req.setBody(body);
       req.setEndpoint(credencial.Audience__c + '/api/' + servico.Endpoint__c);

       
       		// Send the request, and return a response
       HttpResponse res = h.send(req); 
           
       system.debug('req '+ req); 
       system.debug('res '+ res);
       //PLV - 2336-28 - Inicio/Fim - Removido debug
       return res.getBody(); 
       }else{
            PagamentosRecentesControllerMock pagRecM = new PagamentosRecentesControllerMock();
           	HttpResponse resposta = pagRecM.respond(req);
           	return resposta.getBody(); 
           }
    }        
    
	@AuraEnabled
    public static String cancelapagamentos(Integer recordId) 
    {
       Http h = new Http();
    
       String body = '{"idpagamento" : '+recordId+'}'; 
       
       CredencialOAuth2__mdt  credencial = MetadataDAO.getInstance().buscarCredencial('VidaCloudApi');
       Servico__mdt servico = MetadataDAO.getInstance().buscarServico('Cancela_Pagamento');
       
       String Token;       
       if(!test.isrunningtest()){ Token = HerokuService.getInstance().gerarTokenOAuth2('VidaCloudApi');
        }else{
          Token = 'faketesttoken';
        }
        
       HttpRequest req = new HttpRequest();
       req.setMethod('POST');
       req.setHeader('Content-Type', 'application/json');
       req.setHeader('Authorization', Token);

       req.setBody(body);
       HttpResponse res;
       if(!Test.isRunningTest()){ req.setEndpoint(credencial.Audience__c + '/api/' + servico.Endpoint__c);
       res = h.send(req);
       }else{
            PagamentosRecentesControllerMock pagRecM = new PagamentosRecentesControllerMock();
           	res = pagRecM.respondCancelaPagamento(req);
       }
        return res.getBody(); 
    }            
    
    @AuraEnabled
    public static Map<Id, Account> retornanomeConta(String[] recordId) 
    {
        system.debug(recordId);
        Map<ID, Account> m = new Map<ID, Account>([SELECT Name FROM Account Where Id =: recordId LIMIT 10]);
        return m;          
    }
        
	@AuraEnabled
    public static void mudastatusbeneficiario(String recordId) 
    {
		List<BeneficiarioGarantia__c> Lstbene = [SELECT Id, Status__c
                                                 FROM BeneficiarioGarantia__c
                                                 WHERE Id =: recordId];
		if(Lstbene.size() == 0) return;
        
        LstBene[0].Status__c = 'Pendente';
        database.update(LstBene[0]);
    }        
}