workspace-sf/force-app/main/default/objects/BeneficiarioGarantia__c/BeneficiarioGarantia__c.object-meta.xml
<CustomObject>
    <description>Registrar os beneficiários de cada pagamento de garantia. 
Objeto Detalhe do Pagamento de Garantia.</description>
    <label>Beneficiario da Garantia</label>
    <nameField>
        <displayFormat>BG-{0000}</displayFormat>
        <label>Nome de Beneficiario da Garantia</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Beneficiarios da Garantia</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/BeneficiarioGarantia__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Beneficiarios da Garantia</relationshipLabel>
    <relationshipName>Beneficiarios_Garantia</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/BeneficiarioGarantia__c/fields/Pagamento_de_garantia__c.field-meta.xml
<CustomField>
    <fullName>Pagamento_de_garantia__c</fullName>
    <label>Pagamento de garantia</label>
    <referenceTo>PagamentoGarantia__c</referenceTo>
    <relationshipLabel>Beneficiarios da Garantia</relationshipLabel>
    <relationshipName>Beneficiarios_Garantia</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/BeneficiarioSeguradoProposta__c/BeneficiarioSeguradoProposta__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar os beneficiários da proposta</description>
    <label>Beneficiário do segurado da proposta</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Beneficiários dos segurados da proposta</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/BeneficiarioSeguradoProposta__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Beneficiários dos segurados da proposta</relationshipLabel>
    <relationshipName>BeneficSeguradosProposta</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/BeneficiarioSeguradoProposta__c/fields/CpfCnpj__c.field-meta.xml
<CustomField>
    <fullName>CpfCnpj__c</fullName>
    <label>CPF / CNPJ</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/BeneficiarioSeguradoProposta__c/fields/GrauParentesco__c.field-meta.xml
<CustomField>
    <fullName>GrauParentesco__c</fullName>
    <label>Grau de parentesco</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>GrauParentesco</valueSetName>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/BeneficiarioSeguradoProposta__c/fields/Pep__c.field-meta.xml
<CustomField>
    <fullName>Pep__c</fullName>
    <label>PEP?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sim</fullName>
            </value>
            <value>
                <fullName>RelacionamentoProximo</fullName>
                <label>Relacionamento próximo</label>
            </value>
            <value>
                <fullName>Nao</fullName>
                <label>Não</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/BeneficiarioSeguradoProposta__c/fields/SeguradoProposta__c.field-meta.xml
<CustomField>
    <fullName>SeguradoProposta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Segurado da proposta</label>
    <referenceTo>SeguradoProposta__c</referenceTo>
    <relationshipLabel>Beneficiários dos segurados da proposta</relationshipLabel>
    <relationshipName>BeneficiariosSeguradosProposta</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/BeneficiarioSeguradoProposta__c/fields/TipoBeneficiario__c.field-meta.xml
<CustomField>
    <fullName>TipoBeneficiario__c</fullName>
    <label>Tipo de beneficiário</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nome do beneficiário</fullName>
            </value>
            <value>
                <fullName>Herdeiros legais, conforme artigo 792 do código civil.</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/ContratanteProposta__c/ContratanteProposta__c.object-meta.xml
<CustomObject>
    <description>Objeto responsável por armazenar o cadastro dos contratantes da proposta</description>
    <label>Contratante da proposta</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contratantes da proposta</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/GrupoProposta__c/GrupoProposta__c.object-meta.xml
<CustomObject>
    <description>Objeto responsável por armazenar o cadastro dos grupos de segurados da proposta</description>
    <label>Grupo da proposta</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grupos da proposta</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/GrupoProposta__c/fields/ContratanteProposta__c.field-meta.xml
<CustomField>
    <fullName>ContratanteProposta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contratante da proposta</label>
    <referenceTo>ContratanteProposta__c</referenceTo>
    <relationshipLabel>Grupos da proposta</relationshipLabel>
    <relationshipName>GruposProposta</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/PagamentoGarantia__c/PagamentoGarantia__c.object-meta.xml
<CustomObject>
    <description>Registrar os pagamentos das garantias dentro da frente de Sinistro Vida.
Objeto Detalhe de Caso</description>
    <label>Garantia do Sinistro</label>
    <nameField>
        <label>Nome da Garantia do Sinistro</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Garantias do Sinistro</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/PagamentoGarantia__c/fields/Caso__c.field-meta.xml
<CustomField>
    <fullName>Caso__c</fullName>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>Pagamentos_de_garantia</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Pep__c/Pep__c.object-meta.xml
<CustomObject>
    <label>Pep</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Peps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/Pep__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Peps</relationshipLabel>
    <relationshipName>PepsAccount</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Pep__c/fields/Avaliado__c.field-meta.xml
<CustomField>
    <fullName>Avaliado__c</fullName>
    <label>Avaliado</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Pep__c/fields/BeneficiarioGarantia__c.field-meta.xml
<CustomField>
    <fullName>BeneficiarioGarantia__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Beneficiario da Garantia</label>
    <referenceTo>BeneficiarioGarantia__c</referenceTo>
    <relationshipLabel>Peps</relationshipLabel>
    <relationshipName>Peps</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Pep__c/fields/BeneficiarioSeguradoProposta__c.field-meta.xml
<CustomField>
    <fullName>BeneficiarioSeguradoProposta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Beneficiário do segurado da proposta</label>
    <referenceTo>BeneficiarioSeguradoProposta__c</referenceTo>
    <relationshipLabel>Peps</relationshipLabel>
    <relationshipName>Peps</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Pep__c/fields/CodigoPEP__c.field-meta.xml
<CustomField>
    <fullName>CodigoPEP__c</fullName>
    <label>Código PEP</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Pep__c/fields/DateUpdate__c.field-meta.xml
<CustomField>
    <fullName>DateUpdate__c</fullName>
    <label>Data Atualização</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Pep__c/fields/LastAppointment__c.field-meta.xml
<CustomField>
    <fullName>LastAppointment__c</fullName>
    <label>Última consulta</label>
    <type>DateTime</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Pep__c/fields/PepList__c.field-meta.xml
<CustomField>
    <fullName>PepList__c</fullName>
    <label>Pep?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sim</fullName>
            </value>
            <value>
                <fullName>Não</fullName>
            </value>
            <value>
                <fullName>Relacionamento próximo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/Pep__c/fields/Segurado_da_proposta__c.field-meta.xml
<CustomField>
    <fullName>Segurado_da_proposta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Segurado da proposta</label>
    <referenceTo>SeguradoProposta__c</referenceTo>
    <relationshipLabel>Peps</relationshipLabel>
    <relationshipName>Peps</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Pep__c/recordTypes/BeneficiarioGarantia.recordType-meta.xml
<RecordType>
    <fullName>BeneficiarioGarantia</fullName>
    <active>true</active>
    <label>BeneficiarioGarantia</label>
</RecordType>

workspace-sf/force-app/main/default/objects/Pep__c/recordTypes/BenificiarioSeguradoProposta.recordType-meta.xml
<RecordType>
    <fullName>BenificiarioSeguradoProposta</fullName>
    <active>true</active>
    <label>BenificiarioSeguradoProposta</label>
</RecordType>

workspace-sf/force-app/main/default/objects/Pep__c/recordTypes/seguradoProposta.recordType-meta.xml
<RecordType>
    <fullName>seguradoProposta</fullName>
    <active>true</active>
    <label>seguradoProposta</label>
</RecordType>

workspace-sf/force-app/main/default/objects/PepRelacionamento__c/PepRelacionamento__c.object-meta.xml
<CustomObject>
    <label>Pep Relacionamento</label>
    <nameField>
        <displayFormat>PR-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pep Relacionamentos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/PepRelacionamento__c/fields/codigoPEP__c.field-meta.xml
<CustomField>
    <fullName>codigoPEP__c</fullName>
    <label>Código Pep</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

workspace-sf/force-app/main/default/objects/PepRelacionamento__c/fields/DataAtualizacao__c.field-meta.xml
<CustomField>
    <fullName>DataAtualizacao__c</fullName>
    <label>Data Atualização</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/PepRelacionamento__c/fields/GrauParentesco__c.field-meta.xml
<CustomField>
    <fullName>GrauParentesco__c</fullName>
    <label>Grau de Parentesco</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/PepRelacionamento__c/fields/NomePep__c.field-meta.xml
<CustomField>
    <fullName>NomePep__c</fullName>
    <label>Nome</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/PepRelacionamento__c/fields/Pep__c.field-meta.xml
<CustomField>
    <fullName>Pep__c</fullName>
    <label>Pep</label>
    <referenceTo>Pep__c</referenceTo>
    <relationshipLabel>Pep Relacionamentos</relationshipLabel>
    <relationshipName>Pep_Relacionamentos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/SeguradoProposta__c/SeguradoProposta__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar os segurados da proposta</description>
    <label>Segurado da proposta</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Segurados da proposta</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/SeguradoProposta__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Segurados da proposta</relationshipLabel>
    <relationshipName>SeguradosProposta</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/SeguradoProposta__c/fields/GrauParentesco__c.field-meta.xml
<CustomField>
    <fullName>GrauParentesco__c</fullName>
    <label>Grau de Parentesco</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>COMPANHEIRO</fullName>
            </value>
            <value>
                <fullName>CÔNJUGE</fullName>
            </value>
            <value>
                <fullName>ENTEADO</fullName>
            </value>
            <value>
                <fullName>FILHO</fullName>
            </value>
            <value>
                <fullName>PAIMAE</fullName>
                <label>PAI MAE</label>
            </value>
            <value>
                <fullName>OUTROS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/SeguradoProposta__c/fields/GrupoProposta__c.field-meta.xml
<CustomField>
    <fullName>GrupoProposta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Grupo da proposta</label>
    <referenceTo>GrupoProposta__c</referenceTo>
    <relationshipLabel>Segurados da proposta</relationshipLabel>
    <relationshipName>SeguradosProposta</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/classes/PepBO.cls
/***
* Created: Jeferson Santana (Sys4b)
* Date: 2024-08
* Description: class responsible for testing: BatchCreateFileReportMegaDayTest 
* task-History : LECVPV-218
***/ 
public with sharing class PepBO {
    private static final PepBO instance = new PepBO();
	public Boolean processoPep = false;
	public static PepBO getInstance() {return instance; }
    //INICIO - LECVPV-218-V1
    public static void createPepObjeto(List<PepTO> listpepPessoa){
		System.debug('##createPepObjeto##'+listpepPessoa);
		//System.debug('##createPepObjeto##'+listpepPessoa.size());
		List<Pep__c> listPep = new List<Pep__c>();
		List<PepRelacionamento__c> listPepRelacionamento = new List<PepRelacionamento__c>();
		Map<Integer,List<PepRelacionamento__c>> mapListPepRelac = new Map<Integer, List<PepRelacionamento__c>>();
		Integer count = 0;
		for(PepTO pepPessoa : listpepPessoa){
			Pep__c pepObj = new Pep__c();
			Boolean relacionamento = false;		
			if((pepPessoa.listaPessoa == null) && (pepPessoa.listaRelacionada == null)){
				pepObj.PepList__c = 'Não';
				pepObj.CPF__c = pepPessoa.dadosObjeto.cpf;
				pepObj.Name = pepPessoa.dadosObjeto.nomeAccount;
			}else if(pepPessoa.listaPessoa != null){
				pepObj.PepList__c = 'Sim';
				pepObj.Name = pepPessoa?.listaPessoa?.nomePEP;
				pepObj.CPF__c = String.valueOf(pepPessoa?.listaPessoa?.cpfPEP);
				//pepObj.Cargo__c = pepPessoa?.listaPessoa?.mandatoPEPs?.cargoPEPWS?.nomeCargo;
				pepObj.CodigoPEP__c = pepPessoa?.listaPessoa?.codigoPEP;
				pepObj.DateUpdate__c = pepPessoa?.listaPessoa?.dataAtualizacao;
				pepObj.Avaliado__c = 'Paulo Roberto Ferreira Lisboa';
			}else if((pepPessoa.listaRelacionada != null) && (pepPessoa.listaPessoa == null)){ 
				pepObj.PepList__c = 'Relacionamento próximo';
				pepObj.Name = pepPessoa?.listaRelacionada.nomePessoaRelacionada;
				pepObj.CPF__c = String.valueOf(pepPessoa?.listaRelacionada?.numeroCPF);
				pepObj.DateUpdate__c = pepPessoa?.listaRelacionada?.dataAtualizacao;
				pepObj.Avaliado__c = 'Paulo Roberto Ferreira Lisboa';
				relacionamento = true;
			}
			List<PepTO.PessoaRelacaoPEPs> listRelacao;
			
			pepObj.LastAppointment__c = System.now();
			pepObj.Account__c = pepPessoa.dadosObjeto.accountId;
			switch on  pepPessoa.dadosObjeto.nomeObject{
				when 'SeguradoProposta__c' {
					pepObj.Segurado_da_proposta__c = pepPessoa.dadosObjeto.id;
					pepObj.RecordTypeId = Schema.SObjectType.Pep__c.getRecordTypeInfosByName().get('seguradoProposta').getRecordTypeId();
				}	
				when 'BeneficiarioSeguradoProposta__c' {
					pepObj.BeneficiarioSeguradoProposta__c = pepPessoa.dadosObjeto.id;
					pepObj.RecordTypeId = Schema.SObjectType.Pep__c.getRecordTypeInfosByName().get('BenificiarioSeguradoProposta').getRecordTypeId();
				}	
				when 'BeneficiarioGarantia__c' {
					pepObj.BeneficiarioGarantia__c = pepPessoa.dadosObjeto.id;
					pepObj.RecordTypeId = Schema.SObjectType.Pep__c.getRecordTypeInfosByName().get('BeneficiarioGarantia').getRecordTypeId();
				}										
			}
			
			listPep.add(pepObj);

			if(relacionamento){	
				for(PepTO.PessoaRelacaoPEPs obj : pepPessoa.listaRelacionada.pessoaRelacaoPEPs){
					PepRelacionamento__c objPepRelacionamento = new PepRelacionamento__c();
					objPepRelacionamento.Pep__c = pepObj.Id;
					objPepRelacionamento.GrauParentesco__c = obj?.descricaoRelacionamento;
					objPepRelacionamento.DataAtualizacao__c = obj?.dataAtualizacao;
					objPepRelacionamento.NomePep__c = obj?.pessoaPEPWS?.nomePEP;
					objPepRelacionamento.codigoPEP__c = obj?.pessoaPEPWS?.codigoPEP;
					listPepRelacionamento.add(objPepRelacionamento);
				}
				mapListPepRelac.put(count,listPepRelacionamento);
			}
			count++;
		}
		//System.debug('####listPep##'+listPep);
		//System.debug('###mapListPepRelac##'+mapListPepRelac);
		
		Database.SaveResult[] listPepsInsert = Database.insert(listPep, true);

		List<PepRelacionamento__c> listPepRelacionamentoInsert = new List<PepRelacionamento__c>();
		for(Integer x=0; x < listPepsInsert.size(); x++){
			if(listPepsInsert[x].isSuccess()){	

				if(mapListPepRelac.containsKey(x)){
					for(PepRelacionamento__c objPepRelacionamento : mapListPepRelac.get(x)){
						objPepRelacionamento.Pep__c = listPepsInsert[x].Id;
						listPepRelacionamentoInsert.add(objPepRelacionamento);
					}
				}	
			}
		}
		
		insert listPepRelacionamento;
	}
	//FIM - LECVPV-218-V1
	//INICIO - LECVPV-218-V1
     public Map<String,Pep__c> getPepSeguradoProposta(Set<Id> setIds){
		List<Pep__c> listPep = [SELECT Id, Segurado_da_proposta__c FROM Pep__c WHERE Segurado_da_proposta__c IN: setIds];
		Map<String, Pep__c> mapPep = new Map<String, Pep__c>();
		for(Pep__c obj : listPep){
			mapPep.put(obj.Segurado_da_proposta__c,obj);
		}

		return mapPep;
	}
	//FIM - LECVPV-218-V1
	//INICIO - LECVPV-218-V1
	public Map<String, Pep__c> getPepBenificiarioProposta(Set<Id> setIds){
		Map<String, Pep__c> mapPep = new Map<String, Pep__c>();
		List<Pep__c> listPep = [SELECT Id, BeneficiarioSeguradoProposta__c FROM Pep__c WHERE BeneficiarioSeguradoProposta__c IN: setIds];
		for(Pep__c obj : listPep){
			mapPep.put(obj.BeneficiarioSeguradoProposta__c,obj);
		}
		return mapPep;
    }

	public Map<String, Pep__c> getPepBenificiarioGarantia(Set<Id> setIds){
		Map<String, Pep__c> mapPep = new Map<String, Pep__c>();
		List<Pep__c> listPep = [SELECT Id, BeneficiarioGarantia__c FROM Pep__c WHERE BeneficiarioGarantia__c IN: setIds];
		for(Pep__c obj : listPep){
			mapPep.put(obj.BeneficiarioGarantia__c,obj);
		}
		return mapPep;
	}
	//FIM  - LECVPV-218-V1
	//INICIO - LECVPV-218-V1
	 public void getListObjectPep(List<SObject> listObj){
		System.debug('###listObj'+listObj);
		Map<String,PepTo.DataObjects> mapObjects = new Map<String,PepTo.DataObjects>();
		Set<Id> setIds = new Set<Id>();
		for(SObject obj : listObj){
			setIds.add((Id) obj.get('Id'));
		}
		Id id = (Id) listObj[0].get('Id');
		SObjectType t = id.getSObjectType();
		String nameObject = t.getDescribe().getName();
		
		switch on nameObject {
			when 'SeguradoProposta__c'{
				Map<String, Pep__c> mapPepSeg = this.getPepSeguradoProposta(setIds);
				Set<Id> setIdsSeg = new Set<Id>();
				if(mapPepSeg.size() == 0){
					setIdsSeg.addAll(setIds);
				}else{
					for(String key : setIds){
						if(!mapPepSeg.containsKey(key)){
							setIdsSeg.add(mapPepSeg.get(key).Segurado_da_proposta__c);
						}
					}
				}
				if(setIdsSeg.size() > 0){
					List<SeguradoProposta__c> listSegurado = [SELECT Id, GrupoProposta__r.ContratanteProposta__r.Proposta__r.Account.Cpf__c, GrupoProposta__r.ContratanteProposta__r.Proposta__r.Account.Name, GrupoProposta__r.ContratanteProposta__r.Proposta__r.AccountId FROM SeguradoProposta__c WHERE Id IN: setIdsSeg AND (GrupoProposta__r.ContratanteProposta__r.Proposta__r.Segmento__c NOT IN ('Viagem','Massificados') AND GrupoProposta__r.ContratanteProposta__r.Proposta__r.Segmento__c != null)]; //INICIO/FIM LECVPV-235
				
					for(SeguradoProposta__c obj : listSegurado){
						PepTo.DataObjects objPep = new PepTo.DataObjects();
						String cpf = (String.isNotEmpty(obj.GrupoProposta__r.ContratanteProposta__r.Proposta__r.Account.Cpf__c)) ? obj.GrupoProposta__r.ContratanteProposta__r.Proposta__r.Account.Cpf__c.replace('.', '').replace('-','') : null;
						if(String.isNotEmpty(cpf) && cpf.length() == 11){
							objPep.cpf = obj.GrupoProposta__r.ContratanteProposta__r.Proposta__r.Account.Cpf__c;
							objPep.nomeAccount = obj.GrupoProposta__r.ContratanteProposta__r.Proposta__r.Account.Name;
							objPep.nomeObject = nameObject;
							objPep.id = obj.Id;
							objPep.accountId = obj.GrupoProposta__r.ContratanteProposta__r.Proposta__r.AccountId;

			
							mapObjects.put(cpf, objPep);
						}
					}
				}
			}
			when 'BeneficiarioSeguradoProposta__c'{
				//System.debug('####'+this.getPepBenificiarioProposta(setIds).size()); 
				//INICIO LECVPV-235-FIX1
				List<BeneficiarioSeguradoProposta__c> listBen = listObj;
				if(listBen[0].TipoBeneficiario__c == 'Nome do beneficiário'){
					Map<String, Pep__c> mapPepBenSegProp = this.getPepBenificiarioProposta(setIds);
					Set<Id> setIdsBen = new Set<Id>();
					if(mapPepBenSegProp.size() == 0){
						setIdsBen.addAll(setIds);
					}else{
						for(String key : setIds){
							if(!mapPepBenSegProp.containsKey(key)){
								setIdsBen.add(mapPepBenSegProp.get(key).BeneficiarioSeguradoProposta__c);
							}
						}
					}
					//System.debug('###setIdsBen'+setIdsBen);
					if(setIdsBen.size() > 0){
						List<BeneficiarioSeguradoProposta__c> listBenificiario = [SELECT Id, Nome__c, CpfCnpj__c FROM BeneficiarioSeguradoProposta__c WHERE Id IN: setIdsBen AND (SeguradoProposta__r.GrupoProposta__r.ContratanteProposta__r.Proposta__r.Segmento__c NOT IN ('Viagem','Massificados') AND SeguradoProposta__r.GrupoProposta__r.ContratanteProposta__r.Proposta__r.Segmento__c != null)]; //INICIO/FIM LECVPV-235
						for(BeneficiarioSeguradoProposta__c obj : listBenificiario){
							PepTo.DataObjects objPep = new PepTo.DataObjects();
							String cpf = (String.isNotEmpty(obj.CpfCnpj__c)) ? obj.CpfCnpj__c.replace('.', '').replace('-','') : null;

							if(String.isNotEmpty(obj.CpfCnpj__c) && cpf.length() == 11){
								objPep.cpf = obj.CpfCnpj__c;
								objPep.nomeAccount = obj.Nome__c;
								objPep.nomeObject = nameObject;
								objPep.id = obj.Id;
								//objPep.accountId = obj.GrupoProposta__r.ContratanteProposta__r.Proposta__r.AccountId;

				
								mapObjects.put(objPep.cpf.replace('.','').replace('-', ''), objPep);
							}
							
						}
					}
					//FIM LECVPV-235-FIX1
				}//INICIO-FIM
				
			}
			when 'BeneficiarioGarantia__c'{
				Map<String, Pep__c> mapPepSinistro = this.getPepBenificiarioGarantia(setIds);
				Set<Id> setIdsSinistro = new Set<Id>();
				if(mapPepSinistro.size() == 0){
					setIdsSinistro.addAll(setIds);
				}else{
					for(String key : setIds){
						if(!mapPepSinistro.containsKey(key)){
							setIdsSinistro.add(mapPepSinistro.get(key).Segurado_da_proposta__c);
						}
					}
				}
				//System.debug('###SINISTRO##'+setIdsSinistro);
				if(setIdsSinistro.size() > 0){
					//INICIO - LECVPV-235-FIX1
					List<BeneficiarioGarantia__c> listSinistro = new List<BeneficiarioGarantia__c>();
					if(Test.isRunningTest()){
						listSinistro = [SELECT Id,Conta__c, Pagamento_de_garantia__r.Id, Conta__r.Cpf__c, Conta__r.Name FROM BeneficiarioGarantia__c WHERE Id IN: setIdsSinistro];
					}else{
						listSinistro = [SELECT Id,Conta__c, Pagamento_de_garantia__r.Id, Conta__r.Cpf__c, Conta__r.Name FROM BeneficiarioGarantia__c WHERE Id IN: setIdsSinistro AND (Pagamento_de_garantia__r.Caso__r.Contrato__r.Proposta__r.Segmento__c NOT IN ('Viagem','Massificados') AND Pagamento_de_garantia__r.Caso__r.Contrato__r.Proposta__r.Segmento__c != null)];
					}
					
					//FIM - LECVPV-235-FIX1
					for(BeneficiarioGarantia__c obj : listSinistro){
						PepTo.DataObjects objPep = new PepTo.DataObjects();
						String cpf = (String.isNotEmpty(obj.Conta__r.Cpf__c)) ? obj.Conta__r.Cpf__c.replace('.', '').replace('-','') : null;
						if(String.isNotEmpty(cpf) && cpf.length() == 11){
							objPep.cpf = obj.Conta__r.Cpf__c;
							objPep.nomeAccount = obj.Conta__r.Name;
							objPep.nomeObject = nameObject;
							objPep.id = obj.Id;
							objPep.accountId = obj.Conta__c;

			
							mapObjects.put(cpf, objPep);
						}
					}
				}
			}
		}
		

		if(!Test.isRunningTest()){
			processoPep = true;
		}
		
		ID jobID = (mapObjects.size() > 0) ? System.enqueueJob(new BatchPep(mapObjects, processoPep),0) : null;
	 }
	//FIM - LECVPV-218-V1
}