workspace-sf/force-app/main/default/objects/BeneficiarioGarantia__c/BeneficiarioGarantia__c.object-meta.xml
<CustomObject>
    <description>Registrar os beneficiários de cada pagamento de garantia. 
Objeto Detalhe do Pagamento de Garantia.</description>
    <label>Beneficiario da Garantia</label>
    <nameField>
        <displayFormat>BG-{0000}</displayFormat>
        <label>Nome de Beneficiario da Garantia</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Beneficiarios da Garantia</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/BeneficiarioGarantia__c/fields/Pagamento_de_garantia__c.field-meta.xml
<CustomField>
    <fullName>Pagamento_de_garantia__c</fullName>
    <label>Pagamento de garantia</label>
    <referenceTo>PagamentoGarantia__c</referenceTo>
    <relationshipLabel>Beneficiarios da Garantia</relationshipLabel>
    <relationshipName>Beneficiarios_Garantia</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/BeneficiarioGarantia__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pendente</fullName>
                <default>true</default>
                <label>Pendente</label>
            </value>
            <value>
                <fullName>Aguardando pagamento</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
            <value>
                <fullName>Liberado</fullName>
            </value>
            <value>
                <fullName>Pago</fullName>
            </value>
            <value>
                <fullName>Serviço prestado</fullName>
            </value>
            <value>
                <fullName>Serviço não prestado</fullName>
            </value>
            <value>
                <fullName>Erro</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/BeneficiarioGarantia__c/fields/ValorIndenizacao__c.field-meta.xml
<CustomField>
    <fullName>ValorIndenizacao__c</fullName>
    <label>Valor de Indenização</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

workspace-sf/force-app/main/default/objects/PagamentoGarantia__c/PagamentoGarantia__c.object-meta.xml
<CustomObject>
    <description>Registrar os pagamentos das garantias dentro da frente de Sinistro Vida.
Objeto Detalhe de Caso</description>
    <label>Garantia do Sinistro</label>
    <nameField>
        <label>Nome da Garantia do Sinistro</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Garantias do Sinistro</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/classes/BeneficiarioGarantiaDAO.cls
// POR062-1 - INICIO
public inherited sharing virtual class BeneficiarioGarantiaDAO {
    private static final BeneficiarioGarantiaDAO INSTANCIA = new BeneficiarioGarantiaDAO();
    private BeneficiarioGarantiaDAO() {}

    public static BeneficiarioGarantiaDAO getInstance(){
        return instancia;
    }

    public List<BeneficiarioGarantia__c> buscarPorIdDePagamentosDeGarantia(Set<Id> idsPagamentoGarantia) {
        List<BeneficiarioGarantia__c> beneficiarios = [
            SELECT Id, Status__c, ValorIndenizacao__c //LECVP-193 - INICIO/FIM
            FROM BeneficiarioGarantia__c
            WHERE Pagamento_de_garantia__c IN :idsPagamentoGarantia
        ];
        return beneficiarios;
    }

    //LECVP-344 - INICIO
    public AggregateResult[] buscarValPagoGarSin(String statusPgto, Id pgtoGarId){

        AggregateResult[] ar = 
          [
            SELECT 
              Id, 
              SUM(ValorIndenizacao__c)valorPagoGar 
            FROM 
              BeneficiarioGarantia__c 
            WHERE 
              Status__c = :statusPgto
            AND 
              Pagamento_de_garantia__r.Id = :pgtoGarId
            GROUP BY
              Id
            ];
            
        return ar;
      }
      
    public AggregateResult[] buscarValPagoGarsSin(String statusPgto, Set<Id> pgtosGarId){

      AggregateResult[] ar = 
        [
          SELECT 
            Id, 
            SUM(ValorIndenizacao__c)valorPagoGar 
          FROM 
            BeneficiarioGarantia__c 
          WHERE 
            Status__c = :statusPgto
          AND 
            Pagamento_de_garantia__r.Id IN :pgtosGarId
          GROUP BY
            Id
          ];
          
      return ar;
    }
    //LECVP-344 - FIM
}
// POR062-1 - FIM