workspace-sf/force-app/main/default/objects/BeneficiarioGarantia__c/BeneficiarioGarantia__c.object-meta.xml
<CustomObject>
    <description>Registrar os beneficiários de cada pagamento de garantia. 
Objeto Detalhe do Pagamento de Garantia.</description>
    <label>Beneficiario da Garantia</label>
    <nameField>
        <displayFormat>BG-{0000}</displayFormat>
        <label>Nome de Beneficiario da Garantia</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Beneficiarios da Garantia</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/BeneficiarioGarantia__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pendente</fullName>
                <default>true</default>
                <label>Pendente</label>
            </value>
            <value>
                <fullName>Aguardando pagamento</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
            <value>
                <fullName>Liberado</fullName>
            </value>
            <value>
                <fullName>Pago</fullName>
            </value>
            <value>
                <fullName>Serviço prestado</fullName>
            </value>
            <value>
                <fullName>Serviço não prestado</fullName>
            </value>
            <value>
                <fullName>Erro</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/ContratanteContrato__c/ContratanteContrato__c.object-meta.xml
<CustomObject>
    <description>Objeto responsável por armazenar o cadastro dos contratantes do contrato</description>
    <label>Contratante do contrato</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contratantes do contrato</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/ContratanteContrato__c/fields/Contrato__c.field-meta.xml
<CustomField>
    <fullName>Contrato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contrato</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Contratantes do contrato</relationshipLabel>
    <relationshipName>ContratantesContrato</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/ContratanteContrato__c/fields/FormaPagamento__c.field-meta.xml
<CustomField>
    <fullName>FormaPagamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Forma de pagamento</label>
    <referenceTo>FormaPagamento__c</referenceTo>
    <relationshipLabel>Contratantes do contrato</relationshipLabel>
    <relationshipName>ContratantesContrato</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/ContratanteContrato__c/fields/InformacaoBancaria__c.field-meta.xml
<CustomField>
    <fullName>InformacaoBancaria__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Informação bancária</label>
    <referenceTo>InformacaoBancaria__c</referenceTo>
    <relationshipLabel>Contratantes do contrato</relationshipLabel>
    <relationshipName>ContratantesContrato</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Garantia__c/Garantia__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar o cadastro das garantias</description>
    <label>Garantia</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Garantias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/Garantia__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Em análise</fullName>
            </value>
            <value>
                <fullName>Ativo</fullName>
            </value>
            <value>
                <fullName>Inativo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaSeguradoContrato__c/GarantiaSeguradoContrato__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar as garantias do segurado do contrato</description>
    <label>Garantia do segurado do contrato</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Garantias do segurado do contrato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/GarantiaSeguradoContrato__c/fields/Garantia__c.field-meta.xml
<CustomField>
    <fullName>Garantia__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Garantia</label>
    <referenceTo>Garantia__c</referenceTo>
    <relationshipLabel>Garantias do segurado do contrato (Garantia)</relationshipLabel>
    <relationshipName>GarantiasSeguradoContrato</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaSeguradoContrato__c/fields/SeguradoContrato__c.field-meta.xml
<CustomField>
    <fullName>SeguradoContrato__c</fullName>
    <label>Segurado do contrato</label>
    <referenceTo>SeguradoContrato__c</referenceTo>
    <relationshipLabel>Garantias do segurado do contrato</relationshipLabel>
    <relationshipName>GarantiasSeguradoContrato</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GrupoContrato__c/GrupoContrato__c.object-meta.xml
<CustomObject>
    <description>Objeto responsável por armazenar os dados dos grupos de segurados do contrato</description>
    <label>Grupo do contrato</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grupos do contrato</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/GrupoContrato__c/fields/ContratanteContrato__c.field-meta.xml
<CustomField>
    <fullName>ContratanteContrato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contratante do contrato</label>
    <referenceTo>ContratanteContrato__c</referenceTo>
    <relationshipLabel>Grupos do contrato</relationshipLabel>
    <relationshipName>GruposContrato</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/OperacaoProdutoParceiro__c/OperacaoProdutoParceiro__c.object-meta.xml
<CustomObject>
    <description>Objeto para informar a operação do Produto do Parceiro</description>
    <label>Operação do produto do parceiro</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Operações dos produtos do parceiro</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/OperacaoProdutoParceiro__c/fields/ProdutoParceiro__c.field-meta.xml
<CustomField>
    <fullName>ProdutoParceiro__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Produto do parceiro</label>
    <referenceTo>ProdutoParceiro__c</referenceTo>
    <relationshipLabel>Operações dos produtos do parceiro</relationshipLabel>
    <relationshipName>OperacoesProdutosParceiro</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/PagamentoGarantia__c/PagamentoGarantia__c.object-meta.xml
<CustomObject>
    <description>Registrar os pagamentos das garantias dentro da frente de Sinistro Vida.
Objeto Detalhe de Caso</description>
    <label>Garantia do Sinistro</label>
    <nameField>
        <label>Nome da Garantia do Sinistro</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Garantias do Sinistro</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/PagamentoGarantia__c/fields/Fase__c.field-meta.xml
<CustomField>
    <fullName>Fase__c</fullName>
    <label>Fase</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aberto</fullName>
            </value>
            <value>
                <fullName>Em Análise</fullName>
            </value>
            <value>
                <fullName>Fechado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/PagamentoGarantia__c/fields/Garantia_do_segurado_do_contrato__c.field-meta.xml
<CustomField>
    <fullName>Garantia_do_segurado_do_contrato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Garantia do segurado do contrato</label>
    <referenceTo>GarantiaSeguradoContrato__c</referenceTo>
    <relationshipName>Pagamentos_de_garantia</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/PagamentoGarantia__c/fields/Status_do_pagamento__c.field-meta.xml
<CustomField>
    <fullName>Status_do_pagamento__c</fullName>
    <label>Status do Pagamento</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Fase__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Em análise</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
            <value>
                <fullName>Com Pendências</fullName>
            </value>
            <value>
                <fullName>Aguardando Pagamento</fullName>
            </value>
            <value>
                <fullName>Pago Parcialmente</fullName>
            </value>
            <value>
                <fullName>Pago</fullName>
            </value>
            <value>
                <fullName>Recusado</fullName>
            </value>
            <value>
                <fullName>Serviço Prestado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/Parceiro__c/Parceiro__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar as informações dos parceiros da Porto</description>
    <label>Parceiro</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parceiros</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/Parceiro__c/fields/FormaPagamento__c.field-meta.xml
<CustomField>
    <fullName>FormaPagamento__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Forma de pagamento</label>
    <referenceTo>FormaPagamento__c</referenceTo>
    <relationshipLabel>Parceiros</relationshipLabel>
    <relationshipName>Parceiros</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Parceiro__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Em Criação</fullName>
                <default>true</default>
                <label>Em Criação</label>
            </value>
            <value>
                <fullName>Ativo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/ProdutoParceiro__c/ProdutoParceiro__c.object-meta.xml
<CustomObject>
    <description>Objeto de relacionamento entre o parceiro e o produto</description>
    <label>Produto do parceiro</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número do Produto do Parceiro</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Produtos do parceiro</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/ProdutoParceiro__c/fields/Parceiro__c.field-meta.xml
<CustomField>
    <fullName>Parceiro__c</fullName>
    <label>Parceiro</label>
    <referenceTo>Parceiro__c</referenceTo>
    <relationshipLabel>Produtos do parceiro</relationshipLabel>
    <relationshipName>ProdutosParceiro</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/SeguradoContrato__c/SeguradoContrato__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar os segurados do contrato</description>
    <label>Segurado do contrato</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Segurados do contrato</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/SeguradoContrato__c/fields/FormaPagamento__c.field-meta.xml
<CustomField>
    <fullName>FormaPagamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Forma de pagamento</label>
    <referenceTo>FormaPagamento__c</referenceTo>
    <relationshipLabel>Segurados do contrato</relationshipLabel>
    <relationshipName>SeguradosContrato</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/SeguradoContrato__c/fields/GrupoContrato__c.field-meta.xml
<CustomField>
    <fullName>GrupoContrato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Grupo do contrato</label>
    <referenceTo>GrupoContrato__c</referenceTo>
    <relationshipLabel>Segurados do contrato</relationshipLabel>
    <relationshipName>SeguradosContrato</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/classes/CasoRestMock.cls
/**
 * @author AVX - Daniel Zampieri
 * @date 2019-03-28
 * @description CasoRest Classe de Mock
 */
@isTest
global class CasoRestMock implements HttpCalloutMock{
	global HTTPResponse respond(HTTPRequest req){
		Account contaPessoal2 = (Account) new AccountFactory.PessoaFisica().createRecord();
		Garantia__c garantia2 = (Garantia__c) new GarantiaFactory().createRecord();
		
		ContadorCodigo__c contCodigoTec2 = (ContadorCodigo__c) new ContadorCodigoFactory.ProdutoTecnico().createRecord();
        ContadorCodigo__c contCodigoCom2 = (ContadorCodigo__c) new ContadorCodigoFactory.ProdutoComercial().createRecord();
        Product2 produtoTecnico2 = (Product2) new ProdutoFactory.ProdutoTecnico().createRecord();
        produtoTecnico2.Status__c = 'Ativo';
        update produtoTecnico2;
        Product2 produtoComercial2 = (Product2) new ProdutoFactory.ProdutoComercial(produtoTecnico2).createRecord();

        FormaPagamento__c formaPagamento2 = (FormaPagamento__c) new FormaPagamentoFactory().createRecord();
        Parceiro__c parceiro2 = (Parceiro__c) new ParceiroFactory(contaPessoal2, formaPagamento2).createRecord();
        ProdutoParceiro__c prodParc2 = (ProdutoParceiro__c) new ProdutoParceiroFactory(parceiro2, produtoComercial2).createRecord();
        OperacaoProdutoParceiro__c oProdParc2 = (OperacaoProdutoParceiro__c) new OperacaoProdutoParceiroFactory(prodParc2).createRecord();

        Contact contato2 = (Contact) new ContactFactory().createRecord();
        Contract contrato2 = (Contract) new ContratoFactory.ContratoFactoryComParam(contaPessoal2, produtoComercial2, parceiro2).createRecord();
        ContratanteContrato__c contratante2 = (ContratanteContrato__c) new ContratanteFactory(contrato2).createRecord();
        GrupoContrato__c grupo2 = (GrupoContrato__c) new GrupoFactory(contratante2).createRecord();
        SeguradoContrato__c segurado2 = (SeguradoContrato__c) new SeguradoContratoFactory(contaPessoal2, grupo2).createRecord();
        GarantiaSeguradoContrato__c garantiaSegurado2 = (GarantiaSeguradoContrato__c) new GarantiaSeguradoContratoFactory(segurado2, garantia2).createRecord();
		
		Case casoAtendimento3 = (Case) new CasoFactory.AtendimentoSinistro().createRecord();
        
        Case casoSinistro2 = (Case) new CasoFactory.Sinistro(casoAtendimento3, contaPessoal2).createRecord();	

			casoSinistro2.ContactId = contato2.id;
            casoSinistro2.Contrato__c = contrato2.id;
            casoSinistro2.Garantia_do_segurado_do_contrato__c = garantiaSegurado2.id;
            casoSinistro2.NumeroSinistro__c = '321';
            casoSinistro2.Data_sinistro_avisado__c = System.today();
            casoSinistro2.Status = 'Avisado';
            casoSinistro2.Status_Dependente__c = 'Em Análise';
            casoSinistro2.Segurado_do_Contrato__c = segurado2.id;
            update casoSinistro2;

            casoSinistro2.Status = 'Em Regulação';
            update casoSinistro2;

            PagamentoGarantia__c pag = (PagamentoGarantia__c) new PagamentoGarantiaFactory(casoSinistro2, garantiaSegurado2).createRecord();
            pag.Fase__c = 'Em Análise';
            pag.Status_do_pagamento__c = 'Em Análise';
            update pag;

		InformacaoBancaria__c infoBan = (InformacaoBancaria__c) new InformacaoBancariaFactory.InfoPessoaFisica().createRecord();
		BeneficiarioGarantia__c beneGaran = (BeneficiarioGarantia__c) new BeneficiarioGarantiaFactory.BenePessoaFisica(contaPessoal2, infoBan, pag).createRecord();
		HTTPResponse res = new HttpResponse();

      //PLV-2285 - Início - Código alterado para aumento de cobertura na classe de teste
        if (req.getBody() == 'PAGO') {
            res.setHeader('Content-Type', 'application/json');
            res.setBody('[{"id":1,"idconta":"0010j00000FHy4vAAD","idobjeto": "'+ beneGaran.id + '","dataprogramadapagamento":null,"datapagamento":"2019-05-06T00:00:00Z","dataatualizacao":null,"valorpagamento":"100.00000","status":"PAGO","motivo":null}]');
            res.setStatusCode(200);
        }else if(req.getBody() == 'ERRO'){
            res.setHeader('Content-Type', 'application/json');
            res.setBody('[{"id":1,"idconta":"0010j00000FHy4vAAD","idobjeto": "'+ beneGaran.id + '","dataprogramadapagamento":null,"datapagamento":"2019-05-06T00:00:00Z","dataatualizacao":null,"valorpagamento":"100.00000","status":"ERRO","motivo":null}]');
            res.setStatusCode(200);
        }else if(req.getBody() == 'CANCELADO'){
            res.setHeader('Content-Type', 'application/json');
            res.setBody('[{"id":1,"idconta":"0010j00000FHy4vAAD","idobjeto": "'+ beneGaran.id + '","dataprogramadapagamento":null,"datapagamento":"2019-05-06T00:00:00Z","dataatualizacao":null,"valorpagamento":"100.00000","status":"CANCELADO","motivo":null}]');
            res.setStatusCode(200);
        }else if(req.getBody() == 'POST'){
            res.setHeader('Content-Type', 'application/json');
            res.setBody('[{"id":1,"idconta":"0010j00000FHy4vAAD","idobjeto": "'+ beneGaran.id + '","dataprogramadapagamento":null,"datapagamento":"2019-05-06T00:00:00Z","dataatualizacao":null,"valorpagamento":"100.00000","status":"PAGO","motivo":null}]');
            res.setStatusCode(200);
        }
	//PLV-2285 - Fim - Código alterado para aumento de cobertura na classe de teste
		return res;
	}
}