workspace-sf/force-app/main/default/objects/BeneficiarioGarantia__c/BeneficiarioGarantia__c.object-meta.xml
<CustomObject>
    <description>Registrar os beneficiários de cada pagamento de garantia. 
Objeto Detalhe do Pagamento de Garantia.</description>
    <label>Beneficiario da Garantia</label>
    <nameField>
        <displayFormat>BG-{0000}</displayFormat>
        <label>Nome de Beneficiario da Garantia</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Beneficiarios da Garantia</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/BeneficiarioGarantia__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Beneficiarios da Garantia</relationshipLabel>
    <relationshipName>Beneficiarios_Garantia</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/BeneficiarioGarantia__c/fields/Endereco__c.field-meta.xml
<CustomField>
    <fullName>Endereco__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Endereço</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Endereco__c.Conta__c</field>
            <operation>equals</operation>
            <valueField>$Source.Conta__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Endereco__c</referenceTo>
    <relationshipLabel>Beneficiarios da Garantia</relationshipLabel>
    <relationshipName>Beneficiarios_da_Garantia</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/BeneficiarioGarantia__c/fields/IdExterno__c.field-meta.xml
<CustomField>
    <fullName>IdExterno__c</fullName>
    <externalId>true</externalId>
    <label>Id Externo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/BeneficiarioGarantia__c/fields/Pagamento_de_garantia__c.field-meta.xml
<CustomField>
    <fullName>Pagamento_de_garantia__c</fullName>
    <label>Pagamento de garantia</label>
    <referenceTo>PagamentoGarantia__c</referenceTo>
    <relationshipLabel>Beneficiarios da Garantia</relationshipLabel>
    <relationshipName>Beneficiarios_Garantia</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/BeneficiarioGarantia__c/fields/RelacionamentoSegurado__c.field-meta.xml
<CustomField>
    <fullName>RelacionamentoSegurado__c</fullName>
    <label>Relacionamento com o Segurado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Grau_Parentesco</valueSetName>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/BeneficiarioGarantia__c/fields/Sucursal_Destino_de_Cheque__c.field-meta.xml
<CustomField>
    <fullName>Sucursal_Destino_de_Cheque__c</fullName>
    <label>Sucursal Destino de Cheque</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

workspace-sf/force-app/main/default/objects/BeneficiarioGarantia__c/fields/Tipo_de_Pagamento__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Pagamento__c</fullName>
    <label>Tipo de Pagamento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Transferencia Bancaria para Conta Corrente</fullName>
                <label>Transferência Bancária para Conta Corrente</label>
            </value>
            <value>
                <fullName>Transferencia Bancaria para Conta Poupanca</fullName>
                <label>Transferência Bancária para Conta Poupança</label>
            </value>
            <value>
                <fullName>Cheque</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/Endereco__c/Endereco__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar os endereços das contas</description>
    <label>Endereço</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Endereços</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/Endereco__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Endereços</relationshipLabel>
    <relationshipName>Enderecos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Endereco__c/fields/IdExterno__c.field-meta.xml
<CustomField>
    <fullName>IdExterno__c</fullName>
    <externalId>true</externalId>
    <label>IdExterno</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaSeguradoContrato__c/GarantiaSeguradoContrato__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar as garantias do segurado do contrato</description>
    <label>Garantia do segurado do contrato</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Garantias do segurado do contrato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/PagamentoGarantia__c/PagamentoGarantia__c.object-meta.xml
<CustomObject>
    <description>Registrar os pagamentos das garantias dentro da frente de Sinistro Vida.
Objeto Detalhe de Caso</description>
    <label>Garantia do Sinistro</label>
    <nameField>
        <label>Nome da Garantia do Sinistro</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Garantias do Sinistro</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/PagamentoGarantia__c/fields/Caso__c.field-meta.xml
<CustomField>
    <fullName>Caso__c</fullName>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>Pagamentos_de_garantia</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/PagamentoGarantia__c/fields/Data_da_cotacao_da_moeda_estrangeira__c.field-meta.xml
<CustomField>
    <fullName>Data_da_cotacao_da_moeda_estrangeira__c</fullName>
    <label>Data da cotação da moeda estrangeira</label>
    <type>Date</type>
</CustomField>

workspace-sf/force-app/main/default/objects/PagamentoGarantia__c/fields/Fase__c.field-meta.xml
<CustomField>
    <fullName>Fase__c</fullName>
    <label>Fase</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aberto</fullName>
            </value>
            <value>
                <fullName>Em Análise</fullName>
            </value>
            <value>
                <fullName>Fechado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/PagamentoGarantia__c/fields/Garantia_do_segurado_do_contrato__c.field-meta.xml
<CustomField>
    <fullName>Garantia_do_segurado_do_contrato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Garantia do segurado do contrato</label>
    <referenceTo>GarantiaSeguradoContrato__c</referenceTo>
    <relationshipName>Pagamentos_de_garantia</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/PagamentoGarantia__c/fields/IsPagAdc__c.field-meta.xml
<CustomField>
    <fullName>IsPagAdc__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pagamento Adicional</label>
    <type>Checkbox</type>
</CustomField>

workspace-sf/force-app/main/default/objects/PagamentoGarantia__c/fields/JustPagAdc__c.field-meta.xml
<CustomField>
    <fullName>JustPagAdc__c</fullName>
    <label>Justificativa pagamento adicional</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>1 - Complemento de pagamento devido a prorrogação de afastamento (DIT / RIT)</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>2 - Complemento de pagamento devido a recidiva da doença (DIT / RIT)</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>3 - Complemento de pagamento devido a valor da diária maior que o pago (DIT / RIT)</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>4 - Complemento sobre a diferença de correção de indenização</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>5 - Correção de dados bancários incorretos de OP anterior</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>6 - Divergência do número de CPF de OP anterior</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>7 - Divergência do nome do favorecido de OP anterior</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>8 - Valor pago maior que a importância segurada devida</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>9 - Valor pago menor que a importância segurada devida</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>10 - Valor pago maior que as despesas apresentadas</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>11 - Valor pago menor que as despesas apresentadas</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>12 - Valor pago para favorecido incorreto</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>13 - Complemento de Pagamento</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>14 - Falha Operacional - Pagamento anterior incorreto</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/PagamentoGarantia__c/fields/Status_do_pagamento__c.field-meta.xml
<CustomField>
    <fullName>Status_do_pagamento__c</fullName>
    <label>Status do Pagamento</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Fase__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Em análise</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
            <value>
                <fullName>Com Pendências</fullName>
            </value>
            <value>
                <fullName>Aguardando Pagamento</fullName>
            </value>
            <value>
                <fullName>Pago Parcialmente</fullName>
            </value>
            <value>
                <fullName>Pago</fullName>
            </value>
            <value>
                <fullName>Recusado</fullName>
            </value>
            <value>
                <fullName>Serviço Prestado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/PagamentoGarantia__c/fields/Valor_da_cotacao_em_reais__c.field-meta.xml
<CustomField>
    <fullName>Valor_da_cotacao_em_reais__c</fullName>
    <label>Valor da cotação em R$</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

workspace-sf/force-app/main/default/objects/PagamentoGarantia__c/fields/Valor_indenizado__c.field-meta.xml
<CustomField>
    <fullName>Valor_indenizado__c</fullName>
    <label>Valor Provisionado</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

workspace-sf/force-app/main/default/classes/BtnPagAdcGarController.cls
// PLV-4163 - criação classe
public with sharing class BtnPagAdcGarController {

    public class innerPicklist{
        @AuraEnabled public String value {get;set;}
        @AuraEnabled public String label {get;set;}
    }
    
    @AuraEnabled
    public static Map<String,Object> buscarInformacoes(String recordId){
        Map<String,Object> mapToReturn = new Map<String,Object>();
        
        PagamentoGarantia__c garantia = [SELECT Id, Caso__r.Status, JustPagAdc__c, Status_do_pagamento__c FROM PagamentoGarantia__c WHERE Id=:recordId];

        String visible = 'visivel';
        if( garantia.Status_do_pagamento__c == 'Em análise' || garantia.Status_do_pagamento__c == 'Com Pendências' || garantia.Status_do_pagamento__c == 'Aguardando Pagamento' ) visible = 'statusPagamento';
        if(garantia.Caso__r.Status !='Em Regulação' && garantia.Caso__r.Status !='Liquidação') visible = 'casoFase'; // PLV-4163 FIX 3
        if(garantia.Caso__r.Status =='Fechado') visible = 'casoFechado';
        if(!FeatureManagement.checkPermission('canOpenComponent')) visible = 'permissaoPerfil';
        mapToReturn.put('visible', visible );

        if( visible != 'visivel' ) return mapToReturn;            
        
        List<innerPicklist> justPagToReturn = new List<innerPicklist>();
  
        Map<String,String> justPag = new Map<String,String>();
		Schema.DescribeFieldResult fieldResult = PagamentoGarantia__c.JustPagAdc__c.getDescribe();
		List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
		for( Schema.PicklistEntry pickListVal : ple){
            justPag.put(pickListVal.getValue(), pickListVal.getLabel());
		}

        for(String key : justPag.keyset()){
            innerPicklist entry = new innerPicklist();
            entry.value = key;
            entry.label = justPag.get(key);
            justPagToReturn.add(entry);
        }

        mapToReturn.put('justificativasPagamento',justPagToReturn);

        return mapToReturn;
    }

    // PLV-4163 FIX2 INICIO
    @AuraEnabled
    public static Map<String,Object> criarGarantia(String recordId, String justPag, Decimal valor){
        Map<String,Object> mapToReturn = new Map<String,Object>();
        
        PagamentoGarantia__c garantiaSin =[ SELECT  Id, Name, Garantia_do_segurado_do_contrato__c, Caso__c, Data_da_cotacao_da_moeda_estrangeira__c,
                                                    CurrencyIsoCode, Valor_da_cotacao_em_reais__c, Garantia_do_segurado_do_contrato__r.Capital__c
                                            FROM    PagamentoGarantia__c 
                                            WHERE   Id = :recordId];  

        // PLV-4163 FIX 3 - INICIO
        List<BeneficiarioGarantia__c> benGarList = new List<BeneficiarioGarantia__c> ([
            SELECT  Id, Pagamento_de_garantia__c, Conta__c, Endereco__c, IdExterno__c, CurrencyIsoCode, Name,
                    RelacionamentoSegurado__c, Sucursal_Destino_de_Cheque__c, Tipo_de_Pagamento__c
            FROM    BeneficiarioGarantia__c
            WHERE Pagamento_de_garantia__c = :recordId
        ]);

        PagamentoGarantia__c novaGarantia = new PagamentoGarantia__c();
        novaGarantia = garantiaSin;
        novaGarantia.id = null;
        novaGarantia.Fase__c = 'Em Análise';
        novaGarantia.Status_do_pagamento__c = 'Em análise';
        novaGarantia.JustPagAdc__c = justPag;
        novaGarantia.Capital__c = garantiaSin.Garantia_do_segurado_do_contrato__r.Capital__c;
        novaGarantia.Valor_indenizado__c = valor;        
        novaGarantia.IsPagAdc__c = true;

        
        Savepoint sp = Database.setSavepoint();
        try {

            Case caso = new Case();
            caso.Id = novaGarantia.Caso__c;
            caso.Status_Dependente__c = 'Aguardando Pagamento';
            update caso;

            insert novaGarantia;
        // PLV-4163 FIX 3 - FIM

            List<BeneficiarioGarantia__c> benGarToIns = new List<BeneficiarioGarantia__c>();

        if( !benGarList.isEmpty() ){
            for( BeneficiarioGarantia__c bg : benGarList){
                BeneficiarioGarantia__c bene = bg;
                bene.Id = null;
                bene.Pagamento_de_garantia__c = novaGarantia.Id;
                benGarToIns.add(bene);
            }
        }

            insert benGarToIns;
            mapToReturn.put('sucesso', true);
                    
        } catch (Exception e) {
    	    Database.rollback(sp);
            System.debug('Erro ao criar novo pagamento'+ e.getLineNumber() + ' - '+e.getMessage());           
            mapToReturn.put('sucesso', false);         
            mapToReturn.put('mensagem', 'Erro ao criar novo pagamento: '+ e.getMessage());         
        }

        // PLV-4163 FIX2 FIM

        return mapToReturn;
    }
}