workspace-sf/force-app/main/default/objects/RemuneracaoProposta__c/RemuneracaoProposta__c.object-meta.xml
<CustomObject>
    <description>Objeto de relacionamento entre a proposta e o tipo de remuneração.</description>
    <label>Remuneração da proposta</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Remunerações da proposta</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/RemuneracaoProposta__c/fields/Proposta__c.field-meta.xml
<CustomField>
    <fullName>Proposta__c</fullName>
    <label>Proposta</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Remunerações da proposta</relationshipLabel>
    <relationshipName>RemuneracoesProposta</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/classes/ExpurgoRemuneracaoProposta.cls
/**
 * Expurgo de dados para o Proposta
 *  objeto: RemuneracaoProposta__c 
 * caminho do objeto:
 *  > RemuneracaoProposta__c 
 *  > Proposta__c
 * 
 * 28/02/2024
 */

public with sharing class ExpurgoRemuneracaoProposta {

    public List<RemuneracaoProposta__c> getDadosExpurgo(Integer qt) { 
        List<RemuneracaoProposta__c> expList= new List<RemuneracaoProposta__c>();
        String query= 'SELECT Id '
            +'FROM RemuneracaoProposta__c '
            +'WHERE Proposta__r.Segmento__c = \'Massificados\' ';
        if (qt != 0) {
            query+= 'LIMIT :qt';
        }
        expList= Database.queryWithBinds(query, new Map<String,Object>{'qt' => qt}, AccessLevel.SYSTEM_MODE);
        System.debug(expList);
        return expList;
    }

    public void deleteDadosExpurgo(List<RemuneracaoProposta__c> expList) {
        if (!Test.isRunningTest()) {
           delete (List<RemuneracaoProposta__c>)expList;
        }
    }
}