workspace-sf/force-app/main/default/objects/Carencia__c/Carencia__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar o cadastro de carências</description>
    <label>Carência</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Carências</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/Carencia__c/fields/FimPeriodo__c.field-meta.xml
<CustomField>
    <fullName>FimPeriodo__c</fullName>
    <label>Fim do período</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Carencia__c/fields/FormaCarencia__c.field-meta.xml
<CustomField>
    <fullName>FormaCarencia__c</fullName>
    <label>Forma de carência</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Escalonada</fullName>
            </value>
            <value>
                <fullName>Simples</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/Carencia__c/fields/InicioPeriodo__c.field-meta.xml
<CustomField>
    <fullName>InicioPeriodo__c</fullName>
    <label>InicioPeriodo</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Carencia__c/fields/TipoPeriodo__c.field-meta.xml
<CustomField>
    <fullName>TipoPeriodo__c</fullName>
    <label>Tipo de período</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Dia(s)</fullName>
            </value>
            <value>
                <fullName>Semana(s)</fullName>
            </value>
            <value>
                <fullName>Mês(es)</fullName>
            </value>
            <value>
                <fullName>Ano(s)</fullName>
            </value>
            <value>
                <fullName>Bimestre(s)</fullName>
            </value>
            <value>
                <fullName>Trimestre(s)</fullName>
            </value>
            <value>
                <fullName>Quadrimestre(s)</fullName>
            </value>
            <value>
                <fullName>Semestre(s)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/Carencia__c/fields/ValorBase__c.field-meta.xml
<CustomField>
    <fullName>ValorBase__c</fullName>
    <label>Valor base</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Capital</fullName>
            </value>
            <value>
                <fullName>Salário</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/classes/CarenciaFactory.cls
/**
 * @author AVX - Daniel Zampieri
 * @date 2019-06-27
 * @description Carencia__c Factory Class
 */
@isTest
public class CarenciaFactory extends SObjectFactory{

	private static Carencia__c staticRecord;

	private static Carencia__c getRecordStatic(){

		if(staticRecord == null){
			staticRecord = new Carencia__c(
				Name = 'TesteCarencia',
				FormaCarencia__c = 'Simples',
				TipoPeriodo__c = 'Dia(s)',
				ValorBase__c = 'Capital'
				//PLV-4175-Início
				//InicioPeriodo__c = 1,
				//FimPeriodo__c = 10
				//PLV-4175-Fim
            );
		}
		return staticRecord;
	}

	public CarenciaFactory() {

		super(getRecordStatic());
	}

}