workspace-sf/force-app/main/default/objects/FormaPagamento__c/FormaPagamento__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar o cadastro das formas de pagamento</description>
    <label>Forma de pagamento</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Formas de pagamento</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/PremioMinimoProduto__c/PremioMinimoProduto__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar as regras de prêmio mínimo do produto</description>
    <label>Forma de pagamento e Prêmio Mínimo</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Formas de pagamentos e Prêmios Mínimos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/PremioMinimoProduto__c/fields/FormaPagamento__c.field-meta.xml
<CustomField>
    <fullName>FormaPagamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Forma de pagamento</label>
    <referenceTo>FormaPagamento__c</referenceTo>
    <relationshipName>PremiosFormaPagamento</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/PremioMinimoProduto__c/fields/PeriodicidadePagamento__c.field-meta.xml
<CustomField>
    <fullName>PeriodicidadePagamento__c</fullName>
    <label>Periodicidade de pagamento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Anual</fullName>
            </value>
            <value>
                <fullName>Mensal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/PremioMinimoProduto__c/fields/PremioMinimoProduto__c.field-meta.xml
<CustomField>
    <fullName>PremioMinimoProduto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prêmio minimo do produto</label>
    <referenceTo>PremioMinimoProduto__c</referenceTo>
    <relationshipName>PremiosMinimoProduto</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/PremioMinimoProduto__c/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>PremiosMinimoProduto</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/PremioMinimoProduto__c/fields/TipoContratacao__c.field-meta.xml
<CustomField>
    <fullName>TipoContratacao__c</fullName>
    <label>Tipo de contratação</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Endosso</fullName>
            </value>
            <value>
                <fullName>Novo</fullName>
            </value>
            <value>
                <fullName>Renovação</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/classes/PremioMinimoProdutoBO.cls
/**************************************************************************************************************************************************************************
 * 
 *	Classe responsável pelo negócio do objeto de PremioMinimoProduto__c
 *
 **************************************************************************************************************************************************************************/
public  class PremioMinimoProdutoBO {
	private static final PremioMinimoProdutoBO instancia = new PremioMinimoProdutoBO();
	private PremioMinimoProdutoDAO dao = PremioMinimoProdutoDAO.getInstance();

	private PremioMinimoProdutoBO() {
	}

	public static PremioMinimoProdutoBO getInstance(){
		return instancia;
	}

	/**
     * Realiza validação se algum cadastro existente na base. Metodo de trigger
     *
     * @param premiosProduto  - lista dos itens de premios do produto a ser validado
     */
    public void validarPremiosMinimo(List<PremioMinimoProduto__c> premiosProduto){
    	Set<Id> produtosIds = new Set<Id>();
    	Set<Id> premiosMinimosIds = new Set<Id>();
    	Set<String> valoresExistentes = new Set<String>();

    	//Extrai valores
    	for(PremioMinimoProduto__c premio : premiosProduto){
    		premiosMinimosIds.add(premio.Id);
    		produtosIds.add(premio.Produto__c);
    	}

    	List<PremioMinimoProduto__c> premiosExistentes = dao.buscarPremios(produtosIds, premiosMinimosIds);

    	//Se achou algo, verifica se algum registro é extamente igual ao que está sendo inserido/atualizado (de acordo com uma garantia de produto)
    	if(!premiosExistentes.isEmpty()){
    		//Monta set com a combinacao de valores a serem validados
	    	for(PremioMinimoProduto__c premioExistente : premiosExistentes){
	    		valoresExistentes.add(premioExistente.FormaPagamento__c + premioExistente.TipoContratacao__c + premioExistente.PeriodicidadePagamento__c);
	    	}

	    	//Realiza validação
	    	for(PremioMinimoProduto__c premio : premiosProduto){
	    		if(valoresExistentes.contains(premio.FormaPagamento__c + premio.TipoContratacao__c + premio.PeriodicidadePagamento__c)){
	    			premio.addError('Cadastro de prêmio já existente para estes valores');
	    		}
	    	}
    	}
    }


    /*********************************************************************************************************
    *
    * Habilita novamente a flag que permite que as regra de limite sejam executadas
    *
    *********************************************************************************************************/
    public void habilitarValidacaoRegrasProdutoComercial(List<PremioMinimoProduto__c> premiosMinimo){
        RegrasFabricaProdutos.habilitarValidacaoRegrasProdutoComercial(premiosMinimo, 'PremioMinimoProduto__c', 'PremioMinimoProdutoHandler');
    }
}