workspace-sf/force-app/main/default/objects/FormaPagamento__c/FormaPagamento__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar o cadastro das formas de pagamento</description>
    <label>Forma de pagamento</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Formas de pagamento</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/FormaPagamento__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <label>Código</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/FormaPagamento__c/fields/RamoSeguro__c.field-meta.xml
<CustomField>
    <fullName>RamoSeguro__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ramo de seguro</label>
    <referenceTo>RamoSeguro__c</referenceTo>
    <relationshipLabel>Formas de pagamento</relationshipLabel>
    <relationshipName>FormasPagamento</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/RamoSeguro__c/RamoSeguro__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar o cadastro dos ramos de seguro</description>
    <label>Ramo de seguro</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ramos de seguro</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/RamoSeguro__c/fields/CodigoEmpresa__c.field-meta.xml
<CustomField>
    <fullName>CodigoEmpresa__c</fullName>
    <label>Código da empresa</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/RamoSeguro__c/fields/IdExterno__c.field-meta.xml
<CustomField>
    <fullName>IdExterno__c</fullName>
    <externalId>true</externalId>
    <label>Id externo</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

workspace-sf/force-app/main/default/classes/FormaPagametoBO.cls
/**************************************************************************************************************************************************************************
 * 
 *	Classe responsável pelo negócio do objeto de Forma de pagamento
 *
 **************************************************************************************************************************************************************************/
public  class FormaPagametoBO {
	private static final FormaPagametoBO instancia = new FormaPagametoBO();
	private FormaPagamentoDAO dao = FormaPagamentoDAO.getInstance();

	private FormaPagametoBO() {	
	}

	public static FormaPagametoBO getInstance(){
		return instancia;
	}

	/**
	 * Realiza a busca de formas de pagamento via serviço externo, e atualiza Salesforce
	 *
	 */
	public void sincronizarFormasPagamento(){
		List<FormaPagamento__c> formasPagamentoSincronizar = new List<FormaPagamento__c>();
		Date dataAtual = System.today();
		String vigencia = String.valueOf(dataAtual.year()) + '-' + String.valueOf(dataAtual.month()) + '-' + String.valueOf(dataAtual.day());

		for(RamoSeguro__c ramo : RamoSeguroBO.getInstance().listarRamos()){	
			for(ServiceTO.FormaPagamentoTO formaPgto : F5Service.getInstance().buscarFormasPagamento(ramo.CodigoEmpresa__c, ramo.Codigo__c, vigencia) ) {
				formasPagamentoSincronizar.add(
					new FormaPagamento__c(
						Codigo__c = formaPgto.codigoPlanoParcelamento,
						Name = formaPgto.descricaoPlanoParcelamento,
						IdExterno__c = ramo.Id + '|' + formaPgto.codigoModalidade + '|' + formaPgto.codigoPlanoParcelamento
					)
				);
			}
		}

		if(!formasPagamentoSincronizar.isEmpty()){
			upsert formasPagamentoSincronizar IdExterno__c;
		}
	}

	//Retorna todas as formas de pagamento relacionado com um os ramos de seguro passador por parametro
	public List<FormaPagamento__c> buscarFormasPagamentoPorIds(Set<Id> idsFormaPagamento){
		return dao.buscarFormasPagamentoPorIds(idsFormaPagamento);
	}
}