workspace-sf/force-app/main/default/objects/CriticaProposta__c/CriticaProposta__c.object-meta.xml
<CustomObject>
    <description>Objeto responsável por armazenar as críticas da proposta</description>
    <label>Crítica da proposta</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Críticas da proposta</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/CriticaProposta__c/fields/MomentoAnalise__c.field-meta.xml
<CustomField>
    <fullName>MomentoAnalise__c</fullName>
    <label>Momento de análise</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Análise interna</fullName>
            </value>
            <value>
                <fullName>Subscrição</fullName>
            </value>
            <value>
                <fullName>Resseguro</fullName>
            </value>
            <value>
                <fullName>Recalculo</fullName>
                <label>Recálculo</label>
            </value>
            <value>
                <fullName>Crítica de Controle</fullName>
            </value>
            <value>
                <fullName>Palavra final</fullName>
            </value>
            <value>
                <fullName>Renovação</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/CriticaProposta__c/fields/Proposta__c.field-meta.xml
<CustomField>
    <fullName>Proposta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proposta</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Críticas da proposta</relationshipLabel>
    <relationshipName>CriticasProposta</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/CriticaProposta__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Não iniciada</fullName>
            </value>
            <value>
                <fullName>Pendente</fullName>
            </value>
            <value>
                <fullName>Em aprovação</fullName>
            </value>
            <value>
                <fullName>Condicionada</fullName>
            </value>
            <value>
                <fullName>Inconclusiva</fullName>
            </value>
            <value>
                <fullName>Liberado</fullName>
            </value>
            <value>
                <fullName>Recusado</fullName>
            </value>
            <value>
                <fullName>Cancelada</fullName>
            </value>
            <value>
                <fullName>Pendenciado</fullName>
            </value>
            <value>
                <fullName>Falha na Integração</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/CriticaProposta__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Analise</fullName>
                <label>Análise</label>
            </value>
            <value>
                <fullName>Aviso</fullName>
            </value>
            <value>
                <fullName>CriticaSAP</fullName>
                <label>Crítica SAP</label>
            </value>
            <value>
                <fullName>Pendencia</fullName>
                <label>Pendência</label>
            </value>
            <value>
                <fullName>Recusa</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/classes/BatchReestimuloProposta.cls
/****************************************************************************************************************************
 * Classe de Negocio implementada para o processo automático de alteração de Status de Propostas que já foram liberadas     *
 * @author : Globant                                                                                                        *
 * @date 09/11/2023                                                                                                         *
 * Classe implementada tendo como origem a história PLV-5856                                                                *
 * **************************************************************************************************************************/
global class BatchReestimuloProposta implements Database.Batchable<SObject>, Schedulable, Database.Stateful{
    global Set<String> quoteNames {get;set;}
    global Set<String> updatedQuoteNames {get;set;} //PLV-5856 FIX-03 INICIO/FIM
    global List<String> emailAdress {get;set;}
    
    global BatchReestimuloProposta(){
        this.quoteNames = new Set<String>();
        this.emailAdress = new List<String>();
        this.updatedQuoteNames = new Set<String>(); //PLV-5856 FIX-03 INICIO/FIM
    }

    global Database.QueryLocator start(Database.BatchableContext bc) {
        String query = 'select id, Status__c, Proposta__c, Proposta__r.Name from CriticaProposta__c where MomentoAnalise__c = \'Palavra final\' and Status__c =\'Liberado\' and Proposta__r.Status =\'Em análise\'and Proposta__r.Tipo__c != \'Renovacao\' AND Proposta__r.Contract.Id = null'; //PLV-5856 FIX-03 INICIO/FIM
        return Database.getQueryLocator(query);
    }
    global void execute(Database.BatchableContext bc, List<CriticaProposta__c> records){
        //PLV-5856 FIX 01 INICIO
        Set<Quote> quoteSet = new Set<Quote>();

        for(CriticaProposta__c record: records){
            Quote toUpdate = new Quote();
            toUpdate.id = record.Proposta__c;
            toUpdate.Status = 'Disponível para contratação';
            toUpdate.name = record.Proposta__r.name; //PLV-5856 FIX-03 INICIO/FIM
            quoteSet.add(toUpdate);
            this.quoteNames.add(record.Proposta__r.Name);
        }
        List<Quote> listOfQuotes = new List<Quote>(quoteSet);

        //PLV-5856 FIX 06 INICIO
        Integer scheduledJobCount = [SELECT COUNT() FROM CronJobDetail WHERE JobType = '7'];

        Integer controleRegistrosCrt = 100 - scheduledJobCount;  
        //PLV-5856 FIX 06 FIM

        Integer count = 1; //PLV-5856 FIX-04 INICIO/FIM
        for(Quote QuoteUpdate : listOfQuotes){
            if(count <= controleRegistrosCrt){ //PLV-5856 FIX-04 INICIO/FIM
                String minute = string.valueOf(system.now().minute() +1); //PLV-5856 FIX-03 INICIO/FIM        
                String second = string.valueOf(count); //PLV-5856 FIX 05 INICIO/FIM
                
                String jobName = '30_Job_' + string.valueOf(QuoteUpdate.id);
                String cronTime = second+' '+minute+' * * * ?';
                BatchReestimuloPropostaJob jobClass = new BatchReestimuloPropostaJob();
                jobClass.quoteToUpdate = QuoteUpdate;
                if(!Test.isRunningTest()) System.schedule(jobName, cronTime, jobClass); //PLV-5856 FIX 02 INICIO/FIM
                this.updatedQuoteNames.add(QuoteUpdate.name);
            }
            count++; //PLV-5856 FIX-04 INICIO/FIM
        }

        //PLV-5856 FIX 01 FIM
    }
    
    global void finish(Database.BatchableContext bc){
        if (!this.updatedQuoteNames.isEmpty()){ //PLV-5856 FIX-03 INICIO/FIM
            StaticResource srObject = [SELECT id, body FROM StaticResource WHERE Name = 'EmailsReestimulo' LIMIT 1];
            String contents = srObject.body.toString();
            this.emailAdress = contents.split(',');
            
            //PLV-5856 FIX 03 INICIO
            String bodyToSend = 'Propostas que tiveram o status alterado para \'Disponível para contratação\' pelo processo de reestimulo de propostas: #listaQuote# <br> Data de execução:  #processDate# <br> Número de propostas que restam processar: #numQuotesNaoProcessada# ';
            
            String numQuotesNaoProcessada = String.ValueOf(this.quoteNames.size() - this.updatedQuoteNames.size());
            String stringQuotesValue = '';
            for(String quoteName : this.updatedQuoteNames){
                stringQuotesValue = stringQuotesValue + quoteName +'<br>'; 
            }

            bodyToSend = bodyToSend.replace('#listaQuote#', stringQuotesValue);
            bodyToSend = bodyToSend.replace('#numQuotesNaoProcessada#', numQuotesNaoProcessada);
            //PLV-5856 FIX 03 FIM
            bodyToSend = bodyToSend.replace('#processDate#', String.valueOf(date.today()));
            
            Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
            email.setToAddresses(this.emailAdress);
            email.setSubject('Reestimulo Propostas ' + date.today().format());
            email.setHtmlBody(bodyToSend);
    
            Messaging.SendEmailResult[] results = Messaging.sendEmail(new Messaging.SingleEmailMessage[] { email });    
        }
    }
    
    global void execute(SchedulableContext SC)
    {
        BatchReestimuloProposta batchPropostas = new BatchReestimuloProposta();
        Database.executeBatch(batchPropostas);
    }

    global void scheduleBatch() {

        String cron1  = ' 0 0 9 * * ?';
        String cron2 = ' 0 0 16 * * ?';

        system.schedule('ReestimuloProposta1', cron1, this);
        system.schedule('ReestimuloProposta2', cron2, this);
    }
}