workspace-sf/force-app/main/default/objects/CriticaProposta__c/CriticaProposta__c.object-meta.xml
<CustomObject>
    <description>Objeto responsável por armazenar as críticas da proposta</description>
    <label>Crítica da proposta</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Críticas da proposta</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/CriticaProposta__c/fields/Proposta__c.field-meta.xml
<CustomField>
    <fullName>Proposta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proposta</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Críticas da proposta</relationshipLabel>
    <relationshipName>CriticasProposta</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/classes/ExpurgoCriticaProposta.cls
/**
 * Expurgo de dados para o Proposta
 *  objeto: CriticaProposta__c  
 * caminho do objeto:
 *  > CriticaProposta__c  
 *  > Proposta__c
 * 
 * 28/02/2024
 */


public with sharing class ExpurgoCriticaProposta {
    public List<CriticaProposta__c> getDadosExpurgo(Integer qt) { 
        List<CriticaProposta__c> expList= new List<CriticaProposta__c>();
        String query= 'SELECT Id '
            +'FROM CriticaProposta__c '
            +'WHERE Proposta__r.Segmento__c = \'Massificados\' ';
        if (qt != 0) {
            query+= 'LIMIT :qt';
        }
        expList= Database.queryWithBinds(query, new Map<String,Object>{'qt' => qt}, AccessLevel.SYSTEM_MODE);
        System.debug(expList);
        return expList;
    }

    public void deleteDadosExpurgo(List<CriticaProposta__c> expList) {
        if (!Test.isRunningTest()) {
           delete (List<CriticaProposta__c>)expList;
        }
    }
}