workspace-sf/force-app/main/default/objects/CartaoCredito__c/CartaoCredito__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar as informações de cartão de crédito</description>
    <label>Cartão de crédito</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cartões de crédito</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/CartaoCredito__c/fields/CodigoSeguranca__c.field-meta.xml
<CustomField>
    <fullName>CodigoSeguranca__c</fullName>
    <label>Código de segurança</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/CartaoCredito__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cartões de crédito</relationshipLabel>
    <relationshipName>CartoesCredito</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/CartaoCredito__c/fields/NomeTitular__c.field-meta.xml
<CustomField>
    <fullName>NomeTitular__c</fullName>
    <label>Nome do titular</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/CartaoCredito__c/fields/NumeroCartao__c.field-meta.xml
<CustomField>
    <fullName>NumeroCartao__c</fullName>
    <label>Número do cartão</label>
    <length>175</length>
    <maskChar>asterisk</maskChar>
    <maskType>creditCard</maskType>
    <type>EncryptedText</type>
</CustomField>

workspace-sf/force-app/main/default/objects/CartaoCredito__c/fields/Vencimento__c.field-meta.xml
<CustomField>
    <fullName>Vencimento__c</fullName>
    <inlineHelpText>mm/aaaa</inlineHelpText>
    <label>Vencimento</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/classes/CartaoCreditoFactory.cls
/**
 * @author AVX - Renato Matheus Simião
 * @date 2019-09-11
 * @description Cartao Credito Factory Class (CartaoCredito__c)
 */
 @isTest
public class CartaoCreditoFactory{

	private static Map<String,CartaoCredito__c> mStaticRecord = new Map<String,CartaoCredito__c>();
    private static String teste = 'teste10';

//-----------------------------Cartao Credito Pessoa Física------------------------------------------

	private static CartaoCredito__c getRecordPessoaFisica(Account pAccount){

		if(!mStaticRecord.containsKey('PessoaFisica')){
		
			mStaticRecord.put('PessoaFisica', new CartaoCredito__c(
				Conta__c = pAccount.Id,
                NomeTitular__c = 'Porto Seguro Pessoa Fisica',
                NumeroCartao__c = '1234.5678.1234.5678',
                CodigoSeguranca__c = '123',
				Vencimento__c = '12/'+Date.today().year(),
                //PLV_2822 - INICIO - Informações do cartão de crédito não podem ser armazenadas no SF
                Ticket__c = '5678'
                //PLV_2822 - FIM - Informações do cartão de crédito não podem ser armazenadas no SF
            ));
		}
		return mStaticRecord.get('PessoaFisica');
	}

    public class PessoaFisica extends SObjectFactory {

        public PessoaFisica() {

            this(
                (Account) new AccountFactory.PessoaFisica().createRecord()
            );
        }

        public PessoaFisica(Account pAccount){

            super(getRecordPessoaFisica(pAccount));
        }
    }

    //------------------------------Cartao Credito Pessoa Jurídica----------------------------------------

    private static CartaoCredito__c getRecordPessoaJuridica(Account pAccount){

        if(!mStaticRecord.containsKey('PessoaJuridica')){
            //PLV_2822 - INICIO - Informações do cartão de crédito não podem ser armazenadas no SF
            mStaticRecord.put('PessoaJuridica', new CartaoCredito__c(
            //PLV_2822 - FIM - Informações do cartão de crédito não podem ser armazenadas no SF
                Conta__c = pAccount.Id,
                NomeTitular__c = 'Porto Seguro Pessoa Juridica',
                NumeroCartao__c = '1234.5678.1234.5679',
                CodigoSeguranca__c = '124',
                Vencimento__c = '12/'+Date.today().year(),
                //PLV_2822 - INICIO - Informações do cartão de crédito não podem ser armazenadas no SF
                Ticket__c = '5679'
                //PLV_2822 - FIM - Informações do cartão de crédito não podem ser armazenadas no SF
            ));
        }
        return mStaticRecord.get('PessoaJuridica');
    }

    public class PessoaJuridica extends SObjectFactory {
        
        public PessoaJuridica() {

            this(
                (Account) new AccountFactory.PessoaJuridica().createRecord()
            );
        }

        public PessoaJuridica(Account pAccount) {

            super(getRecordPessoaJuridica(pAccount));
        }
    }
}