workspace-sf/force-app/main/default/objects/CartaoCredito__c/CartaoCredito__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar as informações de cartão de crédito</description>
    <label>Cartão de crédito</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cartões de crédito</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/CartaoCredito__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cartões de crédito</relationshipLabel>
    <relationshipName>CartoesCredito</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/CondicaoCobranca__c/CondicaoCobranca__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar as condições de cobrança dos produtos</description>
    <label>Condição de cobrança</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Condições de cobrança</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/CondicaoCobranca__c/fields/FormaPagamento__c.field-meta.xml
<CustomField>
    <fullName>FormaPagamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Forma de pagamento</label>
    <referenceTo>FormaPagamento__c</referenceTo>
    <relationshipLabel>Condições de cobrança</relationshipLabel>
    <relationshipName>CondicoesCobranca</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/CondicaoCobranca__c/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Condições de cobrança</relationshipLabel>
    <relationshipName>CondicoesCobranca</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/ContratanteProposta__c/ContratanteProposta__c.object-meta.xml
<CustomObject>
    <description>Objeto responsável por armazenar o cadastro dos contratantes da proposta</description>
    <label>Contratante da proposta</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contratantes da proposta</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/ContratanteProposta__c/fields/CartaoCredito__c.field-meta.xml
<CustomField>
    <fullName>CartaoCredito__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cartão de crédito</label>
    <referenceTo>CartaoCredito__c</referenceTo>
    <relationshipLabel>Contratantes da proposta</relationshipLabel>
    <relationshipName>ContratantesProposta</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/ContratanteProposta__c/fields/Cidade__c.field-meta.xml
<CustomField>
    <fullName>Cidade__c</fullName>
    <label>Cidade</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/ContratanteProposta__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contratantes da proposta</relationshipLabel>
    <relationshipName>ContratantesProposta</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/ContratanteProposta__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AC</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AP</fullName>
            </value>
            <value>
                <fullName>AM</fullName>
            </value>
            <value>
                <fullName>BA</fullName>
            </value>
            <value>
                <fullName>CE</fullName>
            </value>
            <value>
                <fullName>DF</fullName>
            </value>
            <value>
                <fullName>ES</fullName>
            </value>
            <value>
                <fullName>GO</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MG</fullName>
            </value>
            <value>
                <fullName>PA</fullName>
            </value>
            <value>
                <fullName>PB</fullName>
            </value>
            <value>
                <fullName>PR</fullName>
            </value>
            <value>
                <fullName>PE</fullName>
            </value>
            <value>
                <fullName>PI</fullName>
            </value>
            <value>
                <fullName>RJ</fullName>
            </value>
            <value>
                <fullName>RN</fullName>
            </value>
            <value>
                <fullName>RS</fullName>
            </value>
            <value>
                <fullName>RO</fullName>
            </value>
            <value>
                <fullName>RR</fullName>
            </value>
            <value>
                <fullName>SC</fullName>
            </value>
            <value>
                <fullName>SP</fullName>
            </value>
            <value>
                <fullName>SE</fullName>
            </value>
            <value>
                <fullName>TO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/ContratanteProposta__c/fields/FormaPagamento__c.field-meta.xml
<CustomField>
    <fullName>FormaPagamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Forma de pagamento</label>
    <referenceTo>FormaPagamento__c</referenceTo>
    <relationshipLabel>Contratantes da proposta</relationshipLabel>
    <relationshipName>ContratantesProposta</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/ContratanteProposta__c/fields/NumeroEndereco__c.field-meta.xml
<CustomField>
    <fullName>NumeroEndereco__c</fullName>
    <label>Número do endereço</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/ContratanteProposta__c/fields/PremioTotal__c.field-meta.xml
<CustomField>
    <fullName>PremioTotal__c</fullName>
    <label>Prêmio total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

workspace-sf/force-app/main/default/objects/ContratanteProposta__c/fields/Proposta__c.field-meta.xml
<CustomField>
    <fullName>Proposta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proposta</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Contratantes da proposta</relationshipLabel>
    <relationshipName>ContratantesProposta</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/ContratanteProposta__c/fields/QuantidadeParcelas__c.field-meta.xml
<CustomField>
    <fullName>QuantidadeParcelas__c</fullName>
    <label>Quantidade de parcelas</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

workspace-sf/force-app/main/default/objects/ContratanteProposta__c/fields/ResponsavelPagamento__c.field-meta.xml
<CustomField>
    <fullName>ResponsavelPagamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Responsável pelo pagamento</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contratantes da proposta (Responsável pelo pagamento)</relationshipLabel>
    <relationshipName>ContratantesPropostaDependente</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/ContratanteProposta__c/fields/TipoEndereco__c.field-meta.xml
<CustomField>
    <fullName>TipoEndereco__c</fullName>
    <inlineHelpText>O campo &quot;recado&quot;  foi removido. diferente da picklist Tipo de endereço do objeto Endereço, o objeto Segurado da proposta terá dois campos de endereço. Um como o endereço principal e outro como endereço de correspondência, inutilizando o campo &quot;recado&quot;</inlineHelpText>
    <label>Tipo de endereço</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Comercial</fullName>
            </value>
            <value>
                <fullName>Residencial</fullName>
            </value>
            <value>
                <fullName>Veraneio</fullName>
            </value>
            <value>
                <fullName>Recado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/ContratanteProposta__c/fields/TipoLogradouro__c.field-meta.xml
<CustomField>
    <fullName>TipoLogradouro__c</fullName>
    <label>Tipo de logradouro</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Alameda</fullName>
            </value>
            <value>
                <fullName>Avenida</fullName>
            </value>
            <value>
                <fullName>Rua</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/FormaPagamento__c/FormaPagamento__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar o cadastro das formas de pagamento</description>
    <label>Forma de pagamento</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Formas de pagamento</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/FormaPagamento__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <label>Código</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GrupoProposta__c/GrupoProposta__c.object-meta.xml
<CustomObject>
    <description>Objeto responsável por armazenar o cadastro dos grupos de segurados da proposta</description>
    <label>Grupo da proposta</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grupos da proposta</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/GrupoProposta__c/fields/ContratanteProposta__c.field-meta.xml
<CustomField>
    <fullName>ContratanteProposta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contratante da proposta</label>
    <referenceTo>ContratanteProposta__c</referenceTo>
    <relationshipLabel>Grupos da proposta</relationshipLabel>
    <relationshipName>GruposProposta</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/InformacaoBancaria__c/InformacaoBancaria__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar as informações bancárias das contas</description>
    <label>Informação bancária</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Informações bancárias</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/InformacaoBancaria__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>InformacoesBancarias</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Pais__c/Pais__c.object-meta.xml
<CustomObject>
    <description>Objeto responsável por armazenar os dados dos países</description>
    <label>País</label>
    <nameField>
        <label>Pais Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Países</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/Pais__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <externalId>true</externalId>
    <label>Código</label>
    <length>8</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

workspace-sf/force-app/main/default/objects/SeguradoProposta__c/SeguradoProposta__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar os segurados da proposta</description>
    <label>Segurado da proposta</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Segurados da proposta</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/SeguradoProposta__c/fields/CartaoCredito__c.field-meta.xml
<CustomField>
    <fullName>CartaoCredito__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cartão de crédito</label>
    <referenceTo>CartaoCredito__c</referenceTo>
    <relationshipLabel>Segurados da proposta</relationshipLabel>
    <relationshipName>SeguradosProposta</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/SeguradoProposta__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Segurados da proposta</relationshipLabel>
    <relationshipName>SeguradosProposta</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/SeguradoProposta__c/fields/FormaPagamento__c.field-meta.xml
<CustomField>
    <fullName>FormaPagamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Forma de pagamento</label>
    <referenceTo>FormaPagamento__c</referenceTo>
    <relationshipLabel>Segurados da proposta</relationshipLabel>
    <relationshipName>SeguradosProposta</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/SeguradoProposta__c/fields/PremioTotal__c.field-meta.xml
<CustomField>
    <fullName>PremioTotal__c</fullName>
    <label>Prêmio total</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Currency</type>
</CustomField>

workspace-sf/force-app/main/default/objects/SeguradoProposta__c/fields/ResponsavelPagamento__c.field-meta.xml
<CustomField>
    <fullName>ResponsavelPagamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Responsável pelo pagamento</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Segurados da proposta (Responsável pelo pagamento)</relationshipLabel>
    <relationshipName>SeguradosPropostaDependente</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/classes/QuoteComplementoTest.cls
/**************************************************************************************************************************************************************************
 * 
 *	Classe responsável pelos testes no objeto Quote
 *
 **************************************************************************************************************************************************************************/

@isTest
private class QuoteComplementoTest {

    public static final QuoteBO bo = QuoteBO.getInstance();

    @TestSetup
    static void setup(){
        TestDataFactory.gerarDadosSetup();
	    // PLV-2312-28 INICIO
        TestDataFactory.gerarProposta(true);
	    // PLV-2312-28 FIM
    }

    @IsTest
    static void testValidarDadosPagamentoContratantePropostaSemCartaoCredito(){
        // Recupera dados
        Quote proposta = [SELECT Id, Produto__c FROM Quote LIMIT 1];
        Account conta = [SELECT Id FROM Account LIMIT 1];
        FormaPagamento__c formaPagamento = [SELECT Id FROM FormaPagamento__c LIMIT 1];
        Product2 produto = [SELECT Id FROM Product2 WHERE Id =: proposta.Produto__c LIMIT 1];
        String erroEsperado = '';

        // Apaga todos os contratantes da Proposta para gerar um novo
        List<ContratanteProposta__c> listContratantePropostaParaDeletar = [SELECT Id FROM ContratanteProposta__c WHERE Proposta__c =: proposta.Id];
        delete listContratantePropostaParaDeletar;

        // Apaga todas as condicoes de cobranca
        List<CondicaoCobranca__c> listCondicaoCobranca = [SELECT Id FROM CondicaoCobranca__c];
        delete listCondicaoCobranca;

        // altera a forma de pagamento para cartao de credito
        formaPagamento.Codigo__c = 'CAT';
        // não é permitido esta alteração: formaPagamento.Name = 'Cartão de Crédito';
        update formaPagamento;

        // cria uma condicao de cobraca para cartao de credito
        CondicaoCobranca__c condicaoCobranca = new CondicaoCobranca__c(
            FormaPagamento__c = formaPagamento.Id,
            QuantidadeParcelas__c = '5',
            Produto__c = produto.Id
        );
        insert condicaoCobranca;

        // Apaga os cartões de credito do responsavel pelo pagamento
        List<CartaoCredito__c> listCartaoCredito = [SELECT Id FROM CartaoCredito__c WHERE Conta__c =: conta.Id];
        delete listCartaoCredito;

        // Gera um contratante da proposta
        ContratanteProposta__c contratanteProposta = new ContratanteProposta__c(
            Conta__c = conta.Id,
            Proposta__c = proposta.Id,
            Tipo__c = 'Principal',
            TipoEndereco__c = 'Residencial',
            Cep__c = '03020-000',
            TipoLogradouro__c = 'Rua',
            Logradouro__c = '15',
            NumeroEndereco__c = '15',
            Bairro__c = 'Osasco',
            Cidade__c = 'São Paulo',
            Estado__c = 'SP',
            Pais__c = 'Brasil',
            ResponsavelPagamento__c = conta.Id,
            FormaPagamento__c = formaPagamento.Id,
            PremioTotal__c = 10
        );

        Test.startTest();

        try{
            // Insere o contratante
            insert contratanteProposta;
        }catch (Exception e){
            erroEsperado = e.getMessage();
        }

        Test.stopTest();

        System.debug('====> Erro esperado: ' + erroEsperado);

        // Valida se o contratante foi criado
        System.assert(erroEsperado.contains('Insert failed'));
        System.assert(erroEsperado.contains('FIELD_CUSTOM_VALIDATION_EXCEPTION'));
        System.assert(erroEsperado.contains('Para cartão de crédito é necessário ter um cartão cadastrado!'));
    }

    @IsTest
    static void testValidarDadosPagamentoContratantePropostaSemCartaoCreditoPorto(){
        // Recupera dados
        Quote proposta = [SELECT Id, Produto__c FROM Quote LIMIT 1];
        Account conta = [SELECT Id FROM Account LIMIT 1];
        FormaPagamento__c formaPagamento = [SELECT Id FROM FormaPagamento__c LIMIT 1];
        Product2 produto = [SELECT Id FROM Product2 WHERE Id =: proposta.Produto__c LIMIT 1];
        String erroEsperado = '';

        // Apaga todos os contratantes da Proposta para gerar um novo
        List<ContratanteProposta__c> listContratantePropostaParaDeletar = [SELECT Id FROM ContratanteProposta__c WHERE Proposta__c =: proposta.Id];
        delete listContratantePropostaParaDeletar;

        // Apaga todas as condicoes de cobranca
        List<CondicaoCobranca__c> listCondicaoCobranca = [SELECT Id FROM CondicaoCobranca__c];
        delete listCondicaoCobranca;

        // altera a forma de pagamento para cartao de credito
        formaPagamento.Codigo__c = 'CPO';
        update formaPagamento;

        // cria uma condicao de cobraca para cartao de credito
        CondicaoCobranca__c condicaoCobranca = new CondicaoCobranca__c(
            FormaPagamento__c = formaPagamento.Id,
            QuantidadeParcelas__c = '5',
            Produto__c = produto.Id
        );
        insert condicaoCobranca;

        // Apaga os cartões de credito do responsavel pelo pagamento
        List<CartaoCredito__c> listCartaoCredito = [SELECT Id FROM CartaoCredito__c WHERE Conta__c =: conta.Id];
        delete listCartaoCredito;

        // Gera um contratante da proposta
        ContratanteProposta__c contratanteProposta = new ContratanteProposta__c(
            Conta__c = conta.Id,
            Proposta__c = proposta.Id,
            Tipo__c = 'Principal',
            TipoEndereco__c = 'Residencial',
            Cep__c = '03020-000',
            TipoLogradouro__c = 'Rua',
            Logradouro__c = '15',
            NumeroEndereco__c = '15',
            Bairro__c = 'Osasco',
            Cidade__c = 'São Paulo',
            Estado__c = 'SP',
            Pais__c = 'Brasil',
            ResponsavelPagamento__c = conta.Id,
            FormaPagamento__c = formaPagamento.Id,
            PremioTotal__c = 10
        );

        Test.startTest();

        try{
            // Insere o contratante
            insert contratanteProposta;
        }catch (Exception e){
            erroEsperado = e.getMessage();
        }

        Test.stopTest();

        // Valida se o contratante foi criado
        System.assert(erroEsperado.contains('Insert failed'));
        System.assert(erroEsperado.contains('FIELD_CUSTOM_VALIDATION_EXCEPTION'));
        System.assert(erroEsperado.contains('Para pagamento no cartão de crédito Porto é necessário ter um cartão Porto cadastrado!'));
    }


    @IsTest
    static void testValidarDadosPagamentoContratantePropostaSemInformacaoBancaria(){
        // Recupera dados
        Quote proposta = [SELECT Id, Produto__c FROM Quote LIMIT 1];
        Account conta = [SELECT Id FROM Account LIMIT 1];
        FormaPagamento__c formaPagamento = [SELECT Id FROM FormaPagamento__c LIMIT 1];
        Product2 produto = [SELECT Id FROM Product2 WHERE Id =: proposta.Produto__c LIMIT 1];
        String erroEsperado = '';

        // Apaga todos os contratantes da Proposta para gerar um novo
        List<ContratanteProposta__c> listContratantePropostaParaDeletar = [SELECT Id FROM ContratanteProposta__c WHERE Proposta__c =: proposta.Id];
        delete listContratantePropostaParaDeletar;

        // Apaga todas as condicoes de cobranca
        List<CondicaoCobranca__c> listCondicaoCobranca = [SELECT Id FROM CondicaoCobranca__c];
        delete listCondicaoCobranca;

        // altera a forma de pagamento para cartao de credito
        formaPagamento.Codigo__c = 'ADC';
        update formaPagamento;

        // cria uma condicao de cobraca para cartao de credito
        CondicaoCobranca__c condicaoCobranca = new CondicaoCobranca__c(
            FormaPagamento__c = formaPagamento.Id,
            QuantidadeParcelas__c = '5',
            Produto__c = produto.Id
        );
        insert condicaoCobranca;

        // Apaga os cartões de credito do responsavel pelo pagamento
        List<InformacaoBancaria__c> listInformacaoBancaria = [SELECT Id FROM InformacaoBancaria__c WHERE Conta__c =: conta.Id];
        delete listInformacaoBancaria;

        // Gera um contratante da proposta
        ContratanteProposta__c contratanteProposta = new ContratanteProposta__c(
            Conta__c = conta.Id,
            Proposta__c = proposta.Id,
            Tipo__c = 'Principal',
            TipoEndereco__c = 'Residencial',
            Cep__c = '03020-000',
            TipoLogradouro__c = 'Rua',
            Logradouro__c = '15',
            NumeroEndereco__c = '15',
            Bairro__c = 'Osasco',
            Cidade__c = 'São Paulo',
            Estado__c = 'SP',
            Pais__c = 'Brasil',
            ResponsavelPagamento__c = conta.Id,
            FormaPagamento__c = formaPagamento.Id,
            PremioTotal__c = 10
        );

        Test.startTest();

        try{
            // Insere o contratante
            insert contratanteProposta;
        }catch (Exception e){
            erroEsperado = e.getMessage();
        }

        Test.stopTest();

        // Valida se o contratante foi criado
        System.assert(erroEsperado.contains('Insert failed'));
        System.assert(erroEsperado.contains('FIELD_CUSTOM_VALIDATION_EXCEPTION'));
        System.assert(erroEsperado.contains('Para débito em conta é necessário ter uma informação bancária cadastrada!'));
    }

    @IsTest
    static void testValidarDadosPagamentoVidaProposta(){
        // Recupera dados
        Quote proposta = [SELECT Id FROM Quote LIMIT 1];
        Account conta = [SELECT Id FROM Account LIMIT 1];
        FormaPagamento__c formaPagamento = [SELECT Id FROM FormaPagamento__c LIMIT 1];
        GrupoProposta__c grupoProposta = [SELECT Id FROM GrupoProposta__c WHERE ContratanteProposta__r.Proposta__c =: proposta.Id LIMIT 1];

        // Apaga todos os contratantes da Proposta para gerar um novo
        List<SeguradoProposta__c> listVidaPropostaParaDeletar = [SELECT Id FROM SeguradoProposta__c WHERE GrupoProposta__r.ContratanteProposta__r.Proposta__c =: proposta.Id];
        delete listVidaPropostaParaDeletar;

        Test.startTest();
        // Gera uma segurado do grupo da proposta
        SeguradoProposta__c vidaProposta = TestDataFactory.gerarSeguradoProposta(conta,grupoProposta,formaPagamento);
        Test.stopTest();

        // Valida se a segurado foi criada
        List<SeguradoProposta__c> listVidaProposta = [SELECT Id FROM SeguradoProposta__c WHERE GrupoProposta__r.ContratanteProposta__r.Proposta__c =: proposta.Id];
        System.assert(listVidaProposta.size() > 0);
        System.assert(vidaProposta.Id != null);
    }

    @IsTest
    static void testValidarDadosPagamentoVidaPropostaSemInformacaoBancaria(){
        // Recupera dados
        Quote proposta = [SELECT Id FROM Quote LIMIT 1];
        Account conta = [SELECT Id FROM Account LIMIT 1];
        FormaPagamento__c formaPagamento = [SELECT Id FROM FormaPagamento__c LIMIT 1];
        GrupoProposta__c grupoProposta = [SELECT Id FROM GrupoProposta__c WHERE ContratanteProposta__r.Proposta__c =: proposta.Id LIMIT 1];
        String erroEsperado = '';

        // Apaga todos os contratantes da Proposta para gerar um novo
        List<SeguradoProposta__c> listVidaPropostaParaDeletar = [SELECT Id FROM SeguradoProposta__c WHERE GrupoProposta__r.ContratanteProposta__r.Proposta__c =: proposta.Id];
        delete listVidaPropostaParaDeletar;

        // Atualiza a forma de pagamento
        formaPagamento.Codigo__c = 'ADC';
        update formaPagamento;

        List<InformacaoBancaria__c> listInformacaoBancaria = [SELECT Id FROM InformacaoBancaria__c WHERE Conta__c =: conta.Id];
        delete listInformacaoBancaria;

        SeguradoProposta__c vidaGrupoProposta = new SeguradoProposta__c(
            Conta__c = conta.Id,
            FormaPagamento__c = formaPagamento.Id,
            PremioTotal__c = 10,
            QuantidadeParcelas__c = 1,
            GrupoProposta__c = grupoProposta.Id,
            ResponsavelPagamento__c = conta.Id
        );

        Test.startTest();
        // Gera uma segurado do grupo da proposta
        try{
            insert vidaGrupoProposta;
        }catch (Exception e){
            erroEsperado = e.getMessage();
        }
        Test.stopTest();

        // Valida se a segurado foi criada
        System.assert(erroEsperado.contains('Insert failed'));
        System.assert(erroEsperado.contains('FIELD_CUSTOM_VALIDATION_EXCEPTION'));
        System.assert(erroEsperado.contains('Para débito em conta é necessário ter uma informação bancária cadastrada!'));
    }

    @IsTest
    static void testValidarDadosPagamentoVidaPropostaSemCartaoCredito(){
        // Recupera dados
        Quote proposta = [SELECT Id FROM Quote LIMIT 1];
        Account conta = [SELECT Id FROM Account LIMIT 1];
        FormaPagamento__c formaPagamento = [SELECT Id FROM FormaPagamento__c LIMIT 1];
        GrupoProposta__c grupoProposta = [SELECT Id FROM GrupoProposta__c WHERE ContratanteProposta__r.Proposta__c =: proposta.Id LIMIT 1];
        String erroEsperado = '';

        // Apaga todos os contratantes da Proposta para gerar um novo
        List<SeguradoProposta__c> listVidaPropostaParaDeletar = [SELECT Id FROM SeguradoProposta__c WHERE GrupoProposta__r.ContratanteProposta__r.Proposta__c =: proposta.Id];
        delete listVidaPropostaParaDeletar;

        // Atualiza a forma de pagamento
        formaPagamento.Codigo__c = 'CAT';
        update formaPagamento;

        List<CartaoCredito__c> listCartaoCredito = [SELECT Id FROM CartaoCredito__c WHERE Conta__c =: conta.Id];
        delete listCartaoCredito;

        SeguradoProposta__c vidaGrupoProposta = new SeguradoProposta__c(
            Conta__c = conta.Id,
            FormaPagamento__c = formaPagamento.Id,
            PremioTotal__c = 10,
            QuantidadeParcelas__c = 1,
            GrupoProposta__c = grupoProposta.Id,
            ResponsavelPagamento__c = conta.Id
        );

        Test.startTest();
        // Gera uma segurado do grupo da proposta
        try{
            insert vidaGrupoProposta;
        }catch (Exception e){
            erroEsperado = e.getMessage();
        }
        Test.stopTest();

        // Valida se a segurado foi criada
        System.assert(erroEsperado.contains('Insert failed'));
        System.assert(erroEsperado.contains('FIELD_CUSTOM_VALIDATION_EXCEPTION'));
        System.assert(erroEsperado.contains('Para cartão de crédito é necessário ter um cartão cadastrado!'));
    }
    @IsTest
    static void testValidarDadosPagamentoVidaPropostaSemCartaoCreditoPorto(){
        // Recupera dados
        Quote proposta = [SELECT Id FROM Quote LIMIT 1];
        Account conta = [SELECT Id FROM Account LIMIT 1];
        FormaPagamento__c formaPagamento = [SELECT Id FROM FormaPagamento__c LIMIT 1];
        GrupoProposta__c grupoProposta = [SELECT Id FROM GrupoProposta__c WHERE ContratanteProposta__r.Proposta__c =: proposta.Id LIMIT 1];
        String erroEsperado = '';

        // Apaga todos os contratantes da Proposta para gerar um novo
        List<SeguradoProposta__c> listVidaPropostaParaDeletar = [SELECT Id FROM SeguradoProposta__c WHERE GrupoProposta__r.ContratanteProposta__r.Proposta__c =: proposta.Id];
        delete listVidaPropostaParaDeletar;

        // Atualiza a forma de pagamento
        formaPagamento.Codigo__c = 'CPO';
        update formaPagamento;

        List<CartaoCredito__c> listCartaoCredito = [SELECT Id FROM CartaoCredito__c WHERE Conta__c =: conta.Id];
        delete listCartaoCredito;

        SeguradoProposta__c vidaGrupoProposta = new SeguradoProposta__c(
            Conta__c = conta.Id,
            FormaPagamento__c = formaPagamento.Id,
            PremioTotal__c = 10,
            QuantidadeParcelas__c = 1,
            GrupoProposta__c = grupoProposta.Id,
            ResponsavelPagamento__c = conta.Id
        );

        Test.startTest();
        // Gera uma segurado do grupo da proposta
        try{
            insert vidaGrupoProposta;
        }catch (Exception e){
            erroEsperado = e.getMessage();
        }
        Test.stopTest();

        // Valida se a segurado foi criada
        System.assert(erroEsperado.contains('Insert failed'));
        System.assert(erroEsperado.contains('FIELD_CUSTOM_VALIDATION_EXCEPTION'));
        System.assert(erroEsperado.contains('Para pagamento no cartão de crédito Porto é necessário ter um cartão Porto cadastrado!'));
    }


}