workspace-sf/force-app/main/default/objects/ComplementoIndenizacao__c/ComplementoIndenizacao__c.object-meta.xml
<CustomObject>
    <description>Objeto criado pela frente de Sinistro para complementar o Pagamento de Garantia</description>
    <label>Complemento de Indenização</label>
    <nameField>
        <displayFormat>CG-{00000}</displayFormat>
        <label>Nome de Complemento de Indenização</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Complementos de Indenizações</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/ComplementoIndenizacao__c/fields/Descricao__c.field-meta.xml
<CustomField>
    <fullName>Descricao__c</fullName>
    <label>Descrição</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/ComplementoIndenizacao__c/fields/Motivo__c.field-meta.xml
<CustomField>
    <fullName>Motivo__c</fullName>
    <label>Motivo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prazo de regulação excedido</fullName>
            </value>
            <value>
                <fullName>Jurídico</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/ComplementoIndenizacao__c/fields/PagamentoGarantia__c.field-meta.xml
<CustomField>
    <fullName>PagamentoGarantia__c</fullName>
    <label>Pagamento de garantia</label>
    <referenceTo>PagamentoGarantia__c</referenceTo>
    <relationshipLabel>Complementos de Indenizações</relationshipLabel>
    <relationshipName>ComplementosIndenizacoes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/ComplementoIndenizacao__c/fields/TipoComplemento__c.field-meta.xml
<CustomField>
    <fullName>TipoComplemento__c</fullName>
    <label>Tipo Complemento</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Juros</fullName>
            </value>
            <value>
                <fullName>Atualização Monetária</fullName>
            </value>
            <value>
                <fullName>Deságio</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/ComplementoIndenizacao__c/fields/Valor__c.field-meta.xml
<CustomField>
    <fullName>Valor__c</fullName>
    <label>Valor</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Garantia__c/Garantia__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar o cadastro das garantias</description>
    <label>Garantia</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Garantias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/GarantiaSeguradoContrato__c/GarantiaSeguradoContrato__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar as garantias do segurado do contrato</description>
    <label>Garantia do segurado do contrato</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Garantias do segurado do contrato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/GarantiaSeguradoContrato__c/fields/Garantia__c.field-meta.xml
<CustomField>
    <fullName>Garantia__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Garantia</label>
    <referenceTo>Garantia__c</referenceTo>
    <relationshipLabel>Garantias do segurado do contrato (Garantia)</relationshipLabel>
    <relationshipName>GarantiasSeguradoContrato</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/MovimentoSinistro__c/MovimentoSinistro__c.object-meta.xml
<CustomObject>
    <description>Registrar os movimentos de sinistro relacionado ao caso. 
Objeto Relacionado do Caso.</description>
    <label>Movimento de Sinistro</label>
    <nameField>
        <displayFormat>MS-{00000}</displayFormat>
        <label>Nome de Movimento de Sinistro</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Movimentos de Sinistro</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/MovimentoSinistro__c/fields/Caso__c.field-meta.xml
<CustomField>
    <fullName>Caso__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Movimentos de Sinistro</relationshipLabel>
    <relationshipName>MovimentosSinistro</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/MovimentoSinistro__c/fields/DescricaoMovimento__c.field-meta.xml
<CustomField>
    <fullName>DescricaoMovimento__c</fullName>
    <label>Descrição do Movimento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>AVISO +</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>AC. AVISADO +</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>AC. AVISADO -</label>
            </value>
            <value>
                <fullName>24</fullName>
                <label>ENC. SEM INDENIZACAO -</label>
            </value>
            <value>
                <fullName>25</fullName>
                <label>REATIVACAO</label>
            </value>
            <value>
                <fullName>32</fullName>
                <label>ACERTO AVISO AUTOM  +</label>
            </value>
            <value>
                <fullName>33</fullName>
                <label>ACERTO AVISO AUTOM   -</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>DESPESAS             +</label>
            </value>
            <value>
                <fullName>17</fullName>
                <label>ACERTO DESPESAS      +</label>
            </value>
            <value>
                <fullName>18</fullName>
                <label>ACERTO DESPESAS      -</label>
            </value>
            <value>
                <fullName>44</fullName>
                <label>Multas Contratuais</label>
            </value>
            <value>
                <fullName>46</fullName>
                <label>Pagamentos Indevidos</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>PAGAMENTO PARCIAL    +</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>ACERTO PGTO PARCIAL  +</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>ACERTO PGTO PARCIAL -</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>PAGAMENTO FINAL      +</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>ACERTO PAGTO FINAL   +</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>ACERTO PAGTO FINAL   -</label>
            </value>
            <value>
                <fullName>52</fullName>
                <label>ACERTO JUROS JUR (+)</label>
            </value>
            <value>
                <fullName>53</fullName>
                <label>ACERTO JUROS JUR (-)</label>
            </value>
            <value>
                <fullName>62</fullName>
                <label>ACERTO CORRECAO JUR (+)</label>
            </value>
            <value>
                <fullName>63</fullName>
                <label>ACERTO CORRECAO JUR (-)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/MovimentoSinistro__c/fields/PagamentoGarantia__c.field-meta.xml
<CustomField>
    <fullName>PagamentoGarantia__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Garantia do Sinistro</label>
    <referenceTo>PagamentoGarantia__c</referenceTo>
    <relationshipLabel>Movimentos de Sinistro</relationshipLabel>
    <relationshipName>MovimentosSinistro</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/MovimentoSinistro__c/fields/TipoMovimento__c.field-meta.xml
<CustomField>
    <fullName>TipoMovimento__c</fullName>
    <label>Tipo de Movimento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aviso</fullName>
            </value>
            <value>
                <fullName>Despesa</fullName>
            </value>
            <value>
                <fullName>Pagamento</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/MovimentoSinistro__c/fields/ValorMovimento__c.field-meta.xml
<CustomField>
    <fullName>ValorMovimento__c</fullName>
    <label>Valor Movimento</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

workspace-sf/force-app/main/default/objects/PagamentoGarantia__c/PagamentoGarantia__c.object-meta.xml
<CustomObject>
    <description>Registrar os pagamentos das garantias dentro da frente de Sinistro Vida.
Objeto Detalhe de Caso</description>
    <label>Garantia do Sinistro</label>
    <nameField>
        <label>Nome da Garantia do Sinistro</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Garantias do Sinistro</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/PagamentoGarantia__c/fields/Caso__c.field-meta.xml
<CustomField>
    <fullName>Caso__c</fullName>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>Pagamentos_de_garantia</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/PagamentoGarantia__c/fields/Fase__c.field-meta.xml
<CustomField>
    <fullName>Fase__c</fullName>
    <label>Fase</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aberto</fullName>
            </value>
            <value>
                <fullName>Em Análise</fullName>
            </value>
            <value>
                <fullName>Fechado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/PagamentoGarantia__c/fields/Garantia_do_segurado_do_contrato__c.field-meta.xml
<CustomField>
    <fullName>Garantia_do_segurado_do_contrato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Garantia do segurado do contrato</label>
    <referenceTo>GarantiaSeguradoContrato__c</referenceTo>
    <relationshipName>Pagamentos_de_garantia</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/PagamentoGarantia__c/fields/Saldo_da_reserva__c.field-meta.xml
<CustomField>
    <fullName>Saldo_da_reserva__c</fullName>
    <label>Saldo da reserva - Garantia</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

workspace-sf/force-app/main/default/objects/PagamentoGarantia__c/fields/Status_do_pagamento__c.field-meta.xml
<CustomField>
    <fullName>Status_do_pagamento__c</fullName>
    <label>Status do Pagamento</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Fase__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Em análise</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
            <value>
                <fullName>Com Pendências</fullName>
            </value>
            <value>
                <fullName>Aguardando Pagamento</fullName>
            </value>
            <value>
                <fullName>Pago Parcialmente</fullName>
            </value>
            <value>
                <fullName>Pago</fullName>
            </value>
            <value>
                <fullName>Recusado</fullName>
            </value>
            <value>
                <fullName>Serviço Prestado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/PagamentoGarantia__c/fields/Valor_indenizado__c.field-meta.xml
<CustomField>
    <fullName>Valor_indenizado__c</fullName>
    <label>Valor Provisionado</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

workspace-sf/force-app/main/default/objects/PagamentoGarantia__c/fields/Valor_Pago__c.field-meta.xml
<CustomField>
    <fullName>Valor_Pago__c</fullName>
    <label>Valor Pago - Garantia</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

workspace-sf/force-app/main/default/objects/PagamentoGarantia__c/fields/ValorIndenizado__c.field-meta.xml
<CustomField>
    <fullName>ValorIndenizado__c</fullName>
    <description>Campo inicialmente composto pela soma do capital e do complemento de indenização. Formula alterada para Valor_Indenizado__c + ComplementoIndenizacao__c por conta da história PLV-4070.</description>
    <formula>Valor_indenizado__c + ComplementoIndenizacao__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Valor Total Provisionado</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

workspace-sf/force-app/main/default/classes/PagamentoGarantiaDAO.cls
// POR062-1 - INICIO
public inherited sharing virtual class PagamentoGarantiaDAO {
    private static final PagamentoGarantiaDAO INSTANCIA = new PagamentoGarantiaDAO();
    private PagamentoGarantiaDAO() {}

	public static PagamentoGarantiaDAO getInstance()
    {
		return instancia;
	}
    
    public List<PagamentoGarantia__c> buscarPorCaso(Set<Id> idsCaso)
    {
        List<PagamentoGarantia__c> pagamentoGarantiaLista = [
            SELECT
                Id, Name, Fase__c, Status_do_pagamento__c, Caso__c, Garantia_do_segurado_do_contrato__c, Garantia_do_segurado_do_contrato__r.Garantia__r.Name,
				Garantia_do_segurado_do_contrato__r.Garantia__r.Sigla__c, Garantia_do_segurado_do_contrato__r.Garantia__r.Descricao__c,
				Valor_indenizado__c/* PLV-4624 */, ValorIndenizado__c /* PLV-4624 */, Capital__c, /*LECVP-216 - INICIO / FIM*/Saldo_da_reserva__c, Valor_Pago__c, /*LECVP-344 INICIO - FIM*/
                (SELECT Id, Motivo__c, Descricao__c, TipoComplemento__c, Valor__c FROM ComplementosIndenizacoes__r ORDER By ID)
			FROM PagamentoGarantia__c
			WHERE Caso__c IN :idsCaso
            ORDER By ID
        ];
        return pagamentoGarantiaLista;
    }
    
    public List<PagamentoGarantia__c> buscarPorIdDeCasoECobertura(Set<Id> idsCaso, Set<String> coberturas)
    {
        List<PagamentoGarantia__c> pagamentoGarantiaLista = [
            SELECT
                Id, Name, Fase__c, Status_do_pagamento__c, Caso__c, Garantia_do_segurado_do_contrato__c, Garantia_do_segurado_do_contrato__r.Garantia__r.Name,
                Garantia_do_segurado_do_contrato__r.Garantia__r.Sigla__c, Garantia_do_segurado_do_contrato__r.Garantia__r.Descricao__c,
                Valor_indenizado__c/* PLV-4624 */, ValorIndenizado__c /* PLV-4624 */, Capital__c, /*LECVP-216 - INICIO / FIM */
                (SELECT Id, Motivo__c, Descricao__c, TipoComplemento__c, Valor__c FROM ComplementosIndenizacoes__r ORDER By ID)
			FROM PagamentoGarantia__c
			WHERE
                Caso__c IN :idsCaso AND
                Garantia_do_segurado_do_contrato__r.Garantia__r.Sigla__c IN :coberturas
            ORDER By ID
        ];
        return pagamentoGarantiaLista;
    }

    //LECVP-318 - INICIO
    public List<PagamentoGarantia__c> buscarCasoParaAtualizarFaseStatus(Id casoId){ 
        List<PagamentoGarantia__c> pagamentoGarantiaLista = [
            SELECT 
                Id,
                Caso__c,
                Caso__r.Id,
                Caso__r.Saldo_da_reserva__c, //II-59 INICIO-FIM
                Caso__r.Contrato__r.CodigoRamo__c,
                Caso__r.Status, // II-59-FIX02-INICIO/FIM
                Caso__r.Status_Dependente__c, // II-59-FIX02-INICIO/FIM
                Caso__r.Motivos_de_recusa__c, // II-59-FIX02-INICIO/FIM
                Fase__c,
                Status_do_pagamento__c,
                Capital__c,
                ValorIndenizado__c, //LECVPV-238-INICIO/FIM
                CreatedDate, //II-59 INICIO-FIM
                Garantia_do_segurado_do_contrato__r.Garantia__r.Sigla__c,
                Saldo_da_reserva__c // II-59-FIX02-INICIO/FIM
            FROM
                PagamentoGarantia__c 
            WHERE
                Caso__c = :casoId   
        ];

        return pagamentoGarantiaLista;
    }
    //LECVP-318 - FIM

    //FNPVVEP-19 - INICIO
    public List<PagamentoGarantia__c> buscarCasosBySetId(Set<Id> casosId){ 
        List<PagamentoGarantia__c> pagamentosGarantia = [
            SELECT 
                Id,
                Caso__c,
                Caso__r.Id,
                Caso__r.Saldo_da_reserva__c,           
                Caso__r.Contrato__r.CodigoRamo__c,
                Caso__r.Status, 
                Caso__r.Status_Dependente__c, 
                Caso__r.Motivos_de_recusa__c, 
                Fase__c,
                Status_do_pagamento__c,
                Capital__c,
                CreatedDate,           
                Garantia_do_segurado_do_contrato__r.Garantia__r.Sigla__c,
                Saldo_da_reserva__c 
            FROM
                PagamentoGarantia__c 
            WHERE
                Caso__c IN :casosId   
        ];

        return pagamentosGarantia;
    }
    //FNPVVEP-19 - INICIO



    //LECVP-344 - INICIO
    public List<MovimentoSinistro__c> buscarTipoMovEGarantias(Set<Id> garantiasId, Set<String> tipoMovimento){
        List<MovimentoSinistro__c> movimentos = [
            SELECT 
                Id,
                ValorMovimento__c,
                TipoMovimento__c,  
                DescricaoMovimento__c,
                PagamentoGarantia__c
            FROM
                MovimentoSinistro__c 
            WHERE
                PagamentoGarantia__c IN :garantiasId
            AND 
                TipoMovimento__c LIKE :tipoMovimento
        ];

        return movimentos;
    }    
    //LECVP-344 - FIM
}
// POR062-1 - FIM