workspace-sf/force-app/main/default/objects/Banco__c/Banco__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar os bancos.</description>
    <label>Banco</label>
    <nameField>
        <label>Nome do Banco</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bancos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/BeneficiarioGarantia__c/BeneficiarioGarantia__c.object-meta.xml
<CustomObject>
    <description>Registrar os beneficiários de cada pagamento de garantia. 
Objeto Detalhe do Pagamento de Garantia.</description>
    <label>Beneficiario da Garantia</label>
    <nameField>
        <displayFormat>BG-{0000}</displayFormat>
        <label>Nome de Beneficiario da Garantia</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Beneficiarios da Garantia</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/BeneficiarioGarantia__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Beneficiarios da Garantia</relationshipLabel>
    <relationshipName>Beneficiarios_Garantia</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/BeneficiarioGarantia__c/fields/IdExterno__c.field-meta.xml
<CustomField>
    <fullName>IdExterno__c</fullName>
    <externalId>true</externalId>
    <label>Id Externo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/BeneficiarioGarantia__c/fields/Informacao_bancaria__c.field-meta.xml
<CustomField>
    <fullName>Informacao_bancaria__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>A busca pode ser realizada por: Código do banco, nome do banco, agência e conta corrente/poupança</inlineHelpText>
    <label>Informação bancária</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Conta__c</field>
            <operation>equals</operation>
            <valueField>InformacaoBancaria__c.Conta__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>InformacaoBancaria__c</referenceTo>
    <relationshipLabel>Beneficiarios da Garantia</relationshipLabel>
    <relationshipName>Beneficiarios_Garantia</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/InformacaoBancaria__c/InformacaoBancaria__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar as informações bancárias das contas</description>
    <label>Informação bancária</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Informações bancárias</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/InformacaoBancaria__c/fields/Agencia__c.field-meta.xml
<CustomField>
    <fullName>Agencia__c</fullName>
    <label>Agência</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/InformacaoBancaria__c/fields/Banco__c.field-meta.xml
<CustomField>
    <fullName>Banco__c</fullName>
    <label>Banco</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/InformacaoBancaria__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>InformacoesBancarias</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/InformacaoBancaria__c/fields/Digito__c.field-meta.xml
<CustomField>
    <fullName>Digito__c</fullName>
    <label>Dígito</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/InformacaoBancaria__c/fields/ErroIntegracao__c.field-meta.xml
<CustomField>
    <fullName>ErroIntegracao__c</fullName>
    <label>Erro da integração</label>
    <type>TextArea</type>
</CustomField>

workspace-sf/force-app/main/default/objects/InformacaoBancaria__c/fields/IdExterno__c.field-meta.xml
<CustomField>
    <fullName>IdExterno__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Id externo</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

workspace-sf/force-app/main/default/objects/InformacaoBancaria__c/fields/NumeroConta__c.field-meta.xml
<CustomField>
    <fullName>NumeroConta__c</fullName>
    <label>Número da conta</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/InformacaoBancaria__c/fields/StatusIntegracao__c.field-meta.xml
<CustomField>
    <fullName>StatusIntegracao__c</fullName>
    <label>Status da integração</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Validada</fullName>
            </value>
            <value>
                <fullName>Não validada</fullName>
            </value>
            <value>
                <fullName>Aguardando validação</fullName>
                <default>true</default>
                <label>Aguardando validação</label>
            </value>
            <value>
                <fullName>Não existe parceiro</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/classes/InformacaoBancariaDAO.cls
/**
 * InformacaoBancariaDAO
 * @author Fernando Barcellos @ 06/02/2018
 *
 **/
public class InformacaoBancariaDAO {
    private static final InformacaoBancariaDAO instancia = new InformacaoBancariaDAO();

    private InformacaoBancariaDAO() {   
    }

    public static InformacaoBancariaDAO getInstance(){
        return instancia;
    }

    public List<InformacaoBancaria__c> buscarInformacoesBancariasPorIdExterno(Set<String> idsExternos)
    {  
        return [
            SELECT
                Id,
                IdExterno__c,
                Conta__c,
                Banco__c,
                Agencia__c,
            	//PLV-3918-FIX6-INICIO
            	//PLV-3918-FIX7-INICIO
                NumeroConta__c,            	
                Digito__c
                //PLV-3918-FIX7 - FIM
            	//PLV-3918-FIX6 - FIM
            FROM
                InformacaoBancaria__c
            WHERE
                IdExterno__c IN : idsExternos
        ];
    }

    public List<InformacaoBancaria__c> buscarInformacoesBancariasPorId(Set<Id> idInformacoesBancarias) 
    {
        return [
            SELECT
                Id,
                IdExterno__c,
                Conta__c,
                Banco__c,
                Agencia__c,
                //PLV-3918-FIX6-INICIO
                //PLV-3918-FIX7-INICIO
                NumeroConta__c,        	
                Digito__c,
                //PLV-3918-FIX7 - FIM
            	//PLV-3918-FIX6 - FIM
                StatusIntegracao__c,
                ErroIntegracao__c
            FROM
                InformacaoBancaria__c
            WHERE
                id IN : idInformacoesBancarias
        ];
    }
    
    
    public List<BeneficiarioGarantia__c> buscarinfobancaria(String IdBeneficiario) 
    {
        return [
                SELECT Informacao_Bancaria__c 
                FROM BeneficiarioGarantia__c 
                WHERE Id =: IdBeneficiario
        ];
    }
    
    
    public List<InformacaoBancaria__c> buscarinfobancariasdosbeneficiarios(String Informacaobancaria) 
    {
        return [
            SELECT Id,
                    IdExterno__c,
                    Conta__c,
                    Conta__r.Cpf__c,
                    Conta__r.Cnpj__c,
                    Banco__c,
                    Agencia__c,
                    NumeroConta__c,
            		//PLV-3918-FIX6 - INICIO
                    //PLV-3918-FIX7-INICIO   	
                	Digito__c,
                	//PLV-3918-FIX7 - FIM
            		//PLV-3918-FIX6 - INICIO
                    StatusIntegracao__c,
                    ErroIntegracao__c 
            FROM InformacaoBancaria__c 
            WHERE
                Id  =:  Informacaobancaria
            //AND
                //StatusIntegracao__c = 'Não Validada' 
        ];
    }
}