workspace-sf/force-app/main/default/objects/Banco__c/Banco__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar os bancos.</description>
    <label>Banco</label>
    <nameField>
        <label>Nome do Banco</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bancos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/Banco__c/fields/CodigoBanco__c.field-meta.xml
<CustomField>
    <fullName>CodigoBanco__c</fullName>
    <label>Código do Banco</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/InformacaoBancaria__c/InformacaoBancaria__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar as informações bancárias das contas</description>
    <label>Informação bancária</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Informações bancárias</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/InformacaoBancaria__c/fields/Banco__c.field-meta.xml
<CustomField>
    <fullName>Banco__c</fullName>
    <label>Banco</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/InformacaoBancaria__c/fields/BancoNew__c.field-meta.xml
<CustomField>
    <fullName>BancoNew__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Banco</label>
    <referenceTo>Banco__c</referenceTo>
    <relationshipLabel>Informações bancárias</relationshipLabel>
    <relationshipName>Informacoes_bancarias</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/InformacaoBancaria__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>InformacoesBancarias</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/InformacaoBancaria__c/fields/Papel__c.field-meta.xml
<CustomField>
    <fullName>Papel__c</fullName>
    <label>Papel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agenciador</fullName>
            </value>
            <value>
                <fullName>Parceiro</fullName>
            </value>
            <value>
                <fullName>Prestador</fullName>
            </value>
            <value>
                <fullName>Segurado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/classes/CargaLegadoInformixBatch.cls
public with sharing class CargaLegadoInformixBatch implements Database.Batchable<sObject> {
    //PLV-4293 - INICIO
    public Database.QueryLocator start(Database.BatchableContext context) {
        return Database.getQueryLocator([
            SELECT Id
                ,Banco__c
                ,BancoNew__c
                ,Conta__c
                ,Conta__r.Papel__c
            FROM InformacaoBancaria__c 
            WHERE Papel__c = 'Agenciador'
            AND BancoNew__c = null
            AND Banco__c <> null
            AND Conta__c <> null
            LIMIT 10000
        ]);
    }

    public void execute(Database.BatchableContext context, List<InformacaoBancaria__c> infoBancarias) {

        if (infoBancarias.size() > 0) {
            Map<String,Banco__c> mapBancos = new Map<String,Banco__c>();
        
            List<Banco__c> bancos = [
                SELECT Id
                    ,CodigoBanco__c
                FROM Banco__c
                WHERE Ativo__c = true
                LIMIT 10000
            ];
        
            if(bancos.size() > 0) {
                for (Banco__c banco : bancos) {
                    mapBancos.put(banco.CodigoBanco__c, banco);
                }
            }
        
            Map<Id,Account> accountsToUpdate = new Map<Id,Account>();
        
            for (InformacaoBancaria__c info : infoBancarias) {
                Account conta = new Account(Id = info.Conta__c);

                //Se encontrar o Banco preenche
                if (mapBancos.containsKey(info.Banco__c)) {
                    info.BancoNew__c = mapBancos.get(info.Banco__c).Id;
                    conta.Ativo__c = true;
                }
                else {
                    conta.Ativo__c = false;
                }

                if (info.Conta__r.Papel__c != null && !info.Conta__r.Papel__c.contains('Agenciador')) {
                    conta.Papel__c = info.Conta__r.Papel__c + 'Agenciador;';
                }
                else if (info.Conta__r.Papel__c == null) {
                    conta.Papel__c = 'Agenciador;';
                }

                accountsToUpdate.put(info.Conta__c, conta);
            }
        
            Integer nErros = 0;
        
            Database.SaveResult[] srListInfo = Database.update(infoBancarias, false);
            for (Database.SaveResult sr : srListInfo) {
                if (!sr.isSuccess()) {
                    nErros++;
                    for (Database.Error err: sr.getErrors()) {
                        System.debug('Os seguinte erros ocorreram.');
                        System.debug(err.getStatusCode() + ': ' + err.getMessage());
                    }
                }
            }
        
            if (accountsToUpdate.values().size() > 0) {
                Integer nErrosConta = 0;
        
                Database.SaveResult[] srListInfoContas = Database.update(accountsToUpdate.values(), false);
                for (Database.SaveResult sr : srListInfoContas) {
                    if (!sr.isSuccess()) {
                        nErrosConta++;
                        for (Database.Error err: sr.getErrors()) {
                            System.debug('Os seguinte erros ocorreram.');
                            System.debug(err.getStatusCode() + ': ' + err.getMessage());
                        }
                    }
                }
        
                System.debug('SCRIPT 4293 - INFO BANCARIA - Contas ERROS: ' + nErrosConta);
            }
        } 
    }

    public void finish(Database.BatchableContext context) {

    }
    //PLV-4293 - FIM
}