workspace-sf/force-app/main/default/objects/Banco__c/Banco__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar os bancos.</description>
    <label>Banco</label>
    <nameField>
        <label>Nome do Banco</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bancos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/Banco__c/fields/CodigoBanco__c.field-meta.xml
<CustomField>
    <fullName>CodigoBanco__c</fullName>
    <label>Código do Banco</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Banco__c/fields/ConveniadoADC__c.field-meta.xml
<CustomField>
    <fullName>ConveniadoADC__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Banco Conveniado para ADC</label>
    <type>Checkbox</type>
</CustomField>

workspace-sf/force-app/main/default/objects/InformacaoBancaria__c/InformacaoBancaria__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar as informações bancárias das contas</description>
    <label>Informação bancária</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Informações bancárias</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/InformacaoBancaria__c/fields/Agencia__c.field-meta.xml
<CustomField>
    <fullName>Agencia__c</fullName>
    <label>Agência</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/InformacaoBancaria__c/fields/Banco__c.field-meta.xml
<CustomField>
    <fullName>Banco__c</fullName>
    <label>Banco</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/InformacaoBancaria__c/fields/BancoNew__c.field-meta.xml
<CustomField>
    <fullName>BancoNew__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Banco</label>
    <referenceTo>Banco__c</referenceTo>
    <relationshipLabel>Informações bancárias</relationshipLabel>
    <relationshipName>Informacoes_bancarias</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/InformacaoBancaria__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>InformacoesBancarias</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/InformacaoBancaria__c/fields/Digito__c.field-meta.xml
<CustomField>
    <fullName>Digito__c</fullName>
    <label>Dígito</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/InformacaoBancaria__c/fields/NumeroConta__c.field-meta.xml
<CustomField>
    <fullName>NumeroConta__c</fullName>
    <label>Número da conta</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/InformacaoBancaria__c/fields/StatusIntegracao__c.field-meta.xml
<CustomField>
    <fullName>StatusIntegracao__c</fullName>
    <label>Status da integração</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Validada</fullName>
            </value>
            <value>
                <fullName>Não validada</fullName>
            </value>
            <value>
                <fullName>Aguardando validação</fullName>
                <default>true</default>
                <label>Aguardando validação</label>
            </value>
            <value>
                <fullName>Não existe parceiro</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/classes/InformacaoBancariaFactory.cls
/**
 * @author AVX - Daniel Zampieri
 * @date 2019-02-27
 * @description Informação Bancária Factory Class
 */
 @isTest
public class InformacaoBancariaFactory{

	private static Map<String,InformacaoBancaria__c> mStaticRecord = new Map<String,InformacaoBancaria__c>();

//-----------------------------Info Bancaria Pessoa Física------------------------------------------

	private static InformacaoBancaria__c getRecordInfoPessoaFisica(Account contaFisica){
		//PLV-4363 - INICIO
        Banco__c banconew = new Banco__c();
        banconew.CodigoBanco__c = '246';
        banconew.ConveniadoADC__c  = false;
        banconew.Name = 'A B C ROMA S/A';
        banconew.Ativo__c = true;
        insert banconew; 
        //PLV-4363 - FIM
		if(!mStaticRecord.containsKey('InfoPessoaFisica')){
			
			mStaticRecord.put('InfoPessoaFisica', new InformacaoBancaria__c(
				Banco__c = '246',
				Agencia__c = '3758',
				NumeroConta__c = '35958',
                //PLV-3918 -FIX6 - INICIO
                //PLV-3918 -FIX7 - INICIO
				Digito__c = '6',
                //PLV-3918 -FIX7 - FIM
                //PLV-3918 -FIX6 - FIM
				StatusIntegracao__c = 'Validada',
				BancoNew__c = banconew.Id, //PLV-4363 -INICIO/FIM
				Conta__c = contaFisica.Id)
			);
		}
		return mStaticRecord.get('InfoPessoaFisica');
	}

public class InfoPessoaFisica extends SObjectFactory {

	public InfoPessoaFisica() {

		this(
			(Account) new AccountFactory.PessoaFisica().createRecord()
		);
	}

	public InfoPessoaFisica(Account contaFisica){

		super(getRecordInfoPessoaFisica(contaFisica));
	}

}

//------------------------------Info Bancaria Pessoa Jurídica----------------------------------------

	private static InformacaoBancaria__c getRecordInfoPessoaJuridica(Account contaJuridica){
		//PLV-4363 - INICIO
        Banco__c banconew = new Banco__c();
        banconew.CodigoBanco__c = '246';
        banconew.ConveniadoADC__c  = false;
        banconew.Name = 'A B C ROMA S/A';
        banconew.Ativo__c = true;
        insert banconew; 
        //PLV-4363 - FIM
		if(!mStaticRecord.containsKey('InfoPessoaJuridica')){

			mStaticRecord.put('InfoPessoaJuridica', new InformacaoBancaria__c(
				Banco__c = '246',
				Agencia__c = '2028',
				NumeroConta__c = '522100',
                //PLV-3918 -FIX6 - INICIO
                //PLV-3918 -FIX7 - INICIO
				Digito__c = '5',
                //PLV-3918 -FIX7 - FIM
                //PLV-3918 -FIX6 - FIM
				StatusIntegracao__c = 'Validada',
				BancoNew__c = banconew.Id, //PLV-4363 -INICIO/FIM
				Conta__c = contaJuridica.Id)
			);
		}
		return mStaticRecord.get('InfoPessoaJuridica');
	}

public class InfoPessoaJuridica extends SObjectFactory {
	
	public InfoPessoaJuridica() {

		this(
			(Account) new AccountFactory.PessoaJuridica().createRecord()
		);
	}

	public InfoPessoaJuridica(Account contaJuridica) {

		super(getRecordInfoPessoaJuridica(contaJuridica));
	}
}

}