workspace-sf/force-app/main/default/objects/Banco__c/Banco__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar os bancos.</description>
    <label>Banco</label>
    <nameField>
        <label>Nome do Banco</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bancos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/Banco__c/fields/CodigoBanco__c.field-meta.xml
<CustomField>
    <fullName>CodigoBanco__c</fullName>
    <label>Código do Banco</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Banco__c/fields/ConveniadoADC__c.field-meta.xml
<CustomField>
    <fullName>ConveniadoADC__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Banco Conveniado para ADC</label>
    <type>Checkbox</type>
</CustomField>

workspace-sf/force-app/main/default/objects/BeneficiarioGarantia__c/BeneficiarioGarantia__c.object-meta.xml
<CustomObject>
    <description>Registrar os beneficiários de cada pagamento de garantia. 
Objeto Detalhe do Pagamento de Garantia.</description>
    <label>Beneficiario da Garantia</label>
    <nameField>
        <displayFormat>BG-{0000}</displayFormat>
        <label>Nome de Beneficiario da Garantia</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Beneficiarios da Garantia</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/BeneficiarioGarantia__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Beneficiarios da Garantia</relationshipLabel>
    <relationshipName>Beneficiarios_Garantia</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/BeneficiarioGarantia__c/fields/IdExterno__c.field-meta.xml
<CustomField>
    <fullName>IdExterno__c</fullName>
    <externalId>true</externalId>
    <label>Id Externo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/BeneficiarioGarantia__c/fields/Pagamento_de_Sinistro__c.field-meta.xml
<CustomField>
    <fullName>Pagamento_de_Sinistro__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pagamento de Sinistro</label>
    <referenceTo>Pagamento_de_Sinistro__c</referenceTo>
    <relationshipLabel>Beneficiarios da Garantia</relationshipLabel>
    <relationshipName>Beneficiarios_da_Garantia</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaSeguradoContrato__c/GarantiaSeguradoContrato__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar as garantias do segurado do contrato</description>
    <label>Garantia do segurado do contrato</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Garantias do segurado do contrato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/InformacaoBancaria__c/InformacaoBancaria__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar as informações bancárias das contas</description>
    <label>Informação bancária</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Informações bancárias</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/InformacaoBancaria__c/fields/Agencia__c.field-meta.xml
<CustomField>
    <fullName>Agencia__c</fullName>
    <label>Agência</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/InformacaoBancaria__c/fields/Banco__c.field-meta.xml
<CustomField>
    <fullName>Banco__c</fullName>
    <label>Banco</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/InformacaoBancaria__c/fields/BancoNew__c.field-meta.xml
<CustomField>
    <fullName>BancoNew__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Banco</label>
    <referenceTo>Banco__c</referenceTo>
    <relationshipLabel>Informações bancárias</relationshipLabel>
    <relationshipName>Informacoes_bancarias</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/InformacaoBancaria__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>InformacoesBancarias</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/InformacaoBancaria__c/fields/IdExterno__c.field-meta.xml
<CustomField>
    <fullName>IdExterno__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Id externo</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

workspace-sf/force-app/main/default/objects/InformacaoBancaria__c/fields/NumeroConta__c.field-meta.xml
<CustomField>
    <fullName>NumeroConta__c</fullName>
    <label>Número da conta</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/InformacaoBancaria__c/fields/Papel__c.field-meta.xml
<CustomField>
    <fullName>Papel__c</fullName>
    <label>Papel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agenciador</fullName>
            </value>
            <value>
                <fullName>Parceiro</fullName>
            </value>
            <value>
                <fullName>Prestador</fullName>
            </value>
            <value>
                <fullName>Segurado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/Pagamento_de_Sinistro__c/Pagamento_de_Sinistro__c.object-meta.xml
<CustomObject>
    <label>Pagamento de Sinistro</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Pagamento de Sinistro</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pagamentos de Sinistro</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/Pagamento_de_Sinistro__c/fields/Caso_de_Sinistro__c.field-meta.xml
<CustomField>
    <fullName>Caso_de_Sinistro__c</fullName>
    <label>Caso de Sinistro</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Case.RecordTypeId</field>
            <operation>equals</operation>
            <value>Sinistro</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Pagamentos de Sinistro</relationshipLabel>
    <relationshipName>Pagamentos_de_Sinistro</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Pagamento_de_Sinistro__c/fields/Dados_Bancarios__c.field-meta.xml
<CustomField>
    <fullName>Dados_Bancarios__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dados Bancários</label>
    <referenceTo>InformacaoBancaria__c</referenceTo>
    <relationshipLabel>Pagamentos de Sinistro</relationshipLabel>
    <relationshipName>Pagamentos_de_Sinistro</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/PagamentoGarantia__c/PagamentoGarantia__c.object-meta.xml
<CustomObject>
    <description>Registrar os pagamentos das garantias dentro da frente de Sinistro Vida.
Objeto Detalhe de Caso</description>
    <label>Garantia do Sinistro</label>
    <nameField>
        <label>Nome da Garantia do Sinistro</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Garantias do Sinistro</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/classes/ConsultaSinistroTest.cls
/*******************************************************************************************************************************
* Consulta dados Básicos de Apólice/Contrato
* @author Gabriel Roetger- Globant
* @date 20/07/2020
* Classe criada por conta da história PLV-3967
******************************************************************************************************************************/
@isTest
public class ConsultaSinistroTest  {
    public static RestRequest request = new RestRequest();
    
    
    @testSetup
    static void makeData(){        
        Account conta = (Account) new AccountFactory.PessoaFisica().createRecord();

        Contract contrato = (Contract) new ContratoFactory.ContratoFactorySemParam(conta).createRecord();
        contrato.IdExterno__c = '1-1-9999-999999999-0';
        update contrato;
        
        Case casoAtendimento = (Case) new CasoFactory.AtendimentoSinistro().createRecord();
        Case casoSinistro = (Case) new CasoFactory.Sinistro(casoAtendimento, conta).createRecord();
        casoSinistro.Contrato__c = contrato.id;
        casoSinistro.NumeroSinistro__c = '123456-teste';
        casoSinistro.Type = 'Sinistro';
        update casoSinistro;
        
        insert new CaseComment(CommentBody = 'test',ParentId = casoSinistro.id);
        
        GarantiaSeguradoContrato__c garantiaSeguradoContrato = (GarantiaSeguradoContrato__c) new GarantiaSeguradoContratoFactory().createRecord();

        PagamentoGarantia__c pagamentoGarantia = (PagamentoGarantia__c) new PagamentoGarantiaFactory(casoSinistro, garantiaSeguradoContrato).createRecord();
        PagamentoGarantia__c pagamentoGarantiaClone = pagamentoGarantia.clone(false, false, false, false);
       	insert pagamentoGarantiaClone;
        
        //PLV-4363 - INICIO
        Banco__c banconew = new Banco__c();
        banconew.CodigoBanco__c = '341';
        banconew.ConveniadoADC__c  = false;
        banconew.Name = 'BANCO ITAU S/A';
        banconew.Ativo__c = true;
        insert banconew; 
        //PLV-4363 - FIM
        
        InformacaoBancaria__c beneConta = new InformacaoBancaria__c(
            Papel__c = 'Parceiro', 
            Banco__c = '341',
            Agencia__c = '2332', 
            NumeroConta__c = '1234545',
            BancoNew__c = banconew.Id, //PLV-4363 - INICIO/FIM
            Conta__c = conta.Id
        );
        
        insert beneConta;
        Pagamento_de_sinistro__c pagSinistro = new Pagamento_de_sinistro__c();
       
        pagSinistro.Caso_de_Sinistro__c = casoSinistro.Id;
        pagSinistro.Dados_Bancarios__c = beneConta.Id;       
        pagSinistro.Data_Programada_de_Pagamento__c = Date.today();
        
		insert pagSinistro; 
        
        BeneficiarioGarantia__c beneficiario = (BeneficiarioGarantia__c) new BeneficiarioGarantiaFactory.BenePessoaFisica(conta, beneConta, pagamentoGarantia).createRecord();
        beneficiario.Pagamento_de_Sinistro__c = pagSinistro.Id; 
        update beneficiario;
    }
    
    @isTest 
    public static void consultarTest_semParam(){        
        request.httpMethod = 'GET';
        RestContext.request = request;
        
        Test.startTest();
        
        ConsultaSinistroRest.consultar();
        
        Test.stopTest();
    } //ok
    
    @isTest 
    public static void consultarTest_paramInexistente(){
        request.requestUri = URL.getSalesforceBaseUrl().toExternalForm().toLowercase() + '/services/apexrest/sinistro/buscar';   
        request.httpMethod = 'GET';
        RestContext.request = request;
        
        request.params.put('apolice', '123');
        request.params.put('sinistro', '123');
        
        
        Test.startTest();
        
        ConsultaSinistroRest.consultar();
        
        Test.stopTest();
    } 
    
    @isTest
    public static void consultarTest_Apolice(){
        request.requestUri = URL.getSalesforceBaseUrl().toExternalForm().toLowercase() + '/services/apexrest/sinistro/buscar';
        request.httpMethod = 'GET';
        RestContext.request = request;
        
        request.params.put('apolice', '1-1-9999-999999999-0');
        
        Test.startTest();
        
        ConsultaSinistroRest.consultar();
        
        Test.stopTest();
    }
    
    @isTest
    public static void consultarTest_Sinistro(){
        request.requestUri = URL.getSalesforceBaseUrl().toExternalForm().toLowercase() + '/services/apexrest/sinistro/buscar';
        request.httpMethod = 'GET';
        RestContext.request = request;
        
        request.params.put('sinistro', '123456-teste');
        
        Test.startTest();
        
        ConsultaSinistroRest.consultar();
        
        Test.stopTest();
    }
    @isTest
    public static void getBeneficiariosTest(){
        Test.startTest();
        new ConsultaSinistroService('','').getBeneficiarios(new Set<Id>());
        Test.stopTest();
    }
}