workspace-sf/force-app/main/default/objects/Banco__c/Banco__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar os bancos.</description>
    <label>Banco</label>
    <nameField>
        <label>Nome do Banco</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bancos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/Banco__c/fields/CodigoBanco__c.field-meta.xml
<CustomField>
    <fullName>CodigoBanco__c</fullName>
    <label>Código do Banco</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Banco__c/fields/ConveniadoADC__c.field-meta.xml
<CustomField>
    <fullName>ConveniadoADC__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Banco Conveniado para ADC</label>
    <type>Checkbox</type>
</CustomField>

workspace-sf/force-app/main/default/objects/FormaPagamento__c/FormaPagamento__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar o cadastro das formas de pagamento</description>
    <label>Forma de pagamento</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Formas de pagamento</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/FormaPagamento__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <label>Código</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/InformacaoBancaria__c/InformacaoBancaria__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar as informações bancárias das contas</description>
    <label>Informação bancária</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Informações bancárias</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/InformacaoBancaria__c/fields/Agencia__c.field-meta.xml
<CustomField>
    <fullName>Agencia__c</fullName>
    <label>Agência</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/InformacaoBancaria__c/fields/Banco__c.field-meta.xml
<CustomField>
    <fullName>Banco__c</fullName>
    <label>Banco</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/InformacaoBancaria__c/fields/BancoNew__c.field-meta.xml
<CustomField>
    <fullName>BancoNew__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Banco</label>
    <referenceTo>Banco__c</referenceTo>
    <relationshipLabel>Informações bancárias</relationshipLabel>
    <relationshipName>Informacoes_bancarias</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/InformacaoBancaria__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>InformacoesBancarias</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/InformacaoBancaria__c/fields/Digito__c.field-meta.xml
<CustomField>
    <fullName>Digito__c</fullName>
    <label>Dígito</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/InformacaoBancaria__c/fields/NumeroConta__c.field-meta.xml
<CustomField>
    <fullName>NumeroConta__c</fullName>
    <label>Número da conta</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/InformacaoBancaria__c/fields/Principal__c.field-meta.xml
<CustomField>
    <fullName>Principal__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Define se a informação bancária é a principal informação da conta relacionada.</inlineHelpText>
    <label>Principal?</label>
    <type>Checkbox</type>
</CustomField>

workspace-sf/force-app/main/default/objects/InformacaoBancaria__c/fields/StatusIntegracao__c.field-meta.xml
<CustomField>
    <fullName>StatusIntegracao__c</fullName>
    <label>Status da integração</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Validada</fullName>
            </value>
            <value>
                <fullName>Não validada</fullName>
            </value>
            <value>
                <fullName>Aguardando validação</fullName>
                <default>true</default>
                <label>Aguardando validação</label>
            </value>
            <value>
                <fullName>Não existe parceiro</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/Parceiro__c/Parceiro__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar as informações dos parceiros da Porto</description>
    <label>Parceiro</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parceiros</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/Parceiro__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <formula>LPAD( Conta__r.IdExterno__c , 14, &quot;0&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Código de identificação do parceiro  - CNPJ da conta sem pontuação</inlineHelpText>
    <label>Código</label>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Parceiro__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Parceiros</relationshipLabel>
    <relationshipName>Parceiro</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Parceiro__c/fields/DiaFaturamento__c.field-meta.xml
<CustomField>
    <fullName>DiaFaturamento__c</fullName>
    <label>Dia do Faturamento</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Parceiro__c/fields/DiaPreFaturamento__c.field-meta.xml
<CustomField>
    <fullName>DiaPreFaturamento__c</fullName>
    <label>Dia do Pré-faturamento</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Parceiro__c/fields/FaturaProdutosSeparados__c.field-meta.xml
<CustomField>
    <fullName>FaturaProdutosSeparados__c</fullName>
    <label>Fatura produtos separados?</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sim</fullName>
            </value>
            <value>
                <fullName>Não</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/Parceiro__c/fields/FormaPagamento__c.field-meta.xml
<CustomField>
    <fullName>FormaPagamento__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Forma de pagamento</label>
    <referenceTo>FormaPagamento__c</referenceTo>
    <relationshipLabel>Parceiros</relationshipLabel>
    <relationshipName>Parceiros</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Parceiro__c/fields/PossuiAnexoFatura__c.field-meta.xml
<CustomField>
    <fullName>PossuiAnexoFatura__c</fullName>
    <label>Possui Anexo Fatura?</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sim</fullName>
            </value>
            <value>
                <fullName>Nao</fullName>
                <label>Não</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/Parceiro__c/fields/PrazoVencimento__c.field-meta.xml
<CustomField>
    <fullName>PrazoVencimento__c</fullName>
    <inlineHelpText>Quantidade de dias para o vencimento da fatura, após o dia do faturamento</inlineHelpText>
    <label>Prazo de vencimento</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Parceiro__c/fields/Ramo__c.field-meta.xml
<CustomField>
    <fullName>Ramo__c</fullName>
    <label>Ramo</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Parceiro__c/fields/SiglaParceiro__c.field-meta.xml
<CustomField>
    <fullName>SiglaParceiro__c</fullName>
    <label>Sigla do Parceiro</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Parceiro__c/fields/Sucursal__c.field-meta.xml
<CustomField>
    <fullName>Sucursal__c</fullName>
    <label>Sucursal</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Pep__c/Pep__c.object-meta.xml
<CustomObject>
    <label>Pep</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Peps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/ProdutoParceiro__c/ProdutoParceiro__c.object-meta.xml
<CustomObject>
    <description>Objeto de relacionamento entre o parceiro e o produto</description>
    <label>Produto do parceiro</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número do Produto do Parceiro</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Produtos do parceiro</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/ProdutoParceiro__c/fields/CodigoProdutoParceiro__c.field-meta.xml
<CustomField>
    <fullName>CodigoProdutoParceiro__c</fullName>
    <description>Esse campo terá a descrição do código do produto no parceiro (no caso da Renner, seria V0003065 para o CCR e V0003064 para o EP).</description>
    <label>Código do Produto no Parceiro</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/ProdutoParceiro__c/fields/Parceiro__c.field-meta.xml
<CustomField>
    <fullName>Parceiro__c</fullName>
    <label>Parceiro</label>
    <referenceTo>Parceiro__c</referenceTo>
    <relationshipLabel>Produtos do parceiro</relationshipLabel>
    <relationshipName>ProdutosParceiro</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/classes/CriarPagamentoSinistroTest.cls
@isTest 
private class CriarPagamentoSinistroTest {

	@testSetup static void setup() {
        Account contaFisica = (Account) new AccountFactory.PessoaFisica().createRecord();
        
        contact contato = [SELECT Id FROM Contact WHERE AccountId =: contaFisica.Id];
		
        FormaPagamento__c formaPG = new FormaPagamento__c();
        formaPG.Codigo__c = '1234';
        FormaPG.Name = '3X';
        insert formaPG;
        
        Parceiro__c parceiro = new Parceiro__c();
        parceiro.DiaFaturamento__c = '10';
        parceiro.DiaPreFaturamento__c = '08';
        parceiro.PrazoVencimento__c = '30';
        parceiro.Conta__c = contaFisica.Id;
        parceiro.FaturaProdutosSeparados__c = 'Não';  
        parceiro.FormaPagamento__c = formaPG.Id;
        parceiro.PossuiAnexoFatura__c = 'Sim';
        parceiro.SiglaParceiro__c = 'PSEG';
        parceiro.Empresa__c = '1';
        parceiro.Sucursal__c = '1';
        parceiro.Ramo__c = '1377';
        
        
        insert parceiro;
        
        case caso = new case();
        
        Id IdRegistro = [SELECT Id, Name, DeveloperName, SobjectType	FROM RecordType where Name = 'Atendimento'].Id;
        //Recordtype REC_ID_SINISTRO = RecordTypeBO.buscarTipoRegistro('Case', 'Sinistro');
        caso.RecordTypeId = IdRegistro;
        caso.AccountId = contaFisica.Id;
        caso.ContactId = contato.Id;
        caso.Status_Dependente__c = 'Avisado';
		caso.Parceiro__c = parceiro.Id;
		caso.Nome_Segurado__c = 'Teste';
		caso.Cpf_Segurado__c = '075.487.587-87';
		//caso.digitoCpfSegurado = casoObj.Cpf_Segurado__c.substring(12, 14); //Digito CPF
		//caso.Dataocorrencia__c = Date.valueOf('2005-10-10');
		caso.Subject = 'Teste';
		caso.Description = 'Teste';			
		caso.Origin = 'Prestadora';
		caso.Numero_titulo__c = '14587452';
		caso.Vitima__c = 'Segurado';
		caso.IdPrestadora__c = 'Teste';
		//caso.Id = '254785478';
		caso.TipoEvento__c = 'Acidente';
		//caso.avisado = 'true';
		//caso.EmpresaSplit__c = 52.5;
		//caso.sucursal__c = 'Teste';
		caso.RamoSplit__c = 54.5;
		caso.Numero_Apolice__c  = '102458798754';
		//caso.endosso = objCasoSinistro.apolice.substring(10, 11);
		caso.SinistroPrioritario__c = True;
		//caso.edsTip = '2';
		caso.Type = 'Padrão';

        caso.Data_Aviso_Cliente__c = system.today();
        caso.Dataocorrencia__c = system.today();
        //caso.CurrencyIsoCode = 'USD';
        System.debug('casoPai = ' + caso);
        insert caso;
          
    }

	@isTest
    static void Sucesso(){
        Recordtype REC_ID_PERSONACCOUNT = RecordTypeBO.buscarTipoRegistro('Account', 'PessoaFisica'); 
        Date datePersonBirthdate = Date.newInstance(1984, 02, 02);
        Account contaFisica2 =  new Account(RecordtypeId = REC_ID_PERSONACCOUNT.Id,
				FirstName = 'PessoaFisica',
				LastName = 'PessoaFisica',
				Cpf__c = '075.517.654-50',
				Pep__c = 'Não',
				Nacionalidade__c = 'Brasileira',
				Phone = '(00) 0000-0000', // ANNVI-55 - INICIO/FIM
				PersonBirthdate = datePersonBirthdate);
        
        insert contaFisica2;
        
        contact contato = [SELECT Id FROM Contact WHERE AccountId =: contaFisica2.Id];
		
        FormaPagamento__c formaPG = new FormaPagamento__c();
        formaPG.Codigo__c = '987654';
        FormaPG.Name = '5X';
        insert formaPG;
        
        Parceiro__c parceiro = new Parceiro__c();
        parceiro.DiaFaturamento__c = '10';
        parceiro.DiaPreFaturamento__c = '08';
        parceiro.PrazoVencimento__c = '30';
        parceiro.Conta__c = contaFisica2.Id;
        parceiro.FaturaProdutosSeparados__c = 'Não';  
        parceiro.FormaPagamento__c = formaPG.Id;
        parceiro.PossuiAnexoFatura__c = 'Sim';
        parceiro.SiglaParceiro__c = 'PSEG';
        parceiro.Empresa__c = '1';
        parceiro.Sucursal__c = '1';
        parceiro.Ramo__c = '1377';
        
        
        insert parceiro;
        
        Case caso  = [select Id from Case ];        
        
       	case casoFilho = new case();
        
        Id IdRegistro = [SELECT Id, Name, DeveloperName, SobjectType	FROM RecordType where Name = 'Sinistro'].Id;
        //Recordtype REC_ID_SINISTRO = RecordTypeBO.buscarTipoRegistro('Case', 'Sinistro');
        //casoFilho.ParentId = caso.Id;
        casoFilho.RecordTypeId = IdRegistro;
        casoFilho.ParentId = caso.Id;
        casoFilho.AccountId = contaFisica2.Id;
        casoFilho.ContactId = contato.Id;
        casoFilho.Status_Dependente__c = 'Aberto';

        casoFilho.Data_Aviso_Cliente__c = system.today();
        casoFilho.Dataocorrencia__c = system.today().addDays(-30);
        casoFilho.CurrencyIsoCode = 'USD';
        casoFilho.Parceiro__c = parceiro.Id;
        insert casoFilho; 
        
        
        Set<Id> lcasos = new Set<Id>();
        Case pg  = [select Id, Parceiro__r.conta__c, Parceiro__c, ProdutoContratoFormula__c, Nome_Segurado__c, Cpf_Segurado__c, Dataocorrencia__c, Subject, Description, Numero_titulo__c,
		Vitima__c, IdPrestadora__c, TipoEvento__c, EmpresaSplit__c, sucursal__c, RamoSplit__c, Numero_Apolice__c, SinistroPrioritario__c from Case where Id =: casoFilho.Id ];
        lcasos.add(pg.Id);
		
		ProdutoParceiro__c pp = new ProdutoParceiro__c();

		pp.CodigoProdutoParceiro__c  = pg.ProdutoContratoFormula__c;
		pp.Parceiro__c = pg.Parceiro__c;

		insert pp;
		
        //PLV-4363 - INICIO
        Banco__c banconew = new Banco__c();
        banconew.CodigoBanco__c = '246';
        banconew.ConveniadoADC__c  = false;
        banconew.Name = 'A B C ROMA S/A';
        banconew.Ativo__c = true;
        insert banconew; 
        //PLV-4363 - FIM

        
		InformacaoBancaria__c banco = new InformacaoBancaria__c();
        
        banco.Banco__c = '246';
		banco.Agencia__c = '3758';
		banco.NumeroConta__c = '35958';
        //PLV-3918-FIX6 - INICIO
        //PLV-3918-FIX7 - INICIO
		banco.Digito__c = '6';
		//PLV-3918-FIX7 - FIM
        //PLV-3918-FIX6 - FIM
        banco.StatusIntegracao__c = 'Validada';
		banco.Conta__c = pg.Parceiro__r.conta__c;
        banco.Principal__c = true;
        banco.BancoNew__c = banconew.Id; //PLV-4363 - INICIO/FIM

		insert banco;
        
        test.startTest();
        CriarPagamentoSinistro.inserirPagamentoSinistro(lcasos);
        test.stopTest();

        
    }
}