workspace-sf/force-app/main/default/objects/Banco__c/Banco__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar os bancos.</description>
    <label>Banco</label>
    <nameField>
        <label>Nome do Banco</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bancos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/Banco__c/fields/CodigoBanco__c.field-meta.xml
<CustomField>
    <fullName>CodigoBanco__c</fullName>
    <label>Código do Banco</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Banco__c/fields/ConveniadoADC__c.field-meta.xml
<CustomField>
    <fullName>ConveniadoADC__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Banco Conveniado para ADC</label>
    <type>Checkbox</type>
</CustomField>

workspace-sf/force-app/main/default/objects/InformacaoBancaria__c/InformacaoBancaria__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar as informações bancárias das contas</description>
    <label>Informação bancária</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Informações bancárias</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/InformacaoBancaria__c/fields/Agencia__c.field-meta.xml
<CustomField>
    <fullName>Agencia__c</fullName>
    <label>Agência</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/InformacaoBancaria__c/fields/Banco__c.field-meta.xml
<CustomField>
    <fullName>Banco__c</fullName>
    <label>Banco</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/InformacaoBancaria__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>InformacoesBancarias</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/InformacaoBancaria__c/fields/NumeroConta__c.field-meta.xml
<CustomField>
    <fullName>NumeroConta__c</fullName>
    <label>Número da conta</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/InformacaoBancaria__c/fields/Papel__c.field-meta.xml
<CustomField>
    <fullName>Papel__c</fullName>
    <label>Papel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agenciador</fullName>
            </value>
            <value>
                <fullName>Parceiro</fullName>
            </value>
            <value>
                <fullName>Prestador</fullName>
            </value>
            <value>
                <fullName>Segurado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/classes/CargaLegadoInformixBatchTest.cls
@IsTest
public with sharing class CargaLegadoInformixBatchTest {
    //PLV-4293 - INICIO
    @TestSetup
    static void makeData() {
        
        String banco = '341';
        String agencia = '0123';
        String numeroConta = '01234567';

        Account conta1 = new Account(
            Name = 'Conta 1', 
            Cnpj__c = '08.370.609/0001-64',
            Inscricao_Estadual__c = '12345'
        );
        insert conta1;

        Account conta2 = new Account(
            Name = 'Conta 2',
            Papel__c = 'Segurado;',
            Cnpj__c = '08.571.415/0001-27',
            Inscricao_Estadual__c = '12345'
        );
        insert conta2;

        Banco__c bancoNew = new Banco__c(
            CodigoBanco__c = banco,
            ConveniadoADC__c  = false,
            Name = 'BANCO ITAU S/A',
            Ativo__c = true
        );
        insert bancoNew;
        
        insert new InformacaoBancaria__c (
            Banco__c = '341',
            Conta__c = conta1.Id,
            Agencia__c = agencia,
            NumeroConta__c = numeroConta,
            Papel__c = 'Agenciador'
        );

        insert new InformacaoBancaria__c (
            Banco__c = '111',
            Conta__c = conta2.Id,
            Agencia__c = agencia,
            NumeroConta__c = numeroConta,
            Papel__c = 'Agenciador'
        );
    }

    @IsTest 
	static void carga() {
        Test.startTest();
        Database.executeBatch(new CargaLegadoInformixBatch(), 200);
        Test.stopTest();
    }
    //PLV-4293 - FIM
}