workspace-sf/force-app/main/default/objects/MovimentoSinistro__c/MovimentoSinistro__c.object-meta.xml
<CustomObject>
    <description>Registrar os movimentos de sinistro relacionado ao caso. 
Objeto Relacionado do Caso.</description>
    <label>Movimento de Sinistro</label>
    <nameField>
        <displayFormat>MS-{00000}</displayFormat>
        <label>Nome de Movimento de Sinistro</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Movimentos de Sinistro</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/MovimentoSinistro__c/fields/Caso__c.field-meta.xml
<CustomField>
    <fullName>Caso__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Movimentos de Sinistro</relationshipLabel>
    <relationshipName>MovimentosSinistro</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/MovimentoSinistro__c/fields/DataMovimento__c.field-meta.xml
<CustomField>
    <fullName>DataMovimento__c</fullName>
    <label>Data do Movimento</label>
    <type>DateTime</type>
</CustomField>

workspace-sf/force-app/main/default/objects/MovimentoSinistro__c/fields/DescricaoMovimento__c.field-meta.xml
<CustomField>
    <fullName>DescricaoMovimento__c</fullName>
    <label>Descrição do Movimento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>AVISO +</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>AC. AVISADO +</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>AC. AVISADO -</label>
            </value>
            <value>
                <fullName>24</fullName>
                <label>ENC. SEM INDENIZACAO -</label>
            </value>
            <value>
                <fullName>25</fullName>
                <label>REATIVACAO</label>
            </value>
            <value>
                <fullName>32</fullName>
                <label>ACERTO AVISO AUTOM  +</label>
            </value>
            <value>
                <fullName>33</fullName>
                <label>ACERTO AVISO AUTOM   -</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>DESPESAS             +</label>
            </value>
            <value>
                <fullName>17</fullName>
                <label>ACERTO DESPESAS      +</label>
            </value>
            <value>
                <fullName>18</fullName>
                <label>ACERTO DESPESAS      -</label>
            </value>
            <value>
                <fullName>44</fullName>
                <label>Multas Contratuais</label>
            </value>
            <value>
                <fullName>46</fullName>
                <label>Pagamentos Indevidos</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>PAGAMENTO PARCIAL    +</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>ACERTO PGTO PARCIAL  +</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>ACERTO PGTO PARCIAL -</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>PAGAMENTO FINAL      +</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>ACERTO PAGTO FINAL   +</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>ACERTO PAGTO FINAL   -</label>
            </value>
            <value>
                <fullName>52</fullName>
                <label>ACERTO JUROS JUR (+)</label>
            </value>
            <value>
                <fullName>53</fullName>
                <label>ACERTO JUROS JUR (-)</label>
            </value>
            <value>
                <fullName>62</fullName>
                <label>ACERTO CORRECAO JUR (+)</label>
            </value>
            <value>
                <fullName>63</fullName>
                <label>ACERTO CORRECAO JUR (-)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/MovimentoSinistro__c/fields/PagamentoGarantia__c.field-meta.xml
<CustomField>
    <fullName>PagamentoGarantia__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Garantia do Sinistro</label>
    <referenceTo>PagamentoGarantia__c</referenceTo>
    <relationshipLabel>Movimentos de Sinistro</relationshipLabel>
    <relationshipName>MovimentosSinistro</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/MovimentoSinistro__c/fields/SequenciaMovimento__c.field-meta.xml
<CustomField>
    <fullName>SequenciaMovimento__c</fullName>
    <externalId>true</externalId>
    <label>Sequência do Movimento</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/MovimentoSinistro__c/fields/TipoMovimento__c.field-meta.xml
<CustomField>
    <fullName>TipoMovimento__c</fullName>
    <label>Tipo de Movimento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aviso</fullName>
            </value>
            <value>
                <fullName>Despesa</fullName>
            </value>
            <value>
                <fullName>Pagamento</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/MovimentoSinistro__c/fields/ValorMovimento__c.field-meta.xml
<CustomField>
    <fullName>ValorMovimento__c</fullName>
    <label>Valor Movimento</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

workspace-sf/force-app/main/default/objects/PagamentoGarantia__c/PagamentoGarantia__c.object-meta.xml
<CustomObject>
    <description>Registrar os pagamentos das garantias dentro da frente de Sinistro Vida.
Objeto Detalhe de Caso</description>
    <label>Garantia do Sinistro</label>
    <nameField>
        <label>Nome da Garantia do Sinistro</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Garantias do Sinistro</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/PagamentoGarantia__c/fields/Caso__c.field-meta.xml
<CustomField>
    <fullName>Caso__c</fullName>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>Pagamentos_de_garantia</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/PagamentoGarantia__c/fields/Fase__c.field-meta.xml
<CustomField>
    <fullName>Fase__c</fullName>
    <label>Fase</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aberto</fullName>
            </value>
            <value>
                <fullName>Em Análise</fullName>
            </value>
            <value>
                <fullName>Fechado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/PagamentoGarantia__c/fields/Status_do_pagamento__c.field-meta.xml
<CustomField>
    <fullName>Status_do_pagamento__c</fullName>
    <label>Status do Pagamento</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Fase__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Em análise</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
            <value>
                <fullName>Com Pendências</fullName>
            </value>
            <value>
                <fullName>Aguardando Pagamento</fullName>
            </value>
            <value>
                <fullName>Pago Parcialmente</fullName>
            </value>
            <value>
                <fullName>Pago</fullName>
            </value>
            <value>
                <fullName>Recusado</fullName>
            </value>
            <value>
                <fullName>Serviço Prestado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/classes/BotaoReabrirSinistroController.cls
/*******************************************************************************************************************************
* 
* @author Pedro Augusto - SYS4B
* @date 27/07/2020
* @modifiedAt 
* Classe criada por conta da história PLV-4122
********************************************************************************************************************************/

public with sharing class BotaoReabrirSinistroController {


    public static Map<String, String> getMapPicklist(String Objeto, String Campo) {

		Map<String, String> mapValuesPickList = new Map<String, String> ();

        Schema.SObjectType targetType = Schema.getGlobalDescribe().get(Objeto);

		if (targetType != null) {
			sObject sobj = targetType.newSObject();

			Schema.DescribeSObjectResult describeSObjectResult = sobj.getSObjectType().getDescribe();
			Map<String, Schema.SObjectField> fields = describeSObjectResult.fields.getMap();

			Schema.SObjectField fld = fields.get(Campo);

			if (fld != null) {

				if (fld.getDescribe().getType().equals(Schema.DisplayType.PICKLIST) || fld.getDescribe().getType().equals(Schema.DisplayType.MULTIPICKLIST)) {

					Schema.DescribeFieldResult fieldResult = fld.getDescribe();
					List<Schema.PicklistEntry> listPickListEntry = fieldResult.getPicklistValues();

					for (Schema.PicklistEntry pickListVal : listPickListEntry) {
						mapValuesPickList.put(pickListVal.getValue(), pickListVal.getLabel());
					}

					return mapValuesPickList;
				}
			}
		}

		return mapValuesPickList;
    }

    public class innerPicklist{
        @AuraEnabled public String value {get;set;}
        @AuraEnabled public String label {get;set;}
    }

    @AuraEnabled
    public static Map<String,Object> buscarInformacoes(String recordId){
        Map<String,Object> mapToReturn = new Map<String,Object>();
        String perfilAtual = [SELECT Id,Name FROM Profile WHERE Id=:Userinfo.getProfileId()].Name;
        Case caso = [SELECT Id, Status, Sinistro_Judicial__c FROM Case WHERE Id=:recordId];
        System.debug('Status: '+ caso.Status);
        Boolean visible = caso.Status=='Fechado'?true:false;
        mapToReturn.put('visible', visible);
        
        
        List<innerPicklist> motivosToReturn = new List<innerPicklist>();
        List<innerPicklist> tiposContagemToReturn = new List<innerPicklist>();

        //Busca todos os motivos de acordo com o picklist   
        Map<String,String> motivos = getMapPicklist('Case','MotivosReabertura__c');
        for(String key : motivos.keyset()){
            innerPicklist entry = new innerPicklist();
            entry.value = key;
            entry.label = motivos.get(key);
            motivosToReturn.add(entry);
        }
        mapToReturn.put('motivosReabertura',motivosToReturn);

        Map<String,String> contagem = getMapPicklist('Case','TipoContagem__c');
        for(String key : contagem.keyset()){
            innerPicklist entry = new innerPicklist();
            entry.value = key;
            entry.label = contagem.get(key);
            tiposContagemToReturn.add(entry);
        }
        mapToReturn.put('listTipoContagem',tiposContagemToReturn);
        

        List<String> getCanReabrir = getCanReabrir();
        if(getCanReabrir.contains(perfilAtual)){
            //perfil pode reabrir
            Boolean judicial = caso.Sinistro_Judicial__c;
            
            List<String> getCanReabrirJuridico = getCanReabrirJuridico();

            if(judicial && getCanReabrirJuridico.contains(perfilAtual)){
                mapToReturn.put('canReopen',true);
            }else if(judicial && !getCanReabrirJuridico.contains(perfilAtual)){
                mapToReturn.put('canReopen',false);
            }else{
                mapToReturn.put('canReopen',true);
            }
        }else{
                mapToReturn.put('canReopen',false);
        }        

        
        return mapToReturn;
    }

    
    @AuraEnabled
    public static Map<String,Object> reabrirSinistro(String recordId, String motivo,String TipoContagem, String observacao){
        Map<String,Object> mapToReturn = new Map<String,Object>();

        Case casoToUpdate = new Case();
        casoToUpdate.Id = recordId;
        casoToUpdate.Status = 'Em Regulação';
        casoToUpdate.Status_Dependente__c = 'Avisado';
        casoToUpdate.MotivosReabertura__c = motivo;
        casoToUpdate.DataReabertura__c = System.now();
        casoToUpdate.ConsideracoesReabertura__c = observacao;
        casoToUpdate.TipoContagem__c = TipoContagem;

        //FIX 5415674 - Reabertura de sinistro - INICIO
        List<PagamentoGarantia__c> listGarantias = [SELECT Id
                                                        , Name
                                                        , Capital__c
                                                        FROM PagamentoGarantia__c
                                                        WHERE Caso__c=:recordId 
                                                        AND Fase__c ='Fechado'
                                                        AND (Status_do_pagamento__c='Cancelado' OR Status_do_pagamento__c='Recusado')];

        List<MovimentoSinistro__c> listMovimentoToCreate = null;
        
        if(!listGarantias.isEmpty()){
            Integer iteradorMovimento = 0;  //PLV-5852 INICIO/FIM
            listMovimentoToCreate = new List<MovimentoSinistro__c>();
            for (PagamentoGarantia__c pg : listGarantias) {
                MovimentoSinistro__c tocreate = criarMovimentoReabertura(recordId, pg.Id, pg.Capital__c, iteradorMovimento); //PLV-5852 INICIO/FIM
                listMovimentoToCreate.add(tocreate);

                pg.Fase__c ='Aberto';
                pg.Status_do_pagamento__c= 'Em Análise';
                iteradorMovimento = iteradorMovimento + 1; //PLV-5852 INICIO/FIM
            }
        }
        //FIX 5415674 - Reabertura de sinistro - FIM

		Savepoint sp = Database.setSavepoint();

        try {

            update casoToUpdate;
            
            if(listMovimentoToCreate!=null){
                insert listMovimentoToCreate;
                update listGarantias;
            }

            mapToReturn.put('sucesso', true);   

        } catch (Exception e) {
    	    Database.rollback(sp);
            System.debug('Erro ao atualizar o caso'+ e.getLineNumber() + ' - '+e.getMessage());           
            mapToReturn.put('sucesso', false);         
            mapToReturn.put('mensagem', 'Erro ao atualizar o caso '+ e.getLineNumber() + ' - '+e.getMessage());  
            return mapToReturn;       
        }

        return mapToReturn;
    }

    
    //FIX 5415674 - Reabertura de sinistro - INICIO
    public static MovimentoSinistro__c criarMovimentoReabertura(String caseId, String garantiaId, Decimal valor, Integer iteradorMovimento){ //PLV-5852 INICIO/FIM
        Map<Id, Integer> mSequenciaMov = SequenciaMovimentoSinistroHelper.sequenciaMovimentos(new Set<Id>{caseId});
		PagamentoGarantiaBO pgbo= new PagamentoGarantiaBO();
		Integer movimento = pgbo.getSequencia(mSequenciaMov, caseId) + iteradorMovimento; //PLV-5852 INICIO/FIM		

        MovimentoSinistro__c movimentoToCreate = new MovimentoSinistro__c();
        movimentoToCreate.DescricaoMovimento__c = '25'; // obrigatório para reabrir o caso
        movimentoToCreate.Caso__c=caseId;
        movimentoToCreate.DataMovimento__c=System.now();
        movimentoToCreate.ValorMovimento__c = valor;
		movimentoToCreate.SequenciaMovimento__c = String.valueOf(movimento);
        movimentoToCreate.PagamentoGarantia__c=garantiaId;
        movimentoToCreate.TipoMovimento__c='Aviso';
        return movimentoToCreate;
    }
    //FIX 5415674 - Reabertura de sinistro - FIM

	public static List<String> getCanReabrir(){
		//LISTAR AQUI TODOS OS PERFIS QUE PODEM REABRIR SINISTROS
		List<String> permitidos = new List<String>();
		permitidos.add('Administrador Porto');
		permitidos.add('Administrador do sistema');
		permitidos.add('System Administrator');
		permitidos.add('Jurídico');
		permitidos.add('API');
		permitidos.add('Processos e Projetos');
		permitidos.add('Sinistro e Benefícios');


		return permitidos;
    }
    
	public static List<String> getCanReabrirJuridico(){
		//PERFIS QUE PODEM REABRIR CASOS JURÍDICOS
		List<String> permitidos = new List<String>();
		permitidos.add('Administrador Porto');
		permitidos.add('Administrador do sistema');
        permitidos.add('System Administrator');
        permitidos.add('Jurídico');

		
		return permitidos;
	}
}