workspace-sf/force-app/main/default/objects/Modalidade__c/Modalidade__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar as modalidades</description>
    <label>Modalidade</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Modalidades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/Modalidade__c/fields/CodigoEmpresa__c.field-meta.xml
<CustomField>
    <fullName>CodigoEmpresa__c</fullName>
    <formula>Empresa__r.CodigoEmpresa__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Código da empresa</label>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Modalidade__c/fields/Empresa__c.field-meta.xml
<CustomField>
    <fullName>Empresa__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empresa</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Modalidades</relationshipLabel>
    <relationshipName>Modalidades</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Modalidade__c/fields/IdExterno__c.field-meta.xml
<CustomField>
    <fullName>IdExterno__c</fullName>
    <externalId>true</externalId>
    <label>Id externo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Modalidade__c/fields/RamoSeguro__c.field-meta.xml
<CustomField>
    <fullName>RamoSeguro__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ramo de seguro</label>
    <referenceTo>RamoSeguro__c</referenceTo>
    <relationshipLabel>Modalidades</relationshipLabel>
    <relationshipName>Modalidades</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/RamoSeguro__c/RamoSeguro__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar o cadastro dos ramos de seguro</description>
    <label>Ramo de seguro</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ramos de seguro</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/RamoSeguro__c/fields/CodigoEmpresa__c.field-meta.xml
<CustomField>
    <fullName>CodigoEmpresa__c</fullName>
    <label>Código da empresa</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/RamoSeguro__c/fields/Empresa__c.field-meta.xml
<CustomField>
    <fullName>Empresa__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empresa</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>RamosSeguro</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/RamoSeguro__c/fields/IdExterno__c.field-meta.xml
<CustomField>
    <fullName>IdExterno__c</fullName>
    <externalId>true</externalId>
    <label>Id externo</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

workspace-sf/force-app/main/default/classes/ModalidadeBO.cls
/**
 * Regras de Negócio do Objeto Modalidade__c
 * @author João Losada @ 28/06/2018
 *
 **/
public with sharing class ModalidadeBO {
	private static final ModalidadeBO instance = new ModalidadeBO();
	private ModalidadeDAO dao = ModalidadeDAO.getInstance();

	private ModalidadeBO() { }

	public static ModalidadeBO getInstance() {
		return instance;
	}

	public void sincronizarDados() {

		System.debug('====== Sincronizando Modalidade');

		ServiceTO.ModalidadeTO tempDados = F5Service.getInstance().buscarModalidades('5');

		System.debug('======= Modalidades retornadas do serviço');
		System.debug(tempDados);

		System.debug('======= Quantidade de modalidades retornadas do serviço');
		System.debug(tempDados.Modalidades.size());

		List<Modalidade__c> dadosParaSincronizar = new List<Modalidade__c>();
		Map<String, Id> mapEmpresa = new Map<String, Id>();
		Map<String, Id> mapRamoSeguro = new Map<String, Id>();

	
		Set<String> LstcodEmpresa = new Set<String>();
		Set<String> LstcodRamo = new Set<String>();

		for (ServiceTO.ListModalidadesTO lstModalidade : tempDados.Modalidades) 
		{
			LstcodEmpresa.add(lstModalidade.codigoEmpresa);
			LstcodRamo.add(lstModalidade.codigoRamo);
		}			

		// busca id ramo atividade
		for(RamoSeguro__c RamoSeguro : RamoSeguroDAO.getInstance().obterRamoPorCodigos(LstcodRamo))
		{
			mapRamoSeguro.put(RamoSeguro.Codigo__c, RamoSeguro.Id);
		}

		// busca id empresa
		for(Account Empresa : AccountDAO.getInstance().buscarContasPorCodEmpresa(lstcodEmpresa))
		{
			mapEmpresa.put(Empresa.CodigoEmpresa__c, Empresa.Id);
		}

		Id strIdEmpresa;
		Id strIdRamo;

		for (ServiceTO.ListModalidadesTO lstModalidade : tempDados.Modalidades) 
		{
			// busca id empresa
			if(mapEmpresa.containsKey(lstModalidade.codigoEmpresa))
			{
				strIdEmpresa = mapEmpresa.get(lstModalidade.codigoEmpresa); 
			}

			// busca id ramo atividade
			if(mapRamoSeguro.containsKey(lstModalidade.codigoRamo))
			{
				strIdRamo    = mapRamoSeguro.get(lstModalidade.codigoRamo);
			}

			String strKey = String.valueOf(lstModalidade.codigoModalidade) + '.' + String.valueOf(lstModalidade.codigoEmpresa) + '.' + String.valueOf(lstModalidade.codigoRamo);

			Modalidade__c modalidade = new Modalidade__c();

			modalidade.Codigo__c 	= lstModalidade.codigoModalidade;
			modalidade.Descricao__c = lstModalidade.nomeModalidade;
			modalidade.Name 		= lstModalidade.nomeModalidade;
			modalidade.Empresa__c 	= strIdEmpresa;
			modalidade.RamoSeguro__c = strIdRamo;
			modalidade.IdExterno__c = strKey;

			dadosParaSincronizar.add(modalidade);

		}

		System.debug('======= Modalidades para inserir: ');
		System.debug(dadosParaSincronizar);

		System.debug('======= Quantidade de modalidades para inserir: ');
		System.debug(dadosParaSincronizar.size());

		if(!dadosParaSincronizar.isEmpty()){
			upsert dadosParaSincronizar IdExterno__c;
		}

		IntegracaoBO.getInstance().atualizarUltimaExecucao('Modalidade__c');

	}
}