workspace-sf/force-app/main/default/objects/Constante__mdt/Constante__mdt.object-meta.xml
<CustomObject>
    <label>Constante</label>
    <pluralLabel>Constantes</pluralLabel>
</CustomObject>

workspace-sf/force-app/main/default/objects/MovimentoSinistro__c/MovimentoSinistro__c.object-meta.xml
<CustomObject>
    <description>Registrar os movimentos de sinistro relacionado ao caso. 
Objeto Relacionado do Caso.</description>
    <label>Movimento de Sinistro</label>
    <nameField>
        <displayFormat>MS-{00000}</displayFormat>
        <label>Nome de Movimento de Sinistro</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Movimentos de Sinistro</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/MovimentoSinistro__c/fields/Caso__c.field-meta.xml
<CustomField>
    <fullName>Caso__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Movimentos de Sinistro</relationshipLabel>
    <relationshipName>MovimentosSinistro</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/MovimentoSinistro__c/fields/PagamentoGarantia__c.field-meta.xml
<CustomField>
    <fullName>PagamentoGarantia__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Garantia do Sinistro</label>
    <referenceTo>PagamentoGarantia__c</referenceTo>
    <relationshipLabel>Movimentos de Sinistro</relationshipLabel>
    <relationshipName>MovimentosSinistro</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/MovimentoSinistro__c/fields/SinistroJudicial__c.field-meta.xml
<CustomField>
    <fullName>SinistroJudicial__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Sinaliza se o movimento é judicial ou não</description>
    <label>Sinistro Judicial?</label>
    <type>Checkbox</type>
</CustomField>

workspace-sf/force-app/main/default/objects/PagamentoGarantia__c/PagamentoGarantia__c.object-meta.xml
<CustomObject>
    <description>Registrar os pagamentos das garantias dentro da frente de Sinistro Vida.
Objeto Detalhe de Caso</description>
    <label>Garantia do Sinistro</label>
    <nameField>
        <label>Nome da Garantia do Sinistro</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Garantias do Sinistro</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/PagamentoGarantia__c/fields/Caso__c.field-meta.xml
<CustomField>
    <fullName>Caso__c</fullName>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>Pagamentos_de_garantia</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/PagamentoGarantia__c/fields/Fase__c.field-meta.xml
<CustomField>
    <fullName>Fase__c</fullName>
    <label>Fase</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aberto</fullName>
            </value>
            <value>
                <fullName>Em Análise</fullName>
            </value>
            <value>
                <fullName>Fechado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/PagamentoGarantia__c/fields/Motivo_da_Recusa__c.field-meta.xml
<CustomField>
    <fullName>Motivo_da_Recusa__c</fullName>
    <label>Motivo da Recusa</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>6</fullName>
                <label>ABERTO INDEVIDAMENTE</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>ADMINISTRATIVAMENTE</label>
            </value>
            <value>
                <fullName>23</fullName>
                <label>A EXUMAÇÃO DOS CORPOS QUE ESTIVEREM NO JAZIGO QUANDO DO SEPULTAMENTO</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>AGRAVO DE RISCO</label>
            </value>
            <value>
                <fullName>21</fullName>
                <label>APARELHOS QUE SE REFEREM À ÓRTESES DE QUALQUER NATUREZA E A PRÓTESES DE CARÁTER PERMANENTE, SALVO AS PRÓTESES OU ÓRTESES IMPLANTADAS PELA PRIMEIRA VEZ DEVIDO AO EVENTO COBERTO</label>
            </value>
            <value>
                <fullName>49</fullName>
                <label>APÓLICE COM PARCELA PENDENTE</label>
            </value>
            <value>
                <fullName>22</fullName>
                <label>AQUISIÇÃO DE JAZIGO</label>
            </value>
            <value>
                <fullName>19</fullName>
                <label>AS DOENÇAS E OS ACIDENTES OCORRIDOS COM ALGUM DOS MEMBROS DA SUA FAMÍLIA, QUE NÃO OCASIONE INTERNAÇÃO</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>ATO ILÍCITO</label>
            </value>
            <value>
                <fullName>42</fullName>
                <label>CANCELAMENTO DE VIAGEM - COMPRA DE NOVA PASSAGEM</label>
            </value>
            <value>
                <fullName>18</fullName>
                <label>CANCELAMENTO DE VIAGEM PARA VIAGENS DE NAVIO, TREM , ÔNIBUS, MOTO, CARRO OU OUTRO MEIO DE DESLOCAMENTO</label>
            </value>
            <value>
                <fullName>50</fullName>
                <label>DATA DE OCORRÊNCIA ANTES DO INICIO DE VIGÊNCIA DA APÓLICE</label>
            </value>
            <value>
                <fullName>51</fullName>
                <label>DATA DE OCORRÊNCIA APÓS CANCELAMENTO DA APÓLICE</label>
            </value>
            <value>
                <fullName>52</fullName>
                <label>DATA DE OCORRÊNCIA APÓS O TERMINO VIGÊNCIA APÓLICE</label>
            </value>
            <value>
                <fullName>53</fullName>
                <label>DEMISSÃO POR JUSTA CAUSA</label>
            </value>
            <value>
                <fullName>54</fullName>
                <label>DIAGNOSTICO SEM NEXO CASUAL COM O ACIDENTE</label>
            </value>
            <value>
                <fullName>55</fullName>
                <label>DUPLICIDADE</label>
            </value>
            <value>
                <fullName>56</fullName>
                <label>EMBRIAGUEZ</label>
            </value>
            <value>
                <fullName>32</fullName>
                <label>ENCERRAMENTO POR FALTA DE DOCUMENTOS - VIAGEM</label>
            </value>
            <value>
                <fullName>46</fullName>
                <label>EPIDEMIAS E PANDEMIAS</label>
            </value>
            <value>
                <fullName>57</fullName>
                <label>EVENTO FORA DO PERÍODO DE VIGÊNCIA</label>
            </value>
            <value>
                <fullName>25</fullName>
                <label>EVENTO NÃO COMUNICADO A CIA AÉREA - VIAGEM</label>
            </value>
            <value>
                <fullName>48</fullName>
                <label>EVENTO NÃO SE ENQUADRA NO CONCEITO DE CANCELAMENTO DE VIAGEM</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>EVENTO NÃO SE ENQUADRA NO CONCEITO DE INTERRUPÇÃO DE VIAGEM</label>
            </value>
            <value>
                <fullName>47</fullName>
                <label>EVENTO NÃO SE ENQUADRA NO CONCEITO DE REMARCAÇÃO DE PASSAGEM</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>EVENTO OCORREU APOS CANCELAMENTO DA APÓLICE</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>EVENTO OCORRIDO ANTES DO INICIO DE VIGÊNCIA DA APÓLICE</label>
            </value>
            <value>
                <fullName>41</fullName>
                <label>EXTRAVIO DE BAGAGEM - MALA LOCALIZADA</label>
            </value>
            <value>
                <fullName>58</fullName>
                <label>FALTA DE JUSTIFICATIVA MEDICA PARA O AFASTAMENTO</label>
            </value>
            <value>
                <fullName>59</fullName>
                <label>FALTA DE VINCULO EMPREGATÍCIO</label>
            </value>
            <value>
                <fullName>68</fullName>
                <label>ULTRAPASSOU O PERÍODO DE AVISO</label>
            </value>
            <value>
                <fullName>69</fullName>
                <label>VINCULO EMPREGATÍCIO MENOR QUE 12 MESES</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/PagamentoGarantia__c/fields/Saldo_da_reserva__c.field-meta.xml
<CustomField>
    <fullName>Saldo_da_reserva__c</fullName>
    <label>Saldo da reserva - Garantia</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

workspace-sf/force-app/main/default/objects/PagamentoGarantia__c/fields/Status_do_pagamento__c.field-meta.xml
<CustomField>
    <fullName>Status_do_pagamento__c</fullName>
    <label>Status do Pagamento</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Fase__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Em análise</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
            <value>
                <fullName>Com Pendências</fullName>
            </value>
            <value>
                <fullName>Aguardando Pagamento</fullName>
            </value>
            <value>
                <fullName>Pago Parcialmente</fullName>
            </value>
            <value>
                <fullName>Pago</fullName>
            </value>
            <value>
                <fullName>Recusado</fullName>
            </value>
            <value>
                <fullName>Serviço Prestado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/classes/BatchBaixaReserva.cls
/*********************************************************************************************************************************************************************
@description Classe batch responsavel por dar baixar nos casos de sinistro com Reserva 
@author Rogerio Souza de Menezes - Globant
@date 10/08/2023
**********************************************************************************************************************************************************************/
//II-59 INICIO
global class BatchBaixaReserva implements Database.Batchable<sObject>, Database.StateFul, Database.AllowsCallouts, Schedulable {

    List<Constante__mdt> constante = MetadataDAO.getInstance().buscarConstante('DATA_CORTE_SINISTRO');
    //FNPVVEP-19 - INICIO
    List<Constante__mdt> limite = MetadataDAO.getInstance().buscarConstante('LIMITE_BATCH_BAIXA_RESERVA');

    Integer ultimosDias = Integer.valueOf(constante[0].Valor__c);
    Date dataCorte = Date.today().addDays(-ultimosDias);
    global final Integer limiteQuery = Integer.valueOf(limite[0].Valor__c);
    //FNPVVEP-19 - FIM

    global Database.QueryLocator start(Database.BatchableContext context){
        return Database.getQueryLocator(
                [SELECT Id, RamoSplit__c, Owner.Name, Saldo_da_reserva__c, Status, CreatedDate
                    FROM Case
                    WHERE Type = 'Sinistro'
                        AND RamoSplit__c NOT IN (980, 1380)
                        AND Sinistro_Judicial__c  = false // II-59-FIX01-INICIO/FIM
                        AND Status != 'Fechado'
                        AND Saldo_da_reserva__c != null
                        AND Saldo_da_reserva__c > 0
                        AND PagtoAssistCardInternacional__c != 'Sim' //II-59-FIX06-INICIO/FIM
                        AND Data_sinistro_avisado__c < :dataCorte
                        AND ReservaNegativa__c = false //FNPVVEP-19 - INICIO/FIM
                    LIMIT : limiteQuery
                    ]
        );
    }

    global void execute(Database.BatchableContext batchableContext, List<Case> scope){
        baixarCasosReserva(scope);
    }

    global void execute(SchedulableContext schedulableContext){
        Database.executeBatch(this);
    }

    global void finish(Database.BatchableContext batchableContext){}

    global void agendarBatch(){
        String cron = '0 0 8 * * ?'; 
        String cron1 = '0 0 10 * * ?'; 
        String cron2 = '0 0 12 * * ?'; 
        String cron3 = '0 0 14 * * ?'; 
        String cron4 = '0 0 16 * * ?'; 
        system.schedule('BaixarReserva 8H',cron,this);
        system.schedule('BaixarReserva 10H',cron1,this);
        system.schedule('BaixarReserva 12H',cron2,this);
        system.schedule('BaixarReserva 14H',cron3,this);
        system.schedule('BaixarReserva 16H',cron4,this);
    }

    global void baixarCasosReserva(List<Case> casosReserva){    

        //FNPVVEP-19 - INICIO
        List<PagamentoGarantia__c> garantias = new List<PagamentoGarantia__c>();
        List<PagamentoGarantia__c> garantiaAFechar = new List<PagamentoGarantia__c>();
        List<MovimentoSinistro__c> movimentosGerados = new List<MovimentoSinistro__c>();
        List<Case> fecharCasos = new List<Case>();

        Set<Id> casosId = new Set<Id>(); //II-59-FIX02-INICIO
        Set<Id> setCase = new Set<Id>();

        Map<Id, List<PagamentoGarantia__c>> pagamentoGarantiaIndexedByCaseId = new Map<Id, List<PagamentoGarantia__c>>();

        PagamentoGarantia__c garantia = new PagamentoGarantia__c();
        MovimentoSinistroBO movSinBO = MovimentoSinistroBO.getInstance();

        for(Case casoMov : casosReserva){
            setCase.add(casoMov.id);
        }
        //II-59-FIX05-FIM

        Map<Id, Integer> mapSequencia = SequenciaMovimentoSinistroHelper.sequenciaMovimentos(setcase);

        List<PagamentoGarantia__c> pagamentoGarantias = PagamentoGarantiaDAO.getInstance().buscarCasosBySetId(setCase);  

        for(PagamentoGarantia__c pagGarantia : pagamentoGarantias){
            if(!pagamentoGarantiaIndexedByCaseId.containsKey(pagGarantia.Caso__c)){
                pagamentoGarantiaIndexedByCaseId.put(pagGarantia.Caso__c, new List<PagamentoGarantia__c>());
            }

            pagamentoGarantiaIndexedByCaseId.get(pagGarantia.Caso__c).add(pagGarantia);
        }

        for(Case caso : casosReserva){
            garantias = pagamentoGarantiaIndexedByCaseId.get(caso.Id);

            //II-59-FIX05-INICIO
            if(!garantias.isEmpty()){
                
                Integer iteradorMovimento = 0;

                for(PagamentoGarantia__c garantiasSinistro : garantias){

                    if(caso.Saldo_da_reserva__c >= 0){
                        garantia = verificarGarantia(garantiasSinistro);
                    
                        garantia = prepararGarantia(garantiasSinistro, garantia.Fase__c, garantia.Status_do_pagamento__c, '68');         
                        garantiaAFechar.add(garantia);
    
                        Case casoAFechar = new Case(Id = garantia.Caso__c, 
                                                    Status = garantia.Caso__r.Status, 
                                                    Saldo_da_reserva__c = garantia.Caso__r.Saldo_da_reserva__c, 
                                                    Status_Dependente__c = garantia.Caso__r.Status_Dependente__c, 
                                                    Motivos_de_recusa__c = '69'); //II-59 FIX01 INICIO-FIM        
                        
                        //II-59-FIX06-INICIO
                        if(garantiasSinistro.Saldo_da_reserva__c > 0){
    
                            Decimal valorMovimento = -1 * garantiasSinistro.Saldo_da_reserva__c;
                            Boolean permitirGerarMov = garantia.Saldo_da_reserva__c == 0 && garantia.Caso__r.Saldo_da_reserva__c == 0 ? false : true;
                            
                            iteradorMovimento = iteradorMovimento + 1;

                            Integer sequencia = mapSequencia.containsKey(caso.Id) ? mapSequencia.get(caso.Id) + iteradorMovimento : 1;
    
                            MovimentoSinistro__c movimentoGerado = movSinBO.criarMovimento(caso.Id, MovimentoSinistroTO.AC_AVISADO_MENOS, valorMovimento, String.valueOf(sequencia), garantiasSinistro.Id, false); //FNPVVEP-19 INICIO/FIM
                           
                            if(movimentoGerado != null && movimentoGerado.SinistroJudicial__c == false){
    
                                if(permitirGerarMov){
                                    movimentosGerados.add(movimentoGerado);
                                }
                                
                                if(!casosId.contains(casoAFechar.Id)){
                                    casosId.add(casoAFechar.Id);
                                    casoAFechar.Status = 'Fechado';
                                    fecharCasos.add(casoAFechar);
                                }
                                //II-59-FIX02-FIM
                            }         
                        }
                    //FNPVVEP-19 INICIO
                        if(garantiasSinistro.Saldo_da_reserva__c < 0){
                            caso.ReservaNegativa__c = true;
                            fecharCasos.add(caso);
                        }
                    }

                    if(caso.Saldo_da_reserva__c < 0){
                        caso.ReservaNegativa__c = true;
                        fecharCasos.add(caso);
                    }
                    //FNPVVEP-19 FIM

                    //II-59-FIX06-FIM
                    //II-59-FIX05-FIM                                           
                }
            }
        }
        //FNPVVEP-19 - FIM

    
        if(!garantiaAFechar.isEmpty()){
            update garantiaAFechar;
        }
        if(!fecharCasos.isEmpty()){
            update fecharCasos;
        }        
        if(!movimentosGerados.isEmpty()){
            insert movimentosGerados;
        }
    }

    private static PagamentoGarantia__c prepararGarantia(PagamentoGarantia__c garantia, String fase, String statusPgto, String motivoRecusa){
        garantia.Fase__c = fase;
        garantia.Status_do_pagamento__c = statusPgto;
        garantia.Motivo_da_Recusa__c = motivoRecusa;
        return garantia;
    }
    //II-59-FIX02-INICIO
    private static PagamentoGarantia__c verificarGarantia(PagamentoGarantia__c garantia){ 

        if(garantia.Fase__c == 'Fechado' && garantia.Status_do_pagamento__c == 'Pago' &&
            garantia.Caso__r.Status == 'Liquidação'){
                return garantia;
            }

        if(garantia.Fase__c != 'Fechado' && garantia.Status_do_pagamento__c != 'Pago' &&
            garantia.Caso__r.Status == 'Liquidação'){
                return garantia;
            }

        if(garantia.Fase__c != 'Fechado' && garantia.Status_do_pagamento__c != 'Pago' &&
             garantia.Caso__r.Status != 'Liquidação'){
                garantia.Caso__r.Status_Dependente__c = 'Cancelado';
                garantia.Fase__c = 'Fechado';
                garantia.Status_do_pagamento__c = 'Cancelado';
            }
         
         return garantia;
    }
    //II-59-FIX02-FIM
}
//II-59 FIM