workspace-sf/force-app/main/default/objects/FavorecidoRemuneracaoProposta__c/FavorecidoRemuneracaoProposta__c.object-meta.xml
<CustomObject>
    <label>Favorecido da Remuneração da Proposta</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Favorecido da Proposta</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Favorecidos da Remuneração da Proposta</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/FavorecidoRemuneracaoProposta__c/fields/RemuneracaoProposta__c.field-meta.xml
<CustomField>
    <fullName>RemuneracaoProposta__c</fullName>
    <label>Remuneração da proposta</label>
    <referenceTo>RemuneracaoProposta__c</referenceTo>
    <relationshipLabel>Favorecidos da Remuneração da Proposta</relationshipLabel>
    <relationshipName>FavorecidosRemuneracaodaProposta</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/RemuneracaoProposta__c/RemuneracaoProposta__c.object-meta.xml
<CustomObject>
    <description>Objeto de relacionamento entre a proposta e o tipo de remuneração.</description>
    <label>Remuneração da proposta</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Remunerações da proposta</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/RemuneracaoProposta__c/fields/Proposta__c.field-meta.xml
<CustomField>
    <fullName>Proposta__c</fullName>
    <label>Proposta</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Remunerações da proposta</relationshipLabel>
    <relationshipName>RemuneracoesProposta</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/classes/ExpurgoFavorecidoRemuneracaoProposta.cls
/**
 * Expurgo de dados para o Proposta
 *  objeto: FavorecidoRemuneracaoProposta__c  
 * caminho do objeto:
 *  > FavorecidoRemuneracaoProposta__c  
 *  > RemuneracaoProposta__c
 *  > Proposta__c
 * 
 * 28/02/2024
 */

public with sharing class ExpurgoFavorecidoRemuneracaoProposta {

    public List<FavorecidoRemuneracaoProposta__c> getDadosExpurgo(Integer qt) { 
        List<FavorecidoRemuneracaoProposta__c> expList= new List<FavorecidoRemuneracaoProposta__c>();
        String query= 'SELECT Id '
            +'FROM FavorecidoRemuneracaoProposta__c '
            +'WHERE RemuneracaoProposta__r.Proposta__r.Segmento__c = \'Massificados\' ';
        if (qt != 0) {
            query+= 'LIMIT :qt';
        }
        expList= Database.queryWithBinds(query, new Map<String,Object>{'qt' => qt}, AccessLevel.SYSTEM_MODE);
        System.debug(expList);
        return expList;
    }

    public void deleteDadosExpurgo(List<FavorecidoRemuneracaoProposta__c> expList) {
        if (!Test.isRunningTest()) {
           delete (List<FavorecidoRemuneracaoProposta__c>)expList;
        }
    }
}