workspace-sf/force-app/main/default/objects/OfertaRemuneracaoProduto__c/OfertaRemuneracaoProduto__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar as remunerações dos produtos das Ofertas.</description>
    <label>Oferta de Remuneração de Produto</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Numero</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ofertas de Remunerações de Produto</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/OfertaRemuneracaoProduto__c/fields/Obrigatoria__c.field-meta.xml
<CustomField>
    <fullName>Obrigatoria__c</fullName>
    <formula>RemuneracaoProduto__r.Obrigatoria__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Obrigatoria</label>
    <type>Checkbox</type>
</CustomField>

workspace-sf/force-app/main/default/objects/OfertaRemuneracaoProduto__c/fields/RemuneracaoProduto__c.field-meta.xml
<CustomField>
    <fullName>RemuneracaoProduto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Remuneração do produto</label>
    <referenceTo>RemuneracaoProduto__c</referenceTo>
    <relationshipLabel>Ofertas de Remunerações de Produto</relationshipLabel>
    <relationshipName>OfertasRemuneracoesProduto</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/RemuneracaoProduto__c/RemuneracaoProduto__c.object-meta.xml
<CustomObject>
    <description>Objeto de relacionamento entre o produto e o tipo de remuneração</description>
    <label>Remuneração do produto</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Remunerações do produto</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/RemuneracaoProduto__c/fields/RemuneracaoProduto__c.field-meta.xml
<CustomField>
    <fullName>RemuneracaoProduto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Remuneração do produto</label>
    <referenceTo>RemuneracaoProduto__c</referenceTo>
    <relationshipLabel>Remunerações do produto</relationshipLabel>
    <relationshipName>RemuneracoesProduto</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/classes/OfertaRemuneracaoProdutoHandler.cls
public class OfertaRemuneracaoProdutoHandler extends TriggerHandler  {

    private List<OfertaRemuneracaoProduto__c> listORPNew {get;set;}
    private List<OfertaRemuneracaoProduto__c> listORPOld {get;set;}
    private Map<Id,OfertaRemuneracaoProduto__c> mapORPNew {get;set;}
    private Map<Id,OfertaRemuneracaoProduto__c> mapORPOld {get;set;}

    public OfertaRemuneracaoProdutoHandler() {

        this.listORPNew = (List<OfertaRemuneracaoProduto__c>) Trigger.new;
        this.listORPOld = (List<OfertaRemuneracaoProduto__c>) Trigger.old;
        this.mapORPNew = (Map<Id,OfertaRemuneracaoProduto__c>) Trigger.newMap;
        this.mapORPOld = (Map<Id,OfertaRemuneracaoProduto__c>) Trigger.oldMap;
    }
    
    public override void beforeDelete(){
        this.impedeDelRemuneracaoObrigatoria();
    }
    
    private void impedeDelRemuneracaoObrigatoria(){
        
        List<String> rpIdList = new List<String>();
        for(OfertaRemuneracaoProduto__c orp : listORPOld) rpIdList.add(orp.RemuneracaoProduto__c);
            
        Map<Id,RemuneracaoProduto__c> mapRP = new Map<Id,RemuneracaoProduto__c>([
            SELECT Id, Obrigatoria__c FROM RemuneracaoProduto__c WHERE Id IN :rpIdList
        ]);
        
        for(OfertaRemuneracaoProduto__c orp : listORPOld){
            if(mapRP.get(orp.RemuneracaoProduto__c).Obrigatoria__c) orp.addError('Oferta de remuneração obrigatória não pode ser excluida.');
        }
    }

}