workspace-sf/force-app/main/default/objects/RamoSeguro__c/RamoSeguro__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar o cadastro dos ramos de seguro</description>
    <label>Ramo de seguro</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ramos de seguro</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/RamoSeguro__c/fields/CodigoEmpresa__c.field-meta.xml
<CustomField>
    <fullName>CodigoEmpresa__c</fullName>
    <label>Código da empresa</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/RamoSeguro__c/fields/CodigoOrigemDoMovimentoBCP__c.field-meta.xml
<CustomField>
    <fullName>CodigoOrigemDoMovimentoBCP__c</fullName>
    <label>Código Origem do Movimento BCP</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>32</fullName>
                <label>32 - VIDA INDIVIDUAL</label>
            </value>
            <value>
                <fullName>33</fullName>
                <label>33 - VIDA GRUPO</label>
            </value>
            <value>
                <fullName>34</fullName>
                <label>34 - ACIDENTES PESSOAIS</label>
            </value>
            <value>
                <fullName>61</fullName>
                <label>61 - SEGURO VIAGEM</label>
            </value>
            <value>
                <fullName>64</fullName>
                <label>64 - SINISTRO VIDA</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/RamoSeguro__c/fields/Empresa__c.field-meta.xml
<CustomField>
    <fullName>Empresa__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empresa</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>RamosSeguro</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/RamoSeguro__c/fields/IdExterno__c.field-meta.xml
<CustomField>
    <fullName>IdExterno__c</fullName>
    <externalId>true</externalId>
    <label>Id externo</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

workspace-sf/force-app/main/default/objects/RamoSeguro__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ativo</fullName>
            </value>
            <value>
                <fullName>Inativo</fullName>
            </value>
            <value>
                <fullName>Em análise</fullName>
                <default>true</default>
                <label>Em análise</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/classes/RamoSeguroFactory.cls
/**
 * @author AVX - Daniel Zampieri
 * @date 2019-03-06
 * @description RamoSeguro__c Factory Class
 */
@isTest
public class RamoSeguroFactory extends SObjectFactory {
	private static RamoSeguro__c staticRecord;

	private static RamoSeguro__c getRecordStatic(Account conta){

		if(staticRecord == null){
			staticRecord = new RamoSeguro__c(
				Name = 'Segurado',
                CodigoEmpresa__c = '214',
                Codigo__c = '2',
                //PLV-2932 - Inicio - IdExterno alterado
                IdExterno__c = '214_9',
                //PLV-2932 - Fim - IdExterno alterado
								Empresa__c = conta.Id,
								CodigoOrigemDoMovimentoBCP__c = '32', //PLV-3773 INICIO/FIM - incluso campo para rega de validação
                Status__c = 'Ativo');
		}
		return staticRecord;
	}

	public RamoSeguroFactory(){

		this(
			(Account) new AccountFactory.PessoaFisica().createRecord()
		);
	}

	public RamoSeguroFactory(Account conta) {

		super(getRecordStatic(conta));
	}

}