workspace-sf/force-app/main/default/objects/Garantia__c/Garantia__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar o cadastro das garantias</description>
    <label>Garantia</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Garantias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/Garantia__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Em análise</fullName>
            </value>
            <value>
                <fullName>Ativo</fullName>
            </value>
            <value>
                <fullName>Inativo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/Modalidade__c/Modalidade__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar as modalidades</description>
    <label>Modalidade</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Modalidades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/Modalidade__c/fields/CodigoEmpresa__c.field-meta.xml
<CustomField>
    <fullName>CodigoEmpresa__c</fullName>
    <formula>Empresa__r.CodigoEmpresa__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Código da empresa</label>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Modalidade__c/fields/Empresa__c.field-meta.xml
<CustomField>
    <fullName>Empresa__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empresa</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Modalidades</relationshipLabel>
    <relationshipName>Modalidades</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Modalidade__c/fields/RamoSeguro__c.field-meta.xml
<CustomField>
    <fullName>RamoSeguro__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ramo de seguro</label>
    <referenceTo>RamoSeguro__c</referenceTo>
    <relationshipLabel>Modalidades</relationshipLabel>
    <relationshipName>Modalidades</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/RamoGarantia__c/RamoGarantia__c.object-meta.xml
<CustomObject>
    <description>Objeto de relacionamento entre a garantia e o ramo</description>
    <label>Ramo da garantia</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ramos da garantia</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/RamoGarantia__c/fields/Garantia__c.field-meta.xml
<CustomField>
    <fullName>Garantia__c</fullName>
    <label>Garantia</label>
    <referenceTo>Garantia__c</referenceTo>
    <relationshipName>RamosGarantia</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/RamoGarantia__c/fields/RamoSeguro__c.field-meta.xml
<CustomField>
    <fullName>RamoSeguro__c</fullName>
    <label>Ramo de seguro</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>RamoSeguro__c.Status__c</field>
            <operation>equals</operation>
            <value>Ativo</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>RamoSeguro__c</referenceTo>
    <relationshipLabel>Ramos da garantia</relationshipLabel>
    <relationshipName>RamosGarantia</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/RamoSeguro__c/RamoSeguro__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar o cadastro dos ramos de seguro</description>
    <label>Ramo de seguro</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ramos de seguro</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/RamoSeguro__c/fields/CodigoEmpresa__c.field-meta.xml
<CustomField>
    <fullName>CodigoEmpresa__c</fullName>
    <label>Código da empresa</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/RamoSeguro__c/fields/Empresa__c.field-meta.xml
<CustomField>
    <fullName>Empresa__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empresa</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>RamosSeguro</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/RamoSeguro__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ativo</fullName>
            </value>
            <value>
                <fullName>Inativo</fullName>
            </value>
            <value>
                <fullName>Em análise</fullName>
                <default>true</default>
                <label>Em análise</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/classes/RamoSeguroDAO.cls
/**
 * Camada de abstração de dados do objeto RamoSeguro__c
 * @author Fernando Barcellos @ 09/11/2017
 *
 **/
public class RamoSeguroDAO {
	private static final RamoSeguroDAO instance = new RamoSeguroDAO();
	
	private RamoSeguroDAO() {
	}

	public static RamoSeguroDAO getInstance() {
		return instance;
	}	

	/**
	 * Realiza a listagem de todos os ramos
	 *
	 */
	public List<RamoSeguro__c> listarRamos() {
		return [
			SELECT
				Id,
				Name,
				Codigo__c,
				CodigoEmpresa__c,
				Empresa__c,
				Status__c
			FROM 
				RamoSeguro__c
		];
	}

	public RamoSeguro__c obterRamoPorCodigo(String codigo) 
	{
		return 
		[
			SELECT
				Id,
				Name,
				Codigo__c,
				CodigoEmpresa__c,
				Empresa__c,
				Status__c
			FROM 
				RamoSeguro__c
			WHERE 
				Codigo__c = : codigo
			LIMIT 1
		];
	}

	public List<RamoSeguro__c> buscarRamosPorStatus(String status) {
		return buscarRamosPorStatus(new Set<String>{ status });
	}

	public List<RamoSeguro__c> buscarRamosPorStatus(Set<String> setStatus) {
		return [
			SELECT
				Id,
				Name,
				Codigo__c,
				CodigoEmpresa__c,
				Empresa__c,
				Status__c
			FROM 
				RamoSeguro__c
			WHERE
				Status__c IN : setStatus
		];
	}

	public List<RamoSeguro__c> buscarRamosPorIds(Set<Id> ramoSeguroIds) {
		return [
			SELECT
				Id,
				Name,
				Codigo__c,
				CodigoEmpresa__c,
				Empresa__c,
				Status__c,
				(
					Select
						Id,
						Name
					FROM	
						Modalidades__r	
				)
			FROM 
				RamoSeguro__c
			WHERE
				Id IN : ramoSeguroIds
		];
	}

	public List<RamoGarantia__c> buscarRamosGarantiaPorGarantia(Id garantiaId) {
		return [
			SELECT
				Id,
				Name,
				RamoSeguro__c,
				RamoSeguro__r.Name
			FROM 
				RamoGarantia__c
			WHERE
				Garantia__c =: garantiaId
		];
	}

	public List<RamoSeguro__c> obterRamoPorCodigos(Set<String> setCodigos) 
	{
		return 
		[
			SELECT
				Id,
				Name,
				Codigo__c,
				CodigoEmpresa__c,
				Empresa__c,
				Status__c
			FROM 
				RamoSeguro__c
			WHERE 
				Codigo__c IN : setCodigos
		];
	}




}