workspace-sf/force-app/main/default/objects/Garantia__c/Garantia__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar o cadastro das garantias</description>
    <label>Garantia</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Garantias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/GarantiaOrcamento__c/GarantiaOrcamento__c.object-meta.xml
<CustomObject>
    <description>Objeto de relacionamento entre a garantia e a oportunidade.</description>
    <label>Garantia do orçamento</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Garantias do orçamento</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/GarantiaOrcamento__c/fields/DescontoAgravo__c.field-meta.xml
<CustomField>
    <fullName>DescontoAgravo__c</fullName>
    <label>Desconto ou Agravo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Desconto</fullName>
            </value>
            <value>
                <fullName>Agravo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaOrcamento__c/fields/Garantia__c.field-meta.xml
<CustomField>
    <fullName>Garantia__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Garantia</label>
    <referenceTo>Garantia__c</referenceTo>
    <relationshipLabel>Garantias do orçamento</relationshipLabel>
    <relationshipName>Garantias_da_oportunidade</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaOrcamento__c/fields/GarantiaProduto__c.field-meta.xml
<CustomField>
    <fullName>GarantiaProduto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Garantia do produto</label>
    <referenceTo>GarantiaProduto__c</referenceTo>
    <relationshipLabel>Garantias do orçamento</relationshipLabel>
    <relationshipName>GarantiasOrcamento</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaOrcamento__c/fields/LimiteCapital__c.field-meta.xml
<CustomField>
    <fullName>LimiteCapital__c</fullName>
    <label>Limite de capital</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaOrcamento__c/fields/NumeroSerie__c.field-meta.xml
<CustomField>
    <fullName>NumeroSerie__c</fullName>
    <inlineHelpText>Número de série para garantia capitalização</inlineHelpText>
    <label>Número de série</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaOrcamento__c/fields/NumeroSorte__c.field-meta.xml
<CustomField>
    <fullName>NumeroSorte__c</fullName>
    <inlineHelpText>Número da sorte para garantia capitalização</inlineHelpText>
    <label>Número da sorte</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaOrcamento__c/fields/Orcamento__c.field-meta.xml
<CustomField>
    <fullName>Orcamento__c</fullName>
    <label>Orçamento</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Garantias do orçamento</relationshipLabel>
    <relationshipName>CoberturasOrcamento</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaOrcamento__c/fields/Percentual__c.field-meta.xml
<CustomField>
    <fullName>Percentual__c</fullName>
    <label>Percentual</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaOrcamento__c/fields/PremioComercial__c.field-meta.xml
<CustomField>
    <fullName>PremioComercial__c</fullName>
    <label>Prêmio comercial R$</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaOrcamento__c/fields/PremioComercialDesconto__c.field-meta.xml
<CustomField>
    <fullName>PremioComercialDesconto__c</fullName>
    <label>Prêmio Comercial Desconto R$</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaOrcamento__c/fields/PremioPuroDesconto__c.field-meta.xml
<CustomField>
    <fullName>PremioPuroDesconto__c</fullName>
    <label>Prêmio Puro Desconto R$</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaOrcamento__c/fields/PremioPuroInterno__c.field-meta.xml
<CustomField>
    <fullName>PremioPuroInterno__c</fullName>
    <label>Prêmio puro interno R$</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaOrcamento__c/fields/PremioPuroResseguro__c.field-meta.xml
<CustomField>
    <fullName>PremioPuroResseguro__c</fullName>
    <label>Prêmio puro do resseguro R$</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaOrcamento__c/fields/TaxaAnual__c.field-meta.xml
<CustomField>
    <fullName>TaxaAnual__c</fullName>
    <label>Taxa anual</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaOrcamento__c/fields/TaxaMensal__c.field-meta.xml
<CustomField>
    <fullName>TaxaMensal__c</fullName>
    <label>Taxa mensal</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaOrcamento__c/fields/TaxaPura__c.field-meta.xml
<CustomField>
    <fullName>TaxaPura__c</fullName>
    <label>Taxa pura</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaOrcamento__c/fields/TaxaPuroInterno__c.field-meta.xml
<CustomField>
    <fullName>TaxaPuroInterno__c</fullName>
    <label>Taxa Puro Interno</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaOrcamento__c/fields/TaxaPuroResseguro__c.field-meta.xml
<CustomField>
    <fullName>TaxaPuroResseguro__c</fullName>
    <label>Taxa Puro Resseguro</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaProduto__c/GarantiaProduto__c.object-meta.xml
<CustomObject>
    <description>Objeto de relacionamento entre os produtos e as garantias</description>
    <label>Garantia do produto</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Garantias do produto</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/GarantiaProduto__c/fields/Garantia__c.field-meta.xml
<CustomField>
    <fullName>Garantia__c</fullName>
    <label>Garantia</label>
    <referenceTo>Garantia__c</referenceTo>
    <relationshipLabel>Garantias do produto</relationshipLabel>
    <relationshipName>GarantiasProduto</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaProduto__c/fields/GarantiaProduto__c.field-meta.xml
<CustomField>
    <fullName>GarantiaProduto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Garantia do produto</label>
    <referenceTo>GarantiaProduto__c</referenceTo>
    <relationshipLabel>Garantias do produto (Garantia do produto)</relationshipLabel>
    <relationshipName>GarantiasProdutoTecnico</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaProduto__c/fields/TipoCapital__c.field-meta.xml
<CustomField>
    <fullName>TipoCapital__c</fullName>
    <label>Tipo de capital</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Capital global</fullName>
            </value>
            <value>
                <fullName>Capital uniforme</fullName>
            </value>
            <value>
                <fullName>Escalonado por cargo</fullName>
            </value>
            <value>
                <fullName>Escalonado por faixa salarial</fullName>
            </value>
            <value>
                <fullName>Livre escolha de capital</fullName>
            </value>
            <value>
                <fullName>Múltiplo por prêmio pago</fullName>
            </value>
            <value>
                <fullName>Múltiplo salarial</fullName>
            </value>
            <value>
                <fullName>Sem Capital</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/classes/GarantiaOrcamentoDAO.cls
public class GarantiaOrcamentoDAO 
{
	private static final GarantiaOrcamentoDAO instancia = new GarantiaOrcamentoDAO();
	private GarantiaOrcamentoDAO() {}
	public static GarantiaOrcamentoDAO getInstance() { return instancia; }

	public List<GarantiaOrcamento__c> listarGarantiasOrcamento(Set<Id> idsOrcamentos)
	{
		return
		[
			SELECT
				Capital__c,
				DescontoAgravo__c,
				Garantia__c,
				GarantiaProduto__c,
				LimiteCapital__c,
				NumeroSorte__c,
				NumeroSerie__c,
				Orcamento__c,
				Percentual__c,
                PremioComercial__c,
				PremioPuro__c,
				PremioComercialDesconto__c,
				PremioPuroDesconto__c,
				PremioPuroResseguro__c,
				PremioPuroInterno__c,
				CurrencyIsoCode, //PLV-3884 - INICIO/FIM - Retornando o campo de moeda para referencia
				TaxaAnual__c,
				TaxaComercial__c,
				TaxaMensal__c,
				TaxaPura__c,
				TaxaPuroInterno__c,
				TipoCapital__c,
				TaxaPuroResseguro__c
			FROM
				GarantiaOrcamento__c
			WHERE
				Orcamento__c = :idsOrcamentos
		];
	}
}