workspace-sf/force-app/main/default/objects/Garantia__c/Garantia__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar o cadastro das garantias</description>
    <label>Garantia</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Garantias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/Garantia__c/fields/Sigla__c.field-meta.xml
<CustomField>
    <fullName>Sigla__c</fullName>
    <label>Sigla</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaContrato__c/GarantiaContrato__c.object-meta.xml
<CustomObject>
    <description>Objeto de relacionamento entre a garantia e o contrato.</description>
    <label>Garantia do contrato</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Garantias do contrato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/GarantiaContrato__c/fields/DataSorteio__c.field-meta.xml
<CustomField>
    <fullName>DataSorteio__c</fullName>
    <label>Data de sorteio</label>
    <type>Date</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaContrato__c/fields/Garantia__c.field-meta.xml
<CustomField>
    <fullName>Garantia__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Garantia</label>
    <referenceTo>Garantia__c</referenceTo>
    <relationshipLabel>Garantias do contrato (Garantia)</relationshipLabel>
    <relationshipName>GarantiasContrato</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaContrato__c/fields/LoteCapitalizacao__c.field-meta.xml
<CustomField>
    <fullName>LoteCapitalizacao__c</fullName>
    <label>Lote da capitalização</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaContrato__c/fields/StatusCapitalizacao__c.field-meta.xml
<CustomField>
    <fullName>StatusCapitalizacao__c</fullName>
    <label>Status da capitalização</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AguardandoRecompra</fullName>
                <label>Aguardando recompra</label>
            </value>
            <value>
                <fullName>CapitalizacaoGerada</fullName>
                <label>Capitalização gerada</label>
            </value>
            <value>
                <fullName>Processado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaContrato__c/fields/VersaoTitulo__c.field-meta.xml
<CustomField>
    <fullName>VersaoTitulo__c</fullName>
    <label>Versão do título</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/classes/TitulosRecompraBatchTest.cls
/**
 * Created by Alessandro Ponte on 09/12/2018.
 */

@IsTest
private class TitulosRecompraBatchTest {

  @TestSetup
  static void testSetup(){

    TestDataFactory.gerarDadosSetup();
    // PLV-2312-28 INICIO
    Map<String,List<SObject>> mapListObject = TestDataFactory.gerarContrato(true);
    // PLV-2312-28 FIM

    List<GarantiaContrato__c> listGarantiaContrato = [SELECT Id, VersaoTitulo__c, DataSorteio__c FROM GarantiaContrato__c WHERE Garantia__r.Sigla__c = 'CAP'];

    for(GarantiaContrato__c garantiaContrato : listGarantiaContrato){
      garantiaContrato.DataSorteio__c = System.today();
      garantiaContrato.LoteCapitalizacao__c = '20';
    }
    update listGarantiaContrato;

    System.debug('listGarantiaContrato ------------------ ' + listGarantiaContrato);

  }

  @IsTest
  static void testRecompraTitulos(){
    Test.startTest();

    // Mock de retorno da PortoCap
    String responseJsonString = '[{"Cessionario": [{}],"id_lote": 23232,"nm_retorno": "Código 0: Processamento efetuado com sucesso","cd_retorno": 0, "cd_versao": 2}]';
    Test.setMock(HttpCalloutMock.class, new MockHttpResponse(responseJsonString, 200, 'OK'));

    Database.executeBatch(new TitulosRecompraBatch(), 100);

    Test.stopTest();

    List<GarantiaContrato__c> ListGarantiaContrato = [SELECT Id, VersaoTitulo__c, StatusCapitalizacao__c FROM GarantiaContrato__c WHERE Garantia__r.Sigla__c = 'CAP'];

      //PLV- 2932 Fix2 - Inicio - Código comentado
    //System.assertEquals('2', ListGarantiaContrato[0].VersaoTitulo__c);
    //System.assertEquals('AguardandoRecompra', ListGarantiaContrato[0].StatusCapitalizacao__c);
    //PLV- 2932 Fix2 - Fim - Código comentado
  }

}