workspace-sf/force-app/main/default/objects/Garantia__c/Garantia__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar o cadastro das garantias</description>
    <label>Garantia</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Garantias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/Garantia__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Em análise</fullName>
            </value>
            <value>
                <fullName>Ativo</fullName>
            </value>
            <value>
                <fullName>Inativo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaProduto__c/GarantiaProduto__c.object-meta.xml
<CustomObject>
    <description>Objeto de relacionamento entre os produtos e as garantias</description>
    <label>Garantia do produto</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Garantias do produto</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/GarantiaProduto__c/fields/CodigoPromocao__c.field-meta.xml
<CustomField>
    <fullName>CodigoPromocao__c</fullName>
    <description>Picklist obrigatória se o campo Sorteio no campo tipo de característica especial, for selecionado.</description>
    <inlineHelpText>Cod.167 - Vida 01 Sorteio
Cod.171 - Vida 02 Sorteios
Cod.168 - Vida 04 Sorteios
Cod.VI010 - Vida 1 Sorteio
Cod.VI011 – Vida 3 Sorteios</inlineHelpText>
    <label>Código da promoção</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>167</fullName>
            </value>
            <value>
                <fullName>168</fullName>
            </value>
            <value>
                <fullName>171</fullName>
            </value>
            <value>
                <fullName>VITST</fullName>
            </value>
            <value>
                <fullName>VI010</fullName>
            </value>
            <value>
                <fullName>VI011</fullName>
            </value>
            <value>
                <fullName>VI005</fullName>
                <isActive>false</isActive>
                <label>VI005</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaProduto__c/fields/Garantia__c.field-meta.xml
<CustomField>
    <fullName>Garantia__c</fullName>
    <label>Garantia</label>
    <referenceTo>Garantia__c</referenceTo>
    <relationshipLabel>Garantias do produto</relationshipLabel>
    <relationshipName>GarantiasProduto</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaProduto__c/fields/GarantiaProduto__c.field-meta.xml
<CustomField>
    <fullName>GarantiaProduto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Garantia do produto</label>
    <referenceTo>GarantiaProduto__c</referenceTo>
    <relationshipLabel>Garantias do produto (Garantia do produto)</relationshipLabel>
    <relationshipName>GarantiasProdutoTecnico</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaProduto__c/fields/LimiteCapitalMaximo__c.field-meta.xml
<CustomField>
    <fullName>LimiteCapitalMaximo__c</fullName>
    <label>Limite de capital máximo</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaProduto__c/fields/LimiteCapitalMinimo__c.field-meta.xml
<CustomField>
    <fullName>LimiteCapitalMinimo__c</fullName>
    <label>Limite de capital mínimo</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaProduto__c/fields/LimiteMaximoCaracteristicaEspecial__c.field-meta.xml
<CustomField>
    <fullName>LimiteMaximoCaracteristicaEspecial__c</fullName>
    <label>Limite máximo de característica especial</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaProduto__c/fields/LimiteMinimoCaracteristicaEspecial__c.field-meta.xml
<CustomField>
    <fullName>LimiteMinimoCaracteristicaEspecial__c</fullName>
    <label>Limite mínimo de característica especial</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaProduto__c/fields/Obrigatoria__c.field-meta.xml
<CustomField>
    <fullName>Obrigatoria__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Obrigatória?</label>
    <type>Checkbox</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaProduto__c/fields/OrdemPrioridade__c.field-meta.xml
<CustomField>
    <fullName>OrdemPrioridade__c</fullName>
    <inlineHelpText>Refere-se a prioridade para utilização do ramo líder caso haja a escolha de mais de uma garantia na contratação.</inlineHelpText>
    <label>Ordem de prioridade ramo líder</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaProduto__c/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Garantias do produto</relationshipLabel>
    <relationshipName>GarantiasProduto</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaProduto__c/fields/RamoSeguro__c.field-meta.xml
<CustomField>
    <fullName>RamoSeguro__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ramo de seguro</label>
    <referenceTo>RamoSeguro__c</referenceTo>
    <relationshipLabel>Garantias do produto</relationshipLabel>
    <relationshipName>GarantiasProduto</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaProduto__c/fields/TipoCapital__c.field-meta.xml
<CustomField>
    <fullName>TipoCapital__c</fullName>
    <label>Tipo de capital</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Capital global</fullName>
            </value>
            <value>
                <fullName>Capital uniforme</fullName>
            </value>
            <value>
                <fullName>Escalonado por cargo</fullName>
            </value>
            <value>
                <fullName>Escalonado por faixa salarial</fullName>
            </value>
            <value>
                <fullName>Livre escolha de capital</fullName>
            </value>
            <value>
                <fullName>Múltiplo por prêmio pago</fullName>
            </value>
            <value>
                <fullName>Múltiplo salarial</fullName>
            </value>
            <value>
                <fullName>Sem Capital</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaProduto__c/fields/TipoCaracteristicaEspecial__c.field-meta.xml
<CustomField>
    <fullName>TipoCaracteristicaEspecial__c</fullName>
    <label>Tipo de característica especial</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ano(s)</fullName>
            </value>
            <value>
                <fullName>Assessoria</fullName>
            </value>
            <value>
                <fullName>Cestas</fullName>
            </value>
            <value>
                <fullName>Dia(s)</fullName>
            </value>
            <value>
                <fullName>Mês(es)</fullName>
            </value>
            <value>
                <fullName>Permanência no exterior</fullName>
            </value>
            <value>
                <fullName>Quilos</fullName>
            </value>
            <value>
                <fullName>Semana(s)</fullName>
            </value>
            <value>
                <fullName>Semestre(s)</fullName>
            </value>
            <value>
                <fullName>Trimestre(s)</fullName>
            </value>
            <value>
                <fullName>Sorteio</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaProduto__c/fields/TipoGarantia__c.field-meta.xml
<CustomField>
    <fullName>TipoGarantia__c</fullName>
    <label>Tipo de garantia</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TipoGarantia</valueSetName>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaProduto__c/recordTypes/ProdutoComercial.recordType-meta.xml
<RecordType>
    <fullName>ProdutoComercial</fullName>
    <active>true</active>
    <label>Produto comercial</label>
</RecordType>

workspace-sf/force-app/main/default/objects/GarantiaProduto__c/recordTypes/ProdutoTecnico.recordType-meta.xml
<RecordType>
    <fullName>ProdutoTecnico</fullName>
    <active>true</active>
    <label>Produto técnico</label>
</RecordType>

workspace-sf/force-app/main/default/objects/GarantiaRelacionada__c/GarantiaRelacionada__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar as garantias dependentes de outra garantia</description>
    <label>Garantia relacionada</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Garantias relacionadas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/GarantiaRelacionada__c/fields/Garantia__c.field-meta.xml
<CustomField>
    <fullName>Garantia__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Garantia</label>
    <referenceTo>Garantia__c</referenceTo>
    <relationshipName>CoberturasRelacionadas</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaRelacionada__c/fields/GarantiaProduto__c.field-meta.xml
<CustomField>
    <fullName>GarantiaProduto__c</fullName>
    <label>Garantia do produto</label>
    <referenceTo>GarantiaProduto__c</referenceTo>
    <relationshipLabel>Garantias relacionadas</relationshipLabel>
    <relationshipName>GarantiasRelacionada</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaRelacionada__c/recordTypes/ProdutoComercial.recordType-meta.xml
<RecordType>
    <fullName>ProdutoComercial</fullName>
    <active>true</active>
    <label>Produto comercial</label>
</RecordType>

workspace-sf/force-app/main/default/objects/GarantiaRelacionada__c/recordTypes/ProdutoTecnico.recordType-meta.xml
<RecordType>
    <fullName>ProdutoTecnico</fullName>
    <active>true</active>
    <label>Produto técnico</label>
</RecordType>

workspace-sf/force-app/main/default/objects/LimiteGarantiaProduto__c/LimiteGarantiaProduto__c.object-meta.xml
<CustomObject>
    <description>Objeto para cadastrar os limites de capital das garantias dos Produtos.</description>
    <label>Limite da garantia do produto</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Limites da garantia do produto</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/LimiteGarantiaProduto__c/fields/GarantiaProduto__c.field-meta.xml
<CustomField>
    <fullName>GarantiaProduto__c</fullName>
    <label>Garantia do produto</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Esse registro não pode ser associado com a garantia de um produto comercial.</errorMessage>
        <filterItems>
            <field>GarantiaProduto__c.Produto__r.RecordTypeId</field>
            <operation>equals</operation>
            <value>Produto técnico</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>GarantiaProduto__c</referenceTo>
    <relationshipLabel>Limites da garantia do produto</relationshipLabel>
    <relationshipName>LimitesGarantiaProduto</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/LimiteGarantiaProduto__c/fields/LimiteCapitalMaximo__c.field-meta.xml
<CustomField>
    <fullName>LimiteCapitalMaximo__c</fullName>
    <label>Limite de capital máximo</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

workspace-sf/force-app/main/default/objects/LimiteGarantiaProduto__c/fields/LimiteCapitalMinimo__c.field-meta.xml
<CustomField>
    <fullName>LimiteCapitalMinimo__c</fullName>
    <label>Limite de capital mínimo</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

workspace-sf/force-app/main/default/objects/RamoGarantia__c/RamoGarantia__c.object-meta.xml
<CustomObject>
    <description>Objeto de relacionamento entre a garantia e o ramo</description>
    <label>Ramo da garantia</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ramos da garantia</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/RamoGarantia__c/fields/Garantia__c.field-meta.xml
<CustomField>
    <fullName>Garantia__c</fullName>
    <label>Garantia</label>
    <referenceTo>Garantia__c</referenceTo>
    <relationshipName>RamosGarantia</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/RamoGarantia__c/fields/RamoSeguro__c.field-meta.xml
<CustomField>
    <fullName>RamoSeguro__c</fullName>
    <label>Ramo de seguro</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>RamoSeguro__c.Status__c</field>
            <operation>equals</operation>
            <value>Ativo</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>RamoSeguro__c</referenceTo>
    <relationshipLabel>Ramos da garantia</relationshipLabel>
    <relationshipName>RamosGarantia</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/RamoSeguro__c/RamoSeguro__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar o cadastro dos ramos de seguro</description>
    <label>Ramo de seguro</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ramos de seguro</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/RamoSeguro__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ativo</fullName>
            </value>
            <value>
                <fullName>Inativo</fullName>
            </value>
            <value>
                <fullName>Em análise</fullName>
                <default>true</default>
                <label>Em análise</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/classes/RegrasFabricaProdutosTest.cls
//PLV-2549 - Avanxo - Inicio - Classe de teste criada para cobrir os métodos validarGarantiaRelacionada e compararCamposGarantias da classe RegrasFabricaProdutos
@isTest
public class RegrasFabricaProdutosTest {
    @isTest 
    static void TesteRegras(){
        
    	Account contaPessoal = (Account) new AccountFactory.PessoaFisica().createRecord();
        Garantia__c garantia = (Garantia__c) new GarantiaFactory().createRecord();
        
        ContadorCodigo__c contCodigoTec = (ContadorCodigo__c) new ContadorCodigoFactory.ProdutoTecnico().createRecord();
        ContadorCodigo__c contCodigoCom = (ContadorCodigo__c) new ContadorCodigoFactory.ProdutoComercial().createRecord();
        Product2 produtoTecnico = (Product2) new ProdutoFactory.ProdutoTecnico().createRecord();
        produtoTecnico.Status__c = 'Em ativação';
        produtoTecnico.NumeroSusep__c = '123';
        produtoTecnico.VersaoRenovacao__c = 'Versão atual';
        update produtoTecnico;
        produtoTecnico.Status__c = 'Ativo';
        update produtoTecnico;
        Product2 produtoComercial = (Product2) new ProdutoFactory.ProdutoComercial(produtoTecnico).createRecord();
        
        RamoSeguro__c ramoSeguro = (RamoSeguro__c) new RamoSeguroFactory(contaPessoal).createRecord();
        RamoGarantia__c ramoGarantia2 = (RamoGarantia__c) new RamoGarantiaFactory(garantia, ramoSeguro).createRecord();
        
        GarantiaProduto__c garanProdTec = (GarantiaProduto__c) new GarantiaProdutoFactory.GarantiaProdutoTec(garantia, produtoTecnico, ramoSeguro).createRecord();
        Recordtype REC_ID_GarantiaProdutoTec = RecordTypeBO.buscarTipoRegistro('GarantiaProduto__c', 'ProdutoTecnico');
        GarantiaProduto__c garanProdTec2 = new GarantiaProduto__c(
            	Garantia__c = garantia.Id,
                Produto__c = produtoTecnico.Id,
                RamoSeguro__c = ramoSeguro.Id,
                OrdemPrioridade__c = 1,
                RecordTypeId = REC_ID_GarantiaProdutoTec.Id,
                TipoGarantia__c = 'Cobertura',
                TipoCapital__c = 'Capital uniforme',
                CodigoPromocao__c = 'VITST',
                VersaoTitulo__c = '1');
            
				insert garanProdTec2;
                
                // PLV - 3046 - INICIO
                LimiteGarantiaProduto__c lim = new LimiteGarantiaProduto__c(
                                                            GarantiaProduto__c = garanProdTec2.id,
                                                            CurrencyIsoCode = 'USD',
                                                            LimiteCapitalMinimo__c = 1,
                                                            LimiteCapitalMaximo__c = 100000
                                                            );
                insert lim;
                // PLV - 3046 - FIM
        
        GarantiaProduto__c garanProdCom = (GarantiaProduto__c) new GarantiaProdutoFactory.GarantiaProdutoCom(produtoComercial, garantia, garanProdTec, ramoSeguro).createRecord();
		Recordtype REC_ID_GarantiaProdutoCom = RecordTypeBO.buscarTipoRegistro('GarantiaProduto__c', 'ProdutoComercial');
        GarantiaProduto__c garanProdCom2 = new GarantiaProduto__c(
				Garantia__c = garantia.Id,
                GarantiaProduto__c = garanProdTec2.Id,
                Produto__c = produtoComercial.Id,
                OrdemPrioridade__c = 1,
                RecordTypeId = REC_ID_GarantiaProdutoCom.Id,
                TipoGarantia__c = 'Cobertura',
                TipoCapital__c = 'Capital uniforme',
                RamoSeguro__c = ramoSeguro.Id,
                TipoCaracteristicaEspecial__c = 'Cestas',
                LimiteMaximoCaracteristicaEspecial__c = 100,
                LimiteMinimoCaracteristicaEspecial__c = 10,
                CodigoPromocao__c = 'VITST',
                VersaoTitulo__c = '1',
                Obrigatoria__c = true,
                PrazoMaximoLiquidacao__c = 10,
                TipoPrazoMaximoLiquidacao__c = 'Dia',
                PrazoAvisoSinistro__c = 20,
                TipoPrazoAvisoSinistro__c = 'Ano',
                // PLV - 3046 - INICIO
				LimiteCapitalMinimo__c = 20,
				LimiteCapitalMaximo__c = 900,
				currencyIsoCode = 'USD');
                // PLV - 3046 - INICIO
        insert garanProdCom2;      
        
        GarantiaRelacionada__c garantiaRelTest = (GarantiaRelacionada__c) new GarantiaRelacionadaFactory.ProdutoTecnico(garanProdTec, garanProdTec2).createRecord();
        GarantiaRelacionada__c garantiaRelTest2 = (GarantiaRelacionada__c) new GarantiaRelacionadaFactory.ProdutoComercial(garanProdCom, garanProdCom2).createRecord();
        
        //PLV-3667 - INICIO
        garantiaRelTest2.Acumulativa__c = false;
        update garantiaRelTest2;
        //PLV-3667 - FIM
        
    }
}

//PLV-2549 - Avanxo - Fim