workspace-sf/force-app/main/default/objects/Garantia__c/Garantia__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar o cadastro das garantias</description>
    <label>Garantia</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Garantias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/Garantia__c/fields/Sigla__c.field-meta.xml
<CustomField>
    <fullName>Sigla__c</fullName>
    <label>Sigla</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaContrato__c/GarantiaContrato__c.object-meta.xml
<CustomObject>
    <description>Objeto de relacionamento entre a garantia e o contrato.</description>
    <label>Garantia do contrato</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Garantias do contrato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/GarantiaContrato__c/fields/Contrato__c.field-meta.xml
<CustomField>
    <fullName>Contrato__c</fullName>
    <label>Contrato</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Garantias do contrato</relationshipLabel>
    <relationshipName>GarantiasContrato</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaContrato__c/fields/Garantia__c.field-meta.xml
<CustomField>
    <fullName>Garantia__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Garantia</label>
    <referenceTo>Garantia__c</referenceTo>
    <relationshipLabel>Garantias do contrato (Garantia)</relationshipLabel>
    <relationshipName>GarantiasContrato</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaContrato__c/fields/Status_do_Contrato__c.field-meta.xml
<CustomField>
    <fullName>Status_do_Contrato__c</fullName>
    <formula>TEXT(Contrato__r.Status)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status do Contrato</label>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/classes/ConsultaAcumuloCapitalBusiness.cls
public class ConsultaAcumuloCapitalBusiness {
    //PLV-4503 INICIO

    //++++++++++++++++++++++++
    // PUBLIC STATIC METHODS
    //++++++++++++++++++++++++

    /**
     * Retorna Response de ConsultaAcumuloCapitalRest contendo os acumulos de capital das coberturas das apolices
     * @param  cpf              Cpf da Conta das Apolices das Garantias de Contrato(coberturas)
     * @param  coberturasLegado Objetos com os acumulos das coberturas do sistema legado, agrupados pela Sigla da cobertura
     * @return                  Objeto ConsultaAcumuloCapitalRest.Response com os valores acumulados das coberturas do Legado + Salesforce
     */
    // public static ConsultaAcumuloCapitalRest.Response getAcumuloCapitalCoberturasByCpf(String cpf, List<ConsultaAcumuloCapitalRest.Cobertura> coberturasLegado) {
        public static ConsultaAcumuloCapitalRest.Response getAcumuloCapitalCoberturasByCpf(ConsultaAcumuloCapitalRest.Request req) {
            
        ConsultaAcumuloCapitalRest.Response res = new ConsultaAcumuloCapitalRest.Response();
        res.coberturas = new List<ConsultaAcumuloCapitalRest.Cobertura>();
        Map<String, Double> coberturasAcumuloMap = new Map<String, Double>();

        //CIV envia CPF sem formatação, formatar XXX.XXX.XXX-XX
        String cpf = Util.imprimeCPF(req.cpf);

        System.debug('ConsultaAcumuloCapitalBusiness :: getAcumuloCapitalCoberturasByCpf : cpf : ' + cpf);
        System.debug('ConsultaAcumuloCapitalBusiness :: getAcumuloCapitalCoberturasByCpf : coberturasLegado : ' + JSON.serializePretty(req.coberturasLegado, true));
        System.debug('ConsultaAcumuloCapitalBusiness :: getAcumuloCapitalCoberturasByCpf : coberturasPortal : ' + JSON.serializePretty(req.coberturasPortal, true));
        System.debug('ConsultaAcumuloCapital SalesForce '+ getGarantiasByCpf(cpf));

        somaAcumulo(coberturasAcumuloMap, req.coberturasLegado);
        somaAcumulo(coberturasAcumuloMap, req.coberturasPortal); 
        somaAcumulo(coberturasAcumuloMap, getGarantiasByCpf(cpf)); 

        //!* Monta Resposta com acumulos do mapa
        if (coberturasAcumuloMap.size() > 0) {

            for (String key : coberturasAcumuloMap.keySet()) {
                ConsultaAcumuloCapitalRest.Cobertura cobertura = new ConsultaAcumuloCapitalRest.Cobertura();
                cobertura.sigla = key;
                cobertura.valor = coberturasAcumuloMap.get(key);

                res.coberturas.add(cobertura);
            }

            System.debug('ConsultaAcumuloCapitalBusiness :: getAcumuloCapitalCoberturasByCpf : res.coberturas : ' + JSON.serializePretty(res.coberturas, true));
        }

        return res;
    }

    //++++++++++++++++++++++++
    // PRIVATE METHODS
    //++++++++++++++++++++++++

    private static void somaAcumulo(Map<String, Double> coberturasAcumuloMap, List<ConsultaAcumuloCapitalRest.Cobertura> coberturas) {
        
        if (coberturas != null && coberturas.size() > 0) {

            for (ConsultaAcumuloCapitalRest.Cobertura cobertura : coberturas) {
                if (coberturasAcumuloMap.containsKey(cobertura.sigla)) {
                    coberturasAcumuloMap.put(cobertura.sigla, coberturasAcumuloMap.get(cobertura.sigla) + cobertura.valor);
                }
                else {
                    coberturasAcumuloMap.put(cobertura.sigla, cobertura.valor);
                } 
            }   
        }
    }

    private static void somaAcumulo(Map<String, Double> coberturasAcumuloMap, List<GarantiaContrato__c> coberturas) {
        
        if (coberturas != null && coberturas.size() > 0) {

            for (GarantiaContrato__c cobertura : coberturas) {

                if (coberturasAcumuloMap.containsKey(cobertura.Garantia__r.Sigla__c)) {
                    coberturasAcumuloMap.put(cobertura.Garantia__r.Sigla__c, coberturasAcumuloMap.get(cobertura.Garantia__r.Sigla__c) + cobertura.Capital__c);
                }
                else {
                    coberturasAcumuloMap.put(cobertura.Garantia__r.Sigla__c, cobertura.Capital__c);
                } 
            }
        }
    }

    private static List<GarantiaContrato__c> getGarantiasByCpf(String cpf) {
		// PLV-4923 INICIO
        Date hoje = System.today();

        list<GarantiaContrato__c> lstResponse = [
            SELECT 
                Id,
                Capital__c,
                Garantia__r.Sigla__c,
                Contrato__r.VigenciaFinal__c,
                Contrato__r.StartDate
            FROM GarantiaContrato__c
            WHERE 
                Contrato__r.Account.Cpf__c =: cpf
                AND Garantia__c <> NULL
                AND Capital__c <> NULL
                AND TipoGarantia__c = 'Cobertura'
                AND Contrato__r.VigenciaFinal__c >=: hoje
                AND Contrato__r.StartDate <=: hoje
                AND Status_do_Contrato__c = 'Emitido'
            ORDER BY Garantia__r.Sigla__c
            LIMIT 50000
        ];   
         
        return lstResponse;
        // PLV-4923 FIM
    }

    //PLV-4503 FIM
}