workspace-sf/force-app/main/default/objects/Garantia__c/Garantia__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar o cadastro das garantias</description>
    <label>Garantia</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Garantias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/Garantia__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TipoGarantia</valueSetName>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/classes/GarantiaTriggerHandlerTest.cls
@isTest
public with sharing class GarantiaTriggerHandlerTest {

    @isTest
    static void testGarantia() {

        Garantia__c garantiaTestada = (Garantia__c) new GarantiaFactory().createRecord();
        garantiaTestada.Tipo__c = 'Benefício;Cobertura';
		try{
            update garantiaTestada;
        }catch (DmlException error){
			System.assert(error.getMessage().contains('O campo de Tipo deve conter apenas uma opção selecionada'), 'Erro ao atualizar a garantia');
        }
	}
}