workspace-sf/force-app/main/default/objects/Garantia__c/Garantia__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar o cadastro das garantias</description>
    <label>Garantia</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Garantias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/Garantia__c/fields/Sigla__c.field-meta.xml
<CustomField>
    <fullName>Sigla__c</fullName>
    <label>Sigla</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Garantia__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TipoGarantia</valueSetName>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/Garantia__c/fields/VigenciaInicial__c.field-meta.xml
<CustomField>
    <fullName>VigenciaInicial__c</fullName>
    <label>Vigência inicial</label>
    <type>Date</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaContrato__c/GarantiaContrato__c.object-meta.xml
<CustomObject>
    <description>Objeto de relacionamento entre a garantia e o contrato.</description>
    <label>Garantia do contrato</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Garantias do contrato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/GarantiaContrato__c/fields/Contrato__c.field-meta.xml
<CustomField>
    <fullName>Contrato__c</fullName>
    <label>Contrato</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Garantias do contrato</relationshipLabel>
    <relationshipName>GarantiasContrato</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaContrato__c/fields/Garantia__c.field-meta.xml
<CustomField>
    <fullName>Garantia__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Garantia</label>
    <referenceTo>Garantia__c</referenceTo>
    <relationshipLabel>Garantias do contrato (Garantia)</relationshipLabel>
    <relationshipName>GarantiasContrato</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaContrato__c/fields/TipoCapital__c.field-meta.xml
<CustomField>
    <fullName>TipoCapital__c</fullName>
    <label>Tipo de capital</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Capital global</fullName>
            </value>
            <value>
                <fullName>Capital uniforme</fullName>
            </value>
            <value>
                <fullName>Escalonado por cargo</fullName>
            </value>
            <value>
                <fullName>Escalonado por faixa salarial</fullName>
            </value>
            <value>
                <fullName>Livre escolha de capital</fullName>
            </value>
            <value>
                <fullName>Múltiplo por prêmio pago</fullName>
            </value>
            <value>
                <fullName>Múltiplo salarial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaContrato__c/fields/VersaoTitulo__c.field-meta.xml
<CustomField>
    <fullName>VersaoTitulo__c</fullName>
    <label>Versão do título</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/classes/ComunicacaoTelemedicinaTest.cls
//FNPVVEP-114 INICIO
@isTest
public class ComunicacaoTelemedicinaTest {

    @testSetup
    static void setupData() {
        Map<String, Sobject> records = CreateTestData.createIntegratedScenario();

        Contract contract = [SELECT Id  FROM Contract LIMIT 1];

        Garantia__c garantia = new Garantia__c(
            VigenciaInicial__c = System.today(),
            Tipo__c = 'Assistência',
            Sigla__c = 'Telemed',
            Name = 'Telemedicina'
            
        );
        insert garantia;

        GarantiaContrato__c garantiaContrato = new GarantiaContrato__c(
                Contrato__c = contract.Id,
                Garantia__c = garantia.Id,
                TipoCapital__c = 'Capital uniforme',
                VersaoTitulo__c = '1'
        );
        insert garantiaContrato;
    }

    @IsTest
    public static void testComunicacaoTelemedicina() {

        Contract contract = [SELECT Id, Name, StartDate, VigenciaFinal__c, Segmento__c, Tipo__c, DataEmissao__c , Account.Name, Account.Sexo__c, Account.PersonMobilePhone, Account.Cpf__c, Account.PersonBirthdate, Account.PersonEmail, Account.PersonHomePhone  FROM Contract LIMIT 1];

        Test.startTest();
        ComunicacaoTelemedicina.enviarComunicacaoTelemed(contract.Id);
        Test.stopTest();
    }
}
//FNPVVEP-114 FIM