workspace-sf/force-app/main/default/objects/Garantia__c/Garantia__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar o cadastro das garantias</description>
    <label>Garantia</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Garantias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/GarantiaSeguradoContrato__c/GarantiaSeguradoContrato__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar as garantias do segurado do contrato</description>
    <label>Garantia do segurado do contrato</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Garantias do segurado do contrato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/GarantiaSeguradoContrato__c/fields/Garantia__c.field-meta.xml
<CustomField>
    <fullName>Garantia__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Garantia</label>
    <referenceTo>Garantia__c</referenceTo>
    <relationshipLabel>Garantias do segurado do contrato (Garantia)</relationshipLabel>
    <relationshipName>GarantiasSeguradoContrato</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaSeguradoContrato__c/fields/Limite_de_Uso__c.field-meta.xml
<CustomField>
    <fullName>Limite_de_Uso__c</fullName>
    <label>Limite de Uso</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaSeguradoContrato__c/fields/SeguradoContrato__c.field-meta.xml
<CustomField>
    <fullName>SeguradoContrato__c</fullName>
    <label>Segurado do contrato</label>
    <referenceTo>SeguradoContrato__c</referenceTo>
    <relationshipLabel>Garantias do segurado do contrato</relationshipLabel>
    <relationshipName>GarantiasSeguradoContrato</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaSeguradoContrato__c/fields/Tipo_de_limite_de_utilizacao__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_limite_de_utilizacao__c</fullName>
    <label>Tipo de limite de utilização</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Dia(s)</fullName>
            </value>
            <value>
                <fullName>Monetário</fullName>
            </value>
            <value>
                <fullName>Ano(s)</fullName>
            </value>
            <value>
                <fullName>Assessoria</fullName>
            </value>
            <value>
                <fullName>Cestas</fullName>
            </value>
            <value>
                <fullName>Mês(es)</fullName>
            </value>
            <value>
                <fullName>Permanência no exterior</fullName>
            </value>
            <value>
                <fullName>Quilos</fullName>
            </value>
            <value>
                <fullName>Semana(s)</fullName>
            </value>
            <value>
                <fullName>Semestre(s)</fullName>
            </value>
            <value>
                <fullName>Trimestre(s)</fullName>
            </value>
            <value>
                <fullName>Sorteio</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/SeguradoContrato__c/SeguradoContrato__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar os segurados do contrato</description>
    <label>Segurado do contrato</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Segurados do contrato</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/classes/GarantiaSeguradoContratoFactory.cls
/**
 * @author AVX - Daniel Zampieri
 * @date 2019-02-27
 * @description Garantia do Seegurado do Contrato Factory Class
 */

@isTest
public class GarantiaSeguradoContratoFactory extends SObjectFactory{
	private static GarantiaSeguradoContrato__c staticRecord;
    
    private static GarantiaSeguradoContrato__c getRecordStatic(SeguradoContrato__c segurado, Garantia__c garantia){
        
		if(staticRecord == null){
            //PLV-4559 - INICIO
			staticRecord = new GarantiaSeguradoContrato__c(
                SeguradoContrato__c = segurado.Id,
                Garantia__c = garantia.Id,
                Tipo_de_limite_de_utilizacao__c = 'Dia(s)', //PLV-5747 INICIO/FIM
                Limite_de_Uso__c = 900
            );
            //PLV-4559 -FIM
		}
		return staticRecord;
	}
    
    public GarantiaSeguradoContratoFactory() {

		this(
        	(SeguradoContrato__c) new SeguradoContratoFactory().createRecord(),
            (Garantia__c) new GarantiaFactory().createRecord()
        );
	}

	public GarantiaSeguradoContratoFactory(SeguradoContrato__c segurado, Garantia__c garantia) {

		super(getRecordStatic(segurado, garantia));
	}
}