workspace-sf/force-app/main/default/objects/Garantia__c/Garantia__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar o cadastro das garantias</description>
    <label>Garantia</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Garantias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/GarantiaProduto__c/GarantiaProduto__c.object-meta.xml
<CustomObject>
    <description>Objeto de relacionamento entre os produtos e as garantias</description>
    <label>Garantia do produto</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Garantias do produto</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/GarantiaProduto__c/fields/Garantia__c.field-meta.xml
<CustomField>
    <fullName>Garantia__c</fullName>
    <label>Garantia</label>
    <referenceTo>Garantia__c</referenceTo>
    <relationshipLabel>Garantias do produto</relationshipLabel>
    <relationshipName>GarantiasProduto</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaProduto__c/fields/GarantiaProduto__c.field-meta.xml
<CustomField>
    <fullName>GarantiaProduto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Garantia do produto</label>
    <referenceTo>GarantiaProduto__c</referenceTo>
    <relationshipLabel>Garantias do produto (Garantia do produto)</relationshipLabel>
    <relationshipName>GarantiasProdutoTecnico</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaProduto__c/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Garantias do produto</relationshipLabel>
    <relationshipName>GarantiasProduto</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaRelacionada__c/GarantiaRelacionada__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar as garantias dependentes de outra garantia</description>
    <label>Garantia relacionada</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Garantias relacionadas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/GarantiaRelacionada__c/fields/Acumulativa__c.field-meta.xml
<CustomField>
    <fullName>Acumulativa__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Acumulativa</label>
    <type>Checkbox</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaRelacionada__c/fields/Garantia__c.field-meta.xml
<CustomField>
    <fullName>Garantia__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Garantia</label>
    <referenceTo>Garantia__c</referenceTo>
    <relationshipName>CoberturasRelacionadas</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaRelacionada__c/fields/GarantiaProduto__c.field-meta.xml
<CustomField>
    <fullName>GarantiaProduto__c</fullName>
    <label>Garantia do produto</label>
    <referenceTo>GarantiaProduto__c</referenceTo>
    <relationshipLabel>Garantias relacionadas</relationshipLabel>
    <relationshipName>GarantiasRelacionada</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaRelacionada__c/fields/GarantiaRelacionada__c.field-meta.xml
<CustomField>
    <fullName>GarantiaRelacionada__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Garantia Relacionada</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.GarantiaProduto__c</field>
            <operation>notEqual</operation>
            <valueField>GarantiaProduto__c.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>GarantiaProduto__c</referenceTo>
    <relationshipLabel>Garantias relacionadas (Garantia Relacionada)</relationshipLabel>
    <relationshipName>Garantias_relacionadas</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaRelacionada__c/fields/Incremento__c.field-meta.xml
<CustomField>
    <fullName>Incremento__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Incremento</label>
    <type>Checkbox</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaRelacionada__c/fields/TipoDependencia__c.field-meta.xml
<CustomField>
    <fullName>TipoDependencia__c</fullName>
    <label>Tipo de dependência</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Includente</fullName>
            </value>
            <value>
                <fullName>Excludente</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/classes/CriarGarantiaRelacionadaController.cls
//PLV_2583 - INICIO - Ajuste na busca de coberturas no objeto "Garantia Relacionada"
/**
 * Controller para o componente CriarGarantiaRelacionada.cmp
 * @author Mariana Ribeiro Lial @ 02/01/2020
 *
 **/
public class CriarGarantiaRelacionadaController {
	
    public class GarantiaWrapper{
		@AuraEnabled public String id {get;set;}
		@AuraEnabled public String Name {get;set;}
		@AuraEnabled public String GarantiaName {get;set;}

		public GarantiaWrapper(){
			this.id = '';
			this.Name = '';	
			this.GarantiaName = '';
		}
	}
    
    @AuraEnabled
	public static List<CriarGarantiaRelacionadaController.GarantiaWrapper> pesquisaGarantiaProduto(String recordId, String term){
		String search = term.trim();
		String searchTerm = '%'+search+'%';
		GarantiaProduto__c garantia = [SELECT Id, Name, Produto__c
												FROM GarantiaProduto__c 
												WHERE Id = :recordId LIMIT 1];
   		System.debug('garantia: '+ garantia);
		if(search == null || search == ''){

			return null;
		} else {
			List<GarantiaProduto__c> lGarantiaProduto = [SELECT Id, Name, Garantia__r.Name , Produto__c
												FROM GarantiaProduto__c 
												WHERE Produto__c =: garantia.Produto__c
                                                AND Garantia__r.Name LIKE :searchTerm
                                                ORDER BY Name ASC];
            
            system.debug('lGarantiaProduto: '+lGarantiaProduto);
            
            List<CriarGarantiaRelacionadaController.GarantiaWrapper> lstGarantias = new List<CriarGarantiaRelacionadaController.GarantiaWrapper>();
            
            if(!(lGarantiaProduto.isEmpty())){
                for(GarantiaProduto__c g: lGarantiaProduto){
                    CriarGarantiaRelacionadaController.GarantiaWrapper garantiaNova = new CriarGarantiaRelacionadaController.GarantiaWrapper();
                    garantiaNova.id = g.Id;
                    garantiaNova.Name = g.Name;
                    garantiaNova.GarantiaName = g.Garantia__r.Name;
                    lstGarantias.add(garantiaNova);
            	}
                
                system.debug('lstGarantias: '+lstGarantias);
            
                if(lstGarantias.isEmpty()) return null;
                
                return lstGarantias;
            }else{
                return null;
            }
            
		}

	}
    
    @AuraEnabled
	public static String buscaNomeGarantiaProduto (String recordId){

		GarantiaProduto__c lGarantiaProduto = [SELECT Id, Name 
											FROM GarantiaProduto__c 
											WHERE Id = :recordId];

		return lGarantiaProduto.Name;
	}
    
    @AuraEnabled
	public static String salvarGarantias (String garantiaId, String recordTyp, String GarantiaRelacionada, String tipoDependencia, Boolean acumulativa, Boolean incremento ){
		
        try {
            Id recordTypeId = Schema.SObjectType.GarantiaRelacionada__c.getRecordTypeInfosByDeveloperName().get(recordTyp).getRecordTypeId();
            GarantiaRelacionada__c lGarantia = new GarantiaRelacionada__c();
            lGarantia.RecordTypeId = recordTypeId;
            lGarantia.GarantiaProduto__c = (id)garantiaId;
            lGarantia.GarantiaRelacionada__c = (id)GarantiaRelacionada;
            if(tipoDependencia != 'no'){
                lGarantia.TipoDependencia__c = tipoDependencia;
            }
            lGarantia.Acumulativa__c = acumulativa;
            lGarantia.Incremento__c = incremento;
            
            insert lGarantia;
            return 'Sucesso';
        }
        catch(Exception e) {
            System.debug('######## ERRO: ' + e.getLineNumber() + ', ' + e.getMessage());
            return 'ERROR '+ e.getLineNumber() + ', ' + e.getMessage();
        }	
	}
    
    @AuraEnabled
	public static List<String> getPickListLabelIntoList(){
		List<String> tipoList = new List<String>();
		List<Schema.PicklistEntry> values = GarantiaRelacionada__c.TipoDependencia__c.getDescribe().getPicklistValues();
		for(Schema.PicklistEntry v : values) {
			tipoList.add(v.getLabel());
            System.debug('moeda: '+v.getLabel());
		}
		return tipoList;
	}
}
//PLV_2583 - FIM - Ajuste na busca de coberturas no objeto "Garantia Relacionada"