workspace-sf/force-app/main/default/objects/Garantia__c/Garantia__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar o cadastro das garantias</description>
    <label>Garantia</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Garantias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/Garantia__c/fields/Sigla__c.field-meta.xml
<CustomField>
    <fullName>Sigla__c</fullName>
    <label>Sigla</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaProduto__c/GarantiaProduto__c.object-meta.xml
<CustomObject>
    <description>Objeto de relacionamento entre os produtos e as garantias</description>
    <label>Garantia do produto</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Garantias do produto</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/GarantiaProduto__c/fields/Garantia__c.field-meta.xml
<CustomField>
    <fullName>Garantia__c</fullName>
    <label>Garantia</label>
    <referenceTo>Garantia__c</referenceTo>
    <relationshipLabel>Garantias do produto</relationshipLabel>
    <relationshipName>GarantiasProduto</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaProduto__c/fields/GarantiaProduto__c.field-meta.xml
<CustomField>
    <fullName>GarantiaProduto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Garantia do produto</label>
    <referenceTo>GarantiaProduto__c</referenceTo>
    <relationshipLabel>Garantias do produto (Garantia do produto)</relationshipLabel>
    <relationshipName>GarantiasProdutoTecnico</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiasGrupoProposta__c/GarantiasGrupoProposta__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar as garantias do grupo da proposta</description>
    <label>Garantia do grupo da proposta</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Garantias do grupo da proposta</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/GarantiasGrupoProposta__c/fields/Garantia__c.field-meta.xml
<CustomField>
    <fullName>Garantia__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Garantia</label>
    <referenceTo>Garantia__c</referenceTo>
    <relationshipLabel>Garantias do grupo da proposta (Garantia)</relationshipLabel>
    <relationshipName>GarantiasGrupoProposta</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiasGrupoProposta__c/fields/GarantiaProduto__c.field-meta.xml
<CustomField>
    <fullName>GarantiaProduto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Garantia do produto</label>
    <referenceTo>GarantiaProduto__c</referenceTo>
    <relationshipLabel>Garantias do grupo da proposta</relationshipLabel>
    <relationshipName>GarantiasGrupoProposta</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiasGrupoProposta__c/fields/GarantiaReferenciada__c.field-meta.xml
<CustomField>
    <fullName>GarantiaReferenciada__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Garantia referenciada</label>
    <referenceTo>Garantia__c</referenceTo>
    <relationshipLabel>Garantias do grupo da proposta (Garantia referenciada)</relationshipLabel>
    <relationshipName>GarantiasReferenciadaGrupoProposta</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiasGrupoProposta__c/fields/GrupoProposta__c.field-meta.xml
<CustomField>
    <fullName>GrupoProposta__c</fullName>
    <label>Grupo da proposta</label>
    <referenceTo>GrupoProposta__c</referenceTo>
    <relationshipLabel>Garantias do grupo da proposta</relationshipLabel>
    <relationshipName>GarantiasGrupoProposta</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiasGrupoProposta__c/fields/PremioComercial__c.field-meta.xml
<CustomField>
    <fullName>PremioComercial__c</fullName>
    <label>Prêmio comercial R$</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GrupoProposta__c/GrupoProposta__c.object-meta.xml
<CustomObject>
    <description>Objeto responsável por armazenar o cadastro dos grupos de segurados da proposta</description>
    <label>Grupo da proposta</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grupos da proposta</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/SeguradoProposta__c/SeguradoProposta__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar os segurados da proposta</description>
    <label>Segurado da proposta</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Segurados da proposta</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/SeguradoProposta__c/fields/GrupoProposta__c.field-meta.xml
<CustomField>
    <fullName>GrupoProposta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Grupo da proposta</label>
    <referenceTo>GrupoProposta__c</referenceTo>
    <relationshipLabel>Segurados da proposta</relationshipLabel>
    <relationshipName>SeguradosProposta</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/SeguradoProposta__c/fields/PremioComercial__c.field-meta.xml
<CustomField>
    <fullName>PremioComercial__c</fullName>
    <label>Prêmio comercial</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

workspace-sf/force-app/main/default/objects/SeguradoProposta__c/fields/PremioIntegral__c.field-meta.xml
<CustomField>
    <fullName>PremioIntegral__c</fullName>
    <label>Prêmio Integral</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Currency</type>
</CustomField>

workspace-sf/force-app/main/default/objects/SeguradoProposta__c/fields/PremioPuro__c.field-meta.xml
<CustomField>
    <fullName>PremioPuro__c</fullName>
    <label>Prêmio puro</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

workspace-sf/force-app/main/default/objects/SeguradoProposta__c/fields/PremioTotal__c.field-meta.xml
<CustomField>
    <fullName>PremioTotal__c</fullName>
    <label>Prêmio total</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Currency</type>
</CustomField>

workspace-sf/force-app/main/default/objects/SeguradoProposta__c/fields/TaxaTotal__c.field-meta.xml
<CustomField>
    <fullName>TaxaTotal__c</fullName>
    <label>Taxa total</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

workspace-sf/force-app/main/default/classes/GarantiasGrupoPropostaDAO.cls
public with sharing class GarantiasGrupoPropostaDAO 
{
	private static final GarantiasGrupoPropostaDAO instancia = new GarantiasGrupoPropostaDAO();
	public static GarantiasGrupoPropostaDAO getInstance() { return instancia; }
	private GarantiasGrupoPropostaDAO() {}

	public List<GarantiasGrupoProposta__c> listaGarantiasVida (Set<Id> setIdGrupo)
	{
		return 
		[
			SELECT
				GarantiaReferenciada__r.Sigla__c,
				Capital__c,
				Garantia__c, //AV-36 - INICIO
				GarantiaProduto__c, //AV-36 - FIM
				Percentual__c,
				PremioComercial__c,
				PremioPuro__c,
				PremioTotal__c,
				PremioIntegral__c, //PLV-5351 INICIO/FIM
				TaxaComercial__c,
				TaxaPura__c,
				TaxaTotal__c,
				Valor__c,
				ValorCotacao__c,
				CurrencyIsoCode, //PLV-3884 - INICIO/FIM - Retornando o campo de moeda para referencia
				//SeguradoProposta__c,
				GrupoProposta__c
			FROM
				GarantiasGrupoProposta__c
			WHERE
				GrupoProposta__c =: setIdGrupo
		];
	}

	// PLV-5249 - INÍCIO
	public Map<String, List<GarantiasGrupoProposta__c>> mapGarantiasVida(Set<Id> setSegurados)
	{
		List<GarantiasGrupoProposta__c> garantiasGruposProposta = listaGarantiasVida(setSegurados);
		Map<String, List<GarantiasGrupoProposta__c>> mapGarantiasGruposPropostas = new Map<String, List<GarantiasGrupoProposta__c>>();

		for(GarantiasGrupoProposta__c garantiaGrupoProposta : garantiasGruposProposta)
		{
			if(mapGarantiasGruposPropostas.containsKey(garantiaGrupoProposta.GrupoProposta__c))
			{
				List<GarantiasGrupoProposta__c> lstGarantiasGrupoProposta = mapGarantiasGruposPropostas.get(garantiaGrupoProposta.GrupoProposta__c);
				lstGarantiasGrupoProposta.add(garantiaGrupoProposta);
			}
			else 
			{
				List<GarantiasGrupoProposta__c> lstGarantiasGrupoProposta = new List<GarantiasGrupoProposta__c>();
				lstGarantiasGrupoProposta.add(garantiaGrupoProposta);
				mapGarantiasGruposPropostas.put(garantiaGrupoProposta.GrupoProposta__c, lstGarantiasGrupoProposta);
			}
		}
		return mapGarantiasGruposPropostas;
	}
	// PLV-5249 - FIM
}