workspace-sf/force-app/main/default/objects/ParametroRenovacao__c/ParametroRenovacao__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar os parâmetros de renovação de uma garantia</description>
    <label>Parâmetro de renovação</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parâmetros de renovação</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/ParametroRenovacao__c/fields/ParametroRenovacao__c.field-meta.xml
<CustomField>
    <fullName>ParametroRenovacao__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parâmetro de renovação</label>
    <referenceTo>ParametroRenovacao__c</referenceTo>
    <relationshipLabel>Parâmetros de renovação</relationshipLabel>
    <relationshipName>ParametrosRenovacao</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/classes/ParametroRenovacaoBO.cls
/**************************************************************************************************************************************************************************
 * 
 *	Classe responsável pelo negócio do objeto de ParametroRenovacao__c
 *
 **************************************************************************************************************************************************************************/
public  class ParametroRenovacaoBO {
	private static final ParametroRenovacaoBO instancia = new ParametroRenovacaoBO();
	//private ParametroRenovacaoDAO dao = ParametroRenovacaoDAO.getInstance();

	private ParametroRenovacaoBO() {	
	}

	public static ParametroRenovacaoBO getInstance(){
		return instancia;
	}

	/*********************************************************************************************************
	*
	* Verifica criação/edição de Parametro de renovação para o produto comercial 
	*
	*********************************************************************************************************/
	public void validarParametroRenovacalProdutoComercial(List<ParametroRenovacao__c> parametrosRenovacao){
		RegrasFabricaProdutos.validarPossibilidadeDMLProdutoComercialFilhosGarantiaProduto(parametrosRenovacao, 'ParametroRenovacao__c', 'ParametrosRenovacao__r');
	}

	/*********************************************************************************************************
	*
	* Habilita novamente a flag que permite que as regra de limite sejam executadas
	*
	*********************************************************************************************************/
	public void habilitarValidacaoRegrasProdutoComercial(List<ParametroRenovacao__c> parametrosRenovacao){
		RegrasFabricaProdutos.habilitarValidacaoRegrasProdutoComercial(parametrosRenovacao, 'ParametroRenovacao__c', 'ParametroRenovacaoTriggerHandler');
	}

	/*********************************************************************************************************
	*
	* Vincula tipo de registro comercial de acordo com o produto que estiver vinculado
	*
	*********************************************************************************************************/
	public void vincularTipoRegistroComercial(List<ParametroRenovacao__c> parametrosRenovacao){
		RegrasFabricaProdutos.vincularTipoRegistroComercialFilhoGarantiaProduto(parametrosRenovacao, 'ParametroRenovacao__c');
	}
}