workspace-sf/force-app/main/default/objects/CanalDistribuicao__c/CanalDistribuicao__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar o cadastro dos canais de distribuição</description>
    <label>Canal de distribuição</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Canais de distribuição</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/CanalDistribuicao__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Em criação</fullName>
                <default>true</default>
                <label>Em criação</label>
            </value>
            <value>
                <fullName>Em aprovação</fullName>
            </value>
            <value>
                <fullName>Em revisão</fullName>
            </value>
            <value>
                <fullName>Em ativação</fullName>
            </value>
            <value>
                <fullName>Ativo</fullName>
            </value>
            <value>
                <fullName>Inativo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/ContadorCodigo__c/ContadorCodigo__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Contador Código</label>
</CustomObject>

workspace-sf/force-app/main/default/objects/DadosCorretor__c/DadosCorretor__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar dados dos corretores.</description>
    <label>Dados do corretor</label>
    <nameField>
        <label>Código do corretor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dados dos corretores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/Modalidade__c/Modalidade__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar as modalidades</description>
    <label>Modalidade</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Modalidades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/Modalidade__c/fields/RamoSeguro__c.field-meta.xml
<CustomField>
    <fullName>RamoSeguro__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ramo de seguro</label>
    <referenceTo>RamoSeguro__c</referenceTo>
    <relationshipLabel>Modalidades</relationshipLabel>
    <relationshipName>Modalidades</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/RamoSeguro__c/RamoSeguro__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar o cadastro dos ramos de seguro</description>
    <label>Ramo de seguro</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ramos de seguro</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/RamoSeguro__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ativo</fullName>
            </value>
            <value>
                <fullName>Inativo</fullName>
            </value>
            <value>
                <fullName>Em análise</fullName>
                <default>true</default>
                <label>Em análise</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/classes/AuraVisualizarPDFControllerTest.cls
@IsTest
public class AuraVisualizarPDFControllerTest {
    public AuraVisualizarPDFControllerTest() {}
    
    @IsTest
    static void getPropostaName() {

        Opportunity y = new Opportunity();
        y.Name = 'asd';
        y.StageName = 'Em criação';
        y.CloseDate = System.today();
        insert y;

        //TKCL-246 FIX05 INICIO
        ContadorCodigo__c contadorTecnico = (ContadorCodigo__c) new ContadorCodigoFactory.ProdutoTecnico().createRecord();
        ContadorCodigo__c contadorComercial = (ContadorCodigo__c) new ContadorCodigoFactory.ProdutoComercial().createRecord();

        Account conta = (Account) new AccountFactory.PessoaFisica().createRecord();
        RamoSeguro__c ramoSeguro = (RamoSeguro__c) new RamoSeguroFactory(conta).createRecord();
        DadosCorretor__c dadosCorretor = (DadosCorretor__c) new DadosCorretorFactory(conta).createRecord();
        CanalDistribuicao__c canalDistribuicao = (CanalDistribuicao__c) new CanalDistribuicaoFactory().createRecord(); 

        Modalidade__c modalidade = (Modalidade__c) new ModalidadeFactory(ramoSeguro).createRecord();
        
        Product2 produtoTecnico = (Product2) new ProdutoFactory.ProdutoTecnico().createRecord();
        produtoTecnico.Status__c = 'Em ativação';
        produtoTecnico.NumeroSusep__c = '123';
        produtoTecnico.VersaoRenovacao__c = 'Versão atual';
        update produtoTecnico;
        produtoTecnico.Status__c = 'Ativo';
        produtoTecnico.ProductCode = '49';
        produtoTecnico.Segmento__c = 'Individual';
        update produtoTecnico;
        Product2 produtoComercial = (Product2) new ProdutoFactory.ProdutoComercial(produtoTecnico).createRecord();
        produtoComercial.Status__c = 'Ativo';
        produtoComercial.ProductCode = 'APTLMKT';
        produtoComercial.Segmento__c = 'Individual';
        produtoComercial.CodigoPrecificaProduto__c = 'APTLMKT';
        update produtoComercial;
        //TKCL-246 FIX05 FIM

        Quote x = new Quote();
        x.OpportunityId = y.Id;
        x.Name = 'asd';
        x.Produto__c = produtoComercial.Id; //TKCL-246 FIX05 INICIO/FIM
        insert x;


        new AuraVisualizarPDFController();
        AuraVisualizarPDFController.getPropostaName(x.Id);
    }
}