workspace-sf/force-app/main/default/objects/CanalDistribuicao__c/CanalDistribuicao__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar o cadastro dos canais de distribuição</description>
    <label>Canal de distribuição</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Canais de distribuição</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/CanalDistribuicao__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Em criação</fullName>
                <default>true</default>
                <label>Em criação</label>
            </value>
            <value>
                <fullName>Em aprovação</fullName>
            </value>
            <value>
                <fullName>Em revisão</fullName>
            </value>
            <value>
                <fullName>Em ativação</fullName>
            </value>
            <value>
                <fullName>Ativo</fullName>
            </value>
            <value>
                <fullName>Inativo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/ContadorCodigo__c/ContadorCodigo__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Contador Código</label>
</CustomObject>

workspace-sf/force-app/main/default/objects/ContadorCodigo__c/fields/Numero__c.field-meta.xml
<CustomField>
    <fullName>Numero__c</fullName>
    <label>Número</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Garantia__c/Garantia__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar o cadastro das garantias</description>
    <label>Garantia</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Garantias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/Garantia__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Em análise</fullName>
            </value>
            <value>
                <fullName>Ativo</fullName>
            </value>
            <value>
                <fullName>Inativo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/Garantia__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TipoGarantia</valueSetName>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/Garantia__c/fields/VigenciaInicial__c.field-meta.xml
<CustomField>
    <fullName>VigenciaInicial__c</fullName>
    <label>Vigência inicial</label>
    <type>Date</type>
</CustomField>

workspace-sf/force-app/main/default/objects/ProdutoCanal__c/ProdutoCanal__c.object-meta.xml
<CustomObject>
    <description>Objeto de relacionamento entre o canal e o produto</description>
    <label>Produto do canal</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Produtos do canal</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/ProdutoCanal__c/fields/CanalDistribuicao__c.field-meta.xml
<CustomField>
    <fullName>CanalDistribuicao__c</fullName>
    <label>Canal de distribuição</label>
    <referenceTo>CanalDistribuicao__c</referenceTo>
    <relationshipLabel>Produtos do canal</relationshipLabel>
    <relationshipName>ProdutosCanal</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/ProdutoCanal__c/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto comercial</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.RecordType.Name</field>
            <operation>equals</operation>
            <value>Produto comercial</value>
        </filterItems>
        <filterItems>
            <field>Product2.Status__c</field>
            <operation>equals</operation>
            <value>Ativo</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Produtos comerciais</relationshipLabel>
    <relationshipName>ProdutosCanal</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/RemuneracaoMultinivel__c/RemuneracaoMultinivel__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar as regras para o pagamento de remuneração multinível</description>
    <label>Remuneração multinível</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Remunerações multinível</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/RemuneracaoMultinivel__c/fields/Participacao__c.field-meta.xml
<CustomField>
    <fullName>Participacao__c</fullName>
    <label>Participação</label>
    <precision>18</precision>
    <required>true</required>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

workspace-sf/force-app/main/default/objects/RemuneracaoMultinivel__c/fields/ProdutoCanal__c.field-meta.xml
<CustomField>
    <fullName>ProdutoCanal__c</fullName>
    <label>Produto do canal</label>
    <referenceTo>ProdutoCanal__c</referenceTo>
    <relationshipLabel>Remunerações multinível</relationshipLabel>
    <relationshipName>RemuneracoesMultinivel</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/RemuneracaoMultinivel__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nível 1</fullName>
                <default>true</default>
                <label>Nível 1</label>
            </value>
            <value>
                <fullName>Nível 2</fullName>
            </value>
            <value>
                <fullName>Nível 3</fullName>
            </value>
            <value>
                <fullName>Nível 4</fullName>
            </value>
            <value>
                <fullName>Nível 5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/RemuneracaoMultinivel__c/fields/TipoRemuneracao__c.field-meta.xml
<CustomField>
    <fullName>TipoRemuneracao__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tipo de remuneração</label>
    <referenceTo>TipoRemuneracao__c</referenceTo>
    <relationshipLabel>Remunerações multinível</relationshipLabel>
    <relationshipName>RemuneracoesMultinivel</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/RemuneracaoProduto__c/RemuneracaoProduto__c.object-meta.xml
<CustomObject>
    <description>Objeto de relacionamento entre o produto e o tipo de remuneração</description>
    <label>Remuneração do produto</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Remunerações do produto</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/RemuneracaoProduto__c/fields/ParcelasAgenciamento__c.field-meta.xml
<CustomField>
    <fullName>ParcelasAgenciamento__c</fullName>
    <label>Parcelas de agenciamento</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1ª parcela</fullName>
            </value>
            <value>
                <fullName>2ª parcela</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/RemuneracaoProduto__c/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Remunerações do produto</relationshipLabel>
    <relationshipName>RemuneracoesProduto</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/RemuneracaoProduto__c/fields/RemuneracaoProduto__c.field-meta.xml
<CustomField>
    <fullName>RemuneracaoProduto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Remuneração do produto</label>
    <referenceTo>RemuneracaoProduto__c</referenceTo>
    <relationshipLabel>Remunerações do produto</relationshipLabel>
    <relationshipName>RemuneracoesProduto</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/RemuneracaoProduto__c/fields/TipoRemuneracao__c.field-meta.xml
<CustomField>
    <fullName>TipoRemuneracao__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tipo de remuneração</label>
    <referenceTo>TipoRemuneracao__c</referenceTo>
    <relationshipLabel>Remunerações do produto</relationshipLabel>
    <relationshipName>RemuneracoesProduto</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/RemuneracaoProduto__c/recordTypes/ProdutoComercial.recordType-meta.xml
<RecordType>
    <fullName>ProdutoComercial</fullName>
    <active>true</active>
    <label>Produto comercial</label>
</RecordType>

workspace-sf/force-app/main/default/objects/RemuneracaoProduto__c/recordTypes/ProdutoTecnico.recordType-meta.xml
<RecordType>
    <fullName>ProdutoTecnico</fullName>
    <active>true</active>
    <label>Produto técnico</label>
</RecordType>

workspace-sf/force-app/main/default/objects/TipoRemuneracao__c/TipoRemuneracao__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar o cadastro dos tipos de remuneração</description>
    <label>Tipo de remuneração</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tipos de remuneração</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/TipoRemuneracao__c/fields/ModeloRecuperacao__c.field-meta.xml
<CustomField>
    <fullName>ModeloRecuperacao__c</fullName>
    <label>Modelo de recuperação</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Integral</fullName>
            </value>
            <value>
                <fullName>Multinível</fullName>
            </value>
            <value>
                <fullName>Por parcela à vencer</fullName>
            </value>
            <value>
                <fullName>Por parcela paga</fullName>
            </value>
            <value>
                <fullName>Pro-rata</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/classes/RemuneracaoMultinivelTest.cls
/**
 * Testes Remuneração multinível
 *
 **/
@isTest
private class RemuneracaoMultinivelTest {
	@testSetup
	private static void setup() {
		List<ContadorCodigo__c> contadoresProduto = new List<ContadorCodigo__c>{
			new ContadorCodigo__c(Name='ProdutoTecnico', Numero__c = 0),
			new ContadorCodigo__c(Name='ProdutoComercial', Numero__c = 0)
		};
		insert contadoresProduto;
	}

	@isTest
	private static void testeValidacaoTipoRemuneracao(){
		TipoRemuneracao__c tipoRemuneracaoAgenciamento = new TipoRemuneracao__c();
		tipoRemuneracaoAgenciamento.Name = 'Agenciamento';
		tipoRemuneracaoAgenciamento.Descricao__c = 'Lorem ipsum dolor sit amet, consectetur adipisicing elit.';
		tipoRemuneracaoAgenciamento.ModeloRecuperacao__c = 'Integral';
		insert tipoRemuneracaoAgenciamento;

		TipoRemuneracao__c tipoRemuneracaoCorretagem = new TipoRemuneracao__c();
		tipoRemuneracaoCorretagem.Name = 'Corretagem';
		tipoRemuneracaoCorretagem.Descricao__c = 'Lorem ipsum dolor sit amet, consectetur adipisicing elit.';
		tipoRemuneracaoCorretagem.ModeloRecuperacao__c = 'Integral';
		insert tipoRemuneracaoCorretagem;

		Garantia__c garantia = new Garantia__c();
		garantia.VigenciaInicial__c = System.today();
		garantia.Tipo__c = 'Cobertura';
		insert garantia;

		CanalDistribuicao__c canalDistribuicao = new CanalDistribuicao__c();
		canalDistribuicao.Name = 'Canal Distribuição Teste 001';
		insert canalDistribuicao;

		//Criação da estrutura do produto técnico
		Product2 produtoTec = new Product2();
		produtoTec.Name = 'Nome produtoTec 001';
		produtoTec.Status__c = 'Em criação';
		produtoTec.ProductCode = '201700001';
		produtoTec.Status__c = 'Em criação';
		produtoTec.RecordTypeId = RecordTypeBO.buscarTipoRegistro('Product2', 'ProdutoTecnico').Id;
		produtoTec.TipoResponsavelPagamento__c = 'SEG';
		insert produtoTec;
		//correcao ambientes inicio
		/* ContentVersion versaoArquivoTec = new ContentVersion(
			Title = 'Test 001 - ' + System.now(),
			PathOnClient = 'test_001.txt',
			VersionData = Blob.valueOf('Arquivo #001 de amostra ' + System.now()),
			IsMajorVersion = true
		);
		insert versaoArquivoTec;

		ContentDocumentLink arquivoTec = new ContentDocumentLink();
		arquivoTec.ContentDocumentId = [SELECT Id, ContentDocumentId FROM ContentVersion WHERE Id =: versaoArquivoTec.Id].ContentDocumentId;
		arquivoTec.LinkedEntityId = produtoTec.Id;
		arquivoTec.ShareType = 'V';
		insert arquivoTec; */
		//correcao ambientes fim

		produtoTec.Status__c = 'Em ativação';
		produtoTec.NumeroSusep__c = '1234x';
		update produtoTec;

		produtoTec.Status__c = 'Ativo';
		update produtoTec;

		RemuneracaoProduto__c remuneracaoProduto = new RemuneracaoProduto__c();
		remuneracaoProduto.Produto__c = produtoTec.Id;
		remuneracaoProduto.TipoRemuneracao__c = tipoRemuneracaoAgenciamento.Id;
		remuneracaoProduto.ParcelasAgenciamento__c = '1ª parcela';
		insert remuneracaoProduto;

		//Criação da estrutura do produto comercial
		Product2 produtoCom = new Product2();
		produtoCom.ProdutoTecnico__c = produtoTec.Id;
		produtoCom.Name = 'Nome ProdutoCom 001';
		produtoCom.Status__c = 'Em criação';
		produtoCom.ProductCode = '201700001';
		produtoCom.RecordTypeId = RecordTypeBO.buscarTipoRegistro('Product2', 'ProdutoComercial').Id;
		produtoCom.TipoResponsavelPagamento__c = 'SEG';
		insert produtoCom;

		RemuneracaoProduto__c remuneracaoProdutoCom = new RemuneracaoProduto__c();
		remuneracaoProdutoCom.Produto__c = produtoCom.Id;
		remuneracaoProdutoCom.TipoRemuneracao__c = tipoRemuneracaoAgenciamento.Id;
		remuneracaoProdutoCom.ParcelasAgenciamento__c = '1ª parcela';
		insert remuneracaoProdutoCom;
		//correcao ambientes inicio
		// Cria a versão do documento
		/* ContentVersion cv1 = new ContentVersion(
			Title = 'Test 001 - ' + System.now(),
			PathOnClient = 'test_001.txt',
			VersionData = Blob.valueOf('Arquivo #001 de amostra ' + System.now()),
			IsMajorVersion = true
		);
		insert cv1;

		// Cria a relação de produto produtoCom com documento documento
		ContentDocumentLink cdl1 = new ContentDocumentLink();
		cdl1.ContentDocumentId = [SELECT Id, ContentDocumentId FROM ContentVersion WHERE Id =: cv1.Id].ContentDocumentId;
		cdl1.LinkedEntityId = produtoCom.Id;
		cdl1.ShareType = 'V'; // ??
		insert cdl1; */
		//correcao ambientes fim

		produtoCom.Status__c = 'Em ativação';
		produtoCom.NumeroSusep__c = '1234';
		update produtoCom;

		produtoCom.Status__c = 'Ativo';
		update produtoCom;

		ProdutoCanal__c produtoCanal = new ProdutoCanal__c();
		produtoCanal.CanalDistribuicao__c = canalDistribuicao.Id;
		produtoCanal.Produto__c = produtoCom.Id;
		insert produtoCanal;

		RemuneracaoMultinivel__c remuneracaoMultinivel = new RemuneracaoMultinivel__c();
		remuneracaoMultinivel.ProdutoCanal__c = produtoCanal.Id;
		remuneracaoMultinivel.TipoRemuneracao__c = tipoRemuneracaoCorretagem.Id;
		remuneracaoMultinivel.Tipo__c = 'Nível 1';
		remuneracaoMultinivel.Participacao__c = 10;

		//Teste 1: tenta inserir uma remuneracao multinivel com o tipo de remuneracao diferente da remuneracao do produto
		String erro = '';

		try{
			insert remuneracaoMultinivel;
		}
		catch(Exception ex){
			erro = ex.getMessage();
		}

		System.assert(erro.indexOf('Este tipo de remuneração não está na remuneração do produto.') > -1);

		//Teste 2: tenta inserir um remuneracao do canal com parcelas de agenciamento iguais da remuneracao do produto
		erro = '';
		remuneracaoMultinivel.TipoRemuneracao__c = tipoRemuneracaoAgenciamento.Id;
		insert remuneracaoMultinivel;

		System.assert(remuneracaoMultinivel.Id != null);
	}
}