workspace-sf/force-app/main/default/objects/CanalDistribuicao__c/CanalDistribuicao__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar o cadastro dos canais de distribuição</description>
    <label>Canal de distribuição</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Canais de distribuição</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/CanalDistribuicao__c/fields/Papeis__c.field-meta.xml
<CustomField>
    <fullName>Papeis__c</fullName>
    <label>Papéis</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Papeis</valueSetName>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/CanalDistribuicao__c/fields/Sigla__c.field-meta.xml
<CustomField>
    <fullName>Sigla__c</fullName>
    <label>Sigla</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/CanalDistribuicao__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Em criação</fullName>
                <default>true</default>
                <label>Em criação</label>
            </value>
            <value>
                <fullName>Em aprovação</fullName>
            </value>
            <value>
                <fullName>Em revisão</fullName>
            </value>
            <value>
                <fullName>Em ativação</fullName>
            </value>
            <value>
                <fullName>Ativo</fullName>
            </value>
            <value>
                <fullName>Inativo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/ContadorCodigo__c/ContadorCodigo__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Contador Código</label>
</CustomObject>

workspace-sf/force-app/main/default/objects/DadosCorretor__c/DadosCorretor__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar dados dos corretores.</description>
    <label>Dados do corretor</label>
    <nameField>
        <label>Código do corretor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dados dos corretores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/Modalidade__c/Modalidade__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar as modalidades</description>
    <label>Modalidade</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Modalidades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/Modalidade__c/fields/RamoSeguro__c.field-meta.xml
<CustomField>
    <fullName>RamoSeguro__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ramo de seguro</label>
    <referenceTo>RamoSeguro__c</referenceTo>
    <relationshipLabel>Modalidades</relationshipLabel>
    <relationshipName>Modalidades</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/RamoSeguro__c/RamoSeguro__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar o cadastro dos ramos de seguro</description>
    <label>Ramo de seguro</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ramos de seguro</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/RamoSeguro__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ativo</fullName>
            </value>
            <value>
                <fullName>Inativo</fullName>
            </value>
            <value>
                <fullName>Em análise</fullName>
                <default>true</default>
                <label>Em análise</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/classes/ConsultaPdfPropostaRESTTest.cls
/*******************************************************************************************************************************
* Consulta documento
* @author Yuri - Sys4b
* @date 26/04/2021
* Classe criada por conta da história PLV-4896
******************************************************************************************************************************/
@isTest
public class ConsultaPdfPropostaRESTTest {
	@TestSetup
    static void setupUnit(){
        ContadorCodigo__c contadorTecnico = (ContadorCodigo__c) new ContadorCodigoFactory.ProdutoTecnico().createRecord();
        ContadorCodigo__c contadorComercial = (ContadorCodigo__c) new ContadorCodigoFactory.ProdutoComercial().createRecord();
                
        Account conta = (Account) new AccountFactory.PessoaFisica().createRecord();
        RamoSeguro__c ramoSeguro = ( RamoSeguro__c ) new RamoSeguroFactory( conta ).createRecord();
        DadosCorretor__c dadosCorretor = (DadosCorretor__c) new DadosCorretorFactory(conta).createRecord();
        Modalidade__c modalidade = (Modalidade__c) new ModalidadeFactory(ramoSeguro).createRecord();
       

        Product2 produtoTecnico = (Product2) new ProdutoFactory.ProdutoTecnico().createRecord();
        produtoTecnico.Status__c = 'Em ativação';
        produtoTecnico.NumeroSusep__c = '123';
        produtoTecnico.VersaoRenovacao__c = 'Versão atual';
        update produtoTecnico;
        produtoTecnico.Status__c = 'Ativo';
        update produtoTecnico;

        Product2 produtoComercial = (Product2) new ProdutoFactory.ProdutoComercial(produtoTecnico).createRecord();
        Opportunity orcamento = (Opportunity) new OrcamentoFactory.VidaIndividual(produtoComercial, conta).createRecord();
        
        Quote proposta = (Quote) new PropostaFactory(produtoComercial, ramoSeguro, conta, dadosCorretor, orcamento, modalidade).createRecord();
		CanalDistribuicao__c canal = new CanalDistribuicao__c(
				Name = 'Corretor',
            	Sigla__c = 'COR',
            	Papeis__c = 'Corretor'
        		);
       	
        insert canal;
       

        proposta.CanalDistribuicao__c = canal.Id;
          proposta.CanalDistribuicao__r = canal;
        proposta.Status = 'Contratada';
        update proposta;
        
        System.debug('@@@@');
        System.debug(canal);
        System.debug(canal.Id);
        System.debug(proposta.CanalDistribuicao__c);
        System.debug(proposta.CanalDistribuicao__r.Name);
        System.debug(proposta.CodigoCorretor__c);
        System.debug(proposta.Name);
    }
    
    @IsTest
    static void valida_parametros(){
        RestRequest req = new RestRequest();
        req.requestBody = Blob.valueof('{\"proposta\":\"\"}');
        RestContext.request = req;
        
        Test.startTest();
        ConsultaPdfPropostaREST.Response result = ConsultaPdfPropostaREST.consultar();
        System.debug(JSON.serialize(result));
        req.requestBody = Blob.valueof('{\"proposta\":\"18-00006768\", \"canal\":\"Corretor\"}');
        RestContext.request = req;
        result = ConsultaPdfPropostaREST.consultar();
		req.requestBody = Blob.valueof('{\"idCanal\":\"001\", \"canal\":\"Corretor\"}');
        RestContext.request = req;
        result = ConsultaPdfPropostaREST.consultar();
        req.requestBody = Blob.valueof('');
        RestContext.request = req;
        result = ConsultaPdfPropostaREST.consultar();

        Test.stopTest();
    } 
    
    @IsTest
    static void busca_documento(){
        RestRequest req = new RestRequest();
        req.requestBody = Blob.valueof('{\"proposta\":\"18-00006768\", \"idCanal\":\"001\", \"canal\":\"Corretor\"}');
        RestContext.request = req;

        Test.startTest();
        ConsultaPdfPropostaREST.Response result = ConsultaPdfPropostaREST.consultar();
        System.debug('resposta: ' + JSON.serialize(result));
        Test.stopTest();
    }
 
}