workspace-sf/force-app/main/default/objects/CanalDistribuicao__c/CanalDistribuicao__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar o cadastro dos canais de distribuição</description>
    <label>Canal de distribuição</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Canais de distribuição</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/CanalDistribuicao__c/fields/Sigla__c.field-meta.xml
<CustomField>
    <fullName>Sigla__c</fullName>
    <label>Sigla</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/ProdutoCanal__c/ProdutoCanal__c.object-meta.xml
<CustomObject>
    <description>Objeto de relacionamento entre o canal e o produto</description>
    <label>Produto do canal</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Produtos do canal</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/ProdutoCanal__c/fields/CanalDistribuicao__c.field-meta.xml
<CustomField>
    <fullName>CanalDistribuicao__c</fullName>
    <label>Canal de distribuição</label>
    <referenceTo>CanalDistribuicao__c</referenceTo>
    <relationshipLabel>Produtos do canal</relationshipLabel>
    <relationshipName>ProdutosCanal</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/ProdutoCanal__c/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto comercial</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.RecordType.Name</field>
            <operation>equals</operation>
            <value>Produto comercial</value>
        </filterItems>
        <filterItems>
            <field>Product2.Status__c</field>
            <operation>equals</operation>
            <value>Ativo</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Produtos comerciais</relationshipLabel>
    <relationshipName>ProdutosCanal</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/classes/CanalDistribuicaoDAO.cls
/**************************************************************************************************************************************************************************
 * 
 *	Classe responsável pela buscade dados do objeto de CanalDistribuicao__c
 *
 **************************************************************************************************************************************************************************/
public class CanalDistribuicaoDAO {
	private static final CanalDistribuicaoDAO instancia = new CanalDistribuicaoDAO();

	private CanalDistribuicaoDAO() {	
	}

	public static CanalDistribuicaoDAO getInstance(){
		return instancia;
	}

	public List<CanalDistribuicao__c> buscarCanalDistribuicaoComFilhos(Set<Id> canalDistribuicaoIds){
		return [
			Select 
				Id, 
				(Select 
					Id, 
					Produto__c 
				From 
					ProdutosCanal__r)
			From 
				CanalDistribuicao__c 
			Where 
				Id IN: canalDistribuicaoIds
		];
	}

	public CanalDistribuicao__c buscarCanalDistribuicaoOrcamentoPorSigla(String sigla) {
		return [
			SELECT
				Id,
				Name,
				Sigla__c
			FROM
				CanalDistribuicao__c
			WHERE
				Sigla__c =: sigla
			LIMIT 1
		];
	}
}