workspace-sf/force-app/main/default/objects/CanalDistribuicao__c/CanalDistribuicao__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar o cadastro dos canais de distribuição</description>
    <label>Canal de distribuição</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Canais de distribuição</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/CanalDistribuicao__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Em criação</fullName>
                <default>true</default>
                <label>Em criação</label>
            </value>
            <value>
                <fullName>Em aprovação</fullName>
            </value>
            <value>
                <fullName>Em revisão</fullName>
            </value>
            <value>
                <fullName>Em ativação</fullName>
            </value>
            <value>
                <fullName>Ativo</fullName>
            </value>
            <value>
                <fullName>Inativo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/ContadorCodigo__c/ContadorCodigo__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Contador Código</label>
</CustomObject>

workspace-sf/force-app/main/default/objects/ContratanteProposta__c/ContratanteProposta__c.object-meta.xml
<CustomObject>
    <description>Objeto responsável por armazenar o cadastro dos contratantes da proposta</description>
    <label>Contratante da proposta</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contratantes da proposta</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/ContratanteProposta__c/fields/FormaPagamento__c.field-meta.xml
<CustomField>
    <fullName>FormaPagamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Forma de pagamento</label>
    <referenceTo>FormaPagamento__c</referenceTo>
    <relationshipLabel>Contratantes da proposta</relationshipLabel>
    <relationshipName>ContratantesProposta</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/ContratanteProposta__c/fields/VigenciaInicial__c.field-meta.xml
<CustomField>
    <fullName>VigenciaInicial__c</fullName>
    <label>Vigência inicial</label>
    <type>Date</type>
</CustomField>

workspace-sf/force-app/main/default/objects/CriticaProposta__c/CriticaProposta__c.object-meta.xml
<CustomObject>
    <description>Objeto responsável por armazenar as críticas da proposta</description>
    <label>Crítica da proposta</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Críticas da proposta</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/CriticaProposta__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <label>Código</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/CriticaProposta__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Não iniciada</fullName>
            </value>
            <value>
                <fullName>Pendente</fullName>
            </value>
            <value>
                <fullName>Em aprovação</fullName>
            </value>
            <value>
                <fullName>Condicionada</fullName>
            </value>
            <value>
                <fullName>Inconclusiva</fullName>
            </value>
            <value>
                <fullName>Liberado</fullName>
            </value>
            <value>
                <fullName>Recusado</fullName>
            </value>
            <value>
                <fullName>Cancelada</fullName>
            </value>
            <value>
                <fullName>Pendenciado</fullName>
            </value>
            <value>
                <fullName>Falha na Integração</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/CriticaProposta__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Analise</fullName>
                <label>Análise</label>
            </value>
            <value>
                <fullName>Aviso</fullName>
            </value>
            <value>
                <fullName>CriticaSAP</fullName>
                <label>Crítica SAP</label>
            </value>
            <value>
                <fullName>Pendencia</fullName>
                <label>Pendência</label>
            </value>
            <value>
                <fullName>Recusa</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/DadosCorretor__c/DadosCorretor__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar dados dos corretores.</description>
    <label>Dados do corretor</label>
    <nameField>
        <label>Código do corretor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dados dos corretores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/DadosCorretor__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Principal</fullName>
            </value>
            <value>
                <fullName>Produção</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/FormaPagamento__c/FormaPagamento__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar o cadastro das formas de pagamento</description>
    <label>Forma de pagamento</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Formas de pagamento</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/FormaPagamento__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <label>Código</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/FormaPagamento__c/fields/Modalidade__c.field-meta.xml
<CustomField>
    <fullName>Modalidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Modalidade</label>
    <referenceTo>Modalidade__c</referenceTo>
    <relationshipLabel>Formas de pagamento</relationshipLabel>
    <relationshipName>Formas_de_pagamento</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/FormaPagamento__c/fields/RamoSeguro__c.field-meta.xml
<CustomField>
    <fullName>RamoSeguro__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ramo de seguro</label>
    <referenceTo>RamoSeguro__c</referenceTo>
    <relationshipLabel>Formas de pagamento</relationshipLabel>
    <relationshipName>FormasPagamento</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Garantia__c/Garantia__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar o cadastro das garantias</description>
    <label>Garantia</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Garantias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/Garantia__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Em análise</fullName>
            </value>
            <value>
                <fullName>Ativo</fullName>
            </value>
            <value>
                <fullName>Inativo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/Garantia__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TipoGarantia</valueSetName>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/Garantia__c/fields/VigenciaInicial__c.field-meta.xml
<CustomField>
    <fullName>VigenciaInicial__c</fullName>
    <label>Vigência inicial</label>
    <type>Date</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Modalidade__c/Modalidade__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar as modalidades</description>
    <label>Modalidade</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Modalidades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/Modalidade__c/fields/RamoSeguro__c.field-meta.xml
<CustomField>
    <fullName>RamoSeguro__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ramo de seguro</label>
    <referenceTo>RamoSeguro__c</referenceTo>
    <relationshipLabel>Modalidades</relationshipLabel>
    <relationshipName>Modalidades</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/RamoSeguro__c/RamoSeguro__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar o cadastro dos ramos de seguro</description>
    <label>Ramo de seguro</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ramos de seguro</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/RamoSeguro__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ativo</fullName>
            </value>
            <value>
                <fullName>Inativo</fullName>
            </value>
            <value>
                <fullName>Em análise</fullName>
                <default>true</default>
                <label>Em análise</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/classes/ContratPropRenovaScheduleTest.cls
@istest
public class ContratPropRenovaScheduleTest {
    
    @testSetup
    public static void gerarDadosTeste(){
        // Geração Account
        Account contaTeste = TestDataFactory.gerarConta();

        // Geração Dados do Corretor
        DadosCorretor__c dadosCorretor = TestDataFactory.gerarDadosCorretor(contaTeste);

        // Geração Ramo do Seguro
        RamoSeguro__c ramoSegurado = TestDataFactory.gerarRamoSeguro(contaTeste);

        // Geração Garantia
        Garantia__c garantia1 = TestDataFactory.gerarGarantia();
        
        ContadorCodigo__c contCodigoTec = (ContadorCodigo__c) new ContadorCodigoFactory.ProdutoTecnico().createRecord();
	      ContadorCodigo__c contCodigoCom = (ContadorCodigo__c) new ContadorCodigoFactory.ProdutoComercial().createRecord();
        
        // Geração Propduto Técnico
        Product2 produtoTec = TestDataFactory.gerarProdutoTecnico();
        produtoTec.Status__c = 'Ativo';
        produtoTec.Segmento__c = 'Individual';
        update produtoTec;
        
        // Geração Produto Comercial
        Product2 produtoCom = TestDataFactory.gerarProdutoComericial(produtoTec);
        produtoCom.Status__c ='ativo';
        produtoCom.Segmento__c = 'Individual';
        update produtoCom;

        // Geração Canal de Distribuição
        CanalDistribuicao__c canalDistribuicao = TestDataFactory.gerarCanalDistribuicao();
        
        // Geração Orçamento (Opportunity)
        Opportunity orcamentoContratado = TestDataFactory.gerarOrcamentoObjeto(contaTeste, produtoCom, canalDistribuicao);
        orcamentoContratado.Type = 'Renovacao';        
        update orcamentoContratado;
        
        // Geração Modalidade
        Modalidade__c modalidade = TestDataFactory.gerarModalidade(ramoSegurado);

        // Geração Quote
      	Quote propostaTeste= TestDataFactory.gerarPropostaObjeto(produtoCom, ramoSegurado, contaTeste, dadosCorretor, orcamentoContratado, modalidade);
        propostaTeste.Status = 'Em análise';
        propostaTeste.Tipo__c = 'Renovacao';
        propostaTeste.VigenciaInicial__c = System.today().addDays(10);
        propostaTeste.PaisesDestino__c = 'Brasil';
        update propostaTeste;

        //Geração de forma de Pagamento
        FormaPagamento__c pagamento = TestDataFactory.gerarFormaPagamento();

        //Geração do Contratante da Proposta Para Propostas Liberadas e Não Liberadas
        ContratanteProposta__c contratantePropLiberada = TestDataFactory.gerarContratanteProposta(contaTeste, propostaTeste, pagamento);

        //Criação das Criticas Proposta Liberada
        CriticaProposta__c criticaLibRenovacao = TestDataFactory.gerarCriticasPropostaRenovacao(propostaTeste, '154', 'Pendente');
        CriticaProposta__c criticaLibAssEletr = TestDataFactory.gerarCriticasPropostaRenovacao(propostaTeste, '109', 'Pendente');
        CriticaProposta__c criticaLibQuestVida = TestDataFactory.gerarCriticasPropostaRenovacao(propostaTeste, '124', 'Liberado');
    }

    @istest static void testSchedule(){
        List<CriticaProposta__c> criticasLiberadas = [SELECT Id FROM CriticaProposta__c WHERE Codigo__c = '154'];      
        if (criticasLiberadas <> null) {
            System.assertEquals(1, criticasLiberadas.size());
        }
        
        Test.StartTest();
        System.debug('Iniciando o processamento');
        ContratPropRenovaSchedule schd = new ContratPropRenovaSchedule();
        String scheduleTest = '0 0 23 ? * *';
		System.debug('Iniciando o comparativo');
        System.schedule('Teste de Job', scheduleTest, schd);
        System.debug('Terminando o comparativo');
        Test.stopTest();
    }
}