workspace-sf/force-app/main/default/objects/DeclaracaoSaude__c/DeclaracaoSaude__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar as declarações de saúde das contas</description>
    <label>Declaração de saúde</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número da declaração da saúde</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Declarações de saúde</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/DeclaracaoSaude__c/fields/Proposta__c.field-meta.xml
<CustomField>
    <fullName>Proposta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proposta</label>
    <referenceTo>Quote</referenceTo>
    <relationshipName>DeclaracoesSaude</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/classes/ExpurgoDeclaracaoSaude.cls
/**
 * Expurgo de dados para o Proposta
 *  objeto: DeclaracaoSaude__c 
 * caminho do objeto:
 *  > DeclaracaoSaude__c 
 *  > Proposta__c
 * 
 * 28/02/2024
 */

public with sharing class ExpurgoDeclaracaoSaude {
   
    public List<DeclaracaoSaude__c> getDadosExpurgo(Integer qt) { 
        List<DeclaracaoSaude__c> expList= new List<DeclaracaoSaude__c>();
        String query= 'SELECT Id '
            +'FROM DeclaracaoSaude__c '
            +'WHERE Proposta__r.Segmento__c = \'Massificados\' ';
        if (qt != 0) {
            query+= 'LIMIT :qt';
        }
        expList= Database.queryWithBinds(query, new Map<String,Object>{'qt' => qt}, AccessLevel.SYSTEM_MODE);
        System.debug(expList);
        return expList;
    }

    public void deleteDadosExpurgo(List<DeclaracaoSaude__c> expList) {
        if (!Test.isRunningTest()) {
           delete (List<DeclaracaoSaude__c>)expList;
        }
    }
}