workspace-sf/force-app/main/default/objects/ProdutoCanal__c/ProdutoCanal__c.object-meta.xml
<CustomObject>
    <description>Objeto de relacionamento entre o canal e o produto</description>
    <label>Produto do canal</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Produtos do canal</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/ProdutoCanal__c/fields/MeioComercializacao__c.field-meta.xml
<CustomField>
    <fullName>MeioComercializacao__c</fullName>
    <label>Meio de comercialização</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MeioComercializacao</valueSetName>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/RemuneracaoCanal__c/RemuneracaoCanal__c.object-meta.xml
<CustomObject>
    <description>Objeto de relacionamento entre o canal e o tipo de remuneração</description>
    <label>Remuneração do produto do canal</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Remunerações dos produtos canal</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/RemuneracaoCanal__c/fields/MeioComercializacao__c.field-meta.xml
<CustomField>
    <fullName>MeioComercializacao__c</fullName>
    <label>Meio de Comercialização</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MeioComercializacao</valueSetName>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/RemuneracaoCanal__c/fields/ProdutoCanal__c.field-meta.xml
<CustomField>
    <fullName>ProdutoCanal__c</fullName>
    <label>Produto do canal</label>
    <referenceTo>ProdutoCanal__c</referenceTo>
    <relationshipLabel>Remunerações dos produtos canal</relationshipLabel>
    <relationshipName>RemuneracoesProdutoCanal</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/RemuneracaoCanal__c/fields/TipoRemuneracao__c.field-meta.xml
<CustomField>
    <fullName>TipoRemuneracao__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tipo de remuneração</label>
    <referenceTo>TipoRemuneracao__c</referenceTo>
    <relationshipName>RemuneracoesCanal</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/TipoRemuneracao__c/TipoRemuneracao__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar o cadastro dos tipos de remuneração</description>
    <label>Tipo de remuneração</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tipos de remuneração</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/classes/RemuneracaoCanalDAO.cls
public class RemuneracaoCanalDAO {

	private static final RemuneracaoCanalDAO instance = new RemuneracaoCanalDAO();

	public static RemuneracaoCanalDAO getInstance() {
		return instance;
	}

	public List<RemuneracaoCanal__c> buscarRemuneracaoCanalPorProdutos(Set<Id> produtoCanalIds){
		return [
				Select
					Id,
					TipoRemuneracao__c,
					MeioComercializacao__c
				From 
					RemuneracaoCanal__c	
				Where 
					ProdutoCanal__c IN: produtoCanalIds
				];
	}
}