workspace-sf/force-app/main/default/objects/CriticaOrcamento__c/CriticaOrcamento__c.object-meta.xml
<CustomObject>
    <description>Objeto responsável por armazenar as analises de aceitação geradas pelo ODM ou pelo Sinapse</description>
    <label>Crítica do orçamento</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número da crítica</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Críticas do orçamento</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/CriticaOrcamento__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <label>Área</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/CriticaOrcamento__c/fields/Orcamento__c.field-meta.xml
<CustomField>
    <fullName>Orcamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Orçamento</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Críticas do orçamento</relationshipLabel>
    <relationshipName>CriticaOrcamentos</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/CriticaOrcamento__c/fields/Origem__c.field-meta.xml
<CustomField>
    <fullName>Origem__c</fullName>
    <label>Origem</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ODM</fullName>
            </value>
            <value>
                <fullName>Sinapse</fullName>
            </value>
            <value>
                <fullName>SAP</fullName>
            </value>
            <value>
                <fullName>ProtocoloWeb</fullName>
                <label>Protocolo Web</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/CriticaOrcamento__c/fields/Severidade__c.field-meta.xml
<CustomField>
    <fullName>Severidade__c</fullName>
    <label>Severidade</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

workspace-sf/force-app/main/default/objects/CriticaOrcamento__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pendente</fullName>
            </value>
            <value>
                <fullName>Em aprovação</fullName>
            </value>
            <value>
                <fullName>Liberado</fullName>
            </value>
            <value>
                <fullName>Recusado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/CriticaOrcamento__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Análise</fullName>
            </value>
            <value>
                <fullName>Aviso</fullName>
            </value>
            <value>
                <fullName>Pendência</fullName>
            </value>
            <value>
                <fullName>Recusa</fullName>
            </value>
            <value>
                <fullName>Risco</fullName>
            </value>
            <value>
                <fullName>Assinatura</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/classes/CriticaOrcamentoFactory.cls
/**
 * @author AVX - Leonardo Camacho
 * @date 2019-08-26
 * @description: Crítica do orçamento Factory Class
 */

@isTest
public class CriticaOrcamentoFactory {

	private static Map<String,CriticaOrcamento__c> mStaticRecord = new Map<String,CriticaOrcamento__c>();
          
	//----------------------------- CriticaOrçamento Fila Médica - Orçamento --------------------------------
	
    private static CriticaOrcamento__c criarRegistroFilaMedicaOrcamento(Opportunity orcamento){

  		if(!mStaticRecord.containsKey('FilaMedicaOrcamento')){
			
			mStaticRecord.put('FilaMedicaOrcamento', new CriticaOrcamento__c(
				Area__c = 'MED',
                Codigo__c = '000MED',
				Status__c = 'Pendente',
				Tipo__c = 'Análise',
				Severidade__c = 1,
				Origem__c = 'ODM',
              	Orcamento__c = orcamento.Id)
               );                      
		}
		return mStaticRecord.get('FilaMedicaOrcamento');
	}

	public class FilaMedicaOrcamento extends SObjectFactory {

        public FilaMedicaOrcamento(){
				
            this(
                	//PLV_2673 - INICIO - Ação em caso de ultrapassar validade de orçamento
                	(Opportunity) new OrcamentoFactory.VidaIndividual().createRecord()
                	//PLV_2673 - INICIO - Ação em caso de ultrapassar validade de orçamento
            	);
        }
        
		public FilaMedicaOrcamento(Opportunity orcamento){

			super(criarRegistroFilaMedicaOrcamento(orcamento));
		}

	}
	
	//----------------------------- CriticaOrçamento Fila Técnica - Orçamento -------------------------------
	@isTest
    private static CriticaOrcamento__c criarRegistroFilaTecnicaOrcamento(){

		if(!mStaticRecord.containsKey('FilaTecnicaOrcamento')){
			
			mStaticRecord.put('FilaTecnicaOrcamento', new CriticaOrcamento__c(
				Area__c = 'TEC',
                Codigo__c = '000TEC',
				Status__c = 'Pendente',
				Tipo__c = 'Análise',
				Severidade__c = 1,
				Origem__c = 'ODM')
			);
		}
		return mStaticRecord.get('FilaTecnicaOrcamento');
	}
    
    public class FilaTecnicaOrcamento extends SObjectFactory {

		public FilaTecnicaOrcamento(){

			super(criarRegistroFilaTecnicaOrcamento());
		}

	}

	 
	//-----------------------------CriticaOrcamento Fila Coordenador - Orçamento -------------------------------
	@isTest
    private static CriticaOrcamento__c criarRegistroFilaCoordenador(){

		if(!mStaticRecord.containsKey('FilaCoordenadorOrcamento')){
			
			mStaticRecord.put('FilaCoordenadorOrcamento', new CriticaOrcamento__c(
				Area__c = 'COR',
                Codigo__c = '000COR',
				Status__c = 'Pendente',
				Tipo__c = 'Análise',
				Severidade__c = 2,
				Origem__c = 'ODM')
			);
		}
		return mStaticRecord.get('FilaCoordenadorOrcamento');
	}

    
	public class FilaCoordenadorOrcamento extends SObjectFactory {

		public FilaCoordenadorOrcamento(){

			super(criarRegistroFilaCoordenador());
		}

	}
}