workspace-sf/force-app/main/default/objects/CriticaOrcamento__c/CriticaOrcamento__c.object-meta.xml
<CustomObject>
    <description>Objeto responsável por armazenar as analises de aceitação geradas pelo ODM ou pelo Sinapse</description>
    <label>Crítica do orçamento</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número da crítica</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Críticas do orçamento</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/CriticaOrcamento__c/fields/Justificativa__c.field-meta.xml
<CustomField>
    <fullName>Justificativa__c</fullName>
    <label>Justificativa</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

workspace-sf/force-app/main/default/objects/CriticaOrcamento__c/fields/Orcamento__c.field-meta.xml
<CustomField>
    <fullName>Orcamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Orçamento</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Críticas do orçamento</relationshipLabel>
    <relationshipName>CriticaOrcamentos</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/CriticaOrcamento__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pendente</fullName>
            </value>
            <value>
                <fullName>Em aprovação</fullName>
            </value>
            <value>
                <fullName>Liberado</fullName>
            </value>
            <value>
                <fullName>Recusado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/classes/CriticaTest.cls
@isTest
private class CriticaTest
{
  @testSetup
  static void setup()
  {
    TestDataFactory.gerarDadosSetup();
    // PLV-2312-28 INICIO
    Map<String,List<SObject>> mapListObject = TestDataFactory.gerarOrcamento(false);
    // PLV-2312-28 FIM
  }

  @isTest
  static void atualizarOportunidade()
  {
    //Valida oportunidade com uma critica recusada
    CriticaOrcamento__c critica         = [SELECT Id, Status__c, Orcamento__c FROM CriticaOrcamento__c LIMIT 1];
    Opportunity         oportunidade    = [SELECT Id, StageName FROM Opportunity WHERE Id =: critica.Orcamento__c LIMIT 1];

    //Valida oportunidade com 2 criticas liberadas

    oportunidade.StageName = 'Disponível para contratação';

    Test.startTest();

    update oportunidade;
    System.assertEquals('Disponível para contratação', oportunidade.StageName);

    Test.stopTest();

    critica.Status__c           = 'Recusado';
    critica.Justificativa__c    = 'foi recusada';

    update critica;

    oportunidade = [SELECT Id, StageName FROM Opportunity WHERE Id =: critica.Orcamento__c LIMIT 1];

    System.assertEquals('Recusado', oportunidade.StageName);
  }
}