workspace-sf/force-app/main/default/objects/GarantiaProduto__c/GarantiaProduto__c.object-meta.xml
<CustomObject>
    <description>Objeto de relacionamento entre os produtos e as garantias</description>
    <label>Garantia do produto</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Garantias do produto</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/GarantiaProduto__c/fields/GarantiaProduto__c.field-meta.xml
<CustomField>
    <fullName>GarantiaProduto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Garantia do produto</label>
    <referenceTo>GarantiaProduto__c</referenceTo>
    <relationshipLabel>Garantias do produto (Garantia do produto)</relationshipLabel>
    <relationshipName>GarantiasProdutoTecnico</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/RiscoGarantia__c/RiscoGarantia__c.object-meta.xml
<CustomObject>
    <description>Objeto de relacionamento entre as garantias e os riscos</description>
    <label>Risco da garantia</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Riscos da garantia</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/RiscoGarantia__c/fields/GarantiaProduto__c.field-meta.xml
<CustomField>
    <fullName>GarantiaProduto__c</fullName>
    <label>Garantia do produto</label>
    <referenceTo>GarantiaProduto__c</referenceTo>
    <relationshipLabel>Riscos da garantia</relationshipLabel>
    <relationshipName>RiscosGarantia</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/RiscoGarantia__c/fields/RiscoGarantia__c.field-meta.xml
<CustomField>
    <fullName>RiscoGarantia__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Risco da garantia</label>
    <referenceTo>RiscoGarantia__c</referenceTo>
    <relationshipLabel>Riscos da garantia</relationshipLabel>
    <relationshipName>RiscosGarantia</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/classes/RiscoDAO.cls
/**************************************************************************************************************************************************************************
 * 
 *	Classe responsável pela busca de dados nos objetos relacionados a risco
 *
 **************************************************************************************************************************************************************************/
public  class RiscoDAO {
	private static final RiscoDAO instancia = new RiscoDAO();

	private RiscoDAO() {	
	}

	public static RiscoDAO getInstance(){
		return instancia;
	}

	public List<RiscoGarantia__c> buscarRiscosGarantiasPorGarantiaProduto (Set<Id> garantiaProdutoIds){
		return [
			Select 
				Id, 
				GarantiaProduto__c
			From 
				RiscoGarantia__c 
			Where 
				GarantiaProduto__c IN: garantiaProdutoIds
		];
	}
}