workspace-sf/force-app/main/default/objects/GarantiaProduto__c/GarantiaProduto__c.object-meta.xml
<CustomObject>
    <description>Objeto de relacionamento entre os produtos e as garantias</description>
    <label>Garantia do produto</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Garantias do produto</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/GarantiaProduto__c/fields/Descricao__c.field-meta.xml
<CustomField>
    <fullName>Descricao__c</fullName>
    <inlineHelpText>Necessário alinhamento com Contabilidade para preenchimento desse campo</inlineHelpText>
    <label>Descrição</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaProduto__c/fields/GarantiaProduto__c.field-meta.xml
<CustomField>
    <fullName>GarantiaProduto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Garantia do produto</label>
    <referenceTo>GarantiaProduto__c</referenceTo>
    <relationshipLabel>Garantias do produto (Garantia do produto)</relationshipLabel>
    <relationshipName>GarantiasProdutoTecnico</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaProduto__c/fields/LimiteMaximoCaracteristicaEspecial__c.field-meta.xml
<CustomField>
    <fullName>LimiteMaximoCaracteristicaEspecial__c</fullName>
    <label>Limite máximo de característica especial</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaProduto__c/fields/LimiteMinimoCaracteristicaEspecial__c.field-meta.xml
<CustomField>
    <fullName>LimiteMinimoCaracteristicaEspecial__c</fullName>
    <label>Limite mínimo de característica especial</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaProduto__c/fields/Obrigatoria__c.field-meta.xml
<CustomField>
    <fullName>Obrigatoria__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Obrigatória?</label>
    <type>Checkbox</type>
</CustomField>

workspace-sf/force-app/main/default/objects/InformacaoOferta__c/InformacaoOferta__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar as informações das ofertas.</description>
    <label>Informação da Oferta</label>
    <nameField>
        <label>Informação da Oferta</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Informação da Oferta</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/InformacaoOferta__c/fields/Descricao__c.field-meta.xml
<CustomField>
    <fullName>Descricao__c</fullName>
    <label>Descricão</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/InformacaoOferta__c/fields/Id__c.field-meta.xml
<CustomField>
    <fullName>Id__c</fullName>
    <inlineHelpText>Cadastre como &apos;TIPO_VIAGEM&apos; para definir a oferta como um produto VIAGEM</inlineHelpText>
    <label>Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/InformacaoOferta__c/fields/Servico__c.field-meta.xml
<CustomField>
    <fullName>Servico__c</fullName>
    <label>Serviço</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/InformacaoOferta__c/fields/tipo__c.field-meta.xml
<CustomField>
    <fullName>tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Texto</fullName>
            </value>
            <value>
                <fullName>Número inteiro</fullName>
            </value>
            <value>
                <fullName>Opções fixas</fullName>
            </value>
            <value>
                <fullName>Opções de servico</fullName>
            </value>
            <value>
                <fullName>CPF</fullName>
            </value>
            <value>
                <fullName>CNPJ</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>CEP</fullName>
            </value>
            <value>
                <fullName>Monetário</fullName>
            </value>
            <value>
                <fullName>Booleano</fullName>
            </value>
            <value>
                <fullName>DataCalendario</fullName>
                <label>Data Calendario</label>
            </value>
            <value>
                <fullName>Opção fixa painel</fullName>
            </value>
            <value>
                <fullName>Radiobutton</fullName>
            </value>
            <value>
                <fullName>Data</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/Oferta__c/Oferta__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar as Ofertas.</description>
    <label>Sugestão de oferta</label>
    <nameField>
        <label>Titulo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sugestão de ofertas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/OfertaGarantiaProduto__c/OfertaGarantiaProduto__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar as Garantias dos produtos das Ofertas.</description>
    <label>Oferta de Garantia Produto</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ofertas de Garantias Produto</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/OfertaGarantiaProduto__c/fields/Chave__c.field-meta.xml
<CustomField>
    <fullName>Chave__c</fullName>
    <description>Chave de correspondência ( Oferta__c + &apos;|&apos; + GarantiaProduto__c )</description>
    <label>Chave</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/OfertaGarantiaProduto__c/fields/Formula__c.field-meta.xml
<CustomField>
    <fullName>Formula__c</fullName>
    <label>Fórmula (Cálculo do Valor do Capital)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/OfertaGarantiaProduto__c/fields/GarantiaProduto__c.field-meta.xml
<CustomField>
    <fullName>GarantiaProduto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Garantia do produto</label>
    <referenceTo>GarantiaProduto__c</referenceTo>
    <relationshipLabel>Ofertas de Garantias Produto</relationshipLabel>
    <relationshipName>Ofertas_de_Garantias_Produto</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/OfertaGarantiaProduto__c/fields/LimiteMaximoCaracteristicaEspecial__c.field-meta.xml
<CustomField>
    <fullName>LimiteMaximoCaracteristicaEspecial__c</fullName>
    <formula>GarantiaProduto__r.LimiteMaximoCaracteristicaEspecial__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Limite Máximo Característica Especial</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

workspace-sf/force-app/main/default/objects/OfertaGarantiaProduto__c/fields/LimiteMinimoCaracteristicaEspecial__c.field-meta.xml
<CustomField>
    <fullName>LimiteMinimoCaracteristicaEspecial__c</fullName>
    <formula>GarantiaProduto__r.LimiteMinimoCaracteristicaEspecial__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Limite Mínimo Característica Especial</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

workspace-sf/force-app/main/default/objects/OfertaGarantiaProduto__c/fields/Obrigatoria__c.field-meta.xml
<CustomField>
    <fullName>Obrigatoria__c</fullName>
    <formula>GarantiaProduto__r.Obrigatoria__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Garantia Obrigatória?</label>
    <type>Checkbox</type>
</CustomField>

workspace-sf/force-app/main/default/objects/OfertaGarantiaProduto__c/fields/Oferta__c.field-meta.xml
<CustomField>
    <fullName>Oferta__c</fullName>
    <label>Oferta</label>
    <referenceTo>Oferta__c</referenceTo>
    <relationshipLabel>Ofertas de Garantias de Produto</relationshipLabel>
    <relationshipName>Ofertas_de_Garantias_Produto</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/OfertaGarantiaProduto__c/fields/TipoCalculo__c.field-meta.xml
<CustomField>
    <fullName>TipoCalculo__c</fullName>
    <inlineHelpText>Ao Selecionar Moeda, preencha o campo Valor do capital. Ao selecionar Fórmula, preencha o campo Fórmula (Cálculo do Valor do Capital)</inlineHelpText>
    <label>Tipo Cálculo de Capital</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Moeda</fullName>
            </value>
            <value>
                <fullName>Fórmula</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/OfertaGarantiaProduto__c/fields/ValorCaracteristicaEspecial__c.field-meta.xml
<CustomField>
    <fullName>ValorCaracteristicaEspecial__c</fullName>
    <label>Valor da característica especial</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

workspace-sf/force-app/main/default/objects/OpcaoInformacao__c/OpcaoInformacao__c.object-meta.xml
<CustomObject>
    <label>Opção de Informação</label>
    <nameField>
        <label>Nome da Opção do Portal</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opção de Informação</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/OpcaoInformacao__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <label>Código</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/OpcaoInformacao__c/fields/InformacaoOferta__c.field-meta.xml
<CustomField>
    <fullName>InformacaoOferta__c</fullName>
    <label>Informação da Oferta</label>
    <referenceTo>InformacaoOferta__c</referenceTo>
    <relationshipLabel>Opção de Informação</relationshipLabel>
    <relationshipName>OpcaoInformacao</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/OpcaoInformacao__c/fields/Ordem__c.field-meta.xml
<CustomField>
    <fullName>Ordem__c</fullName>
    <label>Ordem</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

workspace-sf/force-app/main/default/classes/OfertaGarantiaProdutoHandler.cls
public class OfertaGarantiaProdutoHandler extends TriggerHandler  {

    private List<OfertaGarantiaProduto__c> listOGPNew {get;set;}
    private List<OfertaGarantiaProduto__c> listOGPOld {get;set;}
    private Map<Id,OfertaGarantiaProduto__c> mapOGPNew {get;set;}
    private Map<Id,OfertaGarantiaProduto__c> mapOGPOld {get;set;}

    public OfertaGarantiaProdutoHandler() {

        this.listOGPNew = (List<OfertaGarantiaProduto__c>) Trigger.new;
        this.listOGPOld = (List<OfertaGarantiaProduto__c>) Trigger.old;
        this.mapOGPNew = (Map<Id,OfertaGarantiaProduto__c>) Trigger.newMap;
        this.mapOGPOld = (Map<Id,OfertaGarantiaProduto__c>) Trigger.oldMap;
    }
    
	//PLV-3434 - INICIO
    public override void beforeInsert(){
        this.preencheCampoChave();
        //PLV-4071 - INICIO - PEDRO AUGUSTO - SYS4B
        this.validaFormula();
        //PLV-4071 - FIM - PEDRO AUGUSTO - SYS4B
    }
    
    public override void beforeUpdate(){
        this.preencheCampoChave();
        //PLV-4071 - INICIO - PEDRO AUGUSTO - SYS4B
        this.validaFormula();
        //PLV-4071 - FIM - PEDRO AUGUSTO - SYS4B
    }
    
    public class NewException extends Exception {}

    // OfertaGarantiaProdutoHandler.checkDuplicate();
    public static void checkDuplicate(){
        List<AggregateResult> listDuplicate = [ SELECT Oferta__c, GarantiaProduto__c, COUNT(Id) FROM OfertaGarantiaProduto__c GROUP BY Oferta__c, GarantiaProduto__c HAVING COUNT(Id) > 1 ];
        if( listDuplicate.size() > 0 ){
            for(AggregateResult ar : listDuplicate){
                System.debug( 'Duplicate:' + ar.get( 'Oferta__c' ) + '|' + ar.get( 'GarantiaProduto__c' ) );
            } 
            throw new NewException('There are duplicates. Check log file (\"Debug only\").');
        }
    }
    
    // OfertaGarantiaProdutoHandler.updateAll();
    public static void updateAll(){
        List<OfertaGarantiaProduto__c> listAll = [ SELECT Id FROM OfertaGarantiaProduto__c ];
        update listAll;
    }
    
    private void preencheCampoChave(){
        for( OfertaGarantiaProduto__c ogp : listOGPNew ){
            if( String.isBlank( ogp.Chave__c ) || ogp.Chave__c.length() == 19 || ogp.Chave__c.length() == 37 ){
                ogp.Chave__c = ogp.Oferta__c + '|' + ( ogp.GarantiaProduto__c == null ? '' : ogp.GarantiaProduto__c );
            }
        }   
    }
	//PLV-3434 - FIM
    

    //PLV-4071 - INICIO - PEDRO AUGUSTO - SYS4B

    public void validaFormula(){
        Map<String,InformacaoOferta__c> mapInfo = new Map<String,InformacaoOferta__c>();
        Map<String,List<OpcaoInformacao__c>> mapIDxOpcao = new Map<String,List<OpcaoInformacao__c>>();

        Set<Id> setOpcoes = new Set<Id>();

        for(InformacaoOferta__c InfOferta : [SELECT Id
                                                , Id__c
                                                , Name
                                                , Descricao__c
                                                , Obrigatorio__c
                                                , Ordem__c
                                                , Servico__c
                                                , tipo__c
                                                FROM InformacaoOferta__c
                                                WHERE tipo__c='Opções fixas' OR tipo__c='Número inteiro']){
            mapInfo.put(InfOferta.Id__c,InfOferta);
            if(infOferta.tipo__c=='Opções fixas'){
                setOpcoes.add(infOferta.Id);
            }
            if(infOferta.tipo__c=='Número inteiro'){
                mapIDxOpcao.put(infOferta.Id__c,new List<OpcaoInformacao__c>());
            }
        }

        if(!setOpcoes.isEmpty()){
            List<OpcaoInformacao__c> opcoes = [SELECT Id, Codigo__c,InformacaoOferta__r.Id__c FROM OpcaoInformacao__c WHERE InformacaoOferta__c IN:setOpcoes];
            for(OpcaoInformacao__c opcao : opcoes){
                if(opcao.Codigo__c.isNumeric()){
                    if(!mapIDxOpcao.keyset().contains(opcao.InformacaoOferta__r.Id__c)) mapIDxOpcao.put(opcao.InformacaoOferta__r.Id__c,new List<OpcaoInformacao__c>());
                    mapIDxOpcao.get(opcao.InformacaoOferta__r.Id__c).add(opcao);
                }
            }
        }


        for( OfertaGarantiaProduto__c ogp : listOGPNew ){
            if(ogp.TipoCalculo__c!='Fórmula') continue;
            Decimal resultado = null;
            List<String> listIDsErro = new List<String>();
            if(String.isBlank(ogp.formula__c)){
                ogp.addError('A Fórmula (Cálculo do Valor do Capital) não pode estar em branco');
                continue;
            }

            String formula = ogp.formula__c;
            String regex = '(?<=op)|(?=op)'.replace('op', '[-+*\\/()]');
            
            List<String> formulaSplit = formula.split(regex);
            for(String item : formulaSplit){
                //System.debug(LoggingLevel.Error,'>>> item'+item);
                item = item.trim();

                if(item.isAlpha() || ((!item.isAlpha() && (item.contains('_')||item.contains('-')) && item!='_' && item!='-'))){
                    if(!mapIDxOpcao.keyset().contains(item)){
                        listIDsErro.add(item);
                    }
                }else if(!item.isNumeric() && item.isAlphanumeric() &&(item!='+' && item!='-' && item!='*' && item!='/' && item!='(' && item!=')' && item!='%')){
                    if(!mapIDxOpcao.keyset().contains(item)){
                        listIDsErro.add(item);
                    }
                }
            }

            System.debug(LoggingLevel.Error,'>>> listIDsErro'+listIDsErro);


            if(!listIDsErro.isEmpty()){
                ogp.addError('Não foi identificado referência para: '+String.join(listIDsErro, ', ')+'.  Opções Possíveis: '+String.join(new List<String>(mapIDxOpcao.keyset()), ', '));
            }

        }
    }
    //PLV-4071 - FIM - PEDRO AUGUSTO - SYS4B




    public override void beforeDelete(){
        //this.impedeDelGarantiaObrigatoria();
    }
    
    /*private void impedeDelGarantiaObrigatoria(){
		//PLV-3434 - INICIO
        String desabilitarImpedimentoDelecaoGarantiaObrigatoria = Label.Desabilitar_Impedimento_de_Delecao_de_Garantia_Obrigatoria;
        if( desabilitarImpedimentoDelecaoGarantiaObrigatoria == 'true' ) return;
		//PLV-3434 - FIM
        
        List<String> gpIdList = new List<String>();
        for(OfertaGarantiaProduto__c ogp : listOGPOld) gpIdList.add(ogp.GarantiaProduto__c);
            
        Map<Id,GarantiaProduto__c> mapGP = new Map<Id,GarantiaProduto__c>([
            SELECT Id, Obrigatoria__c FROM GarantiaProduto__c WHERE Id IN :gpIdList
        ]);
        
        for(OfertaGarantiaProduto__c ogp : listOGPOld){
            if(mapGP.get(ogp.GarantiaProduto__c).Obrigatoria__c) ogp.addError('Oferta de garantia obrigatória não pode ser excluida.');
        }    
    }*/
    //PLV-4283 - INICIO
    public override void afterUpdate(){
        this.validarCampos();
    }
    public void validarCampos(){
        
        Set<Id> idGarantiaProduto = new Set<Id>();
        
        for(OfertaGarantiaProduto__c ogp: listOGPNew){
            idGarantiaProduto.add(ogp.GarantiaProduto__c);
        }
        //PLV - 4283 INICIO - FIX 
        List<GarantiaProduto__c> lGarantiaProduto = [SELECT Id,LimiteMaximoCaracteristicaEspecial__c, LimiteMinimoCaracteristicaEspecial__c 
                                                     From GarantiaProduto__c
                                                     WHERE Id IN: idGarantiaProduto];
        
        for(GarantiaProduto__c g: lGarantiaProduto){
            for(OfertaGarantiaProduto__c ogp: listOGPNew){
                if(ogp.GarantiaProduto__c == g.Id){
                    if(g.LimiteMaximoCaracteristicaEspecial__c != null && g.LimiteMinimoCaracteristicaEspecial__c != null){
                        if(ogp.ValorCaracteristicaEspecial__c == null){
                            ogp.addError('Valor Caracteristica Especial não pode ser vazio');
                        }else{
                            if(ogp.ValorCaracteristicaEspecial__c >= g.LimiteMinimoCaracteristicaEspecial__c && 
                               ogp.ValorCaracteristicaEspecial__c <= g.LimiteMaximoCaracteristicaEspecial__c){
                               //PLV - 4283 INICIO - FIX 
                               }else{
                                   ogp.addError('O Valor da característica especial  deve estar dentro dos limites mínimo e máximo cadastrados');
                               }
                        }
                    }
                }
            }
        }       
    }
    //PLV-4283 - FIM
}