workspace-sf/force-app/main/default/objects/GarantiaProduto__c/GarantiaProduto__c.object-meta.xml
<CustomObject>
    <description>Objeto de relacionamento entre os produtos e as garantias</description>
    <label>Garantia do produto</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Garantias do produto</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/GarantiaProduto__c/fields/GarantiaProduto__c.field-meta.xml
<CustomField>
    <fullName>GarantiaProduto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Garantia do produto</label>
    <referenceTo>GarantiaProduto__c</referenceTo>
    <relationshipLabel>Garantias do produto (Garantia do produto)</relationshipLabel>
    <relationshipName>GarantiasProdutoTecnico</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/GarantiaProduto__c/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Garantias do produto</relationshipLabel>
    <relationshipName>GarantiasProduto</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Municipio__c/Municipio__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar o cadastro dos municípios</description>
    <label>Município</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Municípios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/Pais__c/Pais__c.object-meta.xml
<CustomObject>
    <description>Objeto responsável por armazenar os dados dos países</description>
    <label>País</label>
    <nameField>
        <label>Pais Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Países</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/Territorio__c/Territorio__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar o cadastro dos territórios dos produtos e das garantias</description>
    <label>Território</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Territórios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/Territorio__c/fields/Continente__c.field-meta.xml
<CustomField>
    <fullName>Continente__c</fullName>
    <label>Continente</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Territorio__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Territorio__c/fields/GarantiaProduto__c.field-meta.xml
<CustomField>
    <fullName>GarantiaProduto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Garantia do produto</label>
    <referenceTo>GarantiaProduto__c</referenceTo>
    <relationshipLabel>Territórios</relationshipLabel>
    <relationshipName>TerritoriosGarantia</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Territorio__c/fields/Municipio__c.field-meta.xml
<CustomField>
    <fullName>Municipio__c</fullName>
    <label>Município</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Territorio__c/fields/Pais__c.field-meta.xml
<CustomField>
    <fullName>Pais__c</fullName>
    <label>País</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Territorio__c/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Regiões de comercialização</relationshipLabel>
    <relationshipName>TerritoriosProduto</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Territorio__c/fields/Territorio__c.field-meta.xml
<CustomField>
    <fullName>Territorio__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Território</label>
    <referenceTo>Territorio__c</referenceTo>
    <relationshipLabel>Territórios</relationshipLabel>
    <relationshipName>Territorios</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Territorio__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Globo terrestre</fullName>
            </value>
            <value>
                <fullName>Continente</fullName>
            </value>
            <value>
                <fullName>País</fullName>
            </value>
            <value>
                <fullName>Estado</fullName>
            </value>
            <value>
                <fullName>Município</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/classes/TerritorioDAO.cls
/**************************************************************************************************************************************************************************
 * 
 *	Classe responsável pelas buscas no objeto de Território da garantia
 *
 **************************************************************************************************************************************************************************/
public class TerritorioDAO {
	private static final TerritorioDAO instance = new TerritorioDAO();
	
	private TerritorioDAO() {
	}

	public static TerritorioDAO getInstance() {
		return instance;
	}	

	/**
	 * Realiza a busca de todos os territorios da garantia referente a uma garantia de produto
	 *
	 * @param   garantiaProdutoId  - id de uma garantia de produto
	 */
	public List<Territorio__c> buscarTerritoriosGarantia(Id garantiaProdutoId) {
		return [
			Select 
				Id,
				Continente__c,
				Estado__c,
				Municipio__c,
				Pais__c,
				Tipo__c,
				RecordTypeId
			From 
				Territorio__c	
			Where 
				GarantiaProduto__c =: garantiaProdutoId
			Order By CreatedDate	
		];
	}

	/**
	 * Realiza a busca de todos os territorios do produto
	 *
	 * @param  produtoId  - id do produto
	 */
	public List<Territorio__c> buscarTerritoriosProduto(Id produtoId) {
		return [
			Select 
				Id,
				Continente__c,
				Estado__c,
				Municipio__c,
				Pais__c,
				Tipo__c,
				RecordTypeId
			From 
				Territorio__c	
			Where 
				Produto__c =: produtoId
			Order By CreatedDate	
		];
	}
}