workspace-sf/force-app/main/default/objects/AntecipacaoComissao__c/AntecipacaoComissao__c.object-meta.xml
<CustomObject>
    <label>Antecipação de Comissão</label>
    <nameField>
        <displayFormat>AC-{000000}</displayFormat>
        <label>Nome de Antecipação de Comissão</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Antecipação de Comissão</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/AntecipacaoComissao__c/fields/LimiteMaximo__c.field-meta.xml
<CustomField>
    <fullName>LimiteMaximo__c</fullName>
    <label>Limite Máximo</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

workspace-sf/force-app/main/default/objects/AntecipacaoComissao__c/fields/LimiteMinimo__c.field-meta.xml
<CustomField>
    <fullName>LimiteMinimo__c</fullName>
    <label>Limite Mínimo</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

workspace-sf/force-app/main/default/objects/AntecipacaoComissao__c/fields/RemuneracaoProduto__c.field-meta.xml
<CustomField>
    <fullName>RemuneracaoProduto__c</fullName>
    <label>Remuneração do produto</label>
    <referenceTo>RemuneracaoProduto__c</referenceTo>
    <relationshipLabel>Antecipação de Comissão</relationshipLabel>
    <relationshipName>Antecipacoes_de_Comissao</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/AntecipacaoComissao__c/fields/TipoEvento__c.field-meta.xml
<CustomField>
    <fullName>TipoEvento__c</fullName>
    <label>Tipo de evento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Seguro Novo</fullName>
            </value>
            <value>
                <fullName>Endosso</fullName>
            </value>
            <value>
                <fullName>Renovação</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/RemuneracaoProduto__c/RemuneracaoProduto__c.object-meta.xml
<CustomObject>
    <description>Objeto de relacionamento entre o produto e o tipo de remuneração</description>
    <label>Remuneração do produto</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Remunerações do produto</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/RemuneracaoProduto__c/fields/LimiteMinimo__c.field-meta.xml
<CustomField>
    <fullName>LimiteMinimo__c</fullName>
    <label>Limite mínimo</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

workspace-sf/force-app/main/default/objects/RemuneracaoProduto__c/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Remunerações do produto</relationshipLabel>
    <relationshipName>RemuneracoesProduto</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/RemuneracaoProduto__c/fields/RemuneracaoProduto__c.field-meta.xml
<CustomField>
    <fullName>RemuneracaoProduto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Remuneração do produto</label>
    <referenceTo>RemuneracaoProduto__c</referenceTo>
    <relationshipLabel>Remunerações do produto</relationshipLabel>
    <relationshipName>RemuneracoesProduto</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/RemuneracaoProduto__c/fields/TipoEvento__c.field-meta.xml
<CustomField>
    <fullName>TipoEvento__c</fullName>
    <label>Tipo de evento</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Endosso</fullName>
            </value>
            <value>
                <fullName>Renovação</fullName>
            </value>
            <value>
                <fullName>Seguro novo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/RemuneracaoProduto__c/fields/TipoRemuneracao__c.field-meta.xml
<CustomField>
    <fullName>TipoRemuneracao__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tipo de remuneração</label>
    <referenceTo>TipoRemuneracao__c</referenceTo>
    <relationshipLabel>Remunerações do produto</relationshipLabel>
    <relationshipName>RemuneracoesProduto</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/TipoRemuneracao__c/TipoRemuneracao__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar o cadastro dos tipos de remuneração</description>
    <label>Tipo de remuneração</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tipos de remuneração</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/TipoRemuneracao__c/fields/LimiteMaximo__c.field-meta.xml
<CustomField>
    <fullName>LimiteMaximo__c</fullName>
    <label>Limite máximo</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

workspace-sf/force-app/main/default/classes/AntecipacaoComissaoDAO.cls
public class AntecipacaoComissaoDAO {

	private static final AntecipacaoComissaoDAO instance = new AntecipacaoComissaoDAO();

	public static AntecipacaoComissaoDAO getInstance() {
		return instance;
	}
   // VIAG-148 INICIO
	public List<AntecipacaoComissao__c> buscarAntecipacaoComissaoPorProdutCode(Set<String> codigosProduto){
  
		return [
            SELECT ID, 
            LimiteMaximo__c, 
            LimiteMinimo__c, 
            TipoEvento__c, 
            RemuneracaoProduto__c, 
            RemuneracaoProduto__r.TipoRemuneracao__r.Name,
            RemuneracaoProduto__r.Name  
            FROM
            AntecipacaoComissao__c 
            WHERE RemuneracaoProduto__r.Produto__r.ProductCode IN: codigosProduto 
            AND RemuneracaoProduto__r.Produto__r.Status__c = 'Ativo'
		];
		
	}
	 // VIAG-148 FIM
}