workspace-sf/force-app/main/default/objects/AntecipacaoComissao__c/AntecipacaoComissao__c.object-meta.xml
<CustomObject>
    <label>Antecipação de Comissão</label>
    <nameField>
        <displayFormat>AC-{000000}</displayFormat>
        <label>Nome de Antecipação de Comissão</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Antecipação de Comissão</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/AntecipacaoComissao__c/fields/RemuneracaoProduto__c.field-meta.xml
<CustomField>
    <fullName>RemuneracaoProduto__c</fullName>
    <label>Remuneração do produto</label>
    <referenceTo>RemuneracaoProduto__c</referenceTo>
    <relationshipLabel>Antecipação de Comissão</relationshipLabel>
    <relationshipName>Antecipacoes_de_Comissao</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/AntecipacaoComissao__c/fields/TipoEvento__c.field-meta.xml
<CustomField>
    <fullName>TipoEvento__c</fullName>
    <label>Tipo de evento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Seguro Novo</fullName>
            </value>
            <value>
                <fullName>Endosso</fullName>
            </value>
            <value>
                <fullName>Renovação</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/RemuneracaoProduto__c/RemuneracaoProduto__c.object-meta.xml
<CustomObject>
    <description>Objeto de relacionamento entre o produto e o tipo de remuneração</description>
    <label>Remuneração do produto</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Remunerações do produto</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/RemuneracaoProduto__c/fields/RemuneracaoProduto__c.field-meta.xml
<CustomField>
    <fullName>RemuneracaoProduto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Remuneração do produto</label>
    <referenceTo>RemuneracaoProduto__c</referenceTo>
    <relationshipLabel>Remunerações do produto</relationshipLabel>
    <relationshipName>RemuneracoesProduto</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/RemuneracaoProduto__c/fields/TipoEvento__c.field-meta.xml
<CustomField>
    <fullName>TipoEvento__c</fullName>
    <label>Tipo de evento</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Endosso</fullName>
            </value>
            <value>
                <fullName>Renovação</fullName>
            </value>
            <value>
                <fullName>Seguro novo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/classes/AntecipacaoComissaoBO.cls
//PLV-4305 Complemento - INICIO - Criação de classe para as regras de negocio
public class AntecipacaoComissaoBO {
    public static void validaAntecipacoes(List<AntecipacaoComissao__c> lstAnt){
        Set<Id> setRemuneracoes = new Set<Id>();

        for(AntecipacaoComissao__c antCom : lstAnt){
            if(antCom.RemuneracaoProduto__c != null) setRemuneracoes.add(antCom.RemuneracaoProduto__c);
        }

        if(setRemuneracoes.isEmpty()) return;

        Map<Id, AntecipacaoComissao__c> mapAntCom = new Map<Id, AntecipacaoComissao__c>([SELECT Id, RemuneracaoProduto__c, TipoEvento__c FROM AntecipacaoComissao__c WHERE RemuneracaoProduto__c IN :setRemuneracoes]);

        if(mapAntCom.isEmpty()) return;

        for(AntecipacaoComissao__c vAnt : lstAnt){
            if(mapAntCom.containsKey(vAnt.Id)) mapAntCom.remove(vAnt.Id);
        }

        if(mapAntCom.isEmpty()) return;
        //PLV-4305 FIX - INICIO - Ajuste na logica
        Map<Id,Map<String,AntecipacaoComissao__c>> mapIdRemAntCom = new Map<Id,Map<String,AntecipacaoComissao__c>>();
        for(AntecipacaoComissao__c antecipMap : mapAntCom.values()){

            Map<String,AntecipacaoComissao__c> mapTipoEvento;

            if(mapIdRemAntCom.containsKey(antecipMap.RemuneracaoProduto__c)) mapTipoEvento = mapIdRemAntCom.get(antecipMap.RemuneracaoProduto__c);
            else mapTipoEvento = new Map<String,AntecipacaoComissao__c>();

            mapTipoEvento.put(antecipMap.TipoEvento__c, antecipMap);
            mapIdRemAntCom.put(antecipMap.RemuneracaoProduto__c, mapTipoEvento);
        }

        for(AntecipacaoComissao__c antecipCom : lstAnt){
            
            if(!mapIdRemAntCom.containsKey(antecipCom.RemuneracaoProduto__c)) continue;
            
            Map<String,AntecipacaoComissao__c> mapTipo = mapIdRemAntCom.get(antecipCom.RemuneracaoProduto__c);
            
            if(!mapTipo.containsKey(antecipCom.TipoEvento__c)) continue;

            AntecipacaoComissao__c vAnt = mapTipo.get(antecipCom.TipoEvento__c);

            //if(antecipCom.RemuneracaoProduto__c == vAnt.RemuneracaoProduto__c && antecipCom.TipoEvento__c == vAnt.TipoEvento__c) antecipCom.addError('Antecipação já cadastrada para a Remunaração do Produto com o mesmo tipo de evento'); //ANNVI-41 FIX-01 INICIO/FIM
        }
        //PLV-4305 FIX - FIM
    }
}
//PLV-4305 Complemento - FIM