workspace-sf/force-app/main/default/objects/FavorecidoRemuneracao__c/FavorecidoRemuneracao__c.object-meta.xml
<CustomObject>
    <description>Objeto de relacionamento entre a conta e remuneração do parceiro</description>
    <label>Favorecido da remuneração</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Favorecidos da remuneração</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/FavorecidoRemuneracao__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>FavorecidosRemuneracao</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/FavorecidoRemuneracao__c/fields/Percentual__c.field-meta.xml
<CustomField>
    <fullName>Percentual__c</fullName>
    <label>Percentual</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

workspace-sf/force-app/main/default/objects/FavorecidoRemuneracao__c/fields/RemuneracaoProdutoParceiro__c.field-meta.xml
<CustomField>
    <fullName>RemuneracaoProdutoParceiro__c</fullName>
    <label>Remuneração do produto do parceiro</label>
    <referenceTo>RemuneracaoProdutoParceiro__c</referenceTo>
    <relationshipLabel>Favorecidos da remuneração</relationshipLabel>
    <relationshipName>FavorecidosRemuneracao</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/FormaPagamento__c/FormaPagamento__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar o cadastro das formas de pagamento</description>
    <label>Forma de pagamento</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Formas de pagamento</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/FormaPagamento__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <label>Código</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Parceiro__c/Parceiro__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar as informações dos parceiros da Porto</description>
    <label>Parceiro</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parceiros</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/Parceiro__c/fields/ApoliceFaturamento__c.field-meta.xml
<CustomField>
    <fullName>ApoliceFaturamento__c</fullName>
    <label>Apólice de Faturamento</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Parceiro__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <formula>LPAD( Conta__r.IdExterno__c , 14, &quot;0&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Código de identificação do parceiro  - CNPJ da conta sem pontuação</inlineHelpText>
    <label>Código</label>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Parceiro__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Parceiros</relationshipLabel>
    <relationshipName>Parceiro</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Parceiro__c/fields/DiaFaturamento__c.field-meta.xml
<CustomField>
    <fullName>DiaFaturamento__c</fullName>
    <label>Dia do Faturamento</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Parceiro__c/fields/DiaPreFaturamento__c.field-meta.xml
<CustomField>
    <fullName>DiaPreFaturamento__c</fullName>
    <label>Dia do Pré-faturamento</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Parceiro__c/fields/EndossoBatimentoContabil__c.field-meta.xml
<CustomField>
    <fullName>EndossoBatimentoContabil__c</fullName>
    <defaultValue>TEXT(YEAR(TODAY())) + LPAD(TEXT(MONTH(TODAY())),2,&apos;0&apos;) + &apos;001&apos;</defaultValue>
    <label>Endosso de Batimento Contábil</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Parceiro__c/fields/EndossoCobranca__c.field-meta.xml
<CustomField>
    <fullName>EndossoCobranca__c</fullName>
    <defaultValue>TEXT(YEAR(TODAY())) + LPAD(TEXT(MONTH(TODAY())),2,&apos;0&apos;) + &apos;000&apos;</defaultValue>
    <label>Endosso de Cobrança</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Parceiro__c/fields/FaturaProdutosSeparados__c.field-meta.xml
<CustomField>
    <fullName>FaturaProdutosSeparados__c</fullName>
    <label>Fatura produtos separados?</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sim</fullName>
            </value>
            <value>
                <fullName>Não</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/Parceiro__c/fields/FormaPagamento__c.field-meta.xml
<CustomField>
    <fullName>FormaPagamento__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Forma de pagamento</label>
    <referenceTo>FormaPagamento__c</referenceTo>
    <relationshipLabel>Parceiros</relationshipLabel>
    <relationshipName>Parceiros</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Parceiro__c/fields/PossuiAnexoFatura__c.field-meta.xml
<CustomField>
    <fullName>PossuiAnexoFatura__c</fullName>
    <label>Possui Anexo Fatura?</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sim</fullName>
            </value>
            <value>
                <fullName>Nao</fullName>
                <label>Não</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/Parceiro__c/fields/PrazoVencimento__c.field-meta.xml
<CustomField>
    <fullName>PrazoVencimento__c</fullName>
    <inlineHelpText>Quantidade de dias para o vencimento da fatura, após o dia do faturamento</inlineHelpText>
    <label>Prazo de vencimento</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Parceiro__c/fields/Ramo__c.field-meta.xml
<CustomField>
    <fullName>Ramo__c</fullName>
    <label>Ramo</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Parceiro__c/fields/SiglaParceiro__c.field-meta.xml
<CustomField>
    <fullName>SiglaParceiro__c</fullName>
    <label>Sigla do Parceiro</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/Parceiro__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Em Criação</fullName>
                <default>true</default>
                <label>Em Criação</label>
            </value>
            <value>
                <fullName>Ativo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

workspace-sf/force-app/main/default/objects/Parceiro__c/fields/Sucursal__c.field-meta.xml
<CustomField>
    <fullName>Sucursal__c</fullName>
    <label>Sucursal</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/ProdutoParceiro__c/ProdutoParceiro__c.object-meta.xml
<CustomObject>
    <description>Objeto de relacionamento entre o parceiro e o produto</description>
    <label>Produto do parceiro</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número do Produto do Parceiro</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Produtos do parceiro</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/ProdutoParceiro__c/fields/CodigoProdutoParceiro__c.field-meta.xml
<CustomField>
    <fullName>CodigoProdutoParceiro__c</fullName>
    <description>Esse campo terá a descrição do código do produto no parceiro (no caso da Renner, seria V0003065 para o CCR e V0003064 para o EP).</description>
    <label>Código do Produto no Parceiro</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/ProdutoParceiro__c/fields/Parceiro__c.field-meta.xml
<CustomField>
    <fullName>Parceiro__c</fullName>
    <label>Parceiro</label>
    <referenceTo>Parceiro__c</referenceTo>
    <relationshipLabel>Produtos do parceiro</relationshipLabel>
    <relationshipName>ProdutosParceiro</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/ProdutoParceiro__c/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Produtos do parceiro</relationshipLabel>
    <relationshipName>ProdutosParceiro</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/ProdutoParceiro__c/fields/Sigla__c.field-meta.xml
<CustomField>
    <fullName>Sigla__c</fullName>
    <label>Sigla</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

workspace-sf/force-app/main/default/objects/RemuneracaoProduto__c/RemuneracaoProduto__c.object-meta.xml
<CustomObject>
    <description>Objeto de relacionamento entre o produto e o tipo de remuneração</description>
    <label>Remuneração do produto</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Remunerações do produto</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/RemuneracaoProduto__c/fields/LimiteMinimo__c.field-meta.xml
<CustomField>
    <fullName>LimiteMinimo__c</fullName>
    <label>Limite mínimo</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

workspace-sf/force-app/main/default/objects/RemuneracaoProduto__c/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Remunerações do produto</relationshipLabel>
    <relationshipName>RemuneracoesProduto</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/RemuneracaoProduto__c/fields/RemuneracaoProduto__c.field-meta.xml
<CustomField>
    <fullName>RemuneracaoProduto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Remuneração do produto</label>
    <referenceTo>RemuneracaoProduto__c</referenceTo>
    <relationshipLabel>Remunerações do produto</relationshipLabel>
    <relationshipName>RemuneracoesProduto</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/RemuneracaoProduto__c/fields/TipoRemuneracao__c.field-meta.xml
<CustomField>
    <fullName>TipoRemuneracao__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tipo de remuneração</label>
    <referenceTo>TipoRemuneracao__c</referenceTo>
    <relationshipLabel>Remunerações do produto</relationshipLabel>
    <relationshipName>RemuneracoesProduto</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/RemuneracaoProduto__c/recordTypes/ProdutoComercial.recordType-meta.xml
<RecordType>
    <fullName>ProdutoComercial</fullName>
    <active>true</active>
    <label>Produto comercial</label>
</RecordType>

workspace-sf/force-app/main/default/objects/RemuneracaoProdutoParceiro__c/RemuneracaoProdutoParceiro__c.object-meta.xml
<CustomObject>
    <description>Objeto de relacionamento entre o parceiro e o tipo de remuneração.</description>
    <label>Remuneração do produto do parceiro</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Remunerações do produto do parceiro</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/RemuneracaoProdutoParceiro__c/fields/Percentual__c.field-meta.xml
<CustomField>
    <fullName>Percentual__c</fullName>
    <label>Percentual</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

workspace-sf/force-app/main/default/objects/RemuneracaoProdutoParceiro__c/fields/ProdutoParceiro__c.field-meta.xml
<CustomField>
    <fullName>ProdutoParceiro__c</fullName>
    <label>Produto do parceiro</label>
    <referenceTo>ProdutoParceiro__c</referenceTo>
    <relationshipLabel>Remunerações do produto do parceiro</relationshipLabel>
    <relationshipName>RemuneracoesProdutoParceiro</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

workspace-sf/force-app/main/default/objects/RemuneracaoProdutoParceiro__c/fields/RemuneracaoProduto__c.field-meta.xml
<CustomField>
    <fullName>RemuneracaoProduto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Remuneração do produto</label>
    <referenceTo>RemuneracaoProduto__c</referenceTo>
    <relationshipName>RemuneracoesProdutoParceiro</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/RemuneracaoProdutoParceiro__c/fields/TipoRemuneracao__c.field-meta.xml
<CustomField>
    <fullName>TipoRemuneracao__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tipo de remuneração</label>
    <referenceTo>TipoRemuneracao__c</referenceTo>
    <relationshipName>RemuneracoesProdutoParceiro</relationshipName>
    <type>Lookup</type>
</CustomField>

workspace-sf/force-app/main/default/objects/TipoRemuneracao__c/TipoRemuneracao__c.object-meta.xml
<CustomObject>
    <description>Objeto para armazenar o cadastro dos tipos de remuneração</description>
    <label>Tipo de remuneração</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tipos de remuneração</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

workspace-sf/force-app/main/default/objects/TipoRemuneracao__c/fields/LimiteMaximo__c.field-meta.xml
<CustomField>
    <fullName>LimiteMaximo__c</fullName>
    <label>Limite máximo</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

workspace-sf/force-app/main/default/classes/ParceiroDAO.cls
public class ParceiroDAO
{

    private static final ParceiroDAO instancia = new ParceiroDAO();

    private ParceiroDAO(){}
    private static final String PRODUTO_COMERCIAL = 'ProdutoComercial';

    public static ParceiroDAO getInstance(){
        return instancia;
    }

    public List<Parceiro__c> buscarTodosParceiros(){
        return [
                SELECT
                        Id,
                        Name,
                        Codigo__c,
                        Conta__c,
                        Conta__r.Name,
                (
                        SELECT
                                Id,
                                Name,
                                Produto__c,
                                Produto__r.Name,
                                CodigoProdutoParceiro__c,
                                Sigla__c
                        FROM
                                ProdutosParceiro__r
                )
                FROM
                        Parceiro__c
        ];
    }

    public List<Parceiro__c> buscarParceirosPorIds(List<Id> setParceirosIds) {
        return [SELECT
                ApoliceFaturamento__c,
                Conta__c,
                DiaFaturamento__c,
                DiaPreFaturamento__c,
                Empresa__c,
                EndossoCobranca__c,
                EndossoBatimentoContabil__c,
                FaturaProdutosSeparados__c,
                FormaPagamento__c,
                Name,
                PossuiAnexoFatura__c,
                PrazoVencimento__c,
                Ramo__c,
                Sucursal__c,
                Status__c,
        (
                SELECT
                        Id,
                        Name,
                        Produto__c,
                        Produto__r.ProductCode,
                        Produto__r.CodigoPrecificaProduto__c, // PLV-5331 INÍCIO / FIM 
                        Produto__r.RecordTypeId,
                        Produto__r.RecordType.DeveloperName,
                        Parceiro__c
                FROM
                        ProdutosParceiro__r
        )
        FROM
                Parceiro__c
        WHERE
                Id IN :setParceirosIds];
    }

    public Parceiro__c obtemParceiro(String  idParceiro)
    {
        List<Parceiro__c> l = [SELECT
                Id,
                Codigo__c,
                ApoliceFaturamento__c,
                Conta__c,
                DiaFaturamento__c,
                DiaPreFaturamento__c,
                Empresa__c,
                EndossoCobranca__c,
                EndossoBatimentoContabil__c,
                FaturaProdutosSeparados__c,
                FormaPagamento__c,
                Name,
                PossuiAnexoFatura__c,
                PrazoVencimento__c,
                Ramo__c,
                Sucursal__c,
                Status__c,
                FormaPagamento__r.Codigo__c
        FROM
                Parceiro__c
        WHERE
                Codigo__c = :idParceiro OR SiglaParceiro__c = :idParceiro]; // VIAG-139 INICIO/FIM
        if(l.isEmpty())
            return null;
        else
                return l[0];
    }
// VIAG-139 INICIO
    public String  obtemParceiroSigla(String  idParceiro)
    {
        String ParceiroId = '';
        List<Parceiro__c> Parceiro = [SELECT Id  FROM  Parceiro__c  WHERE  Codigo__c =: idParceiro  OR   SiglaParceiro__c =: idParceiro Limit 1];
        if (Parceiro.size() >0 ) {
                ParceiroId = Parceiro[0].Id;
        } 
       return ParceiroId;
    }
 // VIAG-139 FIM

 public List<Product2> buscarProdutos(Set<Id> setProdutoId){
        return [
                SELECT
                        Id,
                        VigenciaInicial__c,
                        VigenciaFinal__c,
                        Status__c,
                        ProdutoVigente__c,
                        ProductCode,
                (
                        SELECT
                                Id,
                                Name,
                                LimiteMaximo__c,
                                LimiteMinimo__c,
                                Obrigatoria__c,
                                Produto__c,
                                TipoRemuneracao__c,
                                TipoRemuneracao__r.Name,
                                TipoRemuneracao__r.LimiteMinimo__c,
                                TipoRemuneracao__r.LimiteMaximo__c,
                                TipoRemuneracao__r.Codigo__c
                        FROM
                                RemuneracoesProduto__r
                )
                FROM
                        Product2
                WHERE
                        Id =: setProdutoId
        ];
    }

    public List<RemuneracaoProdutoParceiro__c> buscarRemuneracaoProdutosPorParceiro(Set<Id> setProdutoId, Id parceiroId)
    {
        return [
                SELECT
                        Id,
                        Name,
                        Percentual__c,
                        ProdutoParceiro__r.Parceiro__c,
                        TipoRemuneracao__c,
                        TipoRemuneracao__r.Name,
                        TipoRemuneracao__r.LimiteMinimo__c,
                        TipoRemuneracao__r.LimiteMaximo__c,
                        TipoRemuneracao__r.Codigo__c,
                        ProdutoParceiro__c,
                        ProdutoParceiro__r.Produto__c,
                        RemuneracaoProduto__c,
                (
                        SELECT
                                Id,
                                Name,
                                Conta__c,
                                Conta__r.Papel__c,
                                Conta__r.Name,
                                Conta__r.SusepPrincipal__c,
                                Conta__r.CodigoSusepCia__c,
                                Conta__r.CodigoSusepCorretor__c,
                                DadosCorretor__c,
                                DadosCorretor__r.Name,
                                Percentual__c,
                                Lider__c,
                                Papel__c
                        FROM
                                FavorecidosRemuneracao__r
                )

                FROM
                        RemuneracaoProdutoParceiro__c
                WHERE
                ProdutoParceiro__r.Produto__c IN: setProdutoId AND ProdutoParceiro__r.Parceiro__c = : parceiroId

        ];
    }

    public List<RemuneracaoProdutoParceiro__c> buscarRemuneracaoProdutoParceiro(Set<Id> setParceiroId){
        return [
                SELECT
                        Id,
                        Name,
                        Percentual__c,
                        TipoRemuneracao__c,
                        TipoRemuneracao__r.Name,
                        TipoRemuneracao__r.LimiteMinimo__c,
                        TipoRemuneracao__r.LimiteMaximo__c,
                        TipoRemuneracao__r.Codigo__c,
                        ProdutoParceiro__c,
                        ProdutoParceiro__r.Produto__c,
                        RemuneracaoProduto__c,
                (
                        SELECT
                                Id,
                                Name,
                                Conta__c,
                                Conta__r.Papel__c,
                                Conta__r.Name,
                                Conta__r.SusepPrincipal__c,
                                Conta__r.CodigoSusepCia__c,
                                Conta__r.CodigoSusepCorretor__c,
                                Percentual__c,
                                Lider__c,
                                Papel__c
                        FROM
                                FavorecidosRemuneracao__r
                )

                FROM
                        RemuneracaoProdutoParceiro__c
                WHERE
                        ProdutoParceiro__r.Parceiro__c =: setParceiroId
        ];
    }

    public List<Parceiro__c> buscarParceirosPorCodigo(Set<String> setParceiro) {
        return [SELECT
                Id,
                ApoliceFaturamento__c,
                Conta__c,
                Codigo__c,
                DiaFaturamento__c,
                DiaPreFaturamento__c,
                Empresa__c,
                EndossoCobranca__c,
                EndossoBatimentoContabil__c,
                FaturaProdutosSeparados__c,
                FormaPagamento__c,
                Name,
                PossuiAnexoFatura__c,
                PrazoVencimento__c,
                Ramo__c,
                Sucursal__c,
        (
                SELECT
                        Id,
                        Name,
                        Produto__c,
                        Produto__r.ProductCode,
                        Produto__r.CodigoPrecificaProduto__c, // PLV-5331 INÍCIO / FIM 
                        Produto__r.RecordTypeId,
                        Produto__r.RecordType.DeveloperName,
                        Parceiro__c,
                        Sigla__c,
                        CodigoProdutoParceiro__c
                FROM
                        ProdutosParceiro__r
        )
        FROM
                Parceiro__c
        WHERE Codigo__c =: setParceiro];
    }

    public List<ProdutoParceiro__c> buscarProdutosParceiro(Set<String> setCodigoParceiro, Set<String> setCodigoProduto) {
        return [
                SELECT
                        Id,
                        Name,
                        Produto__c,
                        Produto__r.ProductCode,
                        Produto__r.CodigoPrecificaProduto__c, // PLV-5331 INÍCIO / FIM 
                        Produto__r.RecordTypeId,
                        Produto__r.RecordType.DeveloperName,
                        Parceiro__c,
                        Parceiro__r.Name,
                        Parceiro__r.Codigo__c,
                        Sigla__c,
                        CodigoProdutoParceiro__c
                FROM
                        ProdutoParceiro__c
                WHERE
                        Parceiro__r.Codigo__c =: setCodigoParceiro
                AND
                        Produto__r.ProductCode =: setCodigoProduto

        ];
    }

    public List<ProdutoParceiro__c> buscarProdutosPorProductCode(Set<String> setProductCode){
        return [
                SELECT
                        Id,
                        CodigoProdutoParceiro__c,
                        Parceiro__c,
                        Parceiro__r.Codigo__c,
                        Produto__r.VersaoMaxima__c,
                        Produto__r.Versao__c,
                        Produto__r.ProductCode,
                        Produto__r.CodigoPrecificaProduto__c // PLV-5331 INÍCIO / FIM 
                FROM
                        ProdutoParceiro__c
                WHERE
                        Produto__r.ProductCode =: setProductCode
        ];
    }
   // VIAG-139 INICIO 
    public String buscarParceiroPorProductId(String setProdutoId){
     String siglaParceiro = '';
     List<ProdutoParceiro__c>  Sigla =  [
                SELECT 
                  Parceiro__r.SiglaParceiro__c
                FROM
                        ProdutoParceiro__c
                WHERE
                       Produto__r.Id =: setProdutoId 
                Limit 1
        ];
     
        if ( Sigla.size() >0 ) {
           siglaParceiro = Sigla[0].Parceiro__r.SiglaParceiro__c;
        } 
       return siglaParceiro;
    }
      // VIAG-139 FIM
}